import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/38 - Analysing Clocked Sequential Circuits, "The Reverse Question" (Sequential Logic track).
 * Analysis runs a clocked sequential circuit BACKWARDS through mathematics - the
 * reverse of design/synthesis. The exact 3-step procedure (per the source deck):
 * 1) Schematic -> excitation equations (trace each FF's D/J-K/T pin straight off
 *    the wiring, in terms of present-state variables + external inputs).
 * 2) Excitation equations -> next-state/output equations (substitute each FF
 *    type's characteristic equation; read the output gate directly).
 * 3) Tabulate every present-state x input row -> state table -> state diagram
 *    (circles = states, directed arcs labeled input/output).
 * Worked example (classic Mano-style, from the source deck): two D flip-flops A,B,
 * input X, output Y. DA = A.X + B.X ; DB = A'.X ; since D-type Q(t+1)=D directly,
 * A(t+1)=DA, B(t+1)=DB ; Y = (A+B).X' (a Mealy-flavoured output, previewed here,
 * formalised in module 39). Every table/diagram in scenes.tsx is COMPUTED by
 * evaluating these equations in code via the shared _sequential/blocks ffNext -
 * never hardcoded. A second bespoke practice circuit uses two JK flip-flops
 * (JA=B, KA=B.X', JB=X, KB=A) with a Moore-style output Y=A.B, to contrast
 * "output on the arc" vs "output inside the state" ahead of module 39. The
 * reverse-engineering scene flips the whole method around: no schematic, only
 * a sealed box's input/output pins, reconstructed by probing - the same method
 * a detective uses to reconstruct a routine purely by watching it repeat.
 */
export const CONTENT: SubContent = {
  moduleTitle: 'Analysing Clocked Sequential Circuits - The Reverse Question',
  moduleSubtitle:
    'From a wired schematic to its excitation equations, next-state equations, state table and state diagram - and, in reverse, from a sealed black box back to the same picture.',
  scenes: [
    {
      id: 'S00_Cover',
      label: 'The Reverse Question',
      kind: 'cover',
      subtitle: 'Given the wires, find the map. Toggle X below and watch the state diagram walk itself.',
      theoryEN: [
        "Analysis runs a clocked sequential circuit backwards through mathematics: schematic -> excitation equations -> next-state equations -> state table -> state diagram - the exact reverse of design, where you would start from a wanted behaviour and build the circuit.",
        "The demo above is exactly that circuit: two D flip-flops, FF1 (holds Q1) and FF0 (holds Q0), wired so D1 = Q0 and D0 = X XOR Q1 - nothing more than one straight wire and one XOR gate.",
        'Toggle X and press CLK - the highlighted node on the state diagram moves along an edge that was derived, not guessed, straight from those two equations.',
        'Every one of the four states 00, 01, 10, 11 and all eight edges (one per state per value of X) were generated by evaluating the same two equations for every possible input - nothing on that diagram was hand-drawn.',
        'By the end of this module you will run this exact pipeline on two fully worked circuits, then run it in reverse on a sealed black box where you cannot see a single flip-flop.',
      ],
      theoryHI: [
        'Analysis एक clocked sequential circuit को mathematics से पीछे चलाता है: schematic -> excitation equations -> next-state equations -> state table -> state diagram - यह ठीक design का उल्टा है, जहाँ आप एक चाही गई behaviour से शुरू करके circuit बनाते।',
        'ऊपर वाला demo ठीक वही circuit है: दो D flip-flops, FF1 (Q1 रखता है) और FF0 (Q0 रखता है), इस तरह wire किए कि D1 = Q0 और D0 = X XOR Q1 - बस एक सीधी wire और एक XOR gate।',
        'X toggle कीजिए और CLK दबाइए - state diagram पर highlighted node उसी edge पर चलता है जो इन्हीं दो equations से निकाला गया है, अंदाज़े से नहीं।',
        'चारों states 00, 01, 10, 11 और सभी आठ edges (हर state के लिए हर X मान पर एक) उन्हीं दो equations को हर संभव input पर evaluate करके बनाए गए हैं - उस diagram पर कुछ भी हाथ से नहीं खींचा गया।',
        'इस module के अंत तक आप यही pipeline दो पूरे हल किए circuits पर चलाएँगे, फिर इसे उल्टा एक sealed black box पर चलाएँगे जहाँ आप एक भी flip-flop नहीं देख सकते।',
      ],
      transcriptEN:
        'Welcome to circuit analysis - the reverse question. You have a schematic; the job is to work backwards through excitation equations, next-state equations, a state table and finally a state diagram. The demo above is a live two-flip-flop circuit, D1 equals Q0 and D0 equals X XOR Q1: toggle X, tick the clock, and watch the derived diagram walk itself exactly as the equations say it must.',
      transcriptHI:
        'Circuit analysis में आपका स्वागत है - यह उल्टा सवाल है। आपके पास एक schematic है; काम है excitation equations, next-state equations, एक state table और अंत में एक state diagram से पीछे की ओर चलना। ऊपर वाला demo एक live दो-flip-flop circuit है, D1 बराबर Q0 और D0 बराबर X XOR Q1: X toggle कीजिए, clock tick कीजिए, और derived diagram को ठीक वैसे ही चलते देखिए जैसे equations कहते हैं।',
      visualNote:
        "Hero: a small D0=X⊕Q1, D1=Q0 two-flip-flop circuit drawn as a live block diagram beside its fully-derived 4-state diagram; toggling X and ticking CLK walks the highlighted active state around the diagram.",
    },
    {
      id: 'S01_Video',
      label: "Reading A Circuit's Mind",
      kind: 'video',
      subtitle: 'A short film: the exact three steps that turn a schematic into a state diagram.',
      theoryEN: [
        'Before you watch: analysis is a fixed three-step procedure, always in the same order - schematic to excitation equations, excitation equations to next-state/output equations, then tabulate and draw.',
        "Step 1 is pure wire-tracing: follow every flip-flop's data pin back to the gates that feed it and write that Boolean equation in terms of present-state variables and external inputs - never assume the flip-flop type in advance.",
        "Step 2 leans on four short laws you should already have memorised: SR is Q(t+1)=S+R'.Q, JK is Q(t+1)=J.Q'+K'.Q, D is simply Q(t+1)=D, and T is Q(t+1)=T XOR Q.",
        "Watch for the running example: two D flip-flops A and B, one input X, one output Y, with DA=A.X+B.X and DB=A'.X - because D's law has no dependence on Q(t) at all, this circuit's excitation equations already ARE its next-state equations.",
        "The film also previews the reverse trick: the exact same table and diagram can be rebuilt with no schematic at all, just by watching a sealed box's input and output pins - the method this module names 'reverse-engineering' later on.",
      ],
      theoryHI: [
        'देखने से पहले: analysis एक तय तीन-step procedure है, हमेशा उसी क्रम में - schematic से excitation equations, excitation equations से next-state/output equations, फिर tabulate और draw।',
        'Step 1 शुद्ध wire-tracing है: हर flip-flop के data pin को उन gates तक follow कीजिए जो उसे चलाते हैं और वह Boolean equation present-state variables और external inputs के रूप में लिखिए - पहले से flip-flop type मत मान लीजिए।',
        "Step 2 चार छोटे नियमों पर टिका है जो आपको पहले से याद होने चाहिए: SR है Q(t+1)=S+R'.Q, JK है Q(t+1)=J.Q'+K'.Q, D है सीधे Q(t+1)=D, और T है Q(t+1)=T XOR Q।",
        "चलते उदाहरण पर ग़ौर कीजिए: दो D flip-flops A और B, एक input X, एक output Y, DA=A.X+B.X और DB=A'.X के साथ - चूँकि D के नियम में Q(t) पर कोई dependence ही नहीं है, इस circuit के excitation equations पहले से ही इसके next-state equations हैं।",
        "फ़िल्म उल्टी trick की झलक भी देती है: बिना किसी schematic के, बस एक sealed box के input और output pins देखकर, ठीक वही table और diagram फिर बनाए जा सकते हैं - जिस विधि को यह module आगे 'reverse-engineering' कहता है।",
      ],
      transcriptEN:
        "Here's the whole procedure in one breath. Analysis is always three steps, in order: trace the wires into every flip-flop's data pin to get its excitation equation; substitute each flip-flop type's characteristic equation to get the next-state and output equations; then evaluate every present-state-and-input row to fill a state table, and draw that table as circles and labelled arrows, a state diagram. Watch the running example: two D flip-flops, DA equals A-X plus B-X, DB equals A-prime-X - and because a D flip-flop's law is just Q-next equals D, those excitation equations are already the next-state equations, no extra algebra needed. The film closes on the twist: the same table and diagram can be rebuilt with zero schematic, purely by watching a sealed box's pins - reverse-engineering, which this module tackles next.",
      transcriptHI:
        "पूरी procedure एक साँस में। Analysis हमेशा तीन steps है, क्रम में: हर flip-flop के data pin में wires trace करके उसका excitation equation पाइए; हर flip-flop type के characteristic equation से substitute करके next-state और output equations पाइए; फिर हर present-state-और-input row evaluate करके state table भरिए, और उस table को circles और labelled arrows, यानी state diagram, की तरह बनाइए। चलते उदाहरण पर ग़ौर कीजिए: दो D flip-flops, DA बराबर A-X plus B-X, DB बराबर A-prime-X - और चूँकि D flip-flop का नियम बस Q-next बराबर D है, वे excitation equations पहले से ही next-state equations हैं, कोई अतिरिक्त algebra नहीं चाहिए। फ़िल्म एक मोड़ पर बंद होती है: वही table और diagram बिना किसी schematic के, बस एक sealed box के pins देखकर फिर बनाए जा सकते हैं - reverse-engineering, जिसे यह module आगे संभालता है।",
      visualNote:
        'Animated explainer: a schematic morphing step by step into excitation equations, then next-state equations, then a filling state table, then a state diagram; ends on a sealed black box teaser.',
    },
    {
      id: 'S02_Facts',
      label: 'The Analysis Pipeline',
      kind: 'theory',
      subtitle: 'Schematic -> excitation -> next-state/output -> table -> diagram, in that exact order.',
      theoryEN: [
        'Analysis is the name for going from a physical circuit to a mathematical, tabular and graphical description of it - the reverse of design (synthesis), which instead starts from a wanted behaviour and ends at a circuit. Given a schematic that mixes flip-flops with combinational gates, analysis reconstructs precisely what that schematic does, state by state, with nothing left to guesswork.',
        "Step 1 is trace the wires. For every flip-flop's data input - D, or the pair J and K, or the pair S and R, or T - follow the wiring back through whatever AND/OR/NOT gates feed it, and write its Boolean equation purely in terms of the present-state variables and any external inputs. This is the excitation equation, and it comes straight off the picture; you never assume what it will turn out to be.",
        "Step 2 is apply the characteristic equation of whichever flip-flop type is in the circuit, substituting each excitation equation into it, to get the next-state equation Q(t+1) in terms of Q(t) and the inputs. You also write the output equation Y directly from whatever gate logic drives the output pin. The four laws to have ready: SR is Q(t+1)=S+R'.Q (with S.R=0), JK is Q(t+1)=J.Q'+K'.Q, D is simply Q(t+1)=D, and T is Q(t+1)=T XOR Q.",
        "One shortcut is worth memorising on its own: a D flip-flop's characteristic equation has no dependence on Q(t) at all - it is just Q(t+1)=D - so for a D-type circuit, step 2 changes nothing. The excitation equation IS the next-state equation, verbatim. That is exactly why the worked example ahead moves so fast: writing DA and DB in step 1 already finishes step 2.",
        "Step 3 is evaluate the next-state and output equations for every combination of present state and input, forming the state table, then read each row as a labelled arc to draw the state diagram - circles for states, directed arrows for transitions, each one labelled input/output. Build every single row, even ones that look unreachable at a glance; you can only tell which states are truly reachable once the whole table is finished, never before.",
      ],
      theoryHI: [
        'Analysis उस काम का नाम है जिसमें एक भौतिक circuit से एक mathematical, tabular और graphical description तक जाते हैं - यह design (synthesis) का उल्टा है, जो इसके बजाय एक चाही गई behaviour से शुरू होकर एक circuit पर ख़त्म होता है। एक ऐसा schematic दिया हो जिसमें flip-flops और combinational gates मिले-जुले हों, तो analysis ठीक-ठीक फिर से बनाता है कि वह schematic क्या करता है, state-दर-state, कुछ भी अंदाज़े पर छोड़े बिना।',
        "Step 1 है wires trace कीजिए। हर flip-flop के data input के लिए - D, या जोड़ी J और K, या जोड़ी S और R, या T - उस wiring को AND/OR/NOT gates के पीछे तक follow कीजिए जो उसे चलाते हैं, और उसका Boolean equation केवल present-state variables और किसी भी external input के रूप में लिखिए। यही excitation equation है, और यह सीधे picture से आता है; आप कभी अंदाज़ा नहीं लगाते कि यह क्या निकलेगा।",
        "Step 2 है circuit में जो भी flip-flop type है उसका characteristic equation लगाइए, हर excitation equation को उसमें substitute करके, ताकि next-state equation Q(t+1), Q(t) और inputs के रूप में मिले। output pin को जो भी gate logic चलाता है उससे सीधे output equation Y भी लिखिए। चार नियम तैयार रखिए: SR है Q(t+1)=S+R'.Q (S.R=0 के साथ), JK है Q(t+1)=J.Q'+K'.Q, D है सीधे Q(t+1)=D, और T है Q(t+1)=T XOR Q।",
        "एक shortcut अकेले याद करने लायक़ है: D flip-flop के characteristic equation में Q(t) पर कोई dependence ही नहीं है - यह बस Q(t+1)=D है - तो D-type circuit के लिए, step 2 कुछ नहीं बदलता। excitation equation ही next-state equation है, अक्षरशः। इसीलिए आगे वाला worked example इतनी तेज़ी से चलता है: step 1 में DA और DB लिखना ही step 2 पूरा कर देता है।",
        "Step 3 है present state और input के हर combination पर next-state और output equations evaluate कीजिए, जिससे state table बने, फिर हर row को एक labelled arc की तरह पढ़कर state diagram बनाइए - states के लिए circles, transitions के लिए directed arrows, हर एक input/output से labelled। हर एक row बनाइए, यहाँ तक कि जो देखने में unreachable लगे; कौन से states सच में reachable हैं यह पूरी table बनने के बाद ही, पहले कभी नहीं, पता चलता है।",
      ],
      transcriptEN:
        "The procedure is fixed and always runs in this order: trace wires for excitation, substitute characteristic equations for next-state and output, then tabulate every row before drawing the diagram. A D flip-flop's excitation equation doubles as its next-state equation because Q(t+1)=D has no dependence on Q(t) at all.",
      transcriptHI:
        "Procedure तय है और हमेशा इसी क्रम में चलता है: excitation के लिए wires trace कीजिए, next-state और output के लिए characteristic equations substitute कीजिए, फिर diagram बनाने से पहले हर row tabulate कीजिए। D flip-flop का excitation equation उसका next-state equation भी है क्योंकि Q(t+1)=D में Q(t) पर कोई dependence नहीं है।",
      visualNote:
        'A five-stage pipeline strip (schematic -> excitation -> next-state/output -> state table -> state diagram) plus a quick-reference of the four characteristic equations and a live single D flip-flop to drive by hand.',
    },
    {
      id: 'S03_WorkedExample',
      label: 'The A-B Circuit, Solved End To End',
      kind: 'theory',
      subtitle: 'Two D flip-flops, one input X, one output Y - every row computed live below.',
      theoryEN: [
        'Here is the classic circuit, walked once by hand so the pipeline stops being abstract. Two D flip-flops named A and B, one external input X, one output Y, all sharing one clock. Nothing here is chosen to be tricky - it is chosen to be the cleanest possible run through all three steps.',
        'Step 1, trace the wiring: DA = A.X + B.X and DB = A\'.X. These come straight off the AND and OR gates feeding each D pin - two products summed into DA, one product straight into DB - and nothing else.',
        "Step 2 is almost free here: because D's characteristic equation is Q(t+1)=D with no dependence on Q(t), the excitation equations become the next-state equations by simply renaming the pins: A(t+1) = A.X + B.X and B(t+1) = A'.X. Read the output gate the same direct way: Y = (A+B).X'.",
        "Grind one row by hand before trusting the machine: at present state AB=01 with X=1, DA = 0.1+1.1 = 1, DB = 1.1 = 1, so the next state is 11; Y = (0+1).0 = 0. Every row in the table below, and the sample-calculation callout inside the step-through, reaches that same number by evaluating the same two lines of code.",
        "Step 3 tabulates all eight present-state/input rows and step 4 turns them into the state diagram beneath it. Notice Y depends on BOTH the present state and the input X - a Mealy-flavoured output that lives on the transition arc rather than inside the state circle, a distinction module 39 names formally as the Mealy machine.",
      ],
      theoryHI: [
        'यह रहा classic circuit, एक बार हाथ से चलाया गया ताकि pipeline abstract न रह जाए। दो D flip-flops जिनके नाम A और B, एक external input X, एक output Y, सब एक ही clock साझा करते हुए। यहाँ कुछ भी उलझाने के लिए नहीं चुना गया - बल्कि तीनों steps से सबसे साफ़ गुज़रने के लिए चुना गया है।',
        "Step 1, wiring trace कीजिए: DA = A.X + B.X और DB = A'.X। ये सीधे उन AND और OR gates से आते हैं जो हर D pin को चलाते हैं - दो products जोड़कर DA में, एक product सीधे DB में - और कुछ नहीं।",
        "यहाँ Step 2 लगभग मुफ़्त है: चूँकि D का characteristic equation Q(t+1)=D है, Q(t) पर कोई dependence नहीं, excitation equations बस pins का नाम बदलकर next-state equations बन जाते हैं: A(t+1) = A.X + B.X और B(t+1) = A'.X। Output gate को भी उतने ही सीधे पढ़िए: Y = (A+B).X'।",
        "मशीन पर भरोसा करने से पहले एक row हाथ से पीस लीजिए: present state AB=01 पर X=1 के साथ, DA = 0.1+1.1 = 1, DB = 1.1 = 1, तो next state 11 है; Y = (0+1).0 = 0। नीचे table की हर row, और step-through के अंदर sample-calculation callout, इन्हीं दो lines of code को evaluate करके वही संख्या पाते हैं।",
        "Step 3 सभी आठ present-state/input rows को tabulate करता है और step 4 उन्हें नीचे state diagram में बदल देता है। ग़ौर कीजिए Y present state और input X दोनों पर निर्भर करता है - एक Mealy-रंग का output जो state circle के अंदर नहीं, transition arc पर रहता है, यह भेद module 39 औपचारिक रूप से Mealy machine कहकर बताता है।",
      ],
      transcriptEN:
        'DA equals A-X plus B-X, DB equals A-prime-X; since D-type next-state equals D directly, those excitation equations are the next-state equations. Y equals (A plus B) times X-prime - an output that depends on state and input together, living on the arc, not inside the circle.',
      transcriptHI:
        "DA बराबर A-X plus B-X, DB बराबर A-prime-X; चूँकि D-type का next-state सीधे D के बराबर है, वे excitation equations ही next-state equations हैं। Y बराबर (A plus B) गुणा X-prime - एक output जो state और input दोनों पर निर्भर है, circle के अंदर नहीं, arc पर रहता है।",
      visualNote:
        'A five-step StepThrough (circuit -> excitation -> next-state/output -> sample row -> full table), a computed 8-row state table, an interactive walker (toggle X, tick CLK, watch the live state + Y), and the derived state diagram.',
    },
    {
      id: 'S04_Reverse',
      label: 'The Black Box',
      kind: 'theory',
      subtitle: 'No schematic, only X in and Y out - reconstruct the machine from behaviour alone.',
      theoryEN: [
        'Every analysis so far assumed you HAD the schematic. Reverse-engineering reaches the exact same destination - a state table and a state diagram - with the schematic missing entirely: you are handed a sealed synchronous box with one input pin, one output pin and a clock pin, and nothing else to look at.',
        'The method: apply a controlled sequence of input values, one clock edge at a time, and record the output after every edge. Because the box is synchronous and deterministic, feeding the exact same input while the box is in the exact same internal condition always produces the exact same output and the exact same next condition - so a repeated output pattern under a repeated input is evidence that the box has returned to a state it has already visited.',
        'Group the observations by that repetition: every distinct behaviour signature you can tell apart becomes a candidate state, and every observed (input leads to output, next signature) becomes a candidate edge, labelled input/output exactly like an ordinary state diagram. You are building the same table and the same diagram as before - just from probes instead of from a picture.',
        'This is genuinely harder than forward analysis, because you cannot assume anything about the flip-flop type, or even how many flip-flops sit inside - the one output pin is all you ever get to see. Two behaviours that look different at first probing might secretly be the same state seen from two different lead-ins, a subtlety that state reduction (module 40) resolves properly; here the goal is only the method.',
        'Watch the short film below, then work the black-box probe underneath it yourself: toggle X, tick the clock, and read the trace the box prints out. A "peek inside" switch lets you check your reconstruction against the real flip-flops once you are done - a check a real reverse-engineer never gets to use.',
      ],
      theoryHI: [
        'अब तक हर analysis ने माना कि आपके पास schematic है। Reverse-engineering ठीक उसी मंज़िल तक पहुँचता है - एक state table और एक state diagram - पर schematic पूरी तरह ग़ायब होने पर: आपको एक sealed synchronous box दिया जाता है जिसमें एक input pin, एक output pin और एक clock pin है, और देखने को कुछ और नहीं।',
        'विधि: input values का एक नियंत्रित क्रम लगाइए, एक बार में एक clock edge, और हर edge के बाद output दर्ज कीजिए। चूँकि box synchronous और deterministic है, ठीक वही input देना जब box ठीक उसी internal condition में हो हमेशा वही output और वही next condition देता है - तो एक दोहराए गए input पर दोहराया गया output pattern इस बात का सबूत है कि box किसी पहले देखे state में लौट आया है।',
        'निरीक्षणों को उसी दोहराव से समूहित कीजिए: हर अलग पहचानी जा सकने वाली behaviour signature एक candidate state बन जाती है, और हर देखा गया (input से output, next signature) एक candidate edge बन जाता है, ठीक सामान्य state diagram की तरह input/output से labelled। आप वही table और वही diagram बना रहे हैं - बस picture की जगह probes से।',
        'यह forward analysis से सच में कठिन है, क्योंकि आप flip-flop type के बारे में कुछ भी नहीं मान सकते, या यह भी नहीं कि अंदर कितने flip-flops बैठे हैं - अकेला output pin ही है जो आप कभी देख पाते हैं। दो behaviours जो पहले probing पर अलग दिखें, गुप्त रूप से एक ही state हो सकती हैं जो दो अलग lead-ins से देखी गई हों, यह सूक्ष्मता state reduction (module 40) ठीक से सुलझाता है; यहाँ लक्ष्य सिर्फ़ विधि है।',
        'नीचे छोटी फ़िल्म देखिए, फिर उसके नीचे वाला black-box probe ख़ुद चलाइए: X toggle कीजिए, clock tick कीजिए, और box जो trace छापता है उसे पढ़िए। एक "peek inside" switch आपको अपना reconstruction असली flip-flops से मिलाने देता है, जब आप कर चुकें - एक जाँच जो असली reverse-engineer को कभी नहीं मिलती।',
      ],
      transcriptEN:
        'A sealed box has one input pin, one output pin, one clock pin and no schematic. Apply a controlled input sequence, record every output, and treat a repeated output pattern under a repeated input as proof the box revisited a state - build the same table and diagram, purely from probes.',
      transcriptHI:
        'एक sealed box में एक input pin, एक output pin, एक clock pin है और कोई schematic नहीं। एक नियंत्रित input sequence लगाइए, हर output दर्ज कीजिए, और दोहराए गए input पर दोहराए गए output pattern को इस सबूत की तरह लीजिए कि box किसी state पर लौटा - वही table और diagram बनाइए, पूरी तरह probes से।',
      visualNote:
        'A second embedded video player (dsd38-reverse.mp4) plus a sealed black-box probe: toggle X, tick CLK, watch a running trace of Y, and a "peek inside" reveal that checks the reconstruction against the real hidden flip-flops.',
    },
    {
      id: 'S05_Practice',
      label: 'Your Turn: The JK Pair',
      kind: 'theory',
      subtitle: 'Same three steps, a JK-based circuit this time - output written inside the state.',
      theoryEN: [
        'Practice the identical pipeline on a different circuit so the three steps become a reflex, not a memorised example. This one uses two JK flip-flops, A and B, one external input X, and an output wired straight off the present state instead of off an input.',
        'Step 1, the excitation equations traced off the schematic: JA = B, KA = B.X\', JB = X, KB = A. Four small equations, one pair per flip-flop, read the same way as before - straight off the gates feeding each pin.',
        "Step 2 does real work this time. Q(t+1) = J.Q' + K'.Q must be evaluated row by row, because - unlike the D-type worked example - a JK's next state is not simply equal to one of its own inputs; the same (J,K) pair produces a different Q(t+1) depending on what the present Q already was. There is no shortcut here the way there was for D.",
        'The output is Y = A.B, wired only off the present-state variables, never off X - so it belongs written inside each state circle rather than on an arc, the opposite placement to the earlier Mealy-flavoured Y. Hold that contrast; it is exactly the Moore-versus-Mealy question the next module names formally.',
        'Steps 3 and 4 build the full eight-row table below - JA, KA, JB, KB and the resulting next state for every present-state/input combination - then read the state diagram it produces, with each state circle now carrying its own fixed Y.',
      ],
      theoryHI: [
        'यही pipeline एक अलग circuit पर वापर कर देखिए ताकि तीनों steps एक reflex बन जाएँ, याद किया उदाहरण नहीं। यह वाला दो JK flip-flops वापरता है, A और B, एक external input X, और एक output जो input से नहीं बल्कि सीधे present state से wire है।',
        "Step 1, schematic से trace किए excitation equations: JA = B, KA = B.X', JB = X, KB = A। चार छोटे equations, हर flip-flop के लिए एक जोड़ी, पहले जैसे ही पढ़े गए - सीधे हर pin को चलाते gates से।",
        "इस बार Step 2 असल काम करता है। Q(t+1) = J.Q' + K'.Q को row-दर-row evaluate करना होगा, क्योंकि - D-type worked example के उलट - JK का next state सीधे उसके अपने किसी input के बराबर नहीं होता; वही (J,K) जोड़ी अलग Q(t+1) देती है इस पर निर्भर करते हुए कि present Q पहले से क्या था। यहाँ D जैसा कोई shortcut नहीं है।",
        'Output है Y = A.B, केवल present-state variables से wire, कभी X से नहीं - तो यह हर state circle के अंदर लिखा जाता है, arc पर नहीं, पहले वाले Mealy-रंग के Y से उलटी जगह। यह भेद पकड़े रखिए; यही Moore-versus-Mealy सवाल है जिसे अगला module औपचारिक रूप से नाम देता है।',
        'Steps 3 और 4 नीचे पूरी आठ-row table बनाते हैं - JA, KA, JB, KB और हर present-state/input combination के लिए मिलता next state - फिर इससे बना state diagram पढ़िए, जहाँ हर state circle अब अपना तय Y साथ रखता है।',
      ],
      transcriptEN:
        "JA equals B, KA equals B AND NOT X, JB equals X, KB equals A - and this time the JK characteristic equation must be evaluated every single row, because the same J,K pair answers differently depending on the present Q. Y equals A AND B, written inside the state, not on the arc.",
      transcriptHI:
        "JA बराबर B, KA बराबर B AND NOT X, JB बराबर X, KB बराबर A - और इस बार JK characteristic equation को हर row पर evaluate करना पड़ता है, क्योंकि वही J,K जोड़ी present Q पर निर्भर करते हुए अलग जवाब देती है। Y बराबर A AND B, state के अंदर लिखा गया, arc पर नहीं।",
      visualNote:
        'A live single JK flip-flop to recall the characteristic equation, then a five-step StepThrough for the two-JK circuit, the computed 8-row table, and the resulting state diagram with Y shown inside each node.',
    },
    {
      id: 'S06_Analogy',
      label: "The Detective's Method",
      kind: 'theory',
      subtitle: 'A detective reconstructs a suspect\'s routine by watching the same trigger repeat.',
      theoryEN: [
        'Hold this picture for the reverse-engineering idea: a detective cannot see inside a suspect\'s head, only watch what the suspect does. Across many days, whenever the same trigger shows up while the suspect was already in the same routine the night before, the same action keeps showing up too - that repetition IS the hidden internal state revealing itself indirectly, exactly the black-box logic from two pages ago.',
        'Map the terms directly onto the vocabulary you just used: the suspect\'s clocked routine is the state; the trigger on a given day is the input X; the action observed that day is the output Y; and the case-file map the detective eventually pins to the corkboard - one circle per distinct routine, one labelled arrow per (trigger, action) leading to the next routine - is exactly a state diagram.',
        'The detective builds that map with the same discipline as step 3 of the analysis procedure: log every observation, never throw a day away just because its trigger looked unremarkable, and only after enough days are logged does the full picture - which routines exist, and which triggers move between them - become trustworthy.',
        'Reuse the exact A-B circuit from earlier as the case file below: each of its eight rows is relabelled as one logged day, present state AB as "the routine the suspect was already in", X as "the day\'s trigger", and Y as "the action witnessed". Watch the same eight rows turn into the same state diagram - proof that the detective\'s method and circuit analysis are the identical procedure in different clothes.',
        'Only one thing separates "engineer with a schematic," "engineer with a sealed chip," and "detective with a case file": how the state table gets filled in - by tracing wires, by probing pins, or by logging days. The moment the table exists, the state diagram, and everything else about the machine, follows by the exact same rule.',
      ],
      theoryHI: [
        'Reverse-engineering के idea के लिए यह तस्वीर पकड़े रखिए: एक detective किसी suspect के दिमाग़ के अंदर नहीं देख सकता, सिर्फ़ यह देख सकता है कि suspect क्या करता है। कई दिनों में, जब भी वही trigger आता है जबकि suspect पिछली रात पहले से उसी routine में था, वही action भी दोहराता है - वह दोहराव ही hidden internal state का परोक्ष रूप से प्रकट होना है, ठीक दो पन्ने पहले वाला black-box logic।',
        'शब्दों को सीधे उसी शब्दावली पर बैठाइए जो आपने अभी वापरी: suspect का clocked routine है state; किसी दिन का trigger है input X; उस दिन देखा गया action है output Y; और वह case-file map जो detective आख़िर में corkboard पर टांगता है - हर अलग routine के लिए एक circle, हर (trigger, action) से अगले routine तक एक labelled arrow - ठीक एक state diagram है।',
        'Detective वह map उसी अनुशासन से बनाता है जो analysis procedure के step 3 में है: हर निरीक्षण दर्ज कीजिए, किसी दिन को सिर्फ़ इसलिए मत छोड़िए कि उसका trigger साधारण लगा, और पर्याप्त दिन दर्ज होने के बाद ही पूरी तस्वीर - कौन-कौन से routines हैं, और कौन से triggers उनके बीच ले जाते हैं - भरोसे लायक़ बनती है।',
        'नीचे case file की तरह वही पहले वाला A-B circuit वापरिए: इसकी आठों rows में से हर एक एक दर्ज दिन की तरह फिर से नाम दी गई है, present state AB "वह routine जिसमें suspect पहले से था", X "उस दिन का trigger", और Y "देखा गया action"। देखिए कैसे वही आठ rows वही state diagram बन जाती हैं - सबूत कि detective की विधि और circuit analysis अलग कपड़ों में एक ही procedure हैं।',
        '"schematic वाला engineer," "sealed chip वाला engineer," और "case file वाला detective" के बीच बस एक चीज़ अलग है: state table कैसे भरी गई - wires trace करके, pins probe करके, या दिन दर्ज करके। जिस पल table बनती है, state diagram, और machine के बारे में बाक़ी सब कुछ, ठीक उसी नियम से निकल आता है।',
      ],
      transcriptEN:
        "A detective watches, never reads minds: the same trigger from the same prior routine keeps producing the same action, and that repetition is the hidden state showing through. Routine is the state, trigger is X, action is Y - log enough days and the case file becomes a state diagram.",
      transcriptHI:
        "एक detective देखता है, दिमाग़ नहीं पढ़ता: वही trigger, वही पिछले routine से, बार-बार वही action देता है, और वह दोहराव hidden state का झलकना है। Routine है state, trigger है X, action है Y - काफ़ी दिन दर्ज कीजिए और case file एक state diagram बन जाती है।",
      visualNote:
        'The A-B worked circuit relabelled as a detective\'s case file: eight logged "days" (present routine, trigger, action, next routine) building into the same derived state diagram, with detective/notebook iconography.',
    },
    {
      id: 'S07_Build',
      label: 'Build It, Then Prove It',
      kind: 'theory',
      subtitle: 'Wire the A-B circuit for real, then match your own table against this module\'s.',
      theoryEN: [
        'Every equation in this module was checked by a machine; checking one by hand, in real gates, is what turns the analysis procedure into permanent knowledge instead of a memorised recipe.',
        "On the workbench you will place two D flip-flops, wire DA = A.X + B.X from two ANDs and an OR, wire DB = A'.X from one inverter and one AND, and wire the output Y = (A+B).X' from an OR and an inverter.",
        'Then step the shared clock by hand, one edge at a time, starting from AB=00, and write down every present-state/input row you land on as you go. By the time you have cycled through all four states at both values of X, you will have rebuilt this module\'s entire state table by hand, on real hardware.',
        "Compare your handwritten table, row for row, against the computed one from S03. If a row disagrees, the mistake is almost always a swapped wire on DA or DB, not a flip-flop fault - a D flip-flop has exactly one behaviour, Q(t+1)=D, and it never gets that wrong.",
      ],
      theoryHI: [
        'इस module का हर equation एक machine से जाँचा गया; एक को हाथ से, असली gates में जाँचना ही analysis procedure को याद किए recipe की बजाय स्थायी ज्ञान बनाता है।',
        "Workbench पर आप दो D flip-flops रखेंगे, DA = A.X + B.X को दो ANDs और एक OR से wire करेंगे, DB = A'.X को एक inverter और एक AND से wire करेंगे, और output Y = (A+B).X' को एक OR और एक inverter से wire करेंगे।",
        'फिर साझा clock को हाथ से चलाइए, एक बार में एक edge, AB=00 से शुरू करके, और जैसे-जैसे चलें हर present-state/input row लिखते जाइए। जब तक आप दोनों X मानों पर चारों states घूम चुके होंगे, आप इस module की पूरी state table हाथ से, असली hardware पर, दोबारा बना चुके होंगे।',
        "अपनी हाथ से बनाई table को, row-दर-row, S03 की computed table से मिलाइए। अगर कोई row न मिले, तो ग़लती लगभग हमेशा DA या DB पर बदली हुई wire होती है, flip-flop का दोष नहीं - एक D flip-flop का बर्ताव ठीक एक है, Q(t+1)=D, और यह कभी ग़लत नहीं होता।",
      ],
      transcriptEN:
        'Wire two D flip-flops with DA=A.X+B.X and DB=A\'.X, plus Y=(A+B).X\', then step the clock by hand and rebuild the state table on real hardware.',
      transcriptHI:
        "दो D flip-flops को DA=A.X+B.X और DB=A'.X, साथ ही Y=(A+B).X', से wire कीजिए, फिर clock को हाथ से चलाइए और state table असली hardware पर दोबारा बनाइए।",
      visualNote: 'WorkbenchCTA linking to the guided build tutorial "analyze-clocked-circuit".',
    },
    {
      id: 'S08_Flashcards',
      label: 'Analysis Vocabulary',
      kind: 'flashcards',
      subtitle: 'Eight terms, eight real definitions - flip each card to check yourself.',
      theoryEN: [],
      theoryHI: [],
      transcriptEN: 'Eight flashcards on the vocabulary of clocked-sequential-circuit analysis.',
      transcriptHI: 'Clocked-sequential-circuit analysis की शब्दावली पर आठ flashcards।',
      visualNote: 'A responsive flip-card grid, term on the front, the real logic on the back.',
    },
    {
      id: 'S09_Quiz',
      label: 'Practice - Circuit Analysis',
      kind: 'quiz',
      subtitle: 'Seven questions on the pipeline, the worked circuit and reverse-engineering.',
      theoryEN: [],
      theoryHI: [],
      transcriptEN: 'A seven-question practice set covering the analysis procedure end to end.',
      transcriptHI: 'Analysis procedure को पूरी तरह ढकने वाला सात-सवालों का practice set।',
      visualNote: 'QuizArena-driven practice quiz with instant right/wrong explanations.',
    },
    {
      id: 'S10_Recap',
      label: 'The Whole Pipeline, One More Time',
      kind: 'recap',
      subtitle: 'Schematic to state diagram - and state diagram to schematic, in reverse.',
      theoryEN: [
        'Analysis is one fixed pipeline: trace the wires into every flip-flop for the excitation equations, substitute each type\'s characteristic equation for the next-state and output equations, then tabulate every present-state/input row and draw the state diagram - circles for states, arrows labelled input/output for transitions.',
        "A D flip-flop is the fast case: because Q(t+1)=D has no dependence on Q(t), its excitation equation already IS its next-state equation. The worked A-B circuit rode that shortcut all the way to an 8-row table and a 4-state diagram, with a Mealy-flavoured output Y=(A+B).X' sitting on the transition arcs.",
        'The JK practice circuit rode the opposite case: the characteristic equation had to be evaluated on every single row, because the same (J,K) pair answers differently depending on the present state - and its output, wired only off the state, sat inside the circles instead, previewing Moore-versus-Mealy.',
        'Reverse-engineering runs the identical destination without a schematic: probe a sealed box with a controlled input sequence, treat a repeated output under a repeated input as proof of a revisited state, and build the same table and diagram from behaviour alone - the detective\'s method wearing an engineer\'s coat.',
        'Two modules wait ahead: module 39 gives the Mealy-versus-Moore split you already glimpsed a formal name, and module 40 takes this exact pipeline forward again - from a wanted state diagram all the way down to minimised gates.',
      ],
      theoryHI: [
        'Analysis एक तय pipeline है: excitation equations के लिए हर flip-flop में wires trace कीजिए, next-state और output equations के लिए हर type का characteristic equation substitute कीजिए, फिर हर present-state/input row tabulate करके state diagram बनाइए - states के लिए circles, transitions के लिए input/output से labelled arrows।',
        "D flip-flop तेज़ case है: चूँकि Q(t+1)=D में Q(t) पर कोई dependence नहीं, इसका excitation equation पहले से ही next-state equation है। worked A-B circuit उसी shortcut पर सवार होकर एक 8-row table और एक 4-state diagram तक पहुँचा, transition arcs पर बैठे Mealy-रंग के output Y=(A+B).X' के साथ।",
        'JK practice circuit उलटा case था: characteristic equation को हर row पर evaluate करना पड़ा, क्योंकि वही (J,K) जोड़ी present state पर निर्भर करते हुए अलग जवाब देती है - और इसका output, केवल state से wire, circles के अंदर बैठा, Moore-versus-Mealy की झलक देते हुए।',
        'Reverse-engineering बिना schematic के वही मंज़िल पाता है: एक sealed box को नियंत्रित input sequence से probe कीजिए, दोहराए गए input पर दोहराए गए output को एक दोहराए state के सबूत की तरह लीजिए, और वही table व diagram सिर्फ़ behaviour से बनाइए - detective की विधि, engineer के कोट में।',
        'आगे दो modules इंतज़ार कर रहे हैं: module 39 उसी Mealy-versus-Moore भेद को औपचारिक नाम देता है जिसकी आपने झलक देखी, और module 40 इसी pipeline को फिर आगे ले जाता है - एक चाही गई state diagram से लेकर minimised gates तक।',
      ],
      transcriptEN:
        'Analysis is one pipeline: excitation, next-state/output, table, diagram. D-type collapses steps 1 and 2 into one; JK does not. Reverse-engineering reaches the same table with no schematic at all, purely by probing behaviour.',
      transcriptHI:
        'Analysis एक pipeline है: excitation, next-state/output, table, diagram। D-type steps 1 और 2 को एक में समेट देता है; JK नहीं करता। Reverse-engineering बिना किसी schematic के, सिर्फ़ behaviour probe करके, वही table पाता है।',
      visualNote: 'Recap flow-rail plus the closing prose - no extra bespoke visual beyond the shared FlowRail.',
    },
  ],
  flashcards: [
    {
      frontEN: 'Analysis (sequential logic)',
      backEN:
        'Going from a physical circuit to a mathematical/tabular/graphical description of it - the reverse of design/synthesis, which starts from a wanted behaviour and builds the circuit.',
      frontHI: 'Analysis (sequential logic)',
      backHI:
        'एक भौतिक circuit से एक mathematical/tabular/graphical description तक जाना - यह design/synthesis का उल्टा है, जो एक चाही गई behaviour से शुरू होकर circuit बनाता है।',
    },
    {
      frontEN: 'Excitation equation',
      backEN:
        "The Boolean equation for one flip-flop's data input (D, J&K, S&R, or T), traced straight off the wiring, in terms of present-state variables and external inputs.",
      frontHI: 'Excitation equation',
      backHI:
        'एक flip-flop के data input (D, J&K, S&R, या T) का Boolean equation, सीधे wiring से trace किया गया, present-state variables और external inputs के रूप में।',
    },
    {
      frontEN: 'Next-state equation',
      backEN:
        "Q(t+1) written in terms of Q(t) and inputs - obtained by substituting each excitation equation into that flip-flop type's characteristic equation.",
      frontHI: 'Next-state equation',
      backHI:
        'Q(t+1), Q(t) और inputs के रूप में लिखा गया - हर excitation equation को उस flip-flop type के characteristic equation में substitute करके मिलता है।',
    },
    {
      frontEN: 'Why a D flip-flop skips extra algebra',
      backEN:
        'Its characteristic equation is Q(t+1)=D with no dependence on Q(t) at all, so the excitation equation D=... is already the next-state equation - no substitution needed.',
      frontHI: 'D flip-flop अतिरिक्त algebra क्यों छोड़ देता है',
      backHI:
        'इसका characteristic equation Q(t+1)=D है, Q(t) पर कोई dependence नहीं, तो excitation equation D=... पहले से ही next-state equation है - कोई substitution नहीं चाहिए।',
    },
    {
      frontEN: 'State table',
      backEN:
        'Present state x input -> next state, output - one row for every combination, built by evaluating the next-state/output equations exhaustively, never skipping a row that looks unreachable.',
      frontHI: 'State table',
      backHI:
        'Present state x input -> next state, output - हर combination के लिए एक row, next-state/output equations को पूरी तरह evaluate करके बनाई गई, किसी unreachable लगती row को छोड़े बिना।',
    },
    {
      frontEN: 'State diagram',
      backEN:
        'The state table drawn as a graph: circles are states, directed arcs are transitions, and each arc is labelled input/output.',
      frontHI: 'State diagram',
      backHI:
        'State table को एक graph की तरह खींचा गया: circles states हैं, directed arcs transitions हैं, और हर arc input/output से labelled है।',
    },
    {
      frontEN: 'Mealy-flavoured output (preview)',
      backEN:
        "An output written as a function of state AND input, e.g. Y=(A+B).X' - it lives on the transition arc, not inside the state circle (formalised as the Mealy machine in module 39).",
      frontHI: 'Mealy-रंग का output (preview)',
      backHI:
        "state AND input दोनों के function की तरह लिखा output, जैसे Y=(A+B).X' - यह transition arc पर रहता है, state circle के अंदर नहीं (module 39 में Mealy machine कहकर औपचारिक किया गया)।",
    },
    {
      frontEN: 'Reverse-engineering a black box',
      backEN:
        'Building the state table/diagram from observed input/output behaviour alone, with no schematic - probe a controlled input sequence, and treat a repeated output pattern under a repeated input as evidence of a repeated internal state.',
      frontHI: 'Black box को reverse-engineer करना',
      backHI:
        'सिर्फ़ observed input/output behaviour से, बिना किसी schematic के, state table/diagram बनाना - एक नियंत्रित input sequence probe कीजिए, और दोहराए गए input पर दोहराए गए output pattern को एक दोहराए internal state के सबूत की तरह लीजिए।',
    },
  ],
  quiz: [
    {
      questionEN: 'What is the correct order of the clocked-sequential analysis procedure?',
      options: [
        'Schematic -> excitation equations -> next-state/output equations -> state table -> state diagram',
        'Schematic -> state diagram -> state table -> excitation equations',
        'State table -> schematic -> excitation equations -> state diagram',
        'Excitation equations -> schematic -> state diagram -> state table',
      ],
      answerIndex: 0,
      explainEN:
        'Analysis always runs forward in this order: trace the wires for excitation equations, substitute characteristic equations for next-state/output equations, tabulate every row, then draw the state diagram.',
      explainHI:
        'Analysis हमेशा इसी क्रम में आगे चलता है: excitation equations के लिए wires trace कीजिए, next-state/output equations के लिए characteristic equations substitute कीजिए, हर row tabulate कीजिए, फिर state diagram बनाइए।',
      questionHI: 'Clocked-sequential analysis procedure का सही क्रम क्या है?',
    },
    {
      questionEN:
        "For the worked A-B circuit (DA=A.X+B.X, DB=A'.X), present state AB=01 with X=1: what is the next state?",
      options: ['00', '01', '10', '11'],
      answerIndex: 3,
      explainEN: "DA = 0.1+1.1 = 1, DB = 1.1 = 1, so next state A(t+1)B(t+1) = 11 - exactly the deck's sample row.",
      explainHI: "DA = 0.1+1.1 = 1, DB = 1.1 = 1, तो next state A(t+1)B(t+1) = 11 - ठीक deck वाली sample row।",
      questionHI: "Worked A-B circuit (DA=A.X+B.X, DB=A'.X) में, present state AB=01 और X=1 पर, next state क्या है?",
    },
    {
      questionEN: "For the same circuit, output Y=(A+B).X'. At present state AB=10 with X=1, what is Y?",
      options: ['0', '1', 'undefined', 'depends on B only'],
      answerIndex: 0,
      explainEN: "Y = (1+0).(1') = 1.0 = 0 - X=1 forces X' to 0, which zeroes the whole output regardless of A or B.",
      explainHI: "Y = (1+0).(1') = 1.0 = 0 - X=1, X' को 0 कर देता है, जो A या B चाहे जो हों पूरे output को शून्य कर देता है।",
      questionHI: "उसी circuit के लिए, output Y=(A+B).X'। present state AB=10 और X=1 पर, Y क्या है?",
    },
    {
      questionEN: "Which characteristic equation converts a JK flip-flop's excitation equations into its next-state equation?",
      options: [
        'Q(t+1) = D',
        "Q(t+1) = J.Q' + K'.Q",
        "Q(t+1) = S + R'.Q",
        'Q(t+1) = T XOR Q',
      ],
      answerIndex: 1,
      explainEN:
        "The JK characteristic equation is Q(t+1)=J.Q'+K'.Q; substitute JA/KA and JB/KB into it to get the next-state equations for a JK-based circuit.",
      explainHI:
        "JK characteristic equation है Q(t+1)=J.Q'+K'.Q; इसमें JA/KA और JB/KB substitute करने से JK-based circuit के next-state equations मिलते हैं।",
      questionHI: 'JK flip-flop के excitation equations को उसके next-state equation में कौन सा characteristic equation बदलता है?',
    },
    {
      questionEN: "Why does a D flip-flop's excitation equation double as its next-state equation?",
      options: [
        'Because D flip-flops ignore the clock',
        'Because Q(t+1)=D has no dependence on Q(t)',
        'Because D flip-flops have no excitation table',
        'Because D is always equal to X',
      ],
      answerIndex: 1,
      explainEN:
        "D's characteristic equation is just Q(t+1)=D, with Q(t) nowhere in it - so whatever excitation equation you traced for D IS already the next-state equation, no substitution required.",
      explainHI:
        "D का characteristic equation बस Q(t+1)=D है, इसमें Q(t) कहीं नहीं है - तो जो भी excitation equation आपने D के लिए trace किया वही पहले से next-state equation है, कोई substitution नहीं चाहिए।",
      questionHI: "D flip-flop का excitation equation उसका next-state equation भी क्यों बन जाता है?",
    },
    {
      questionEN: 'You are reverse-engineering a sealed synchronous box with no schematic. What is the correct first move?',
      options: [
        'Guess the flip-flop type and write its characteristic equation',
        'Apply a controlled sequence of inputs, one clock edge at a time, and record every output',
        'Assume the box has exactly two flip-flops',
        'Skip straight to drawing the state diagram',
      ],
      answerIndex: 1,
      explainEN:
        'With no schematic there is nothing to trace, so you must probe: apply inputs edge by edge and log every output before you can group observations into candidate states.',
      explainHI:
        'बिना schematic के trace करने को कुछ नहीं है, तो आपको probe करना होगा: edge-दर-edge inputs लगाइए और हर output दर्ज कीजिए, तभी आप निरीक्षणों को candidate states में समूहित कर सकते हैं।',
      questionHI: 'आप एक sealed synchronous box को बिना schematic reverse-engineer कर रहे हैं। सही पहला क़दम क्या है?',
    },
    {
      questionEN:
        "In the worked A-B circuit, Y=(A+B).X' depends on both the present state and the input X. What output placement does this call for on the state diagram?",
      options: [
        'Written inside each state circle',
        'Written on each transition arc as input/output',
        'Omitted from the diagram entirely',
        'Written only on self-loops',
      ],
      answerIndex: 1,
      explainEN:
        'An output that reacts to the input, not just the state, belongs on the arc as input/output - the Mealy placement this module previews and module 39 names formally.',
      explainHI:
        'एक output जो सिर्फ़ state पर नहीं, input पर भी react करता है, वह arc पर input/output की तरह लिखा जाता है - वह Mealy placement जिसकी झलक यह module देता है और module 39 औपचारिक नाम देता है।',
      questionHI: "Worked A-B circuit में, Y=(A+B).X' present state और input X दोनों पर निर्भर है। State diagram पर इसे कहाँ लिखा जाना चाहिए?",
    },
  ],
};
