/**
 * Analysing Clocked Sequential Circuits - dsd/38, "The Reverse Question"
 * (Sequential Logic track). Generic scenes come from the shared _subtractor
 * kit; every circuit, table and diagram below is COMPUTED live from the
 * shared _sequential/blocks primitives (ffNext, StateDiagram, StateTable) -
 * never hardcoded. Three worked machines run through this file:
 *   - the Q1/Q0 machine (D1=Q0, D0=X⊕Q1) - the cover hero AND the black-box
 *     probe on the reverse-engineering scene (same math, two costumes).
 *   - the A-B machine (DA=A.X+B.X, DB=A'.X, Y=(A+B).X') - the deck's classic
 *     worked example, reused again as the detective's "case file" analogy.
 *   - the JK practice machine (JA=B, KA=B.X', JB=X, KB=A, Y=A.B) - a second,
 *     different circuit run through the identical three-step pipeline.
 * Every state table/diagram is generated by iterating the governing equations
 * over every present-state/input combination, so nothing here can drift from
 * the equations printed beside it.
 */
import React, { useState } from 'react';
import { Search, Cpu, Sigma, ArrowRightLeft, Table2, Workflow, Lock, Eye, EyeOff, Fingerprint } from 'lucide-react';
import {
  SceneShell, Eyebrow, Card, tone, useSubLang,
  CoverScene, VideoScene, TheoryScene, RecapScene, SubFlashCards, QuizScene,
  StepThrough, WorkbenchCTA,
  type SubScene,
} from '../_subtractor/kit';
import type { SubPage } from '../_subtractor/SubEngine';
import {
  StateDiagram, StateTable, FlipFlopViz, ClockButton, Toggle, ffNext,
  type FSMState, type FSMEdge,
} from '../_sequential/blocks';
import { TryItYourself } from '../../ui/TryItYourself';
import { CustomVideoPlayer } from '../../ui/CustomVideoPlayer';
import { CONTENT } from './content';

const ACC = { X: '#38bdf8', Y: '#f59e0b', good: '#34d399', bad: '#fb7185' };
const SRC_EN = '/videos/dsd38-analysis.mp4';
const SRC_REVERSE = '/videos/dsd38-reverse.mp4';

/* curve sign so a from<->to reverse pair never draws on top of itself */
const curveFor = (from: string, to: string): number => (from === to ? 0 : from < to ? 32 : -32);

const fourStates = (): FSMState[] => [
  { id: 'S00', label: '00', x: 78, y: 40 },
  { id: 'S01', label: '01', x: 252, y: 40 },
  { id: 'S10', label: '10', x: 78, y: 168 },
  { id: 'S11', label: '11', x: 252, y: 168 },
];

/* ═══════════════════════ machine 1: Q1/Q0, D1=Q0, D0=X⊕Q1 ═══════════════════════
   The cover-hero circuit, reused (sealed) as the black-box probe on S04. */
const qStates = fourStates();
const qEdges: FSMEdge[] = (() => {
  const es: FSMEdge[] = [];
  for (const q1 of [0, 1]) for (const q0 of [0, 1]) for (const x of [0, 1]) {
    const d1 = q0, d0 = x ^ q1;
    const nq1 = ffNext('D', q1, d1), nq0 = ffNext('D', q0, d0);
    const from = `S${q1}${q0}`, to = `S${nq1}${nq0}`;
    es.push({ from, to, label: `X=${x}`, curve: curveFor(from, to) });
  }
  return es;
})();

/* ───────── bespoke S00 cover hero: the circuit that draws its own diagram ───────── */
const CircuitToDiagram: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const box = isDarkMode ? '#0a0e1a' : '#ffffff';
  const dim = isDarkMode ? '#334155' : '#cbd5e1';
  const [X, setX] = useState(1);
  const [Q1, setQ1] = useState(0);
  const [Q0, setQ0] = useState(0);
  const D1 = Q0;
  const D0 = X ^ Q1;
  const tick = () => {
    const nQ1 = ffNext('D', Q1, D1);
    const nQ0 = ffNext('D', Q0, D0);
    setQ1(nQ1); setQ0(nQ0);
  };

  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-3 text-center font-mono text-[11px] uppercase tracking-[0.3em]" style={{ color: accent }}>
        {lang === 'hi' ? 'circuit -> state diagram · X toggle कीजिए' : 'circuit -> state diagram · toggle X'}
      </div>
      <svg viewBox="0 0 340 150" className="mx-auto w-full max-w-xl">
        {/* XOR gate: D0 = X ^ Q1 */}
        <path d="M44,40 Q64,66 44,92 Q88,92 104,66 Q88,40 44,40 Z" fill={box} stroke={ACC.X} strokeWidth="2.2" />
        <path d="M38,40 Q58,66 38,92" fill="none" stroke={ACC.X} strokeWidth="2.2" />
        <text x="72" y="70" textAnchor="middle" fontFamily="monospace" fontSize="9" fontWeight="800" fill={ACC.X}>XOR</text>
        <line x1="8" y1="52" x2="42" y2="52" stroke={X ? ACC.X : dim} strokeWidth="2.6" />
        <text x="4" y="46" fontFamily="monospace" fontSize="10" fontWeight="800" fill={X ? ACC.X : dim}>X</text>
        <line x1="8" y1="80" x2="42" y2="80" stroke={Q1 ? accent : dim} strokeWidth="2.6" strokeDasharray="3 2" />
        <text x="4" y="94" fontFamily="monospace" fontSize="10" fontWeight="800" fill={Q1 ? accent : (t.faint as string)}>Q1</text>
        <line x1="104" y1="66" x2="140" y2="66" stroke={accent} strokeWidth="2.6" />
        <text x="122" y="58" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={t.faint as string}>D0</text>
        {/* FF0 box */}
        <rect x="140" y="34" width="64" height="64" rx="9" fill={box} stroke={accent} strokeWidth="2.4" />
        <text x="172" y="62" textAnchor="middle" fontFamily="monospace" fontSize="12" fontWeight="800" fill={accent}>FF0</text>
        <text x="172" y="78" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>Q0={Q0}</text>
        {/* Q0 -> D1, straight wire */}
        <line x1="204" y1="66" x2="240" y2="66" stroke={Q0 ? accent : dim} strokeWidth="2.6" />
        <text x="222" y="58" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={t.faint as string}>D1</text>
        {/* FF1 box */}
        <rect x="240" y="34" width="64" height="64" rx="9" fill={box} stroke={accent} strokeWidth="2.4" />
        <text x="272" y="62" textAnchor="middle" fontFamily="monospace" fontSize="12" fontWeight="800" fill={accent}>FF1</text>
        <text x="272" y="78" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>Q1={Q1}</text>
        {/* Q1 output pin + feedback down to XOR's lower input */}
        <line x1="304" y1="50" x2="326" y2="50" stroke={Q1 ? accent : dim} strokeWidth="2.6" />
        <text x="330" y="54" fontFamily="monospace" fontSize="9" fontWeight="800" fill={Q1 ? accent : dim}>Q1</text>
        <path d="M326,50 V128 H20 V80" fill="none" stroke={dim} strokeWidth="1.6" strokeDasharray="4 3" />
      </svg>

      <div className="mt-2 flex flex-wrap items-center justify-center gap-4">
        <Toggle label="X" v={X} onClick={() => setX(X ^ 1)} color={ACC.X} />
        <div className="flex flex-col items-center gap-1">
          <span className={`font-mono text-[11px] ${t.faint}`}>Q1Q0</span>
          <span className="flex h-9 items-center justify-center rounded-lg px-2 font-mono text-base font-black"
            style={{ background: `${accent}22`, color: accent, border: `2px solid ${accent}` }}>{Q1}{Q0}</span>
        </div>
      </div>
      <div className="mt-3"><ClockButton accent={accent} onTick={tick} /></div>

      <div className="mt-5">
        <StateDiagram isDarkMode={isDarkMode} accent={accent} states={qStates} edges={qEdges}
          active={`S${Q1}${Q0}`} width={330} height={210} />
      </div>
      <p className={`mt-2 text-center font-mono text-[12px] ${t.sub}`}>
        {lang === 'hi'
          ? <>D1=Q0, D0=X⊕Q1 - सारे 4 states और 8 edges इन्हीं दो equations से derive किए गए हैं, हाथ से नहीं खींचे।</>
          : <>D1=Q0, D0=X⊕Q1 - all 4 states and 8 edges are derived from just those two equations, never hand-drawn.</>}
      </p>
    </Card>
  );
};

/* ═══════════════════════ machine 2: A-B, DA=AX+BX, DB=A'X, Y=(A+B)X' ═══════════════════════
   The deck's classic worked example - reused verbatim as the S06 detective case file. */
interface ABRow { A: number; B: number; X: number; DA: number; DB: number; nextA: number; nextB: number; Y: number }
const abRows = (): ABRow[] => {
  const out: ABRow[] = [];
  for (const A of [0, 1]) for (const B of [0, 1]) for (const X of [0, 1]) {
    const DA = (A & X) | (B & X);
    const DB = (A ^ 1) & X;
    const nextA = ffNext('D', A, DA);
    const nextB = ffNext('D', B, DB);
    const Y = (A | B) & (X ^ 1);
    out.push({ A, B, X, DA, DB, nextA, nextB, Y });
  }
  return out;
};
const abStates = fourStates();
const abEdges: FSMEdge[] = abRows().map((r) => {
  const from = `S${r.A}${r.B}`, to = `S${r.nextA}${r.nextB}`;
  return { from, to, label: `${r.X}/${r.Y}`, curve: curveFor(from, to) };
});

/* live walker for the A-B machine: drive it by hand, watch Y + the diagram */
const ABWalker: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const [X, setX] = useState(1);
  const [A, setA] = useState(0);
  const [B, setB] = useState(0);
  const DA = (A & X) | (B & X);
  const DB = (A ^ 1) & X;
  const Y = (A | B) & (X ^ 1);
  const tick = () => {
    const nA = ffNext('D', A, DA), nB = ffNext('D', B, DB);
    setA(nA); setB(nB);
  };
  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-3 font-mono text-[11px] uppercase tracking-[0.3em]" style={{ color: accent }}>
        {lang === 'hi' ? 'live: A-B machine को चलाइए' : 'live: drive the A-B machine'}
      </div>
      <StateDiagram isDarkMode={isDarkMode} accent={accent} states={abStates} edges={abEdges}
        active={`S${A}${B}`} width={330} height={210} />
      <div className="mt-2 flex flex-wrap items-center justify-center gap-4">
        <Toggle label="X" v={X} onClick={() => setX(X ^ 1)} color={ACC.X} />
        <div className="flex flex-col items-center gap-1">
          <span className={`font-mono text-[11px] ${t.faint}`}>AB</span>
          <span className="flex h-9 items-center justify-center rounded-lg px-2 font-mono text-base font-black"
            style={{ background: `${accent}22`, color: accent, border: `2px solid ${accent}` }}>{A}{B}</span>
        </div>
        <div className="flex flex-col items-center gap-1">
          <span className={`font-mono text-[11px] ${t.faint}`}>Y</span>
          <span className="flex h-9 w-9 items-center justify-center rounded-lg font-mono text-base font-black"
            style={{ background: Y ? ACC.good : 'transparent', color: Y ? '#000' : ACC.good, border: `2px solid ${ACC.good}` }}>{Y}</span>
        </div>
      </div>
      <div className="mt-3"><ClockButton accent={accent} onTick={tick} /></div>
      <p className={`mt-2 text-center font-mono text-[12px] ${t.sub}`}>
        {lang === 'hi'
          ? <>DA={DA}, DB={DB} → अगली CLK ▲ पर AB → <b style={{ color: accent }}>{DA}{DB}</b></>
          : <>DA={DA}, DB={DB} → on the next CLK ▲, AB → <b style={{ color: accent }}>{DA}{DB}</b></>}
      </p>
    </Card>
  );
};

/* ───────── bespoke S02: the pipeline strip + characteristic-equation reference ───────── */
const PipelineStrip: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const steps = [
    { Icon: Cpu, en: 'Schematic', hi: 'Schematic' },
    { Icon: Sigma, en: 'Excitation eqns', hi: 'Excitation eqns' },
    { Icon: ArrowRightLeft, en: 'Next-state/output', hi: 'Next-state/output' },
    { Icon: Table2, en: 'State table', hi: 'State table' },
    { Icon: Workflow, en: 'State diagram', hi: 'State diagram' },
  ];
  const eqs: { ty: string; eq: string }[] = [
    { ty: 'SR', eq: "Q(t+1)=S+R'.Q" },
    { ty: 'JK', eq: "Q(t+1)=J.Q'+K'.Q" },
    { ty: 'D', eq: 'Q(t+1)=D' },
    { ty: 'T', eq: 'Q(t+1)=T⊕Q' },
  ];
  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-4 flex flex-wrap items-center justify-center gap-1.5 sm:gap-2">
        {steps.map((s, i) => (
          <React.Fragment key={s.en}>
            <div className="flex flex-col items-center gap-1.5 rounded-2xl border px-3 py-2.5" style={{ borderColor: `${accent}44` }}>
              <s.Icon size={18} style={{ color: accent }} />
              <span className={`text-center font-mono text-[9.5px] font-bold leading-tight ${t.sub}`}>
                {lang === 'hi' ? s.hi : s.en}
              </span>
            </div>
            {i < steps.length - 1 && <span className="font-black opacity-40" style={{ color: accent }}>{'->'}</span>}
          </React.Fragment>
        ))}
      </div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        {eqs.map((e) => (
          <div key={e.ty} className={`rounded-xl border p-2.5 text-center ${t.soft}`}>
            <div className="font-mono text-[10px] font-black" style={{ color: accent }}>{e.ty}</div>
            <div className={`mt-1 font-mono text-[11px] ${t.sub}`}>{e.eq}</div>
          </div>
        ))}
      </div>
      <p className={`mt-3 text-center font-mono text-[12px] ${t.faint}`}>
        {lang === 'hi'
          ? 'D की row पर ग़ौर कीजिए: Q(t) कहीं नहीं है - इसीलिए D के लिए step 2 free है।'
          : "notice D's row: Q(t) appears nowhere - that's why step 2 is free for D-type circuits."}
      </p>
    </Card>
  );
};

/* ───────── bespoke S03: the A-B circuit, five-step worked derivation ───────── */
const ABCircuitDiagram: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const t = tone(isDarkMode);
  const box = isDarkMode ? '#0a0e1a' : '#ffffff';
  const dim = isDarkMode ? '#334155' : '#cbd5e1';
  return (
    <svg viewBox="0 0 320 130" className="mx-auto w-full max-w-md">
      <rect x="16" y="14" width="76" height="60" rx="9" fill={box} stroke={accent} strokeWidth="2.2" />
      <text x="54" y="40" textAnchor="middle" fontFamily="monospace" fontSize="12" fontWeight="800" fill={accent}>D FF-A</text>
      <text x="54" y="58" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>DA=AX+BX</text>
      <rect x="16" y="86" width="76" height="34" rx="9" fill={box} stroke={accent} strokeWidth="2.2" />
      <text x="54" y="108" textAnchor="middle" fontFamily="monospace" fontSize="12" fontWeight="800" fill={accent}>D FF-B</text>
      <line x1="92" y1="44" x2="150" y2="44" stroke={accent} strokeWidth="2.4" />
      <text x="120" y="36" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>A</text>
      <line x1="92" y1="103" x2="150" y2="103" stroke={accent} strokeWidth="2.4" />
      <text x="120" y="97" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>B</text>
      <rect x="150" y="60" width="60" height="30" rx="6" fill={box} stroke={ACC.Y} strokeWidth="2" />
      <text x="180" y="80" textAnchor="middle" fontFamily="monospace" fontSize="9" fontWeight="800" fill={ACC.Y}>gates</text>
      <line x1="6" y1="70" x2="150" y2="75" stroke={ACC.X} strokeWidth="2.2" />
      <text x="4" y="66" fontFamily="monospace" fontSize="10" fontWeight="800" fill={ACC.X}>X</text>
      <line x1="210" y1="75" x2="270" y2="75" stroke={ACC.Y} strokeWidth="2.6" />
      <text x="284" y="79" fontFamily="monospace" fontSize="11" fontWeight="800" fill={ACC.Y}>Y</text>
    </svg>
  );
};

const ABWorked: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const mono = (v: string) => <span className="font-mono font-black" style={{ color: accent }}>{v}</span>;
  const rows = abRows();
  const sample = rows.find((r) => r.A === 0 && r.B === 1 && r.X === 1)!;

  const steps = [
    {
      label: lang === 'hi' ? 'circuit' : 'Circuit',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? 'दिया: दो D flip-flops A, B; एक input X; एक output Y; common clock।' : 'Given: two D flip-flops A, B; one input X; one output Y; a common clock.'}</p>
          <ABCircuitDiagram isDarkMode={isDarkMode} accent={accent} />
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'step 1 · excitation' : 'Step 1 · excitation',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? 'हर D pin के wiring से सीधे पढ़िए।' : "Read each D pin's wiring directly."}</p>
          <div className="text-lg">{mono("DA = A.X + B.X")}</div>
          <div className="text-lg">{mono("DB = A'.X")}</div>
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'step 2 · next-state/output' : 'Step 2 · next-state/output',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? "D का law Q(t+1)=D है - pins का नाम भर बदलिए।" : "D's law is Q(t+1)=D - just rename the pins."}</p>
          <div className="text-base">{mono('A(t+1) = A.X + B.X')}</div>
          <div className="text-base">{mono("B(t+1) = A'.X")}</div>
          <div className="text-base">{mono("Y = (A+B).X'")}</div>
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'sample row' : 'Sample row',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? 'AB=01, X=1 हाथ से पीसिए:' : 'Grind AB=01, X=1 by hand:'}</p>
          <div className="text-base">{mono(`DA = 0.1+1.1 = ${sample.DA}`)}</div>
          <div className="text-base">{mono(`DB = 1.1 = ${sample.DB}`)}</div>
          <div className="text-lg font-black" style={{ color: ACC.good }}>
            next = {sample.nextA}{sample.nextB}, Y = {sample.Y}
          </div>
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'full table' : 'Full table',
      body: (
        <div className="space-y-2">
          <p className={`text-center text-[13px] ${t.sub}`}>{lang === 'hi' ? 'हर 8 rows उन्हीं दो equations से computed - सब code में।' : 'All 8 rows computed from those same two equations - all in code.'}</p>
          <StateTable isDarkMode={isDarkMode} accent={accent}
            headers={['A', 'B', 'X', 'DA', 'DB', 'next A', 'next B', 'Y']}
            rows={rows.map((r) => [r.A, r.B, r.X, r.DA, r.DB, r.nextA, r.nextB, r.Y])}
            highlight={rows.indexOf(sample)}
            note={lang === 'hi' ? 'highlighted row वही AB=01,X=1 sample है।' : 'the highlighted row is the AB=01,X=1 sample above.'} />
        </div>
      ),
    },
  ];
  return <StepThrough steps={steps} isDarkMode={isDarkMode} accent={accent} />;
};

/* ═══════════════════════ machine 3: JK practice, JA=B, KA=B.X', JB=X, KB=A, Y=A.B ═══════════════════════ */
interface JKRow { A: number; B: number; X: number; JA: number; KA: number; JB: number; KB: number; nextA: number; nextB: number; Y: number }
const jkRows = (): JKRow[] => {
  const out: JKRow[] = [];
  for (const A of [0, 1]) for (const B of [0, 1]) for (const X of [0, 1]) {
    const JA = B, KA = B & (X ^ 1);
    const JB = X, KB = A;
    const nextA = ffNext('JK', A, JA, KA);
    const nextB = ffNext('JK', B, JB, KB);
    const Y = A & B;
    out.push({ A, B, X, JA, KA, JB, KB, nextA, nextB, Y });
  }
  return out;
};
const jkAllRows = jkRows();
const jkOutOf = (a: number, b: number) => a & b;
const jkStates: FSMState[] = fourStates().map((s) => {
  const a = Number(s.label[0]), b = Number(s.label[1]);
  return { ...s, label: `${s.label} (Y=${jkOutOf(a, b)})` };
});
const jkEdges: FSMEdge[] = jkAllRows.map((r) => {
  const from = `S${r.A}${r.B}`, to = `S${r.nextA}${r.nextB}`;
  return { from, to, label: `X=${r.X}`, curve: curveFor(from, to) };
});

const JKWorked: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const mono = (v: string) => <span className="font-mono font-black" style={{ color: accent }}>{v}</span>;
  const rows = jkAllRows;

  const steps = [
    {
      label: lang === 'hi' ? 'step 1 · excitation' : 'Step 1 · excitation',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? 'दो JK flip-flops A, B; एक input X; schematic से चार equations।' : 'Two JK flip-flops A, B; one input X; four equations off the schematic.'}</p>
          <div className="text-base">{mono("JA = B")}{'   '}{mono("KA = B.X'")}</div>
          <div className="text-base">{mono('JB = X')}{'   '}{mono('KB = A')}</div>
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'step 2 · characteristic eq' : 'Step 2 · characteristic eq',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>
            {lang === 'hi' ? "इस बार Q(t+1)=J.Q'+K'.Q को हर row पर लगाना पड़ता है - कोई shortcut नहीं।" : "This time Q(t+1)=J.Q'+K'.Q must be applied row by row - no shortcut."}
          </p>
          <div className="text-base">{mono("Y = A.B  (present state only)")}</div>
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'full table' : 'Full table',
      body: (
        <div className="space-y-2">
          <p className={`text-center text-[13px] ${t.sub}`}>{lang === 'hi' ? 'हर 8 rows ffNext(JK,...) से computed।' : 'All 8 rows computed via ffNext(JK, ...).'}</p>
          <StateTable isDarkMode={isDarkMode} accent={accent}
            headers={['A', 'B', 'X', 'JA', 'KA', 'JB', 'KB', 'next A', 'next B']}
            rows={rows.map((r) => [r.A, r.B, r.X, r.JA, r.KA, r.JB, r.KB, r.nextA, r.nextB])} />
        </div>
      ),
    },
    {
      label: lang === 'hi' ? 'state diagram' : 'State diagram',
      body: (
        <div className="space-y-2 text-center">
          <p className={`text-[13px] ${t.sub}`}>{lang === 'hi' ? 'Y अब हर state के अंदर बैठा है, arc पर नहीं - Moore-रंग।' : 'Y now sits inside each state, not on an arc - Moore-flavoured.'}</p>
          <StateDiagram isDarkMode={isDarkMode} accent={accent} states={jkStates} edges={jkEdges} width={340} height={210} />
        </div>
      ),
    },
  ];
  return <StepThrough steps={steps} isDarkMode={isDarkMode} accent={accent} />;
};

/* ───────── bespoke S04: the second embedded film (dsd38-reverse.mp4) ───────── */
const ReverseFilm: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-3 flex items-center gap-2">
        <Search size={14} style={{ color: accent }} />
        <span className="font-mono text-[10px] uppercase tracking-widest" style={{ color: accent }}>
          {lang === 'hi' ? 'दूसरी film · reverse-engineering' : 'second film · reverse-engineering'}
        </span>
      </div>
      <div className="overflow-hidden rounded-2xl border" style={{ borderColor: `${accent}33` }}>
        <CustomVideoPlayer src={SRC_REVERSE} accent={accent} className="rounded-2xl border-0" />
      </div>
    </Card>
  );
};

/* ───────── bespoke S04: the sealed black-box probe (reuses the Q1/Q0 machine) ───────── */
const BlackBoxProbe: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const box = isDarkMode ? '#0a0e1a' : '#ffffff';
  const dim = isDarkMode ? '#334155' : '#cbd5e1';
  const [X, setX] = useState(1);
  const [Q1, setQ1] = useState(0);
  const [Q0, setQ0] = useState(0);
  const [trace, setTrace] = useState<{ X: number; Y: number }[]>([]);
  const [reveal, setReveal] = useState(false);
  const D1 = Q0, D0 = X ^ Q1;
  const tick = () => {
    const nQ1 = ffNext('D', Q1, D1);
    const nQ0 = ffNext('D', Q0, D0);
    setQ1(nQ1); setQ0(nQ0);
    setTrace((h) => [...h.slice(-9), { X, Y: nQ0 }]);
  };

  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-3 flex items-center justify-center gap-2 font-mono text-[11px] uppercase tracking-[0.3em]" style={{ color: accent }}>
        <Lock size={13} /> {lang === 'hi' ? 'sealed box · केवल X, Y और CLK दिखते हैं' : 'sealed box · only X, Y and CLK are visible'}
      </div>
      <svg viewBox="0 0 260 110" className="mx-auto w-full max-w-sm">
        <line x1="6" y1="42" x2="60" y2="42" stroke={X ? ACC.X : dim} strokeWidth="2.6" />
        <text x="4" y="36" fontFamily="monospace" fontSize="10" fontWeight="800" fill={X ? ACC.X : dim}>X</text>
        <rect x="60" y="14" width="90" height="70" rx="10" fill={box} stroke={accent} strokeWidth="2.4" strokeDasharray={reveal ? '0' : '5 4'} />
        {!reveal && <text x="105" y="54" textAnchor="middle" fontFamily="monospace" fontSize="22" fontWeight="900" fill={dim}>?</text>}
        {reveal && (
          <>
            <text x="105" y="46" textAnchor="middle" fontFamily="monospace" fontSize="10" fontWeight="800" fill={accent}>D1=Q0</text>
            <text x="105" y="60" textAnchor="middle" fontFamily="monospace" fontSize="10" fontWeight="800" fill={accent}>D0=X⊕Q1</text>
            <text x="105" y="76" textAnchor="middle" fontFamily="monospace" fontSize="9" fill={dim}>Q1Q0={Q1}{Q0}</text>
          </>
        )}
        <line x1="150" y1="42" x2="204" y2="42" stroke={Q0 ? ACC.good : dim} strokeWidth="2.6" />
        <text x="208" y="46" fontFamily="monospace" fontSize="11" fontWeight="800" fill={Q0 ? ACC.good : dim}>Y</text>
        <line x1="105" y1="84" x2="105" y2="100" stroke={dim} strokeWidth="2" />
        <text x="105" y="108" textAnchor="middle" fontFamily="monospace" fontSize="8" fill={t.faint as string}>CLK</text>
      </svg>

      <div className="mt-2 flex flex-wrap items-center justify-center gap-4">
        <Toggle label="X" v={X} onClick={() => setX(X ^ 1)} color={ACC.X} />
        <div className="flex flex-col items-center gap-1">
          <span className={`font-mono text-[11px] ${t.faint}`}>Y</span>
          <span className="flex h-9 w-9 items-center justify-center rounded-lg font-mono text-base font-black"
            style={{ background: Q0 ? ACC.good : 'transparent', color: Q0 ? '#000' : ACC.good, border: `2px solid ${ACC.good}` }}>{Q0}</span>
        </div>
      </div>
      <div className="mt-3"><ClockButton accent={accent} onTick={tick} /></div>

      <div className={`mt-4 overflow-x-auto rounded-2xl border p-3 ${t.soft}`}>
        <div className={`mb-1 font-mono text-[10px] uppercase tracking-widest ${t.faint}`}>
          {lang === 'hi' ? 'printed trace (X/Y हर tick पर)' : 'printed trace (X/Y per tick)'}
        </div>
        <div className="flex min-h-[26px] flex-wrap gap-1.5 font-mono text-[11px]">
          {trace.length === 0 && <span className={t.faint as string}>{lang === 'hi' ? 'CLK दबाइए…' : 'press CLK…'}</span>}
          {trace.map((r, i) => (
            <span key={i} className="rounded px-1.5 py-0.5 font-bold" style={{ background: `${accent}18`, color: accent }}>{r.X}/{r.Y}</span>
          ))}
        </div>
      </div>

      <button onClick={() => setReveal((r) => !r)}
        className="mx-auto mt-4 flex items-center gap-2 rounded-xl border px-4 py-2 font-mono text-[11px] font-black uppercase tracking-wide active:scale-95"
        style={{ borderColor: `${accent}55`, color: accent }}>
        {reveal ? <EyeOff size={14} /> : <Eye size={14} />}
        {reveal
          ? (lang === 'hi' ? 'फिर से sealed कीजिए' : 're-seal the box')
          : (lang === 'hi' ? 'peek inside (जाँचिए)' : 'peek inside (check yourself)')}
      </button>

      {reveal && (
        <div className="mt-4">
          <StateDiagram isDarkMode={isDarkMode} accent={accent} states={qStates} edges={qEdges}
            active={`S${Q1}${Q0}`} width={330} height={210} />
          <p className={`mt-2 text-center font-mono text-[12px] ${t.sub}`}>
            {lang === 'hi'
              ? 'यही वह असली diagram है जिसे आपका trace धीरे-धीरे reconstruct कर रहा था।'
              : 'this is the real diagram your trace was slowly reconstructing.'}
          </p>
        </div>
      )}
    </Card>
  );
};

/* ───────── bespoke S06: the detective's case file (reuses the A-B rows) ───────── */
const DetectiveCaseFile: React.FC<{ isDarkMode: boolean; accent: string }> = ({ isDarkMode, accent }) => {
  const { lang } = useSubLang();
  const t = tone(isDarkMode);
  const rows = abRows();
  return (
    <Card isDarkMode={isDarkMode}>
      <div className="mb-3 flex items-center justify-center gap-2 font-mono text-[11px] uppercase tracking-[0.3em]" style={{ color: accent }}>
        <Fingerprint size={14} /> {lang === 'hi' ? 'case file · 8 दर्ज दिन' : 'case file · 8 logged days'}
      </div>
      <StateTable isDarkMode={isDarkMode} accent={accent}
        headers={[
          lang === 'hi' ? 'दिन शुरू (routine)' : 'started in (routine)',
          lang === 'hi' ? "trigger (X)" : 'trigger (X)',
          lang === 'hi' ? 'देखा action (Y)' : 'observed action (Y)',
          lang === 'hi' ? 'अगला routine' : 'next routine',
        ]}
        rows={rows.map((r) => [`${r.A}${r.B}`, r.X, r.Y, `${r.nextA}${r.nextB}`])}
        note={lang === 'hi' ? 'वही 8 rows जो S03 में थीं - बस suspect की भाषा में फिर से पढ़ी गईं।' : 'the same 8 rows from S03 - just re-read in a suspect\'s vocabulary.'} />
      <div className="mt-4">
        <StateDiagram isDarkMode={isDarkMode} accent={accent} states={abStates} edges={abEdges} width={330} height={210} />
      </div>
      <p className={`mt-2 text-center font-mono text-[12px] ${t.sub}`}>
        {lang === 'hi'
          ? 'यही case-file map है - circles routines हैं, arrows trigger/action हैं।'
          : 'this is the case-file map itself - circles are routines, arrows are trigger/action.'}
      </p>
    </Card>
  );
};

/* ───────── part assignment ───────── */
const partAt = (i: number, _n: number): string =>
  i <= 2 ? 'PART I · THE FORWARD PASS'
    : i <= 5 ? 'PART II · THE PIPELINE, WORKED'
      : i <= 6 ? "PART III · THE DETECTIVE'S PICTURE"
        : 'PART IV · LOCK IT IN';

const bespokeFor = (scene: SubScene): string | null => {
  switch (scene.id) {
    case 'S02_Facts': return 'pipeline';
    case 'S03_WorkedExample': return 'worked';
    case 'S04_Reverse': return 'reverse';
    case 'S05_Practice': return 'practice';
    case 'S06_Analogy': return 'analogy';
    case 'S07_Build': return 'build';
    default: return null;
  }
};

function componentFor(scene: SubScene, _i: number, _n: number): React.FC<any> {
  switch (scene.kind) {
    case 'cover':
      return (p) => <CoverScene {...p} scene={scene} moduleTitle={CONTENT.moduleTitle} moduleSubtitle={CONTENT.moduleSubtitle}
        kicker="Analysis · Circuit -> State Diagram"
        hero={<CircuitToDiagram isDarkMode={p.isDarkMode} accent={p.accent} />} />;
    case 'video':
      return (p) => <VideoScene {...p} scene={scene} src={SRC_EN} />;
    case 'flashcards':
      return (p) => (
        <SceneShell>
          <section className="space-y-3">
            <Eyebrow accent={p.accent}>{scene.label}</Eyebrow>
            {scene.subtitle && <h2 className={`text-3xl md:text-4xl font-black ${tone(p.isDarkMode).text}`}>{scene.subtitle}</h2>}
          </section>
          <SubFlashCards isDarkMode={p.isDarkMode} accent={p.accent} cards={CONTENT.flashcards} />
        </SceneShell>
      );
    case 'quiz':
      return (p) => (
        <div className="relative">
          <TryItYourself corner />
          <QuizScene isDarkMode={p.isDarkMode} accent={p.accent} quiz={CONTENT.quiz} badge="Analysis" tag="Practice · Circuit Analysis" title={scene.label} intro={scene.subtitle ?? ''} />
        </div>
      );
    case 'recap':
      return (p) => <RecapScene {...p} scene={scene} />;
    default: {
      const which = bespokeFor(scene);
      return (p) => (
        <TheoryScene {...p} scene={scene}>
          {which === 'pipeline' && (
            <div className="space-y-6">
              <TryItYourself />
              <PipelineStrip isDarkMode={p.isDarkMode} accent={p.accent} />
              <FlipFlopViz isDarkMode={p.isDarkMode} accent={p.accent} type="D" />
            </div>
          )}
          {which === 'worked' && (
            <div className="space-y-6">
              <TryItYourself />
              <ABWorked isDarkMode={p.isDarkMode} accent={p.accent} />
              <ABWalker isDarkMode={p.isDarkMode} accent={p.accent} />
            </div>
          )}
          {which === 'reverse' && (
            <div className="space-y-6">
              <TryItYourself />
              <ReverseFilm isDarkMode={p.isDarkMode} accent={p.accent} />
              <BlackBoxProbe isDarkMode={p.isDarkMode} accent={p.accent} />
            </div>
          )}
          {which === 'practice' && (
            <div className="space-y-6">
              <TryItYourself />
              <FlipFlopViz isDarkMode={p.isDarkMode} accent={p.accent} type="JK" />
              <JKWorked isDarkMode={p.isDarkMode} accent={p.accent} />
            </div>
          )}
          {which === 'analogy' && (
            <div className="space-y-6">
              <TryItYourself />
              <DetectiveCaseFile isDarkMode={p.isDarkMode} accent={p.accent} />
            </div>
          )}
          {which === 'build' && (
            <WorkbenchCTA isDarkMode={p.isDarkMode} accent={p.accent} tutorial="analyze-clocked-circuit"
              titleEN="Build the A-B circuit and read its own table back"
              titleHI="A-B circuit बनाइए और उसकी अपनी table वापस पढ़िए"
              bodyEN="Open the live workbench and wire two D flip-flops with DA=A.X+B.X and DB=A'.X plus the output gate Y=(A+B).X'. Then step the clock through every present-state/input combination and confirm your hand-built state table against the one this module computed."
              bodyHI="live workbench खोलिए और दो D flip-flops को DA=A.X+B.X और DB=A'.X के साथ, और output gate Y=(A+B).X' के साथ wire कीजिए। फिर clock को हर present-state/input combination से चलाइए और अपनी हाथ से बनाई state table को इस module की computed table से मिलाइए।" />
          )}
        </TheoryScene>
      );
    }
  }
}

const slug = (s: string) => s.replace(/^S\d+_/, '').toLowerCase();

export const PAGES: SubPage[] = CONTENT.scenes.map((scene, i, arr) => ({
  id: slug(scene.id),
  part: partAt(i, arr.length),
  label: scene.label,
  subtitle: scene.subtitle ?? '',
  Component: componentFor(scene, i, arr.length),
}));
