import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/40 - Designing State Machines, "From Word Problem To Working Hardware"
 * (Sequential Logic track, FINAL module - closes dsd 28-42).
 * The complete forward-design (synthesis) pipeline: a plain-English word spec
 * turns into a state diagram, then a state table, then a REDUCED state table
 * (row-matching and the implication chart, two independent proofs of the same
 * equivalence), then an ASSIGNED state table (binary vs one-hot bit patterns),
 * then excitation equations (reusing ffExcite/ExciteTable from _sequential/
 * blocks), then gates. Every reduction decision, chart cell and excitation
 * equation is computed in scenes.tsx from small worked example tables - never
 * hardcoded conclusions. This module ends the Sequential Logic track: memory
 * (latches/flip-flops) -> datapath (registers/counters) -> FSM theory & design
 * -> the physical realities (timing, async, hazards) that modules 41-42 cover.
 */
export const CONTENT: SubContent = {
  moduleTitle: "Designing State Machines - From Word Problem To Working Hardware",
  moduleSubtitle: "The complete synthesis pipeline: spec, diagram, table, reduction, assignment, excitation equations, gates.",
  scenes: [
    {
      id: "S00_Cover",
      label: "From Word Problem To Working Hardware",
      kind: "cover",
      subtitle: "Watch a one-sentence spec grow into a full state diagram, one clause at a time.",
      theoryEN: [
        "This module builds the complete forward-design pipeline for sequential circuits: starting from a plain-English word problem and ending at real AND/OR gates feeding real flip-flops. Every earlier module in this track analysed circuits that already existed on paper; this one SYNTHESISES a brand new one from a spec, from nothing.",
        "Hold one small worked spec in your head for the opening minutes: \"raise the output the instant the machine has seen two consecutive 1s, and keep detecting overlapping matches afterwards.\" Watch it grow, clause by clause, into the live state diagram in the hero below.",
        "The full pipeline has six stages and this module walks every one of them: word spec, state diagram, state table, state reduction (merge any states that behave identically), state assignment (pick a bit pattern for each surviving state), excitation equations, and finally gates.",
        "Two independent methods do the reduction step, and you will run a real worked example through both: direct row-matching for simple tables, and the triangular implication chart for tables with cyclic or nested dependencies that row-matching alone cannot untangle cleanly.",
        "By the end you will assign bits to states, derive flip-flop excitation equations with the same ffExcite machinery earlier modules used, and this module closes the entire Sequential Logic track - modules 28 through 42 - memory elements, datapath building blocks, FSM theory and design, and the physical timing limits that bound how fast any of it can actually run."
      ],
      theoryHI: [
        "यह module sequential circuits के लिए पूरा forward-design pipeline बनाता है: एक सीधे-सादे अंग्रेज़ी word problem से शुरू होकर असली AND/OR gates तक जो असली flip-flops को चलाते हैं। इस track के पिछले हर module ने पहले से काग़ज़ पर मौजूद circuits analyse किए; यह module एक बिलकुल नया circuit एक spec से, कुछ भी न होने से, SYNTHESISE करता है।",
        "शुरुआती मिनटों के लिए एक छोटा worked spec मन में रखिए: \"जैसे ही machine ने दो लगातार 1s देखे, output उठाइए, और बाद में overlapping matches भी पकड़ते रहिए।\" इसे नीचे hero में, clause-दर-clause, एक live state diagram में बढ़ते देखिए।",
        "पूरे pipeline के छह stages हैं और यह module हर एक से गुज़रता है: word spec, state diagram, state table, state reduction (जो states एक जैसा बर्ताव करें उन्हें merge कीजिए), state assignment (हर बचे state को एक bit pattern दीजिए), excitation equations, और आख़िर में gates।",
        "Reduction step के लिए दो स्वतंत्र methods हैं, और आप एक असली worked example दोनों से चलाएँगे: सादे tables के लिए direct row-matching, और cyclic या nested dependencies वाले tables के लिए triangular implication chart, जिन्हें अकेले row-matching साफ़-साफ़ सुलझा नहीं पाती।",
        "अंत तक आप states को bits assign करेंगे, वही ffExcite मशीनरी वापरकर जो पिछले modules वापरते थे flip-flop excitation equations निकालेंगे, और यह module पूरे Sequential Logic track को बंद करता है - modules 28 से 42 तक - memory elements, datapath building blocks, FSM theory और design, और वे भौतिक timing सीमाएँ जो तय करती हैं यह सब असल में कितनी तेज़ चल सकता है।"
      ],
      transcriptEN: "Welcome to the last module of the Sequential Logic track: designing state machines from scratch. Every earlier module analysed a circuit that already existed. This one starts from a plain sentence and ends at gates. Watch the spec, detect two consecutive ones, grow into a state diagram one clause at a time. Then the pipeline: diagram to table, table to a reduced table by merging equivalent states, reduced table to an assigned table with real bit patterns, assigned table to excitation equations, equations to gates. Two methods handle reduction: direct row-matching, and the implication chart for the messier, cyclic cases. By the end you assign bits, derive excitation equations, and close out modules 28 through 42 - memory, datapath, FSM theory and design, and the physical timing limits next door.",
      transcriptHI: "Sequential Logic track के आख़िरी module में आपका स्वागत है: शुरू से state machines design करना। पिछले हर module ने पहले से मौजूद circuit analyse किया। यह एक सादे वाक्य से शुरू होकर gates पर ख़त्म होता है। Spec, दो लगातार ones detect कीजिए, को clause-दर-clause एक state diagram में बढ़ते देखिए। फिर pipeline: diagram से table, table से equivalent states merge करके reduced table, reduced table से असली bit patterns वाला assigned table, assigned table से excitation equations, equations से gates। दो methods reduction संभालती हैं: direct row-matching, और उलझे, cyclic cases के लिए implication chart। अंत तक आप bits assign करते हैं, excitation equations निकालते हैं, और modules 28 से 42 तक बंद करते हैं - memory, datapath, FSM theory और design, और बग़ल के भौतिक timing सीमाएँ।",
      visualNote: "Hero: a progressive-reveal state-diagram wizard. Click through 4 steps and a 'detect two consecutive 1s' Moore machine grows state by state, edge by edge, from a bare sentence to a full 3-state diagram."
    },
    {
      id: "S01_Video",
      label: "Designing State Machines, The Full Pipeline",
      kind: "video",
      subtitle: "A short film: spec to state diagram to reduced, assigned, gate-level hardware.",
      theoryEN: [
        "Here is the whole pipeline in one breath before you watch. A word spec becomes a state diagram (circles for states, arcs for input/output-labelled transitions), the diagram becomes a state table, the table gets reduced by merging any states that behave identically, the reduced states get assigned real bit patterns, and the assigned table finally yields flip-flop excitation equations that a K-map turns into gates.",
        "Reduction is the step most students skip and regret skipping. Two states are equivalent, by definition, only if they give identical outputs for every input AND their next-states are themselves equivalent for every input. Skipping the check means paying for extra flip-flops and extra gates that a merge would have made unnecessary.",
        "Two methods prove equivalence. Row-matching scans the table by eye for identical rows - fast when the table is small and the equivalences are direct. The implication chart is the fall-back for anything cyclic: a triangular grid of every state pair, crossed out the instant outputs differ, and cascaded closed whenever a cell's fate turns out to depend on a pair that later gets crossed.",
        "Assignment then hands each surviving state a bit pattern. Binary spends the fewest flip-flops - ceil(log2 N) of them - but pays for it with heavier decoding logic. One-hot spends one flip-flop per state but keeps the next-state logic almost embarrassingly simple, because each state already owns its own wire.",
        "Finally the excitation table - the same engine every flip-flop-conversion module in this track has used - reverse-engineers exactly what J, K, D or T value each flip-flop needs to make its required Q(t) to Q(t+1) jump, and a K-map turns those columns into the minimal gates a single master clock drives."
      ],
      theoryHI: [
        "देखने से पहले पूरा pipeline एक साँस में। एक word spec एक state diagram बनता है (states के लिए circles, input/output-labelled transitions के लिए arcs), diagram एक state table बनता है, table equivalent states merge करके reduce होता है, बचे states को असली bit patterns assign होते हैं, और assigned table आख़िर में flip-flop excitation equations देता है जिन्हें एक K-map gates में बदल देता है।",
        "Reduction वह step है जिसे ज़्यादातर students छोड़ते हैं और पछताते हैं। दो states equivalent, परिभाषा से, तभी हैं जब वे हर input के लिए identical outputs दें AND उनके next-states ख़ुद हर input के लिए equivalent हों। जाँच छोड़ना मतलब अतिरिक्त flip-flops और gates के लिए दाम चुकाना जिन्हें एक merge अनावश्यक बना देता।",
        "दो methods equivalence साबित करती हैं। Row-matching table को आँख से पहचान कर identical rows खोजती है - तेज़ जब table छोटी हो और equivalences सीधी हों। Implication chart किसी भी cyclic चीज़ का fall-back है: हर state pair का एक triangular grid, outputs अलग होते ही cross out, और cascade होकर बंद जब भी किसी cell का भाग्य किसी ऐसी pair पर निर्भर निकले जो बाद में cross हो जाए।",
        "Assignment फिर हर बचे state को एक bit pattern थमाता है। Binary सबसे कम flip-flops ख़र्च करता है - ceil(log2 N) - पर बदले में भारी decoding logic का दाम चुकाता है। One-hot हर state पर एक flip-flop ख़र्च करता है पर next-state logic लगभग शर्मनाक रूप से सरल रखता है, क्योंकि हर state के पास पहले से अपनी तार है।",
        "आख़िर में excitation table - वही engine जो इस track के हर flip-flop-conversion module ने वापरा - reverse-engineer करती है कि हर flip-flop को अपना ज़रूरी Q(t) से Q(t+1) उछाल करने को कौन सा J, K, D या T मान चाहिए, और एक K-map उन columns को उन न्यूनतम gates में बदल देता है जिन्हें एक साझा master clock चलाता है।"
      ],
      transcriptEN: "Here's the whole pipeline in one breath. A word spec becomes a state diagram, the diagram becomes a state table, the table gets reduced by merging identical-behaviour states, the reduced states get real bit patterns, and the assigned table yields excitation equations a K-map turns into gates. Reduction matters: two states are equivalent only if their outputs match for every input and their next-states are themselves equivalent. Two methods prove it - row-matching for simple tables, the implication chart, a triangular grid crossed out on output mismatch and cascaded closed on dependency, for anything cyclic. Assignment then hands states bit patterns: binary spends the fewest flip-flops but heavier decode logic; one-hot spends one flip-flop per state but keeps next-state logic almost trivially simple. Finally the excitation table - the same engine flip-flop conversion used - reverse-engineers exactly what input each flip-flop needs, and a K-map turns it into gates on one master clock.",
      transcriptHI: "पूरा pipeline एक साँस में। एक word spec एक state diagram बनता है, diagram एक state table बनता है, table identical-behaviour states merge करके reduce होता है, reduced states को असली bit patterns मिलते हैं, और assigned table excitation equations देता है जिन्हें K-map gates में बदलता है। Reduction मायने रखता है: दो states equivalent तभी हैं जब उनके outputs हर input पर मेल खाएँ और उनके next-states ख़ुद equivalent हों। दो methods इसे साबित करती हैं - सादे tables के लिए row-matching, और cyclic चीज़ के लिए implication chart, output mismatch पर cross out और dependency पर cascade होकर बंद होने वाला triangular grid। Assignment फिर states को bit patterns देता है: binary सबसे कम flip-flops पर भारी decode logic; one-hot हर state पर एक flip-flop पर लगभग सरल next-state logic। आख़िर में excitation table - वही engine जो flip-flop conversion वापरता था - reverse-engineer करती है हर flip-flop को कौन सा input चाहिए, और K-map उसे एक master clock पर gates में बदल देता है।",
      visualNote: "Animated explainer: the six-stage funnel icon (spec -> diagram -> table -> reduction/assignment -> excitation -> chip) with each stage lighting up as it is narrated."
    },
    {
      id: "S02_Facts",
      label: "The Design Procedure",
      kind: "theory",
      subtitle: "Spec -> diagram -> table -> reduction -> assignment -> excitation -> gates, one stage at a time.",
      theoryEN: [
        "Two decks describe the exact same procedure two ways, and both agree on the substance. The short version has five steps: define the state space (diagram, then table, then flag any unused codes), build excitation tables for the chosen flip-flop type, minimise each input column with a K-map, and realise the minimised equations in gates. The longer version names six stages, each one step down in abstraction and one step up in physical concreteness, ending literally at a picture of a chip: specification, diagram, table, assignment-and-reduction, excitation-and-minimisation, realisation.",
        "Stage one to stage two is the creative leap: read the word spec and decide what the machine needs to REMEMBER. Each distinct thing worth remembering becomes one state, drawn as a circle; every clock-triggered change of memory becomes a directed arc labelled input/output. For machines too complex to draw cleanly as a diagram, engineers switch to an ASM (Algorithmic State Machine) chart - a flowchart built from State, Decision and Conditional-Output boxes - but the underlying idea, one box per remembered condition, stays identical.",
        "Stage two to stage three is mechanical: walk every state and every input combination, read the diagram, and fill in a present-state times input grid with the next state and the output it produces. Any binary code that never gets assigned to a real state becomes a don't-care later - free help for the K-map, not wasted space.",
        "Stage four is reduction, and it deserves its own formal definition (Definition 6.1): two states are equivalent if and only if, for every possible input sequence, they produce the same output sequence regardless of which one you started in. Checked one step at a time that means two conditions together - identical outputs for every input, and next-states that are themselves equivalent for every input - and the next two scenes run a real worked table through the two standard ways of proving it: direct row-matching, and the triangular implication chart.",
        "Stage four also covers assignment: every surviving reduced state needs a concrete bit pattern before any equation can be written, and the classic choices are highly-encoded binary (ceil(log2 N) flip-flops, heavier decode logic), Gray code (one bit changes between neighbours, fewer switching hazards) and one-hot (N flip-flops, almost no decode logic at all) - the very trade-off the assignment scene ahead computes on a real table.",
        "Stage five is the excitation table, the engine of change: for the chosen flip-flop type, it tells you exactly what J, K, D or T value forces a required Q(t) to Q(t+1) jump, with JK and SR's don't-cares giving the K-map extra room to simplify. Stage six wires the minimised Boolean equations into real AND/OR gates feeding the flip-flop inputs, all triggered off one shared master clock - the physical circuit you could hand to a fabrication line."
      ],
      theoryHI: [
        "दो decks ठीक एक ही procedure को दो तरीक़ों से बताते हैं, और दोनों सार पर सहमत हैं। छोटे version के पाँच steps हैं: state space परिभाषित कीजिए (diagram, फिर table, फिर कोई unused codes चिह्नित कीजिए), चुने flip-flop type के लिए excitation tables बनाइए, हर input column को K-map से minimise कीजिए, और minimised equations को gates में साकार कीजिए। लंबे version में छह stages नाम दिए गए हैं, हर एक abstraction में एक क़दम नीचे और भौतिक ठोसता में एक क़दम ऊपर, आख़िर में शब्दशः एक chip की तस्वीर पर ख़त्म: specification, diagram, table, assignment-and-reduction, excitation-and-minimisation, realisation।",
        "Stage एक से stage दो रचनात्मक छलांग है: word spec पढ़िए और तय कीजिए machine को क्या याद रखना है। हर अलग याद रखने लायक़ चीज़ एक state बनती है, circle की तरह खींची; memory का हर clock-triggered बदलाव एक directed arc बनता है जो input/output से labelled है। जिन machines को diagram की तरह साफ़ खींचना बहुत जटिल हो, वहाँ engineers ASM (Algorithmic State Machine) chart पर जाते हैं - State, Decision और Conditional-Output boxes से बना एक flowchart - पर मूल विचार, हर याद रखी शर्त के लिए एक box, वही रहता है।",
        "Stage दो से stage तीन यांत्रिक है: हर state और हर input combination चलिए, diagram पढ़िए, और एक present-state गुणा input grid में next state और उसका output भर दीजिए। कोई भी binary code जो किसी असली state को कभी नहीं मिलता वह बाद में एक don't-care बन जाता है - K-map के लिए मुफ़्त मदद, बरबाद जगह नहीं।",
        "Stage चार reduction है, और इसका अपना formal definition (Definition 6.1) लायक़ है: दो states equivalent हैं अगर और सिर्फ़ अगर, किसी भी संभव input sequence के लिए, वे same output sequence देते हैं चाहे आप किसी से भी शुरू करें। एक-एक क़दम जाँचें तो इसका मतलब है दो शर्तें साथ - हर input के लिए identical outputs, और next-states जो ख़ुद हर input के लिए equivalent हों - और अगले दो scenes एक असली worked table को equivalence साबित करने के दो मानक तरीक़ों से चलाते हैं: direct row-matching, और triangular implication chart।",
        "Stage चार assignment भी covers करता है: हर बचा reduced state किसी equation के लिखे जाने से पहले एक ठोस bit pattern माँगता है, और क्लासिक विकल्प हैं highly-encoded binary (ceil(log2 N) flip-flops, भारी decode logic), Gray code (पड़ोसियों के बीच एक bit बदलता है, कम switching hazards) और one-hot (N flip-flops, लगभग कोई decode logic नहीं) - वही trade-off जो आगे assignment scene एक असली table पर गिनती है।",
        "Stage पाँच excitation table है, बदलाव का engine: चुने flip-flop type के लिए, यह ठीक बताती है कि कौन सा J, K, D या T मान एक ज़रूरी Q(t) से Q(t+1) उछाल मजबूर करता है, JK और SR के don't-cares K-map को simplify करने की अतिरिक्त गुंजाइश देते हुए। Stage छह minimised Boolean equations को असली AND/OR gates में wire करता है जो flip-flop inputs चलाते हैं, सब एक साझा master clock से trigger, वह भौतिक circuit जो आप fabrication line को थमा सकें।"
      ],
      transcriptEN: "Two decks, one procedure, five or six named steps. The five-step version: define the state space as a diagram then a table, flag unused codes, build excitation tables, K-map minimise, realise in gates. The six-stage funnel names it: specification, diagram, table, assignment-and-reduction, excitation-and-minimisation, realisation - each stage less abstract, more physical, ending at a chip. Spec to diagram is the creative leap: one circle per remembered condition, one labelled arc per clock-triggered change; complex machines use ASM charts instead. Diagram to table is mechanical bookkeeping. Reduction gets its own definition: two states are equivalent only if their outputs match for every input and their next-states are themselves equivalent - proved by row-matching or the implication chart. Assignment hands surviving states real bit patterns - binary, Gray, or one-hot, each a different flip-flop-versus-decode-logic trade. Excitation reverse-engineers the flip-flop inputs a required jump needs, and the K-map turns it into the gates one master clock drives.",
      transcriptHI: "दो decks, एक procedure, पाँच या छह नामी steps। पाँच-step version: state space को diagram फिर table की तरह परिभाषित कीजिए, unused codes चिह्नित कीजिए, excitation tables बनाइए, K-map minimise कीजिए, gates में साकार कीजिए। छह-stage funnel इसे नाम देता है: specification, diagram, table, assignment-and-reduction, excitation-and-minimisation, realisation - हर stage कम abstract, ज़्यादा physical, एक chip पर ख़त्म। Spec से diagram रचनात्मक छलांग है: हर याद रखी शर्त के लिए एक circle, हर clock-triggered बदलाव के लिए एक labelled arc; जटिल machines ASM charts वापरती हैं। Diagram से table यांत्रिक bookkeeping है। Reduction का अपना definition है: दो states equivalent तभी जब उनके outputs हर input पर मेल खाएँ और next-states ख़ुद equivalent हों - row-matching या implication chart से साबित। Assignment बचे states को असली bit patterns देता है - binary, Gray, या one-hot, हर एक अलग flip-flop-बनाम-decode-logic trade। Excitation एक ज़रूरी उछाल को चाहिए flip-flop inputs reverse-engineer करती है, और K-map उसे उन gates में बदल देता है जिन्हें एक master clock चलाता है।",
      visualNote: "A clickable 6-stage pipeline (StepThrough): specification -> diagram -> table -> assignment & reduction -> excitation & minimisation -> realisation, each stage naming its inputs/outputs."
    },
    {
      id: "S03_RowMatching",
      label: "State Reduction, Row-Matching",
      kind: "theory",
      subtitle: "Two rows that behave identically for every input are the same state - merge them, then look again.",
      theoryEN: [
        "Direct row-matching is the simplest possible proof of state equivalence, and it works whenever the equivalences in a table are not hidden behind cycles: scan every pair of rows, and if two states give identical outputs for every input AND land on identical next-states for every input, they are the same state wearing two different names.",
        "The method is a four-step loop. First, present-row inspection: scan the table for any two rows whose next-state columns and output columns match cell for cell. Second, state-row deletion: keep one of the two (conventionally the alphabetically earlier one) and delete the other. Third, recursive substitution: every remaining row that pointed at the deleted state now gets rewritten to point at the state you kept instead. Fourth, convergence: repeat the whole scan, because a substitution can expose a match that was invisible on the first pass - two rows that looked different only because they pointed at two states that have since turned out to be the same one.",
        "That fourth step is the one beginners skip, and it is the one that matters most. The worked table below starts with six states. The very first pass finds only ONE literal match. But once that merge is substituted through the table, a second pair of rows - which looked different a moment ago only because of where they pointed - becomes identical too, and a second merge fires. The table keeps shrinking until a full pass finds nothing left to merge; that is convergence, and only then is the table truly minimal.",
        "Try it yourself below: pick any two of the six starting states and the comparison panel checks them cell by cell, live, exactly the way the algorithm does internally - same outputs, same next-states, or not, computed on the spot, never pre-decided.",
        "Row-matching is fast and intuitive, but it has one real limitation worth remembering going into the next scene: it depends on spotting literal matches after each substitution pass, which works cleanly for small tables but gets easy to miss by eye once dependencies tangle into cycles. That is exactly the case the implication chart is built to handle."
      ],
      theoryHI: [
        "Direct row-matching state equivalence का सबसे सादा संभव सबूत है, और यह तब काम करता है जब table की equivalences cycles के पीछे छिपी न हों: हर row-जोड़ी को स्कैन कीजिए, और अगर दो states हर input के लिए identical outputs दें AND हर input के लिए identical next-states पर पहुँचें, तो वे दो अलग नामों वाला एक ही state हैं।",
        "Method एक चार-step loop है। पहला, present-row inspection: table में कोई भी दो rows खोजिए जिनके next-state columns और output columns cell-दर-cell मेल खाएँ। दूसरा, state-row deletion: दोनों में से एक रखिए (परंपरा से alphabetically पहला वाला) और दूसरा मिटाइए। तीसरा, recursive substitution: बाक़ी हर row जो मिटाए state की तरफ़ इशारा करती थी अब उसे बदलकर उस state की तरफ़ लिख दिया जाता है जो रखा। चौथा, convergence: पूरा scan दोहराइए, क्योंकि एक substitution ऐसा match खोल सकता है जो पहली बार अदृश्य था - दो rows जो अलग दिख रही थीं सिर्फ़ इसलिए क्योंकि वे दो states की तरफ़ इशारा करती थीं जो अब एक ही निकले।",
        "वही चौथा step है जो शुरुआती छोड़ते हैं, और वही सबसे ज़्यादा मायने रखता है। नीचे वाली worked table छह states से शुरू होती है। पहला ही pass सिर्फ़ एक literal match खोजता है। पर जैसे ही वह merge table में substitute होता है, दो और rows - जो अभी अलग दिख रही थीं सिर्फ़ इसलिए क्योंकि वे कहाँ इशारा करती थीं - भी identical बन जाती हैं, और दूसरा merge होता है। Table तब तक सिकुड़ती रहती है जब तक एक पूरा pass कुछ merge करने को न बचे; वही convergence है, और तभी table सचमुच minimal है।",
        "नीचे ख़ुद आज़माइए: छह शुरुआती states में से कोई भी दो चुनिए और comparison panel उन्हें cell-दर-cell, live, ठीक वैसे जाँचता है जैसे algorithm अंदर करता है - same outputs, same next-states, या नहीं, तुरंत गिना, कभी पहले से तय नहीं।",
        "Row-matching तेज़ और सहज है, पर इसकी एक असली सीमा है जो अगले scene में जाते हुए याद रखने लायक़ है: यह हर substitution pass के बाद literal matches पहचानने पर निर्भर है, जो छोटी tables के लिए साफ़ काम करती है पर जैसे ही dependencies cycles में उलझें, आँख से चूकना आसान हो जाता है। यही वह हालत है जिसे implication chart संभालने को बनाई गई है।"
      ],
      transcriptEN: "Direct row-matching: scan every pair of rows, and if two states give identical outputs for every input and land on identical next-states for every input, they're the same state under two names. Four steps: inspect rows for a literal match, delete one of the matched pair and keep the other, substitute every reference to the deleted state with the kept one, and repeat - because a substitution can expose a match invisible on the first pass. This worked table starts with six states. The first pass finds one match; substituting it through the table exposes a second match a moment later. The table keeps shrinking until a full pass finds nothing left - that's convergence. Try it yourself: pick any two states and the panel checks them live, cell by cell. Row-matching's real limitation: it depends on spotting literal matches, which gets easy to miss once dependencies tangle into cycles - exactly what the implication chart handles next.",
      transcriptHI: "Direct row-matching: हर row-जोड़ी स्कैन कीजिए, और अगर दो states हर input पर identical outputs दें और identical next-states पर पहुँचें, वे दो नामों वाला एक ही state हैं। चार steps: literal match के लिए rows जाँचिए, matched जोड़ी में से एक मिटाइए और दूसरा रखिए, मिटाए state के हर reference को रखे state से बदलिए, और दोहराइए - क्योंकि एक substitution पहली बार अदृश्य match खोल सकता है। यह worked table छह states से शुरू होती है। पहला pass एक match खोजता है; उसे table में substitute करने से एक क्षण बाद दूसरा match खुलता है। Table तब तक सिकुड़ती है जब तक एक पूरा pass कुछ न बचे - यही convergence है। ख़ुद आज़माइए: कोई भी दो states चुनिए और panel उन्हें live, cell-दर-cell जाँचता है। Row-matching की असली सीमा: यह literal matches पहचानने पर निर्भर है, जो dependencies के cycles में उलझते ही चूकना आसान हो जाता है - ठीक वही जो implication chart अगले भाग में संभालती है।",
      visualNote: "A live six-row Mealy state table (present, next-on-0, next-on-1, out-on-0, out-on-1); a pair-picker that compares any two rows cell by cell; a computed round-by-round merge log; the final reduced table. A second CustomVideoPlayer (dsd40-rowmatch.mp4) walks the same worked example."
    },
    {
      id: "S04_ImplicationChart",
      label: "State Reduction, The Implication Chart",
      kind: "theory",
      subtitle: "A triangular compatibility grid that survives the cyclic, cascading dependencies row-matching alone can miss.",
      theoryEN: [
        "The implication chart, sometimes called the triangular or cross-point matrix, is the systematic fall-back for exactly the case row-matching struggles with: two rows that LOOK different because they point to two different next-states, where those two next-states might themselves turn out to be equivalent, or might not - and you cannot tell just by glancing at one row.",
        "Build it as a lower-triangular grid: one cell per pair of states, laid out rows against columns. Every cell gets one of three verdicts. Output incompatibility: if the two states' outputs differ under any input, cross the cell immediately with a red X - they can never be equivalent, full stop, no further checking needed. Instant identity: if outputs match and the two next-states are already identical (or trivially self-referencing), check the cell immediately - compatible, done. Dependency entry: if outputs match but the next-states differ, write the pair those next-states form inside the cell - this cell's fate now depends on that other cell's fate.",
        "Then comes the part row-matching cannot do cleanly: cascaded resolution. Scan every still-open, dependency-holding cell; if the pair it depends on has since been crossed out, cross this cell out too - a single new cross can trigger a chain of further crosses, exactly the way a rumour that one scene got cut forces every scene that only existed to set it up to get cut as well. Repeat the scan until a full pass produces zero new crosses; that equilibrium is convergence, and every cell still uncrossed at that point names a genuinely compatible - equivalent - pair.",
        "The worked chart below runs a different six-state table through exactly this machine, live: click any cell to see, computed on the spot, why it is crossed (an immediate output mismatch, or a cascade back to a specific earlier crossed pair and the round it happened in) or why it survives (instant identity, or a dependency that itself never got crossed). Watch the crosses cascade for two full rounds before the grid settles.",
        "The chart and row-matching are two independent proofs of the same fact, state equivalence, and on a table small enough for both they must always agree - but the chart is the one that scales to cyclic dependencies a human eye would lose track of, which is exactly why textbooks teach it as the general-purpose method and row-matching as the fast path for simple cases."
      ],
      theoryHI: [
        "Implication chart, जिसे कभी-कभी triangular या cross-point matrix कहा जाता है, ठीक उस हालत का systematic fall-back है जिससे row-matching जूझती है: दो rows जो अलग दिखती हैं क्योंकि वे दो अलग next-states की तरफ़ इशारा करती हैं, जहाँ वे दो next-states ख़ुद equivalent निकल सकते हैं, या नहीं - और सिर्फ़ एक row देखकर आप बता नहीं सकते।",
        "इसे एक lower-triangular grid की तरह बनाइए: हर state-जोड़ी के लिए एक cell, rows बनाम columns में बिछी। हर cell को तीन में से एक फ़ैसला मिलता है। Output incompatibility: अगर दोनों states के outputs किसी input पर अलग हों, cell को तुरंत लाल X से cross कीजिए - वे कभी equivalent नहीं हो सकते, बात ख़त्म, आगे जाँच की ज़रूरत नहीं। Instant identity: अगर outputs मेल खाएँ और दोनों next-states पहले से identical हों (या trivially self-referencing), cell को तुरंत check कीजिए - compatible, हो गया। Dependency entry: अगर outputs मेल खाएँ पर next-states अलग हों, उन next-states की जोड़ी cell के अंदर लिख दीजिए - इस cell का भाग्य अब उस दूसरे cell के भाग्य पर निर्भर है।",
        "फिर आता है वह हिस्सा जो row-matching साफ़-साफ़ नहीं कर सकती: cascaded resolution। हर अभी-खुले, dependency रखते cell को स्कैन कीजिए; अगर जिस जोड़ी पर वह निर्भर है वह बाद में cross हो चुकी हो, इस cell को भी cross कीजिए - एक नया cross crosses की एक chain शुरू कर सकता है, ठीक वैसे जैसे यह अफ़वाह कि एक scene कट गई हर उस scene को भी काटने पर मजबूर करती है जो सिर्फ़ उसे set up करने के लिए मौजूद थी। स्कैन तब तक दोहराइए जब तक एक पूरा pass शून्य नए crosses न दे; वह equilibrium ही convergence है, और उस पल अभी uncrossed हर cell एक सचमुच compatible - equivalent - जोड़ी नाम देता है।",
        "नीचे वाली worked chart इसी मशीन से एक अलग छह-state table को live चलाती है: किसी भी cell पर click कीजिए यह देखने को, तुरंत गिना, कि वह क्यों cross हुआ (एक तुरंत output mismatch, या किसी ख़ास पहले cross हुई जोड़ी और round तक वापस cascade) या क्यों बचा (instant identity, या एक dependency जो ख़ुद कभी cross नहीं हुई)। Crosses को दो पूरे rounds तक cascade होते देखिए इससे पहले कि grid settle हो।",
        "Chart और row-matching एक ही तथ्य, state equivalence, के दो स्वतंत्र सबूत हैं, और एक table पर जो दोनों के लिए काफ़ी छोटी हो वे हमेशा सहमत होने चाहिए - पर chart वह है जो cyclic dependencies तक scale करता है जिन्हें इंसानी आँख भूल सकती है, इसीलिए textbooks इसे general-purpose method और row-matching को सादे cases के लिए fast path सिखाती हैं।"
      ],
      transcriptEN: "The implication chart is the systematic fall-back for the case row-matching struggles with: rows that look different only because they point to different next-states, which might themselves turn out equivalent. Build a triangular grid, one cell per state pair. Three verdicts: output incompatibility crosses a cell immediately if outputs ever differ; instant identity checks a cell immediately if next-states already match; dependency entry writes the next-state pair inside the cell when outputs match but next-states don't yet. Then cascaded resolution: scan every open cell, and if its dependency pair has since been crossed, cross this cell too - one new cross can trigger a chain. Repeat until a full pass produces zero new crosses - convergence - and every cell still open names a genuinely compatible pair. The chart below runs a six-state table through this live: click any cell to see why it's crossed or why it survives, and watch crosses cascade for two rounds before the grid settles. The chart and row-matching prove the same fact two ways, but the chart is the one that scales to cycles.",
      transcriptHI: "Implication chart उस हालत का systematic fall-back है जिससे row-matching जूझती है: rows जो अलग दिखती हैं सिर्फ़ इसलिए क्योंकि वे अलग next-states की तरफ़ इशारा करती हैं, जो ख़ुद equivalent निकल सकते हैं। एक triangular grid बनाइए, हर state-जोड़ी के लिए एक cell। तीन फ़ैसले: output incompatibility cell को तुरंत cross करती है अगर outputs कभी अलग हों; instant identity cell को तुरंत check करती है अगर next-states पहले से मेल खाएँ; dependency entry next-state जोड़ी cell के अंदर लिखती है जब outputs मेल खाएँ पर next-states अभी नहीं। फिर cascaded resolution: हर खुले cell को स्कैन कीजिए, और अगर उसकी dependency जोड़ी बाद में cross हुई हो, इस cell को भी cross कीजिए - एक नया cross एक chain शुरू कर सकता है। तब तक दोहराइए जब तक एक पूरा pass शून्य नए crosses न दे - convergence - और उस पल अभी खुला हर cell एक सचमुच compatible जोड़ी नाम देता है। नीचे वाली chart एक छह-state table को इससे live चलाती है: किसी cell पर click कीजिए यह देखने को कि वह क्यों cross हुआ या क्यों बचा, और crosses को दो rounds तक cascade होते देखिए। Chart और row-matching एक ही तथ्य को दो तरीक़ों से साबित करते हैं, पर chart वह है जो cycles तक scale करता है।",
      visualNote: "A clickable triangular grid over a second six-state table; cells show X (crossed, with round + reason), ✓ (checked, instant identity), a dependency pair label, or the resolved verdict; a selected-cell explanation panel; final compatible pairs listed via computed union-find."
    },
    {
      id: "S05_Assignment",
      label: "State Assignment",
      kind: "theory",
      subtitle: "Same reduced states, different bit patterns - binary, Gray or one-hot - and the gate count moves.",
      theoryEN: [
        "A reduced state is still just a label - S0, S1, S2 - until assignment gives it a concrete pattern of 0s and 1s that a real register can hold. Every assignment scheme must obey one hard floor: it needs at least ceil(log2 N) flip-flops to give N states distinct codes, but nothing stops you spending MORE flip-flops than that floor if it buys simpler logic elsewhere.",
        "Binary (highly-encoded) assignment spends exactly the floor: N states get exactly ceil(log2 N) flip-flops, numbered off sequentially. It is the cheapest possible register cost, but the price shows up in the combinational logic - deciding whether the present state IS a specific state means ANDing together every bit of that state's code, so the next-state and output logic has to fully decode multi-bit patterns.",
        "One-hot assignment spends one flip-flop PER state - N of them for N states - with exactly one bit high at any instant. It is the most expensive possible register cost, but the combinational logic barely needs decoding at all: each state already owns a dedicated wire, so a next-state equation is just an OR of (that source state's own bit AND the input condition) for every incoming transition, no multi-bit ANDing required.",
        "Run the machine that opened this module - the three-state \"detect two consecutive 1s\" spec - through both schemes below, live. Binary needs ceil(log2 3) = 2 flip-flops; one-hot needs all 3. Then watch the computed cost model count, for every transition, exactly how many literals a next-state term needs to build under each scheme: binary terms must AND every present-state bit plus the input, while one-hot terms need only that one dedicated source bit plus the input.",
        "There is no universally right answer, and the honest comparison below proves it: for a machine this small, binary can even come out ahead on raw literal count, because it needs fewer flip-flops and fewer total terms even though each term is a little more expensive. The real-world rule of thumb is about which resource is scarcer on your target chip - an ASIC squeezed for register area leans binary or Gray; an FPGA with flip-flops to spare leans one-hot for the faster, simpler decode."
      ],
      theoryHI: [
        "एक reduced state तब तक सिर्फ़ एक label है - S0, S1, S2 - जब तक assignment उसे 0s और 1s का एक ठोस pattern नहीं देती जिसे कोई असली register पकड़ सके। हर assignment scheme को एक सख़्त फ़र्श मानना पड़ता है: N states को अलग codes देने के लिए कम से कम ceil(log2 N) flip-flops चाहिए, पर कुछ भी आपको उस फ़र्श से ज़्यादा ख़र्च करने से नहीं रोकता अगर वह कहीं और सरल logic ख़रीद ले।",
        "Binary (highly-encoded) assignment ठीक फ़र्श ख़र्च करती है: N states को ठीक ceil(log2 N) flip-flops मिलते हैं, क्रम से नंबर किए। यह सबसे सस्ता संभव register दाम है, पर क़ीमत combinational logic में दिखती है - present state किसी ख़ास state के बराबर है यह तय करना उस state के code के हर bit को साथ AND करने जैसा है, तो next-state और output logic को पूरे multi-bit patterns decode करने पड़ते हैं।",
        "One-hot assignment हर state पर एक flip-flop ख़र्च करती है - N states को N - किसी भी पल ठीक एक bit high के साथ। यह सबसे महँगा संभव register दाम है, पर combinational logic को लगभग decode ही नहीं चाहिए: हर state के पास पहले से समर्पित तार है, तो एक next-state equation बस हर आने वाले transition के लिए (उस source state की अपनी bit AND input शर्त) का OR है, कोई multi-bit ANDing नहीं चाहिए।",
        "जिस machine ने यह module खोला - तीन-state \"दो लगातार 1s detect कीजिए\" spec - उसे नीचे दोनों schemes से live चलाइए। Binary को ceil(log2 3) = 2 flip-flops चाहिए; one-hot को पूरे 3। फिर computed cost model को गिनते देखिए, हर transition के लिए, ठीक कितने literals एक next-state term को हर scheme के तहत बनाने चाहिए: binary terms को present-state की हर bit जमा input AND करनी पड़ती है, जबकि one-hot terms को सिर्फ़ वह एक समर्पित source bit जमा input चाहिए।",
        "कोई सार्वभौमिक सही जवाब नहीं है, और नीचे वाली ईमानदार तुलना यह साबित करती है: इतनी छोटी machine के लिए, binary raw literal गिनती पर भी आगे निकल सकती है, क्योंकि इसे कम flip-flops और कम कुल terms चाहिए भले ही हर term थोड़ा महँगा हो। असली दुनिया का अंगूठा-नियम इस बारे में है कि आपकी target chip पर कौन सा resource दुर्लभ है - register area को लेकर तंग एक ASIC binary या Gray की तरफ़ झुकता है; बचे flip-flops वाला एक FPGA तेज़, सरल decode के लिए one-hot की तरफ़ झुकता है।"
      ],
      transcriptEN: "A reduced state is just a label until assignment gives it a real bit pattern. Every scheme needs at least ceil(log2 N) flip-flops for N states, but you can spend more if it buys simpler logic. Binary spends exactly that floor - cheapest register cost - but the price shows up in decode logic: deciding you're in a specific state means ANDing together every bit of its code. One-hot spends one flip-flop per state, the most expensive register cost, but barely needs decoding at all - each state owns a dedicated wire, so a next-state equation is just an OR of source-bit-AND-input terms. Run the two-consecutive-ones machine through both live: binary needs two flip-flops, one-hot needs three. Watch the cost model count literals per term under each scheme. There's no universal winner - for a machine this small binary can even win on raw literal count, because it needs fewer flip-flops and fewer terms even though each term costs a bit more. The real rule of thumb is which resource is scarcer on your target chip.",
      transcriptHI: "एक reduced state सिर्फ़ एक label है जब तक assignment उसे असली bit pattern नहीं देती। हर scheme को N states के लिए कम से कम ceil(log2 N) flip-flops चाहिए, पर आप ज़्यादा ख़र्च कर सकते हैं अगर वह सरल logic ख़रीद ले। Binary ठीक वह फ़र्श ख़र्च करती है - सबसे सस्ता register दाम - पर क़ीमत decode logic में दिखती है: किसी ख़ास state में होने का फ़ैसला उसके code की हर bit को साथ AND करना है। One-hot हर state पर एक flip-flop ख़र्च करती है, सबसे महँगा register दाम, पर लगभग decode ही नहीं चाहिए - हर state की अपनी समर्पित तार है, तो next-state equation बस source-bit-AND-input terms का OR है। दो-लगातार-ones machine को दोनों से live चलाइए: binary को दो flip-flops चाहिए, one-hot को तीन। Cost model को हर scheme के तहत term-प्रति-literals गिनते देखिए। कोई सार्वभौमिक विजेता नहीं है - इतनी छोटी machine के लिए binary raw literal गिनती पर भी जीत सकती है, क्योंकि इसे कम flip-flops और कम terms चाहिए भले ही हर term थोड़ा महँगा हो। असली अंगूठा-नियम यह है कि आपकी target chip पर कौन सा resource दुर्लभ है।",
      visualNote: "A binary vs one-hot code table for the 3-state spec machine; a next-state-per-scheme table; a computed literal/term/flip-flop cost comparison rendered as two stat panels side by side."
    },
    {
      id: "S06_Excitation",
      label: "Excitation Equations",
      kind: "theory",
      subtitle: "From the assigned state table to the flip-flop input equations, one bit column at a time.",
      theoryEN: [
        "The excitation table is the same engine every flip-flop-conversion module in this track has leaned on: for a chosen flip-flop type, it answers the question \"what input value forces THIS specific Q(t) to Q(t+1) jump?\" for all four possible jumps, 0 to 0, 0 to 1, 1 to 0 and 1 to 1. D is trivial - the excitation IS the next value, D = Q(t+1) - while T asks only whether the bit needs to toggle, T = Q(t) xor Q(t+1). JK and SR carry genuine don't-cares, which is exactly the flexibility a K-map exploits to shrink the final equation.",
        "Turning an assigned state table into excitation equations is now pure bookkeeping. For every row of the table - present code, input, next code - and for every flip-flop bit position, look up what that flip-flop's excitation table demands to move THIS bit from its present value to its next value, and write it into a new column. Do that for all bit positions and all rows and you have the master table this scene builds live, reusing the very same ffExcite function the earlier flip-flop modules used, never a hand-typed answer.",
        "Reading the equation off that master table depends on which assignment you picked in the previous scene. Under binary assignment, a flip-flop's excitation column is 1 only for specific present-state codes, so each product term in the resulting sum-of-products has to AND together every present-state bit to pin down exactly which state it is talking about, plus the input literal. Under one-hot assignment the same excitation column collapses to something much shorter: since only one flip-flop is ever set for a given state, a term needs only that one source flip-flop's own output ANDed with the input - no other bit's complement is required at all.",
        "Pick a flip-flop type and an assignment scheme below and watch both the master table and the resulting equation regenerate live, alongside the flip-flop's own excitation table for reference - the blueprint every column above is reading from.",
        "This is the very last algebra step before silicon: once every flip-flop's excitation equation is written and minimised, wiring it up is just AND and OR gates feeding the flip-flop's data pins, all sharing one master clock - exactly the same six-gate-and-a-clock picture Sequential_Sequential_Design's two worked counters (the JK 3-bit counter and the D-type stepper sequence) end on."
      ],
      theoryHI: [
        "Excitation table वही engine है जिस पर इस track के हर flip-flop-conversion module ने भरोसा किया: चुने flip-flop type के लिए, यह सवाल का जवाब देती है \"कौन सा input मान ठीक इस Q(t) से Q(t+1) उछाल को मजबूर करता है?\" चारों संभव उछालों के लिए, 0 से 0, 0 से 1, 1 से 0 और 1 से 1। D तुच्छ है - excitation ख़ुद अगला मान है, D = Q(t+1) - जबकि T सिर्फ़ पूछता है कि bit को toggle होना चाहिए या नहीं, T = Q(t) xor Q(t+1)। JK और SR असली don't-cares रखते हैं, जो ठीक वह लचीलापन है जिसे एक K-map आख़िरी equation सिकोड़ने को वापरता है।",
        "एक assigned state table को excitation equations में बदलना अब शुद्ध bookkeeping है। Table की हर row के लिए - present code, input, next code - और हर flip-flop bit position के लिए, देखिए कि उस flip-flop की excitation table क्या माँगती है इस bit को अपने present मान से अगले मान तक ले जाने को, और उसे एक नए column में लिख दीजिए। सभी bit positions और सभी rows के लिए यह कीजिए और आपके पास वह master table है जो यह scene live बनाता है, वही ffExcite function फिर से वापरते हुए जो पिछले flip-flop modules वापरते थे, कभी हाथ से टाइप जवाब नहीं।",
        "उस master table से equation पढ़ना इस पर निर्भर करता है कि आपने पिछले scene में कौन सा assignment चुना। Binary assignment के तहत, एक flip-flop का excitation column सिर्फ़ ख़ास present-state codes के लिए 1 है, तो नतीजे वाले sum-of-products में हर product term को present-state की हर bit साथ AND करनी पड़ती है ठीक-ठीक बताने को कि यह कौन से state की बात कर रहा है, जमा input literal। One-hot assignment के तहत वही excitation column कहीं छोटे में सिमट जाता है: चूँकि किसी दिए state के लिए कभी सिर्फ़ एक flip-flop set होता है, एक term को सिर्फ़ उस एक source flip-flop के अपने output को input से AND करना चाहिए - किसी और bit के complement की ज़रूरत ही नहीं।",
        "नीचे एक flip-flop type और एक assignment scheme चुनिए और master table और नतीजा equation दोनों को live फिर से बनते देखिए, साथ में reference के लिए flip-flop की अपनी excitation table - वह blueprint जिससे ऊपर का हर column पढ़ रहा है।",
        "यह silicon से पहले का बिलकुल आख़िरी algebra step है: एक बार हर flip-flop का excitation equation लिख और minimise हो जाए, इसे wire करना बस AND और OR gates है जो flip-flop के data pins चलाते हैं, सब एक साझा master clock बाँटते - ठीक वही six-gate-and-a-clock तस्वीर जिस पर Sequential_Sequential_Design के दोनों worked counters (JK 3-bit counter और D-type stepper sequence) ख़त्म होते हैं।"
      ],
      transcriptEN: "The excitation table is the same engine flip-flop conversion leaned on: for a chosen type it answers what input forces a specific Q(t) to Q(t+1) jump. D is trivial - D equals the next value. T asks only whether to toggle. JK and SR carry real don't-cares, the flexibility a K-map exploits. Turning an assigned table into excitation equations is bookkeeping: for every row and every flip-flop bit, look up what that bit's excitation table demands and write a new column - reusing the same ffExcite function earlier modules used, never a hand-typed answer. Under binary assignment, each product term must AND together every present-state bit plus the input, to pin down exactly which state. Under one-hot, a term needs only that one source flip-flop's output ANDed with the input - no other bit's complement required. Pick a flip-flop type and a scheme below and watch the master table and equation regenerate live, next to the flip-flop's own excitation table for reference. This is the last algebra step before silicon - AND and OR gates feeding the flip-flop pins, one shared master clock.",
      transcriptHI: "Excitation table वही engine है जिस पर flip-flop conversion भरोसा करती थी: चुने type के लिए यह बताती है कौन सा input एक ख़ास Q(t) से Q(t+1) उछाल मजबूर करता है। D तुच्छ है - D बराबर अगला मान। T सिर्फ़ पूछता है toggle करें या नहीं। JK और SR असली don't-cares रखते हैं, वह लचीलापन जो K-map वापरता है। Assigned table को excitation equations में बदलना bookkeeping है: हर row और हर flip-flop bit के लिए, देखिए उस bit की excitation table क्या माँगती है और एक नया column लिखिए - वही ffExcite function फिर वापरते हुए, कभी हाथ से टाइप जवाब नहीं। Binary assignment के तहत, हर product term को present-state की हर bit जमा input AND करनी पड़ती है, ठीक बताने को कौन सा state। One-hot के तहत, एक term को सिर्फ़ उस एक source flip-flop के output को input से AND करना चाहिए - किसी और bit के complement की ज़रूरत नहीं। नीचे एक flip-flop type और scheme चुनिए और master table व equation को live फिर बनते देखिए, साथ reference के लिए flip-flop की अपनी excitation table। यह silicon से पहले का आख़िरी algebra step है - AND और OR gates जो flip-flop pins चलाते हैं, एक साझा master clock।",
      visualNote: "A flip-flop type picker (D/T) + assignment scheme picker (binary/one-hot); a computed master table (present code, X, next code, excitation per bit); the derived SOP equation per flip-flop; the reference ExciteTable component."
    },
    {
      id: "S07_Analogy",
      label: "The Film Editor's Cut",
      kind: "theory",
      subtitle: "Two scenes that tell the same story from here on are the same scene - cut one, keep the other.",
      theoryEN: [
        "Picture a film editor with a rough cut that runs too long. Two scenes, shot on different days, turn out to carry exactly the same weight in the story: from either one, the audience reacts the same way to whatever happens next, and the story from that point forward plays out identically no matter which of the two scenes they just watched. Definition 6.1's two conditions - identical outputs for every input, and next-states that are themselves equivalent for every input - is exactly that test, just written in circuit language instead of screenplay language.",
        "So the editor cuts one of the two scenes and splices every cue that used to point at it onto the surviving scene instead. Nothing about the finished film changes - not one frame the audience sees is different - because the cut scene was never carrying information the story needed on its own. That is precisely what a state-reduction merge does to a state machine: delete the redundant state, redirect every transition that pointed at it, and the machine's observable input-output behaviour, for every possible input sequence, does not change by a single bit.",
        "The convergence step has a script-editing parallel too. Cutting one duplicate scene can reveal that a SECOND pair of scenes, which looked different only because one of them referenced the scene that just got cut, are now telling the identical story as well - so the editor makes a second cut, and checks again. A real edit does not stop after one merge any more than the row-matching algorithm does; both keep passing over the material until a full pass finds nothing left to trim.",
        "The computed cut list below is generated live from this module's own row-matching worked example - the same six states from two scenes ago, the same merges, in the same order they actually fired. Read it as the editor's cut sheet: which scene got cut, which surviving scene absorbed its cues, and why - because the two agreed on every output and every next scene.",
        "The payoff is the same in both worlds. A tighter film costs less to shoot and holds the audience's attention better; a reduced state machine costs fewer flip-flops and less gate delay while producing an output sequence indistinguishable from the unreduced original. Reduction is never optional editorial polish - it is free hardware savings, sitting there for anyone willing to check."
      ],
      theoryHI: [
        "एक film editor की कल्पना कीजिए जिसका rough cut बहुत लंबा चल रहा है। दो scenes, अलग दिनों शूट हुई, कहानी में ठीक एक ही वज़न रखती निकलती हैं: दोनों में से किसी से भी, दर्शक आगे जो भी हो उस पर वही react करते हैं, और उस बिंदु से आगे कहानी बिलकुल एक जैसी चलती है चाहे उन्होंने दोनों में से कौन सी scene अभी देखी हो। Definition 6.1 की दो शर्तें - हर input के लिए identical outputs, और next-states जो ख़ुद हर input के लिए equivalent हों - ठीक यही जाँच है, बस circuit की भाषा में लिखी न कि screenplay की भाषा में।",
        "तो editor दोनों में से एक scene काटता है और जो भी cue उसकी तरफ़ इशारा करता था उसे बदलकर बचे scene पर splice कर देता है। पूरी बनी film में कुछ नहीं बदलता - दर्शक जो एक भी frame देखते हैं वह अलग नहीं - क्योंकि कटी scene कभी ऐसी जानकारी नहीं ले जा रही थी जो कहानी को अपने आप में चाहिए थी। यही ठीक है जो एक state-reduction merge एक state machine को करता है: फ़ालतू state मिटाइए, उसकी तरफ़ इशारा करता हर transition redirect कीजिए, और machine का देखा जा सकने वाला input-output बर्ताव, किसी भी संभव input sequence के लिए, एक bit भी नहीं बदलता।",
        "Convergence step का भी एक script-editing समांतर है। एक duplicate scene काटना यह खोल सकता है कि एक दूसरी जोड़ी scenes, जो अलग दिख रही थीं सिर्फ़ इसलिए क्योंकि उनमें से एक उस scene का reference रखती थी जो अभी कटी, अब भी वही identical कहानी बता रही हैं - तो editor दूसरा cut करता है, और फिर जाँचता है। एक असली edit एक merge के बाद नहीं रुकता, ठीक वैसे जैसे row-matching algorithm नहीं रुकती; दोनों तब तक सामग्री पर से गुज़रते रहते हैं जब तक एक पूरा pass कुछ trim करने को न बचे।",
        "नीचे वाली computed cut list इसी module के अपने row-matching worked example से live बनती है - दो scenes पहले वाले वही छह states, वही merges, ठीक उसी क्रम में जिसमें वे असल में हुए। इसे editor की cut sheet की तरह पढ़िए: कौन सी scene कटी, किस बचे scene ने उसके cues अपनाए, और क्यों - क्योंकि दोनों हर output और हर अगली scene पर सहमत थे।",
        "फ़ायदा दोनों दुनियाओं में एक जैसा है। एक कसी हुई film शूट करने में कम ख़र्च करती है और दर्शक का ध्यान बेहतर पकड़ती है; एक reduced state machine कम flip-flops और कम gate delay ख़र्च करती है जबकि एक output sequence देती है जो बिना-reduce मूल से अलग नहीं पहचाना जा सकता। Reduction कभी वैकल्पिक editorial polish नहीं है - यह मुफ़्त hardware बचत है, वहीं बैठी किसी भी जाँचने को तैयार के लिए।"
      ],
      transcriptEN: "Picture a film editor with a rough cut that runs too long. Two scenes, shot on different days, turn out to carry the same weight in the story - from either one the audience reacts the same way and the story plays out identically from that point on. That's exactly Definition 6.1: identical outputs for every input, and next-states that are themselves equivalent. So the editor cuts one and splices every cue onto the survivor - not one frame the audience sees changes, because the cut scene never carried information the story needed on its own. Convergence has a parallel too: cutting one duplicate can reveal a second pair now telling the identical story, so the editor cuts again and checks once more, exactly like row-matching's repeated passes. The computed cut list below is generated live from this module's own row-matching example - same six states, same merges, same order they actually fired. The payoff matches in both worlds: a tighter film costs less to shoot, a reduced machine costs fewer flip-flops, for identical observable behaviour.",
      transcriptHI: "एक film editor की कल्पना कीजिए जिसका rough cut बहुत लंबा चल रहा है। दो scenes, अलग दिनों शूट हुई, कहानी में एक जैसा वज़न रखती निकलती हैं - दोनों में से किसी से भी दर्शक वही react करते हैं और कहानी उस बिंदु से बिलकुल एक जैसी चलती है। यही ठीक Definition 6.1 है: हर input के लिए identical outputs, और next-states जो ख़ुद equivalent हों। तो editor एक काटता है और हर cue बचे scene पर splice करता है - दर्शक जो frame देखते हैं वह नहीं बदलता, क्योंकि कटी scene कभी ऐसी जानकारी नहीं ले जा रही थी जो कहानी को चाहिए थी। Convergence का भी समांतर है: एक duplicate काटना दूसरी जोड़ी को खोल सकता है जो अब वही identical कहानी बता रही है, तो editor फिर काटता है और फिर जाँचता है, ठीक row-matching के बार-बार passes की तरह। नीचे वाली computed cut list इसी module के अपने row-matching example से live बनती है - वही छह states, वही merges, वही क्रम जिसमें वे हुए। फ़ायदा दोनों दुनियाओं में मेल खाता है: एक कसी film शूट करने में कम ख़र्च करती है, एक reduced machine कम flip-flops ख़र्च करती है, identical observable बर्ताव के लिए।",
      visualNote: "A film-strip row of six scene cards labelled with the row-matching example's states, colour-coded kept/cut, with computed cut-sheet captions generated from the actual merge log."
    },
    {
      id: "S08_Build",
      label: "Build A State Machine For Real",
      kind: "theory",
      subtitle: "Open the workbench and wire the reduced, assigned FSM from real flip-flops and gates.",
      theoryEN: [
        "Now stop reading and design one end to end. Take the three-state \"detect two consecutive 1s\" spec from the top of this module, reduce it (it is already minimal, which is itself worth confirming), assign it binary codes with two flip-flops, derive the D excitation equations exactly the way this module just did, and wire the result on the live workbench.",
        "You will need two D flip-flops for the two state bits, a small handful of AND/OR gates realising the excitation equations you derived, and one shared clock line driving both flip-flops on the same edge. Feed the circuit a bit stream by hand and confirm the output pulses high on exactly the clock edge that completes a second consecutive 1 - and stays high on every immediately following 1, because overlap is allowed.",
        "Then stress-test your own design the way a real engineer would: feed it 1 1 1 and confirm the output goes high on the second 1 AND stays high on the third, feed it 1 0 1 1 and confirm the isolated 1 does nothing until the very next 1 1 pair completes, and feed it a run of 0s and confirm the machine falls back to its start state and stays quiet.",
        "This is the entire module in miniature, hands on hardware: spec, diagram, table, reduction, assignment, excitation, gates - the same six stages, run once more, by you, end to end."
      ],
      theoryHI: [
        "अब पढ़ना रोकिए और शुरू से आख़िर तक एक design कीजिए। इस module के शुरुआती \"दो लगातार 1s detect कीजिए\" वाले तीन-state spec को लीजिए, इसे reduce कीजिए (यह पहले से minimal है, जिसे ख़ुद पुष्टि करना लायक़ है), इसे दो flip-flops के साथ binary codes assign कीजिए, D excitation equations ठीक वैसे निकालिए जैसे यह module अभी-अभी करता था, और नतीजे को live workbench पर wire कीजिए।",
        "आपको दो state bits के लिए दो D flip-flops चाहिए होंगे, आपके निकाले excitation equations साकार करते मुट्ठी भर AND/OR gates, और एक साझा clock line जो दोनों flip-flops को एक ही edge पर चलाए। Circuit को हाथ से एक bit stream खिलाइए और पुष्टि कीजिए कि output ठीक उस clock edge पर high pulse करे जो दूसरा लगातार 1 पूरा करे - और हर अगले 1 पर high रहे, क्योंकि overlap इजाज़त है।",
        "फिर अपने ही design को वैसे तनाव-जाँचिए जैसे एक असली engineer करेगा: इसे 1 1 1 खिलाइए और पुष्टि कीजिए output दूसरे 1 पर high हो AND तीसरे पर high रहे, इसे 1 0 1 1 खिलाइए और पुष्टि कीजिए अकेला 1 तब तक कुछ न करे जब तक अगला 1 1 जोड़ा पूरा न हो, और इसे 0s की एक कतार खिलाइए और पुष्टि कीजिए machine वापस अपने start state पर गिरे और शांत रहे।",
        "यह पूरा module एक छोटे रूप में है, hardware पर हाथ से: spec, diagram, table, reduction, assignment, excitation, gates - वही छह stages, एक बार फिर, आपके द्वारा, शुरू से आख़िर तक।"
      ],
      transcriptEN: "Stop reading and design one end to end. Take the three-state two-consecutive-ones spec, reduce it, assign it binary codes with two flip-flops, derive the D excitation equations, and wire the result on the workbench. Two D flip-flops, a handful of AND/OR gates, one shared clock. Feed it a bit stream and confirm the output pulses on exactly the edge completing a second consecutive one, staying high on every following one since overlap is allowed. Stress-test it: one one one should go high on the second one and stay high on the third; one zero one one should stay quiet until the second pair completes; a run of zeros should fall back to the start state. This is the entire module in miniature, hands on hardware, run once more by you.",
      transcriptHI: "पढ़ना रोकिए और शुरू से आख़िर तक एक design कीजिए। तीन-state दो-लगातार-ones spec लीजिए, इसे reduce कीजिए, दो flip-flops के साथ binary codes assign कीजिए, D excitation equations निकालिए, और नतीजे को workbench पर wire कीजिए। दो D flip-flops, मुट्ठी भर AND/OR gates, एक साझा clock। इसे एक bit stream खिलाइए और पुष्टि कीजिए output ठीक उस edge पर pulse करे जो दूसरा लगातार one पूरा करे, हर अगले one पर high रहते हुए क्योंकि overlap इजाज़त है। तनाव-जाँचिए: one one one दूसरे one पर high हो और तीसरे पर high रहे; one zero one one तब तक शांत रहे जब तक दूसरा जोड़ा पूरा न हो; zeros की एक कतार वापस start state पर गिरे। यह पूरा module एक छोटे रूप में है, hardware पर हाथ से, आपके द्वारा एक बार फिर।",
      visualNote: "WorkbenchCTA opening /workbench?tutorial=state-machine-design, plus a reminder of the two-flip-flop, binary-assigned two-consecutive-ones circuit."
    },
    {
      id: "S09_Flashcards",
      label: "Flashcards",
      kind: "flashcards",
      subtitle: "Eight flip-cards to lock in the pipeline, the two reduction methods and the assignment trade-off.",
      theoryEN: [
        "These eight flip-cards drill the facts that matter most: the six-stage design funnel in order, the formal definition of state equivalence, what row-matching's convergence pass is really checking for, what an X versus a checkmark versus a dependency label means on an implication chart, the flip-flop-count formula, and the binary-versus-one-hot trade-off.",
        "Give extra reps to the equivalence definition card and the implication-chart cascade card - those are the two ideas most often tested with a made-up table where you have to apply the rule, not just recite it.",
        "If you keep only one idea from this whole module, keep this: reducing states before assigning them is never optional polish - every merged state is a flip-flop and a pile of gates you never had to build."
      ],
      theoryHI: [
        "ये आठ flip-cards सबसे ज़रूरी तथ्य रटाते हैं: क्रम में छह-stage design funnel, state equivalence की formal definition, row-matching का convergence pass असल में क्या जाँचता है, implication chart पर X बनाम checkmark बनाम dependency label का क्या मतलब है, flip-flop-count formula, और binary-बनाम-one-hot trade-off।",
        "Equivalence definition वाले card और implication-chart cascade वाले card को ज़्यादा दोहराइए - ये वे दो विचार हैं जो सबसे ज़्यादा एक बनाई table पर जाँचे जाते हैं जहाँ आपको नियम apply करना है, सिर्फ़ रटना नहीं।",
        "अगर आप इस पूरे module से सिर्फ़ एक विचार रखें, तो यह: states को assign करने से पहले reduce करना कभी वैकल्पिक polish नहीं है - हर merged state एक flip-flop और gates का ढेर है जो आपको कभी बनाना नहीं पड़ा।"
      ],
      transcriptEN: "Eight quick flip-cards to set it solid. Front asks, back answers - cover the back, say it aloud, then flip to check. Give extra reps to the equivalence definition and the implication-chart cascade, the two ideas most often tested with a made-up table. Keep one idea: reducing before assigning is never optional polish - every merged state is hardware you never had to build.",
      transcriptHI: "इसे पक्का करने को आठ तेज़ flip-cards। आगे सवाल, पीछे जवाब - पीछे ढककर ज़ोर से बोलिए, फिर पलटिए। Equivalence definition और implication-chart cascade को ज़्यादा दोहराइए, वे दो विचार जो सबसे ज़्यादा एक बनाई table पर जाँचे जाते हैं। एक विचार रखिए: assign करने से पहले reduce करना कभी वैकल्पिक polish नहीं है - हर merged state hardware है जो आपको कभी बनाना नहीं पड़ा।",
      visualNote: "Standard bilingual flip deck, eight cards."
    },
    {
      id: "S10_Quiz",
      label: "Quiz Arena",
      kind: "quiz",
      subtitle: "Seven questions - prove you can reduce, assign and derive a real state machine.",
      theoryEN: [
        "Seven multiple-choice questions now check that the design pipeline has really sunk in. They probe the correct stage order, the two-condition definition of state equivalence, when row-matching is allowed to merge two rows, what an immediate X on an implication chart means, what a cascade cross means, the flip-flop count for a reduced machine, and the honest binary-versus-one-hot trade-off.",
        "Several questions are apply-the-rule questions, not recall: you will check whether a described pair of rows is actually a valid merge, and reason through what happens to a chart cell once its dependency gets crossed. Work those carefully - write down the two conditions and check both, rather than guessing from a gut feeling.",
        "Aim for full marks here, because clearing all seven means you can take any word spec, walk it all the way to a minimal, correctly-assigned, gate-level circuit - which is the exact skill the workbench tutorial puts in your hands, and the skill this entire Sequential Logic track has been building toward since module 28."
      ],
      theoryHI: [
        "सात bahu-vikalp सवाल अब जाँचते हैं कि design pipeline सचमुच बैठा या नहीं। ये पूछते हैं सही stage क्रम, state equivalence की दो-शर्त definition, row-matching कब दो rows को merge करने की इजाज़त देती है, implication chart पर तुरंत X का क्या मतलब है, cascade cross का क्या मतलब है, एक reduced machine के लिए flip-flop गिनती, और ईमानदार binary-बनाम-one-hot trade-off।",
        "कई सवाल apply-the-rule सवाल हैं, सिर्फ़ रटना नहीं: आप जाँचेंगे कि बताई rows की जोड़ी सचमुच एक valid merge है या नहीं, और तर्क करेंगे कि एक chart cell का क्या होता है जब उसकी dependency cross हो जाए। इन्हें ध्यान से कीजिए - दोनों शर्तें लिखिए और दोनों जाँचिए, बजाय gut feeling से अंदाज़ा लगाने के।",
        "यहाँ पूरे अंक का लक्ष्य रखिए, क्योंकि सातों साफ़ करना मतलब आप कोई भी word spec ले सकते हैं, उसे पूरे रास्ते एक minimal, सही-assigned, gate-level circuit तक चला सकते हैं - ठीक वही skill जो workbench tutorial आपके हाथ में देता है, और वह skill जिसकी तरफ़ यह पूरा Sequential Logic track module 28 से बना रहा है।"
      ],
      transcriptEN: "Seven questions check the design pipeline sunk in: stage order, the two-condition equivalence definition, when row-matching may merge, what an immediate X on the chart means, what a cascade cross means, the flip-flop count for a reduced machine, and the honest binary-versus-one-hot trade-off. Several are apply-the-rule, not recall - check both conditions rather than guessing. Aim for full marks: clearing all seven means you can take any word spec all the way to a minimal, correctly-assigned, gate-level circuit, the skill this whole track has built toward since module 28.",
      transcriptHI: "सात सवाल जाँचते हैं design pipeline बैठा: stage क्रम, दो-शर्त equivalence definition, row-matching कब merge कर सकती है, chart पर तुरंत X का मतलब, cascade cross का मतलब, reduced machine के लिए flip-flop गिनती, और ईमानदार binary-बनाम-one-hot trade-off। कई apply-the-rule हैं, सिर्फ़ रटना नहीं - अंदाज़े के बजाय दोनों शर्तें जाँचिए। पूरे अंक का लक्ष्य रखिए: सातों साफ़ करना मतलब आप कोई भी word spec एक minimal, सही-assigned, gate-level circuit तक ले जा सकते हैं, वह skill जिसकी तरफ़ यह पूरा track module 28 से बना रहा है।",
      visualNote: "QuizArena, badge FSM."
    },
    {
      id: "S11_Recap",
      label: "Recap - Sequential Logic, Complete",
      kind: "recap",
      subtitle: "Spec to silicon - and the close of the entire Sequential Logic track, modules 28 through 42.",
      theoryEN: [
        "Designing a state machine is one loop, walked once: read the word spec and decide what to remember (the state diagram), tabulate every present-state-and-input combination (the state table), merge any states that behave identically by row-matching or the implication chart (reduction), give every surviving state a concrete bit pattern (assignment), reverse-engineer what each flip-flop's inputs must do with the excitation table (excitation equations), and wire the minimised result into gates on one shared clock (realisation).",
        "Row-matching and the implication chart are two independent proofs of the exact same fact, Definition 6.1's state equivalence - identical outputs for every input, and next-states that are themselves equivalent. Row-matching is the fast path when the table is small and the matches are direct; the implication chart is the general-purpose method that survives cyclic, cascading dependencies a human eye loses track of.",
        "Assignment is never free: binary spends the fewest flip-flops, ceil(log2 N), at the cost of heavier decode logic; one-hot spends one flip-flop per state at the benefit of almost trivial next-state logic; Gray code sits in between, trading nothing on flip-flop count for far fewer bit-toggles between neighbouring states. The right choice depends on which resource - registers or gate delay - is scarcer on the target chip.",
        "And this module closes the entire Sequential Logic track. It began at memory itself - latches and flip-flops, the one-bit cells that remember a value across a clock edge. It grew into datapath machinery - registers, shift registers, ripple and synchronous counters, decoding logic - built by chaining those memory cells together. It climbed into FSM theory and design - analysing an existing circuit back to its state diagram, the Mealy-versus-Moore output philosophies, and, in this very module, synthesising a brand new machine from nothing but a sentence.",
        "The two modules immediately after this one complete the picture with the physical realities every one of those designs has to survive: asynchronous design and the hazards that appear when signals race each other through real, non-zero-delay gates. Memory, datapath, FSM theory and design, physical reality - four movements of one argument, and you have now walked every one of them."
      ],
      theoryHI: [
        "एक state machine design करना एक loop है, एक बार चला: word spec पढ़िए और तय कीजिए क्या याद रखना है (state diagram), हर present-state-और-input combination सारणीबद्ध कीजिए (state table), जो states एक जैसा बर्ताव करें उन्हें row-matching या implication chart से merge कीजिए (reduction), हर बचे state को एक ठोस bit pattern दीजिए (assignment), excitation table से reverse-engineer कीजिए हर flip-flop के inputs को क्या करना चाहिए (excitation equations), और minimised नतीजे को एक साझा clock पर gates में wire कीजिए (realisation)।",
        "Row-matching और implication chart ठीक एक ही तथ्य, Definition 6.1 की state equivalence, के दो स्वतंत्र सबूत हैं - हर input के लिए identical outputs, और next-states जो ख़ुद equivalent हों। Row-matching fast path है जब table छोटी हो और matches सीधे हों; implication chart general-purpose method है जो cyclic, cascading dependencies तक बचती है जिन्हें इंसानी आँख भूल सकती है।",
        "Assignment कभी मुफ़्त नहीं है: binary सबसे कम flip-flops ख़र्च करती है, ceil(log2 N), भारी decode logic की क़ीमत पर; one-hot हर state पर एक flip-flop ख़र्च करती है लगभग तुच्छ next-state logic के फ़ायदे पर; Gray code बीच में बैठता है, flip-flop गिनती पर कुछ trade किए बिना पड़ोसी states के बीच बहुत कम bit-toggles देता है। सही चुनाव इस पर निर्भर करता है कि target chip पर कौन सा resource - registers या gate delay - दुर्लभ है।",
        "और यह module पूरे Sequential Logic track को बंद करता है। यह ख़ुद memory से शुरू हुआ था - latches और flip-flops, वे one-bit cells जो एक clock edge भर एक मान याद रखते हैं। यह datapath मशीनरी में बढ़ा - registers, shift registers, ripple और synchronous counters, decoding logic - उन memory cells को साथ जोड़कर बनी। यह FSM theory और design में चढ़ा - एक मौजूदा circuit को वापस उसके state diagram तक analyse करना, Mealy-बनाम-Moore output दर्शन, और, ठीक इसी module में, सिर्फ़ एक वाक्य से एक बिलकुल नई machine synthesise करना।",
        "इसके ठीक बाद के दो modules उन भौतिक हक़ीक़तों से तस्वीर पूरी करते हैं जिनसे हर design को बचना पड़ता है: asynchronous design और वे hazards जो तब दिखते हैं जब signals असली, non-zero-delay gates से गुज़रते हुए एक-दूसरे से रेस लगाते हैं। Memory, datapath, FSM theory और design, भौतिक हक़ीक़त - एक तर्क के चार movements, और अब आप उन सबसे गुज़र चुके हैं।"
      ],
      transcriptEN: "Designing a state machine is one loop: spec to diagram, diagram to table, table to reduced table by row-matching or the implication chart, reduced table to assigned table with real bit patterns, assigned table to excitation equations, equations to gates on one shared clock. Row-matching and the implication chart prove the same fact two ways - row-matching fast for direct matches, the chart general-purpose for cyclic dependencies. Assignment always trades: binary cheapest on flip-flops, heaviest on decode; one-hot most flip-flops, simplest decode; Gray in between. And this module closes the Sequential Logic track: it began at memory, latches and flip-flops; grew into datapath, registers and counters; climbed into FSM theory and design, analysis, Mealy versus Moore, and synthesising a machine from a sentence right here. The two modules after this complete it with the physical realities - asynchronous design and hazards. Memory, datapath, FSM theory and design, physical reality - four movements, all walked.",
      transcriptHI: "एक state machine design करना एक loop है: spec से diagram, diagram से table, table से reduced table row-matching या implication chart से, reduced table से assigned table असली bit patterns के साथ, assigned table से excitation equations, equations से gates एक साझा clock पर। Row-matching और implication chart एक ही तथ्य को दो तरीक़ों से साबित करते हैं - direct matches के लिए row-matching तेज़, cyclic dependencies के लिए chart general-purpose। Assignment हमेशा trade करता है: binary flip-flops पर सबसे सस्ता, decode पर सबसे भारी; one-hot सबसे ज़्यादा flip-flops, सबसे सरल decode; Gray बीच में। और यह module Sequential Logic track बंद करता है: यह memory से शुरू हुआ, latches और flip-flops; datapath में बढ़ा, registers और counters; FSM theory और design में चढ़ा, analysis, Mealy बनाम Moore, और यहीं एक वाक्य से एक machine synthesise करना। इसके बाद के दो modules भौतिक हक़ीक़तों से इसे पूरा करते हैं - asynchronous design और hazards। Memory, datapath, FSM theory और design, भौतिक हक़ीक़त - चार movements, सब चले।",
      visualNote: "FlowRail, then a horizontal 15-node timeline (modules 28-42) grouped into Memory / Datapath / FSM Theory & Design / Physical Reality bands, module 40 marked 'you are here'."
    }
  ],
  flashcards: [
    {
      frontEN: "The six-stage design funnel, in order",
      backEN: "Specification (human thought) -> state diagram (spatial geometry) -> state table (tabular data) -> assignment & reduction (mathematical optimisation) -> excitation & Boolean minimisation (binary logic) -> logic circuit realisation (physical silicon).",
      frontHI: "छह-stage design funnel, क्रम में",
      backHI: "Specification (human thought) -> state diagram (spatial geometry) -> state table (tabular data) -> assignment & reduction (mathematical optimisation) -> excitation & Boolean minimisation (binary logic) -> logic circuit realisation (physical silicon)।"
    },
    {
      frontEN: "State equivalence, formal definition (Def. 6.1)",
      backEN: "States Si and Sj are equivalent iff, for every possible input sequence, the same output sequence results no matter which one you started in. In one step that means TWO conditions together: identical outputs for every input, AND next-states that are themselves equivalent for every input.",
      frontHI: "State equivalence, formal definition (Def. 6.1)",
      backHI: "States Si और Sj equivalent हैं अगर, किसी भी संभव input sequence के लिए, same output sequence आए चाहे आप किसी से भी शुरू करें। एक step में इसका मतलब है दो शर्तें साथ: हर input के लिए identical outputs, AND next-states जो ख़ुद हर input के लिए equivalent हों।"
    },
    {
      frontEN: "Row-matching's convergence pass - what is it really checking?",
      backEN: "After every merge, a substitution can turn two rows that LOOKED different (because they pointed at two different states) into two rows that are now identical (because those two states just merged). Convergence means repeating the scan until a full pass finds nothing new - only then is the table truly minimal.",
      frontHI: "Row-matching का convergence pass - यह असल में क्या जाँचता है?",
      backHI: "हर merge के बाद, एक substitution दो rows को जो अलग दिख रही थीं (क्योंकि वे दो अलग states की तरफ़ इशारा करती थीं) अब identical बना सकता है (क्योंकि वे दो states अभी merge हुए)। Convergence मतलब scan दोहराना जब तक एक पूरा pass कुछ नया न पाए - तभी table सचमुच minimal है।"
    },
    {
      frontEN: "Implication chart: X vs checkmark vs a dependency label",
      backEN: "A red X = output-incompatible, crossed immediately, never equivalent. A checkmark = instant identity, outputs match and next-states are already identical. A dependency label like \"b-h\" = outputs match but the cell's fate depends on whether pair (b,h) survives - resolved later by cascade.",
      frontHI: "Implication chart: X बनाम checkmark बनाम dependency label",
      backHI: "लाल X = output-incompatible, तुरंत cross, कभी equivalent नहीं। Checkmark = instant identity, outputs मेल खाते और next-states पहले से identical। \"b-h\" जैसा dependency label = outputs मेल खाते पर cell का भाग्य इस पर निर्भर कि जोड़ी (b,h) बचती है या नहीं - बाद में cascade से तय।"
    },
    {
      frontEN: "Cascade invalidation on the chart",
      backEN: "If a cell's fate depends on pair (X,Y), and (X,Y) later gets crossed, the dependent cell is crossed too - a single new cross can trigger a chain of further crosses, round after round, until a full pass produces zero new crosses.",
      frontHI: "Chart पर cascade invalidation",
      backHI: "अगर किसी cell का भाग्य जोड़ी (X,Y) पर निर्भर है, और (X,Y) बाद में cross हो जाए, तो निर्भर cell भी cross होता है - एक नया cross आगे crosses की एक chain शुरू कर सकता है, round-दर-round, जब तक एक पूरा pass शून्य नए crosses न दे।"
    },
    {
      frontEN: "Required flip-flop count formula",
      backEN: "Required flip-flops = ceil(log2 N), where N is the number of REDUCED states - always minimise states first, because the formula runs on the smaller N.",
      frontHI: "ज़रूरी flip-flop गिनती का formula",
      backHI: "ज़रूरी flip-flops = ceil(log2 N), जहाँ N REDUCED states की संख्या है - हमेशा पहले states minimise कीजिए, क्योंकि formula छोटे N पर चलता है।"
    },
    {
      frontEN: "Binary vs one-hot - the honest trade-off",
      backEN: "Binary: ceil(log2 N) flip-flops, cheapest registers, but next-state logic must AND together every present-state bit to decode a specific state. One-hot: N flip-flops, one bit per state, but next-state logic is just OR of (source bit AND input) terms - almost no decoding at all.",
      frontHI: "Binary बनाम one-hot - ईमानदार trade-off",
      backHI: "Binary: ceil(log2 N) flip-flops, सबसे सस्ते registers, पर next-state logic को एक ख़ास state decode करने को present-state की हर bit साथ AND करनी पड़ती है। One-hot: N flip-flops, हर state पर एक bit, पर next-state logic बस (source bit AND input) terms का OR है - लगभग कोई decoding नहीं।"
    },
    {
      frontEN: "Excitation table - the engine of change",
      backEN: "For a chosen flip-flop type, it reverse-engineers exactly what input value forces a specific Q(t) to Q(t+1) jump - D excitation is just the next value itself, T excitation is Q(t) xor Q(t+1), and JK/SR carry genuine don't-cares a K-map can exploit.",
      frontHI: "Excitation table - बदलाव का engine",
      backHI: "चुने flip-flop type के लिए, यह ठीक-ठीक reverse-engineer करती है कि कौन सा input मान एक ख़ास Q(t) से Q(t+1) उछाल मजबूर करता है - D excitation बस अगला मान ख़ुद है, T excitation Q(t) xor Q(t+1) है, और JK/SR असली don't-cares रखते हैं जिन्हें एक K-map वापर सकता है।"
    }
  ],
  quiz: [
    {
      questionEN: "Which sequence correctly orders the state-machine design pipeline?",
      questionHI: "कौन सा क्रम state-machine design pipeline को सही ठहराता है?",
      options: [
        "word spec -> state diagram -> state table -> reduction -> assignment -> excitation -> gates",
        "state table -> word spec -> gates -> reduction -> excitation -> state diagram -> assignment",
        "excitation -> word spec -> gates -> state diagram -> state table -> reduction -> assignment",
        "gates -> assignment -> excitation -> reduction -> state table -> state diagram -> word spec"
      ],
      answerIndex: 0,
      explainEN: "The funnel only runs one direction, decreasing abstraction: spec, then diagram, then table, then reduction, then assignment, then excitation equations, then gates.",
      explainHI: "Funnel सिर्फ़ एक दिशा में चलता है, घटती abstraction के साथ: spec, फिर diagram, फिर table, फिर reduction, फिर assignment, फिर excitation equations, फिर gates।"
    },
    {
      questionEN: "Two states Si and Sj are formally equivalent only when...",
      questionHI: "दो states Si और Sj formally equivalent तभी हैं जब...",
      options: [
        "their outputs match for at least one input combination",
        "their outputs match for every input, AND their next-states are themselves equivalent for every input",
        "they happen to share the same binary code",
        "they both appear in the same row of the state table"
      ],
      answerIndex: 1,
      explainEN: "Definition 6.1 needs both conditions together - matching outputs alone is not enough if the next-states the two rows lead to are not themselves equivalent.",
      explainHI: "Definition 6.1 को दोनों शर्तें साथ चाहिए - सिर्फ़ outputs मेल खाना काफ़ी नहीं अगर दोनों rows जिन next-states तक ले जाती हैं वे ख़ुद equivalent न हों।"
    },
    {
      questionEN: "In direct row-matching, two rows may be merged into one state as soon as...",
      questionHI: "Direct row-matching में, दो rows को एक state में merge किया जा सकता है जैसे ही...",
      options: [
        "they are physically adjacent in the table",
        "their next-state columns AND output columns are identical, cell for cell, for every input",
        "one of them has a lower state name alphabetically",
        "their outputs are both 1 for at least one input"
      ],
      answerIndex: 1,
      explainEN: "A literal cell-for-cell match on both next-state and output columns, across every input, is exactly the row-matching merge condition.",
      explainHI: "Next-state और output दोनों columns पर, हर input पर, cell-दर-cell literal match ही ठीक row-matching की merge शर्त है।"
    },
    {
      questionEN: "An immediate red X in an implication-chart cell means...",
      questionHI: "Implication-chart cell में एक तुरंत लाल X का मतलब है...",
      options: [
        "the pair's outputs differ under some input - they can never be equivalent, no further checking needed",
        "the pair still needs a K-map to be checked later",
        "the pair is definitely equivalent",
        "the cell was skipped by the algorithm"
      ],
      answerIndex: 0,
      explainEN: "Output incompatibility is a permanent, immediate disqualification - once outputs differ under any input, the pair is done, no matter what their next-states are.",
      explainHI: "Output incompatibility एक स्थायी, तुरंत अयोग्यता है - एक बार outputs किसी input पर अलग हों, जोड़ी ख़त्म, चाहे उनके next-states कुछ भी हों।"
    },
    {
      questionEN: "A chart cell depends on pair (X,Y). Later, (X,Y) itself gets crossed out. What happens to the original cell?",
      questionHI: "एक chart cell जोड़ी (X,Y) पर निर्भर है। बाद में, (X,Y) ख़ुद cross हो जाती है। मूल cell का क्या होता है?",
      options: [
        "nothing - dependencies only matter in the first pass",
        "it is crossed out too, in a later round - cascade invalidation",
        "it automatically becomes an instant identity",
        "the chart is discarded and row-matching must be used instead"
      ],
      answerIndex: 1,
      explainEN: "That is the cascade: a dependent cell can only stay compatible if what it depends on stays compatible. Once (X,Y) is crossed, the cell relying on it is crossed too, in the next round of scanning.",
      explainHI: "यही cascade है: एक निर्भर cell तभी compatible रह सकता है जब जिस पर वह निर्भर है वह compatible रहे। एक बार (X,Y) cross हो, उस पर निर्भर cell भी अगले scanning round में cross होता है।"
    },
    {
      questionEN: "This module's worked row-matching example reduces six states down to four. At minimum, how many flip-flops does the reduced machine need?",
      questionHI: "इस module का worked row-matching example छह states को चार तक reduce करता है। कम से कम, reduced machine को कितने flip-flops चाहिए?",
      options: ["1", "2", "3", "4"],
      answerIndex: 1,
      explainEN: "Required flip-flops = ceil(log2 N). With N = 4 reduced states, ceil(log2 4) = 2 - two flip-flops give exactly four codes, one per surviving state.",
      explainHI: "ज़रूरी flip-flops = ceil(log2 N)। N = 4 reduced states के साथ, ceil(log2 4) = 2 - दो flip-flops ठीक चार codes देते हैं, हर बचे state के लिए एक।"
    },
    {
      questionEN: "Why might a real design lean toward one-hot encoding even though it costs more flip-flops than binary?",
      questionHI: "एक असली design one-hot encoding की तरफ़ क्यों झुक सकती है भले ही यह binary से ज़्यादा flip-flops ख़र्च करे?",
      options: [
        "one-hot is always cheaper overall, in every case, with no trade-off at all",
        "on chips where flip-flops are cheap and plentiful (like FPGAs), one-hot's much simpler next-state/decode logic saves gate delay and design complexity",
        "one-hot never requires any combinational logic whatsoever",
        "binary encoding is illegal on modern hardware"
      ],
      answerIndex: 1,
      explainEN: "The trade is real, not universal: one-hot spends more registers to buy simpler, faster decode logic, which is a good trade specifically where flip-flops are the cheap resource and gate delay/complexity is the scarce one - classically FPGAs and CPLDs.",
      explainHI: "यह trade असली है, सार्वभौमिक नहीं: one-hot ज़्यादा registers ख़र्च करके सरल, तेज़ decode logic ख़रीदता है, जो ख़ास तौर पर वहाँ अच्छा trade है जहाँ flip-flops सस्ता resource हों और gate delay/complexity दुर्लभ - क्लासिक रूप से FPGAs और CPLDs।"
    }
  ]
};
