/**
 * The inspector's contract: what it says about a cell must be what the
 * simulator would do to that cell.
 *
 * The truth-table cases matter most. They are generated by running netlistSim
 * on a one-cell netlist, so a regression here means the inspector and the wires
 * beside it have started telling different stories — which is worse than showing
 * nothing at all.
 */
import { describe, it, expect } from 'vitest';
import {
  parseNetlist, pickModule, inspectCell, inspectNet, truthTableFor, dirOf,
  describeType, moduleSourceAt, excerptAt, submoduleNetlist, moduleNames,
} from './cellInspect';
import { synthesizeNode } from '../../engine/verilog/testing/yosysNode';

/** A netlist with one cell wired to three top-level ports. */
const oneCell = (
  type: string,
  connections: Record<string, (number | string)[]>,
  parameters: Record<string, string> = {},
  ports: Record<string, { direction: string; bits: (number | string)[] }> = {},
) => JSON.stringify({
  modules: {
    top: {
      attributes: { top: 1 },
      ports,
      cells: { 'g$1': { type, parameters, connections } },
      netnames: {},
    },
  },
});

describe('cellInspect — port direction', () => {
  it('trusts port_directions when Yosys supplies them', () => {
    const cell = { type: '$foo', port_directions: { A: 'input', Z: 'output' }, connections: {} };
    expect(dirOf(cell, 'A')).toBe('input');
    expect(dirOf(cell, 'Z')).toBe('output');
  });

  it('falls back to the Y/Q/X naming convention for built-in cells', () => {
    const cell = { type: '$and', connections: {} };
    expect(dirOf(cell, 'A')).toBe('input');
    expect(dirOf(cell, 'B')).toBe('input');
    expect(dirOf(cell, 'Y')).toBe('output');
    expect(dirOf(cell, 'Q')).toBe('output');
  });
});

describe('cellInspect — truth tables by simulation', () => {
  it('enumerates a 1-bit AND exactly', () => {
    const cell = { type: '$and', parameters: { A_WIDTH: '1', B_WIDTH: '1', Y_WIDTH: '1' },
                   connections: { A: [2], B: [3], Y: [4] } };
    const { table } = truthTableFor(cell);
    expect(table).toBeDefined();
    expect(table!.inputs.map((i) => i.name)).toEqual(['A', 'B']);
    expect(table!.outputs.map((o) => o.name)).toEqual(['Y']);
    expect(table!.rows).toHaveLength(4);
    // Rows are enumerated LSB-first over the free bits: A then B.
    expect(table!.rows.map((r) => [...r.in, ...r.out])).toEqual([
      ['0', '0', '0'],
      ['1', '0', '0'],
      ['0', '1', '0'],
      ['1', '1', '1'],
    ]);
  });

  it('enumerates a 1-bit XOR exactly', () => {
    const cell = { type: '$xor', parameters: { A_WIDTH: '1', B_WIDTH: '1', Y_WIDTH: '1' },
                   connections: { A: [2], B: [3], Y: [4] } };
    const rows = truthTableFor(cell).table!.rows.map((r) => r.out[0]);
    expect(rows).toEqual(['0', '1', '1', '0']);
  });

  it('gives a mux its select column and the right choice per row', () => {
    const cell = { type: '$mux', parameters: { WIDTH: '1' },
                   connections: { A: [2], B: [3], S: [4], Y: [5] } };
    const { table } = truthTableFor(cell)!;
    // $mux is Y = S ? B : A.
    for (const row of table!.rows) {
      const [a, b, s] = row.in;
      expect(row.out[0]).toBe(s === '1' ? b : a);
    }
  });

  it('treats a bit wired to two pins as ONE degree of freedom', () => {
    // A and B share net 2, so only the two combinations 0/0 and 1/1 exist.
    const cell = { type: '$and', parameters: { A_WIDTH: '1', B_WIDTH: '1', Y_WIDTH: '1' },
                   connections: { A: [2], B: [2], Y: [4] } };
    const { table } = truthTableFor(cell);
    expect(table!.rows).toHaveLength(2);
    expect(table!.rows.map((r) => [...r.in, ...r.out])).toEqual([
      ['0', '0', '0'],
      ['1', '1', '1'],
    ]);
  });

  it('folds constant inputs into every row rather than enumerating them', () => {
    const cell = { type: '$and', parameters: { A_WIDTH: '1', B_WIDTH: '1', Y_WIDTH: '1' },
                   connections: { A: [2], B: ['0'], Y: [4] } };
    const { table } = truthTableFor(cell);
    expect(table!.rows).toHaveLength(2);
    expect(table!.rows.every((r) => r.in[1] === '0' && r.out[0] === '0')).toBe(true);
  });

  it('formats multi-bit ports as hex', () => {
    const cell = { type: '$add', parameters: { A_WIDTH: '2', B_WIDTH: '2', Y_WIDTH: '2' },
                   connections: { A: [2, 3], B: ['0', '1'], Y: [6, 7] } };
    const { table } = truthTableFor(cell);
    // B is the constant 2 (bit1 set), so Y = A + 2 truncated to 2 bits.
    expect(table!.rows.map((r) => r.out[0])).toEqual(['0x2', '0x3', '0x0', '0x1']);
  });

  it('refuses a table for stateful cells and says why', () => {
    const cell = { type: '$dff', parameters: { WIDTH: '1' },
                   connections: { CLK: [2], D: [3], Q: [4] } };
    const { table, note } = truthTableFor(cell);
    expect(table).toBeUndefined();
    expect(note).toMatch(/stateful/i);
  });

  it('refuses a table that would be too large, and reports the size', () => {
    const bits = (n: number, from: number) => Array.from({ length: n }, (_, i) => from + i);
    const cell = { type: '$add', parameters: { A_WIDTH: '8', B_WIDTH: '8', Y_WIDTH: '8' },
                   connections: { A: bits(8, 10), B: bits(8, 30), Y: bits(8, 50) } };
    const { table, note } = truthTableFor(cell);
    expect(table).toBeUndefined();
    expect(note).toMatch(/16 input bits/);
  });

  it('refuses a table when the cell feeds back into itself', () => {
    const cell = { type: '$and', parameters: { A_WIDTH: '1', B_WIDTH: '1', Y_WIDTH: '1' },
                   connections: { A: [2], B: [4], Y: [4] } };
    const { table, note } = truthTableFor(cell);
    expect(table).toBeUndefined();
    expect(note).toMatch(/feeds back/i);
  });
});

describe('cellInspect — inspectCell', () => {
  it('reports type, position, parameters and ports', () => {
    const nl = parseNetlist(oneCell('$and',
      { A: [2], B: [3], Y: [4] }, { A_WIDTH: '1', Y_WIDTH: '1' }))!;
    const d = inspectCell(nl, 'g$1')!;
    expect(d.kind).toBe('cell');
    expect(d.type).toBe('$and');
    expect(d.title).toBe('AND');
    expect(d.index).toBe(1);
    expect(d.total).toBe(1);
    expect(d.params).toEqual([['A_WIDTH', '1'], ['Y_WIDTH', '1']]);
    expect(d.ports.map((p) => [p.name, p.dir, p.netId]))
      .toEqual([['A', 'input', '2'], ['B', 'input', '3'], ['Y', 'output', '4']]);
    expect(d.truth!.rows).toHaveLength(4);
  });

  it('answers for a module port, which has no Yosys cell behind it', () => {
    const nl = parseNetlist(oneCell('$and', { A: [2], Y: [4] }, {},
      { clk: { direction: 'input', bits: [2] } }))!;
    const d = inspectCell(nl, 'clk')!;
    expect(d.title).toMatch(/module input/);
    expect(d.ports[0].dir).toBe('input');
    expect(d.truthNote).toMatch(/boundary/);
  });

  it('returns null for an id that is neither a cell nor a port', () => {
    const nl = parseNetlist(oneCell('$and', { A: [2], Y: [4] }))!;
    expect(inspectCell(nl, 'nope')).toBeNull();
  });

  it('flags a cell whose type is another module as a submodule', () => {
    const nl = parseNetlist(JSON.stringify({
      modules: {
        top: { attributes: { top: 1 }, ports: {}, cells: { u0: { type: 'adder', connections: {} } } },
        adder: { ports: { a: { direction: 'input', bits: [2] } }, cells: {} },
      },
    }))!;
    expect(inspectCell(nl, 'u0')!.submodule).toBe('adder');
    expect(moduleNames(nl).sort()).toEqual(['adder', 'top']);
  });
});

describe('cellInspect — submoduleNetlist', () => {
  it('extracts one module, marked top, so the renderer needs no mode flag', () => {
    const nl = parseNetlist(JSON.stringify({
      modules: {
        top: { attributes: { top: 1 }, ports: {}, cells: {} },
        adder: { ports: { a: { direction: 'input', bits: [2] } }, cells: {} },
      },
    }))!;
    const sub = parseNetlist(submoduleNetlist(nl, 'adder'))!;
    expect(Object.keys(sub.modules!)).toEqual(['adder']);
    expect(pickModule(sub)![0]).toBe('adder');
    expect(sub.modules!.adder.attributes!.top).toBe(1);
  });

  it('returns null for a module that is not there', () => {
    const nl = parseNetlist(oneCell('$and', {}))!;
    expect(submoduleNetlist(nl, 'ghost')).toBeNull();
  });
});

describe('cellInspect — inspectNet', () => {
  it('finds the driver and the loads of a net', () => {
    const nl = parseNetlist(JSON.stringify({
      modules: {
        top: {
          attributes: { top: 1 },
          ports: { y: { direction: 'output', bits: [5] } },
          cells: {
            a: { type: '$and', connections: { A: [2], B: [3], Y: [4] } },
            b: { type: '$not', connections: { A: [4], Y: [5] } },
            c: { type: '$or', connections: { A: [4], B: [3], Y: [6] } },
          },
          netnames: { mid: { bits: [4] } },
        },
      },
    }))!;
    const d = inspectNet(nl, '4')!;
    expect(d.name).toBe('mid');
    expect(d.width).toBe(1);
    expect(d.driver).toEqual({ id: 'a', type: '$and', port: 'Y' });
    expect(d.loads.map((l) => l.id).sort()).toEqual(['b', 'c']);
    expect(inspectNet(nl, '5')!.topPort).toEqual({ name: 'y', dir: 'output' });
  });

  it('ignores a hidden net name', () => {
    const nl = parseNetlist(JSON.stringify({
      modules: {
        top: {
          attributes: { top: 1 }, ports: {}, cells: {},
          netnames: { '$auto$x': { bits: [4], hide_name: 1 } },
        },
      },
    }))!;
    expect(inspectNet(nl, '4')!.name).toBeUndefined();
  });
});

describe('cellInspect — source recovery', () => {
  const src = [
    'module top(input a, output y);',      // 1
    '  wire t;',                            // 2
    '  sub u0(.a(a), .y(t));',              // 3
    '  assign y = t;',                      // 4
    'endmodule',                            // 5
    '',                                     // 6
    'module sub(input a, output y);',       // 7
    '  assign y = ~a;',                     // 8
    'endmodule',                            // 9
  ].join('\n');

  it('returns the enclosing module block for a line', () => {
    const m = moduleSourceAt(src, 3)!;
    expect(m.name).toBe('top');
    expect(m.startLine).toBe(1);
    expect(m.endLine).toBe(5);
  });

  it('finds the SECOND module when the line is inside it', () => {
    const m = moduleSourceAt(src, 8)!;
    expect(m.name).toBe('sub');
    expect(m.startLine).toBe(7);
    expect(m.code).toContain('assign y = ~a;');
  });

  it('returns null for a line between modules', () => {
    expect(moduleSourceAt(src, 6)).toBeNull();
  });

  it('still answers for an unterminated trailing module', () => {
    const m = moduleSourceAt('module half(input a);\n  wire b;', 2)!;
    expect(m.name).toBe('half');
    expect(m.endLine).toBe(2);
  });

  it('excerpts a window around a line', () => {
    const e = excerptAt(src, 4, 1)!;
    expect(e.startLine).toBe(3);
    expect(e.lines).toEqual(['  sub u0(.a(a), .y(t));', '  assign y = t;', 'endmodule']);
  });

  it('returns null for an out-of-range line', () => {
    expect(excerptAt(src, 99)).toBeNull();
    expect(moduleSourceAt(src, 0)).toBeNull();
  });
});

describe('cellInspect — descriptions', () => {
  it('names every cell type the schematic can draw', () => {
    for (const t of ['$and', '$mux', '$dff', '$adff', '$add', '$eq', '$reduce_or', '$_AND_']) {
      expect(describeType(t).title).not.toBe(t);
      expect(describeType(t).blurb.length).toBeGreaterThan(10);
    }
  });

  it('describes an unknown user module as an instance', () => {
    expect(describeType('my_alu').title).toBe('my_alu instance');
  });
});

describe('cellInspect — against a real Yosys netlist', () => {
  it('inspects a synthesized gate and its truth table matches the source', async () => {
    const { json } = await synthesizeNode(`
module top(input a, input b, output y);
  assign y = a & b;
endmodule`);
    const nl = parseNetlist(json)!;
    const [, mod] = pickModule(nl)!;
    const andId = Object.keys(mod.cells ?? {})
      .find((id) => mod.cells![id].type === '$and');
    expect(andId).toBeDefined();

    const d = inspectCell(nl, andId!)!;
    expect(d.title).toBe('AND');
    expect(d.index).toBeGreaterThan(0);
    expect(d.ports.find((p) => p.name === 'Y')!.dir).toBe('output');
    // Two free input bits -> four rows, one of which is true.
    expect(d.truth!.rows).toHaveLength(4);
    expect(d.truth!.rows.filter((r) => r.out[0] === '1')).toHaveLength(1);
  });

  it('reports the flip-flop family and refuses a truth table for it', async () => {
    const { json } = await synthesizeNode(`
module top(input clk, input rst, input d, output reg q);
  always @(posedge clk) if (rst) q <= 1'b0; else q <= d;
endmodule`);
    const nl = parseNetlist(json)!;
    const [, mod] = pickModule(nl)!;
    const dffId = Object.keys(mod.cells ?? {})
      .find((id) => /^\$[as]?dff/i.test(mod.cells![id].type ?? ''));
    expect(dffId).toBeDefined();

    const d = inspectCell(nl, dffId!)!;
    expect(d.title).toMatch(/flip-flop/i);
    expect(d.truth).toBeUndefined();
    expect(d.truthNote).toMatch(/stateful/i);
    expect(d.ports.some((p) => p.name === 'CLK' && p.dir === 'input')).toBe(true);
    expect(d.ports.some((p) => p.name === 'Q' && p.dir === 'output')).toBe(true);
  });

  it('carries the source location Yosys attributed to the cell', async () => {
    const { json } = await synthesizeNode(`
module top(input a, input b, output y);
  assign y = a | b;
endmodule`);
    const nl = parseNetlist(json)!;
    const [, mod] = pickModule(nl)!;
    const id = Object.keys(mod.cells ?? {})[0];
    const d = inspectCell(nl, id)!;
    expect(d.src?.file).toBe('design.v');
    expect(d.src?.line).toBe(3);
  });
});
