import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/27 - Binary Dividers ("The Chocolate Sharing Grid").
 * Source: dsd27.json spec. A combinational restoring ARRAY DIVIDER is schoolbook
 * long division frozen into a 2D grid of identical controlled-subtractor cells.
 * Each cell = one full subtractor + one 2-to-1 MUX; the row's final borrow-out is
 * the sign, q = borrow', and the MUX restores the minuend when borrow=1.
 * Central analogy woven through every page: 20 chocolates shared among 4 children,
 * each round asking "can I hand out 4 more right now?" - subtract (q=1) or leave
 * the pile (q=0). All boolean results are computed in code in scenes.tsx.
 */
export const CONTENT = ({
  moduleTitle: 'Binary Dividers - Long Division in Hardware',
  moduleSubtitle: 'Lay the schoolbook long-division worksheet flat into a 2D grid of subtract-and-compare cells: the restoring array divider, where every cell asks "does the divisor fit?" and either keeps the difference or restores the pile.',
  scenes: [
    {
      id: 'S00_Cover',
      label: 'The Chocolate Sharing Grid',
      kind: 'cover',
      subtitle: 'Long division, frozen into silicon: a grid of tiny cells that each trial-subtract the divisor and vote 1 or 0.',
      theoryEN: [
        'This module builds the binary divider, the circuit that splits one number (the dividend) by another (the divisor) and hands you back two answers at once: the quotient (how many times it goes in) and the remainder (what is left over). Unlike an adder, a divider is not a single operation; it is a whole sequence of conditional subtractions, which is exactly the long division you learned in school - just done in binary and unrolled into hardware.',
        'Hold onto one picture for the entire module: you have 20 chocolates to share fairly among 4 children. At every round you ask a single yes-or-no question: "can I hand out 4 more chocolates right now?" If yes, you subtract 4 from the pile and mark a successful round by writing a quotient bit of 1; if no, you leave the pile untouched and write a 0, then move on to a smaller question. The remainder is whatever chocolates are left when you can no longer make a full round.',
        'The hardware does exactly this, but it freezes the whole worksheet into a fixed GRID of identical cells. Each cell is a tiny worker that trial-subtracts the divisor and then looks at one flag, the borrow-out: borrow = 0 means "it fit, keep the difference, write 1", borrow = 1 means "it did not fit, put the pile back, write 0". The decision to keep or restore is what the word "restoring" in restoring array divider means.',
        'Two flows run through the grid. The borrow ripples SIDEWAYS across a row to build one quotient bit, and the leftover partial remainder flows DOWNWARD to the next row as its new pile. By the end you will be able to build the unit cell from gates - a full subtractor plus a 2-to-1 MUX - and stack those cells into a complete array that divides any pair of numbers.',
        'The atom of the whole machine is the controlled subtractor, and the boolean equations you will own by the end are D = x ^ y ^ bin for the difference, bout = x\'.y + x\'.bin + y.bin for the borrow, the MUX Y = S\'.I0 + S.I1 for the restore switch, and q = bout\' for reading off each quotient bit.',
      ],
      theoryHI: [
        'इस module में हम binary divider बनाएँगे, वह circuit जो एक संख्या (dividend, यानी भाज्य) को दूसरी (divisor, यानी भाजक) से बाँटती है और एक साथ दो जवाब देती है: quotient (भागफल, कितनी बार पूरा गया) और remainder (शेष, क्या बचा)। adder के उलट, divider एक अकेली operation नहीं है; यह conditional subtractions की एक पूरी श्रृंखला है, जो ठीक वही long division है जो आपने स्कूल में सीखी - बस binary में और hardware में unroll की हुई।',
        'पूरे module के लिए एक तस्वीर पकड़े रखिए: आपके पास 20 chocolates हैं जिन्हें 4 बच्चों में बराबर बाँटना है। हर round में आप एक अकेला हाँ-या-ना सवाल पूछते हैं: "क्या मैं अभी 4 और chocolates बाँट सकता हूँ?" अगर हाँ, तो आप pile में से 4 घटा देते हैं और एक सफल round को quotient bit 1 लिखकर निशान लगाते हैं; अगर ना, तो आप pile को अछूता छोड़ते हैं और 0 लिखते हैं, फिर एक छोटे सवाल पर बढ़ते हैं। remainder वह chocolates हैं जो तब बचते हैं जब आप एक और पूरा round नहीं बना सकते।',
        'Hardware ठीक यही करता है, पर वह पूरे worksheet को एक तय GRID में जमा देता है जो एक जैसे cells से बना है। हर cell एक नन्हा worker है जो divisor को trial-subtract करता है और फिर एक flag देखता है, borrow-out: borrow = 0 मतलब "fit हो गया, difference रखो, 1 लिखो", borrow = 1 मतलब "fit नहीं हुआ, pile वापस रखो, 0 लिखो"। रखने या restore करने का यही फ़ैसला "restoring" शब्द का मतलब है restoring array divider में।',
        'Grid में दो flows चलती हैं। borrow एक row में SIDEWAYS (बग़ल में) ripple होकर एक quotient bit बनाता है, और बचा partial remainder नीचे (DOWNWARD) अगली row में जाता है उसके नए pile की तरह। अंत तक आप unit cell को gates से बना पाएँगे - एक full subtractor जमा एक 2-to-1 MUX - और इन cells को एक पूरे array में जमा पाएँगे जो किसी भी जोड़ी संख्याओं को बाँटता है।',
        'पूरी machine का atom controlled subtractor है, और जो boolean equations आप अंत तक अपनी बना लेंगे वे हैं D = x ^ y ^ bin difference के लिए, bout = x\'.y + x\'.bin + y.bin borrow के लिए, MUX Y = S\'.I0 + S.I1 restore switch के लिए, और q = bout\' हर quotient bit पढ़ने के लिए।',
      ],
      transcriptEN: 'Welcome to the binary divider. A divider splits a dividend by a divisor and gives you two answers, a quotient and a remainder. It is not one subtraction; it is a sequence of conditional subtractions, exactly the long division you know, unrolled into hardware.',
      transcriptHI: 'Binary divider में आपका स्वागत है। एक divider एक dividend को एक divisor से बाँटता है और दो जवाब देता है, एक quotient और एक remainder। यह एक subtraction नहीं है; यह conditional subtractions की एक श्रृंखला है, ठीक वही long division जो आप जानते हैं, hardware में unroll की हुई।',
      visualNote: 'Hero: 20 chocolates and 4 children; rounds tick off, each writing a 1 (deal 4) or 0 (skip), the leftover pile becoming the remainder.',
    },
    {
      id: 'S01_Video',
      label: 'Binary Dividers - Long Division in Hardware',
      kind: 'video',
      subtitle: 'A short film: how a grid of subtract-and-compare cells does long division with no clock.',
      theoryEN: [
        'Here is the whole idea in one breath before you watch. Multiplication is repeated addition, and division is its mirror: repeated, conditional subtraction. To divide, you keep subtracting the divisor from what is left and counting how many times it fit - that count is the quotient, and what never fit is the remainder.',
        'A combinational divider has NO clock and NO memory. It is a pure cloud of gates: you drive the dividend and divisor onto the inputs, and after the signals settle the quotient and remainder simply appear at the outputs. To make that possible we take the time-based long-division algorithm and unroll it across space, one row of cells per step.',
        'Every cell in that grid is a controlled subtractor: it trial-subtracts and then, using its own borrow flag, decides whether to commit the subtraction or undo it. Watch for the two motions in the film: borrow rippling sideways to vote each quotient bit, and the partial remainder dropping down to the next row.',
        'Keep one running example in your head: 1011 divided by 11, which is 11 divided by 3 in decimal. The grid will produce a quotient of 11 (which is 3) and a remainder of 10 (which is 2), and the identity 1011 = 11 . 11 + 10 will hold exactly - that identity is the law every divider must obey.',
        'The single rule to remember from the video is the restoring decision: if a row\'s trial subtraction went negative (borrow-out = 1) the divisor did not fit, so the quotient bit is 0 and we restore the original pile; if it stayed non-negative (borrow-out = 0) the divisor fit, so the quotient bit is 1 and we keep the difference.',
      ],
      theoryHI: [
        'देखने से पहले पूरा विचार एक साँस में। multiplication बार-बार जोड़ना है, और division उसका आईना है: बार-बार, conditional घटाना। बाँटने के लिए, आप जो बचा है उसमें से divisor घटाते रहते हैं और गिनते हैं कि वह कितनी बार fit हुआ - वह गिनती quotient है, और जो कभी fit नहीं हुआ वह remainder है।',
        'एक combinational divider में कोई clock नहीं और कोई memory नहीं। यह gates का एक शुद्ध बादल है: आप dividend और divisor को inputs पर देते हैं, और signals के थमने के बाद quotient और remainder बस outputs पर आ जाते हैं। इसे संभव बनाने के लिए हम समय-आधारित long-division algorithm को space में unroll कर देते हैं, हर कदम के लिए cells की एक row।',
        'उस grid का हर cell एक controlled subtractor है: यह trial-subtract करता है और फिर, अपने ही borrow flag से, तय करता है कि subtraction commit करे या undo। film में दो हरकतें देखिए: borrow बग़ल में ripple होकर हर quotient bit को vote करता है, और partial remainder अगली row में नीचे गिरता है।',
        'एक चलता उदाहरण मन में रखिए: 1011 बँटा 11, जो decimal में 11 बँटा 3 है। grid quotient 11 (जो 3 है) और remainder 10 (जो 2 है) बनाएगा, और identity 1011 = 11 . 11 + 10 बिलकुल सही बैठेगी - वही identity वह क़ानून है जिसे हर divider को मानना ही पड़ता है।',
        'video से याद रखने वाला अकेला नियम restoring फ़ैसला है: अगर किसी row का trial subtraction negative गया (borrow-out = 1) तो divisor fit नहीं हुआ, इसलिए quotient bit 0 है और हम मूल pile restore करते हैं; अगर वह non-negative रहा (borrow-out = 0) तो divisor fit हुआ, इसलिए quotient bit 1 है और हम difference रखते हैं।',
      ],
      transcriptEN: 'Here is the whole idea in one breath. Multiplication is repeated addition; division is repeated, conditional subtraction. A combinational divider has no clock and no memory - drive the dividend and divisor in, and the quotient and remainder settle out. We do it by taking the long-division algorithm and unrolling it into a grid of cells, one row per step. Every cell is a controlled subtractor: it trial-subtracts, then uses its borrow flag to decide whether to keep the difference or restore the original value. Watch the two motions - borrow rippling sideways to make each quotient bit, and the partial remainder dropping down to the next row. Keep one example in mind: 1011 divided by 11, that is 11 over 3 in decimal, giving quotient 11 which is 3, and remainder 10 which is 2, and the identity 1011 equals 11 times 11 plus 10 holds. The one rule: borrow-out of 1 means the divisor did not fit, so quotient bit 0 and restore; borrow-out of 0 means it fit, so quotient bit 1 and keep the difference.',
      transcriptHI: 'पूरा विचार एक साँस में। multiplication बार-बार जोड़ना है; division बार-बार, conditional घटाना है। एक combinational divider में कोई clock और memory नहीं - dividend और divisor अंदर दीजिए, quotient और remainder थम कर बाहर आ जाते हैं। हम यह long-division algorithm को cells के एक grid में unroll करके करते हैं, हर कदम के लिए एक row। हर cell एक controlled subtractor है: यह trial-subtract करता है, फिर अपने borrow flag से तय करता है कि difference रखे या मूल मान restore करे। दो हरकतें देखिए - borrow बग़ल में ripple होकर हर quotient bit बनाता है, और partial remainder अगली row में नीचे गिरता है। एक उदाहरण याद रखिए: 1011 बँटा 11, यानी decimal में 11 बँटा 3, quotient 11 जो 3 है, और remainder 10 जो 2 है, और identity 1011 बराबर 11 गुणा 11 जमा 10 बैठती है। एक नियम: borrow-out 1 मतलब divisor fit नहीं हुआ, तो quotient bit 0 और restore; borrow-out 0 मतलब fit हुआ, तो quotient bit 1 और difference रखो।',
      visualNote: 'Animated explainer: a long-division worksheet morphs into a 2D grid of subtractor+MUX cells; borrow ripples orange sideways, remainder flows blue downward, each row pops a quotient bit.',
    },
    {
      id: 'S02_Identity',
      label: 'What a Divider Computes',
      kind: 'theory',
      subtitle: 'The one law: Dividend = Divisor . Quotient + Remainder, with 0 <= Remainder < Divisor.',
      theoryEN: [
        'Before we build anything, fix in your mind exactly what a divider must compute. It takes two numbers in - the dividend (the pile being split) and the divisor (the number you divide by) - and it produces two numbers out: the quotient (how many whole times the divisor goes in) and the remainder (the leftover that could not make one more full share). One circuit splits two numbers into two new numbers.',
        'There is a single identity that every divider must always satisfy, no matter how it is built: Dividend = Divisor . Quotient + Remainder, where the dot means multiply. In the chocolate picture this reads perfectly: total chocolates = (children per round) times (number of successful rounds) + (chocolates left over). If your answer does not satisfy this equation, it is simply wrong.',
        'Take the running example. Dividing 1011 (which is 11 in decimal) by 11 (which is 3) gives a quotient of 11 (which is 3) and a remainder of 10 (which is 2). Check the identity in binary: 11 . 11 + 10 = 1001 + 10 = 1011. It holds, so the answer is valid.',
        'A second rule pins down the remainder uniquely: 0 <= Remainder < Divisor. The remainder can never be as large as the divisor, because if it were, you could have done one more subtraction and handed out one more round. In chocolate terms, you stop precisely when the pile is too small to give every child one more.',
        'Finally, remember that a combinational divider has no clock and no state. It is a pure cloud of gates: given the dividend and divisor on its inputs, the quotient and remainder appear at its outputs after the propagation delay settles. That is why we can lay the entire algorithm out flat as a grid instead of running it step by step in time.',
      ],
      theoryHI: [
        'कुछ बनाने से पहले, अपने मन में ठीक-ठीक तय कर लीजिए कि एक divider को क्या गिनना है। यह दो संख्याएँ अंदर लेता है - dividend (बँटने वाला pile) और divisor (जिससे आप बाँटते हैं) - और दो संख्याएँ बाहर बनाता है: quotient (divisor कितनी पूरी बार जाता है) और remainder (बचा हुआ जो एक और पूरा हिस्सा नहीं बना सका)। एक circuit दो संख्याओं को दो नई संख्याओं में बाँट देती है।',
        'एक अकेली identity है जिसे हर divider को हमेशा संतुष्ट करना ही पड़ता है, चाहे वह कैसे भी बना हो: Dividend = Divisor . Quotient + Remainder, जहाँ dot का मतलब गुणा है। chocolate तस्वीर में यह बिलकुल सही पढ़ी जाती है: कुल chocolates = (हर round में बच्चे) गुणा (सफल rounds की संख्या) + (बचे chocolates)। अगर आपका जवाब इस समीकरण को संतुष्ट नहीं करता, तो वह बस ग़लत है।',
        'चलता उदाहरण लीजिए। 1011 (जो decimal में 11 है) को 11 (जो 3 है) से बाँटने पर quotient 11 (जो 3 है) और remainder 10 (जो 2 है) मिलता है। identity binary में जाँचिए: 11 . 11 + 10 = 1001 + 10 = 1011. यह बैठती है, तो जवाब वैध है।',
        'एक दूसरा नियम remainder को विशिष्ट रूप से तय करता है: 0 <= Remainder < Divisor। remainder कभी divisor जितना बड़ा नहीं हो सकता, क्योंकि अगर होता, तो आप एक और subtraction कर सकते थे और एक और round बाँट सकते थे। chocolate भाषा में, आप ठीक तब रुकते हैं जब pile इतना छोटा हो कि हर बच्चे को एक और न दे सकें।',
        'आख़िर में, याद रखिए कि एक combinational divider में कोई clock और कोई state नहीं है। यह gates का एक शुद्ध बादल है: inputs पर dividend और divisor देने पर, propagation delay के थमने के बाद quotient और remainder outputs पर आ जाते हैं। इसीलिए हम पूरे algorithm को समय में कदम-दर-कदम चलाने के बजाय एक grid की तरह सपाट बिछा सकते हैं।',
      ],
      transcriptEN: 'Fix what a divider computes. Two inputs, dividend and divisor; two outputs, quotient and remainder. Every divider must satisfy one identity: Dividend equals Divisor times Quotient plus Remainder. In chocolate terms, total equals children-per-round times successful-rounds plus leftover. Example: 1011 over 11 gives quotient 11 and remainder 10, and 11 times 11 plus 10 equals 1011, so it checks. A second rule pins the remainder: zero is less than or equal to the remainder which is strictly less than the divisor - otherwise one more subtraction was possible. And a combinational divider has no clock; drive the inputs, the answers settle out, which is why we can lay the whole algorithm out as a flat grid.',
      transcriptHI: 'तय कीजिए कि divider क्या गिनता है। दो inputs, dividend और divisor; दो outputs, quotient और remainder। हर divider को एक identity माननी पड़ती है: Dividend बराबर Divisor गुणा Quotient जमा Remainder। chocolate भाषा में, कुल बराबर हर-round-बच्चे गुणा सफल-rounds जमा बचा हुआ। उदाहरण: 1011 बँटा 11 quotient 11 और remainder 10 देता है, और 11 गुणा 11 जमा 10 बराबर 1011, तो जाँच पास। एक दूसरा नियम remainder तय करता है: शून्य remainder से छोटा या बराबर जो divisor से कड़ाई से छोटा है - वरना एक और subtraction मुमकिन था। और एक combinational divider में clock नहीं; inputs दीजिए, जवाब थम कर आ जाते हैं, इसीलिए हम पूरे algorithm को सपाट grid की तरह बिछा सकते हैं।',
      visualNote: 'Block symbol: a box with two input buses (Dividend, Divisor) on the left and two output buses (Quotient, Remainder) on the right; the identity Dividend = Divisor*Quotient + Remainder annotated across the wires.',
    },
    {
      id: 'S03_Schoolbook',
      label: 'The Algorithm We Are Freezing',
      kind: 'theory',
      subtitle: 'Binary long division: compare, subtract if it fits, write a bit, bring down the next bit.',
      theoryEN: [
        'The divider is just schoolbook long division frozen into hardware, so let us walk the algorithm by hand first. Binary long division uses the very same four steps as the decimal version you already know: compare the current partial remainder against the divisor, subtract if the divisor fits, write the resulting quotient bit, then bring down the next bit of the dividend and repeat.',
        'Work the running example 1011 / 11, which is 11 / 3 in decimal. Start at the most significant end. The leftmost piece "10" is smaller than the divisor "11", so the divisor does not fit and this quotient bit is 0 - this is a skipped chocolate round, the pile too small to deal a full share.',
        'Now take "101". The divisor "11" fits, so subtract: 101 - 11 leaves "10", and this quotient bit is 1 - a successful round, four chocolates handed out. Bring down the final dividend bit to make "101" again, subtract "11" to leave "10", and this quotient bit is also 1.',
        'Reading the quotient bits in order gives Quotient = 11 (binary for 3), and the last leftover is Remainder = 10 (binary for 2). Check the identity: 1011 = 11 . 11 + 10. It holds exactly, so 11 divided by 3 really is 3 remainder 2.',
        'The key observation for going to hardware is this: every single row of that worksheet is the same little operation - one comparison followed by one conditional subtraction. That repeated unit is exactly what we will replicate in silicon, copy-pasted into a grid, so the entire long-division worksheet becomes a fixed lattice of identical cells.',
      ],
      theoryHI: [
        'divider बस स्कूली long division है जो hardware में जमा दी गई है, तो चलिए पहले algorithm हाथ से चलाएँ। binary long division ठीक वही चार कदम वापरती है जो decimal version में हैं जिन्हें आप पहले से जानते हैं: मौजूदा partial remainder को divisor के सामने compare कीजिए, अगर divisor fit हो तो घटाइए, बनने वाला quotient bit लिखिए, फिर dividend का अगला bit नीचे लाइए और दोहराइए।',
        'चलता उदाहरण 1011 / 11 कीजिए, जो decimal में 11 / 3 है। सबसे बड़े सिरे से शुरू कीजिए। सबसे बाएँ टुकड़ा "10" divisor "11" से छोटा है, तो divisor fit नहीं होता और यह quotient bit 0 है - यह एक छोड़ा हुआ chocolate round है, pile इतना छोटा कि पूरा हिस्सा न बाँटा जाए।',
        'अब "101" लीजिए। divisor "11" fit होता है, तो घटाइए: 101 - 11 बचाता है "10", और यह quotient bit 1 है - एक सफल round, चार chocolates बँटे। dividend का आख़िरी bit नीचे लाकर फिर "101" बनाइए, "11" घटाकर "10" बचाइए, और यह quotient bit भी 1 है।',
        'quotient bits को क्रम में पढ़ने पर Quotient = 11 (3 का binary) मिलता है, और आख़िरी बचा हुआ Remainder = 10 (2 का binary) है। identity जाँचिए: 1011 = 11 . 11 + 10. यह बिलकुल बैठती है, तो 11 बँटा 3 सचमुच 3 शेष 2 है।',
        'hardware में जाने के लिए अहम बात यह है: उस worksheet की हर एक row वही छोटी operation है - एक comparison के बाद एक conditional subtraction। वही दोहराई जाने वाली unit ठीक वह है जिसे हम silicon में दोहराएँगे, एक grid में copy-paste करके, तो पूरा long-division worksheet एक जैसे cells की एक तय जाली बन जाता है।',
      ],
      transcriptEN: 'The divider is long division frozen into hardware, so walk it by hand. Binary long division uses the same four steps as decimal: compare, subtract if it fits, write the quotient bit, bring down the next bit. Take 1011 over 11, that is 11 over 3. The leftmost 10 is smaller than 11, so quotient bit 0, a skipped round. Take 101; 11 fits, subtract to leave 10, quotient bit 1. Bring down the last bit to make 101 again, subtract 11 to leave 10, quotient bit 1. So quotient is 11, which is 3, and remainder is 10, which is 2, and 1011 equals 11 times 11 plus 10. The key point: every row is the same operation, one compare and one conditional subtract - that repeated unit is what we replicate in silicon.',
      transcriptHI: 'divider hardware में जमी long division है, तो इसे हाथ से चलाइए। binary long division decimal जैसे चार कदम वापरती है: compare, fit हो तो subtract, quotient bit लिखो, अगला bit नीचे लाओ। 1011 बँटा 11 लीजिए, यानी 11 बँटा 3। सबसे बाएँ 10, 11 से छोटा है, तो quotient bit 0, एक छोड़ा round। 101 लीजिए; 11 fit होता है, घटाकर 10 बचाइए, quotient bit 1। आख़िरी bit नीचे लाकर फिर 101 बनाइए, 11 घटाकर 10 बचाइए, quotient bit 1। तो quotient 11 है, जो 3 है, और remainder 10 है, जो 2 है, और 1011 बराबर 11 गुणा 11 जमा 10। अहम बात: हर row वही operation है, एक compare और एक conditional subtract - वही दोहराई unit silicon में दोहराते हैं।',
      visualNote: 'Long-division worksheet for 1011 / 11 with the bracket, partial remainders 10 -> 101 -> 101, subtractions of 11, quotient 11 on top and remainder 10 at the bottom; a step button advances each row.',
    },
    {
      id: 'S04_UnitCell',
      label: 'The Unit Cell = Controlled Subtractor',
      kind: 'theory',
      subtitle: 'One full subtractor wired to one 2-to-1 MUX, with the borrow-out steering the MUX.',
      theoryEN: [
        'Here is the atom of the entire array: the controlled subtractor, which is just one full subtractor wired to one 2-to-1 multiplexer. Build this one little cell well and the whole divider is nothing but a grid of copies of it. Each cell is the hardware version of one chocolate round - it tries the subtraction, then decides whether to commit or to undo it.',
        'The full subtractor part takes three bits: the minuend bit x (a bit of the current pile), the subtrahend bit y (a bit of the divisor), and a borrow-in bin from the cell to its right. It produces two things: a Difference bit D and a Borrow-out bout. The difference is the subtracted value; the borrow-out is the honest flag saying whether the subtraction needed to reach into a higher column.',
        'The 2-to-1 MUX part has two data inputs. Input 0 is the Difference D - the subtracted, committed result. Input 1 is the original minuend x - the un-subtracted, untouched value. The MUX will pass exactly one of these to the cell output depending on its select line.',
        'Now the key rule that makes the cell "controlled": the Borrow-out drives the MUX select line. The cell decides for itself, with no extra control logic, whether to keep its work. If borrow-out = 0 the subtraction succeeded with no underflow, so the MUX passes the Difference - we keep the subtracted value. If borrow-out = 1 the subtraction went negative (underflow), so the MUX passes the original minuend x instead - this is RESTORING, throwing the bad result away and putting the pile back.',
        'In one equation the cell output is CellOut = bout\'.D + bout.x, which is a 2-to-1 MUX with select = bout. That single line of boolean algebra is the heart of restoring division: borrow says "did it fit?", and the MUX acts on the answer - keep the difference when it fit, restore the minuend when it did not.',
      ],
      theoryHI: [
        'यह पूरे array का atom है: controlled subtractor, जो बस एक full subtractor है जो एक 2-to-1 multiplexer से जुड़ा है। इस एक छोटे cell को अच्छे से बना लीजिए और पूरा divider इसकी copies के एक grid के सिवा कुछ नहीं। हर cell एक chocolate round का hardware रूप है - यह subtraction आज़माता है, फिर तय करता है कि commit करे या undo।',
        'full subtractor हिस्सा तीन bits लेता है: minuend bit x (मौजूदा pile का एक bit), subtrahend bit y (divisor का एक bit), और दाईं ओर वाले cell से एक borrow-in bin। यह दो चीज़ें बनाता है: एक Difference bit D और एक Borrow-out bout। difference घटाया मान है; borrow-out वह ईमानदार flag है जो बताता है कि subtraction को ऊपरी column तक पहुँचना पड़ा या नहीं।',
        '2-to-1 MUX हिस्से के दो data inputs हैं। Input 0 Difference D है - घटाया, committed नतीजा। Input 1 मूल minuend x है - बिना घटाया, अछूता मान। MUX इनमें से ठीक एक को cell output पर भेजेगा, उसकी select line के हिसाब से।',
        'अब वह अहम नियम जो cell को "controlled" बनाता है: Borrow-out MUX की select line चलाता है। cell ख़ुद, किसी अतिरिक्त control logic के बिना, तय करता है कि अपना काम रखे या नहीं। अगर borrow-out = 0 तो subtraction बिना underflow सफल रहा, तो MUX Difference भेजता है - हम घटाया मान रखते हैं। अगर borrow-out = 1 तो subtraction negative गया (underflow), तो MUX बजाय मूल minuend x भेजता है - यही RESTORING है, ख़राब नतीजा फेंककर pile वापस रखना।',
        'एक समीकरण में cell output है CellOut = bout\'.D + bout.x, जो select = bout वाला एक 2-to-1 MUX है। boolean algebra की वह अकेली line restoring division का दिल है: borrow कहता है "fit हुआ?", और MUX जवाब पर काम करता है - fit होने पर difference रखो, न होने पर minuend restore करो।',
      ],
      transcriptEN: 'The atom of the array is the controlled subtractor: one full subtractor wired to one 2-to-1 MUX. The full subtractor takes minuend bit x, subtrahend bit y, and borrow-in, and makes a difference D and a borrow-out. The MUX has two data inputs: input 0 is the difference D, input 1 is the original minuend x. The key rule: the borrow-out drives the MUX select. If borrow-out is 0 the subtraction fit, so the MUX passes the difference - keep it. If borrow-out is 1 it underflowed, so the MUX passes the original minuend instead - that is restoring, undoing the bad subtraction. In one line, CellOut equals borrow-prime times D plus borrow times x, a 2-to-1 MUX with select equal to the borrow.',
      transcriptHI: 'array का atom controlled subtractor है: एक full subtractor एक 2-to-1 MUX से जुड़ा। full subtractor minuend bit x, subtrahend bit y, और borrow-in लेता है, और एक difference D तथा एक borrow-out बनाता है। MUX के दो data inputs: input 0 difference D है, input 1 मूल minuend x है। अहम नियम: borrow-out MUX की select चलाता है। अगर borrow-out 0 तो subtraction fit हुआ, MUX difference भेजता है - रखो। अगर borrow-out 1 तो underflow हुआ, MUX बजाय मूल minuend भेजता है - यही restoring है, ख़राब subtraction undo करना। एक line में, CellOut बराबर borrow-prime गुणा D जमा borrow गुणा x, select = borrow वाला 2-to-1 MUX।',
      visualNote: 'Schematic: a Full Subtractor box (x, y, borrow-in -> Difference, Borrow-out) feeding a 2-to-1 MUX with I0 = Difference, I1 = x, select = Borrow-out. Note: path 0 keeps the difference if borrow=0, path 1 restores x if borrow=1.',
    },
    {
      id: 'S05_FullSub',
      label: 'Building the Full Subtractor',
      kind: 'theory',
      subtitle: 'D = x ^ y ^ bin and bout = x\'.y + x\'.bin + y.bin, from gates.',
      theoryEN: [
        'Now zoom into the subtract half of the cell and build it from real gates, because the gate-level build is what you will wire on the workbench. A full subtractor has three inputs - minuend bit x, subtrahend bit y, borrow-in bin - and two outputs, the Difference D and the Borrow-out bout.',
        'The Difference is simply the parity of the three inputs: D = x ^ y ^ bin, a three-input XOR. The output is 1 whenever an odd number of the three inputs are 1. In hardware this is just two 2-input XOR gates cascaded, (x ^ y) ^ bin, the same shape as the sum bit of a full adder.',
        'The Borrow-out answers the question "did we have to borrow from the next column?", which happens whenever the subtrahend plus the borrow-in together exceed the minuend. Written as a sum of products it is bout = x\'.y + x\'.bin + y.bin, where the apostrophe means NOT. Notice the inverter sits on the minuend x - that is the one structural difference from a full adder\'s carry, and it is there because you borrow precisely when the minuend x is too small (a 0) against a set subtrahend or borrow.',
        'A clean way to build it mirrors the half-adder/full-adder construction: use two half-subtractors plus one OR gate. The first half-subtractor on (x, y) gives a partial difference and a partial borrow x\'.y; the second on that partial and bin finishes the difference and gives a second partial borrow; an OR of the two partial borrows produces bout. That is two XOR, two AND, two NOT and one OR - seven gates.',
        'The payoff is reuse: this exact full-subtractor cell is the same one used in array subtractors. The divider simply bolts the restoring 2-to-1 MUX on top of it, so once you can build a full subtractor you are most of the way to a full divider cell.',
      ],
      theoryHI: [
        'अब cell के subtract आधे में zoom कीजिए और इसे असली gates से बनाइए, क्योंकि gate-level रूप ही है जिसे आप workbench पर wire करेंगे। एक full subtractor के तीन inputs हैं - minuend bit x, subtrahend bit y, borrow-in bin - और दो outputs, Difference D और Borrow-out bout।',
        'Difference बस तीनों inputs की parity है: D = x ^ y ^ bin, एक तीन-input XOR। output 1 तब है जब तीनों inputs में से विषम संख्या में 1 हों। hardware में यह बस दो 2-input XOR gates cascade हैं, (x ^ y) ^ bin, वही आकार जो एक full adder के sum bit का है।',
        'Borrow-out इस सवाल का जवाब देता है "क्या हमें अगले column से borrow लेना पड़ा?", जो तब होता है जब subtrahend जमा borrow-in मिलकर minuend से ज़्यादा हो जाएँ। sum of products में यह bout = x\'.y + x\'.bin + y.bin है, जहाँ apostrophe का मतलब NOT है। ग़ौर कीजिए inverter minuend x पर बैठता है - यही एक full adder के carry से अकेला structural फ़र्क़ है, और वह इसलिए है कि आप ठीक तब borrow लेते हैं जब minuend x बहुत छोटा (एक 0) हो एक set subtrahend या borrow के सामने।',
        'इसे बनाने का एक साफ़ तरीक़ा half-adder/full-adder निर्माण का आईना है: दो half-subtractors जमा एक OR gate वापरिए। पहला half-subtractor (x, y) पर एक partial difference और एक partial borrow x\'.y देता है; दूसरा उस partial और bin पर difference पूरा करता है और एक दूसरा partial borrow देता है; दो partial borrows का एक OR bout बनाता है। यह दो XOR, दो AND, दो NOT और एक OR है - सात gates।',
        'फ़ायदा है दोबारा इस्तेमाल: यही full-subtractor cell वही है जो array subtractors में वापरी जाती है। divider बस उसके ऊपर restoring 2-to-1 MUX जोड़ देता है, तो जैसे ही आप full subtractor बना पाते हैं, आप एक पूरे divider cell के काफ़ी क़रीब हैं।',
      ],
      transcriptEN: 'Build the subtract half from gates. A full subtractor has three inputs - x, y, borrow-in - and two outputs, difference and borrow-out. The difference is the parity of the three inputs, D equals x XOR y XOR borrow-in, two cascaded XOR gates. The borrow-out asks did we borrow from the next column: bout equals x-prime AND y, plus x-prime AND borrow-in, plus y AND borrow-in. The inverter sits on the minuend x, unlike a full adder, because you borrow when the minuend is too small. You can build it from two half-subtractors plus an OR gate - two XOR, two AND, two NOT, one OR, seven gates. And this is the same full subtractor used in array subtractors; the divider just adds the restoring MUX on top.',
      transcriptHI: 'subtract आधा gates से बनाइए। full subtractor के तीन inputs - x, y, borrow-in - और दो outputs, difference और borrow-out। difference तीनों inputs की parity है, D बराबर x XOR y XOR borrow-in, दो cascade XOR gates। borrow-out पूछता है क्या अगले column से borrow लिया: bout बराबर x-prime AND y, जमा x-prime AND borrow-in, जमा y AND borrow-in। inverter minuend x पर बैठता है, full adder के उलट, क्योंकि minuend छोटा होने पर borrow लेते हैं। इसे दो half-subtractors जमा एक OR gate से बनाइए - दो XOR, दो AND, दो NOT, एक OR, सात gates। और यही full subtractor array subtractors में वापरी जाती है; divider बस ऊपर restoring MUX जोड़ता है।',
      visualNote: 'Gate schematic of a full subtractor: two cascaded XOR for D; an inverter on x, three ANDs (x\'.y, x\'.bin, y.bin) feeding an OR for bout. A live truth table verifies all 8 rows.',
    },
    {
      id: 'S06_Mux',
      label: 'The 2-to-1 MUX: The Restore Switch',
      kind: 'theory',
      subtitle: 'Y = S\'.I0 + S.I1, the commit-or-restore switch; N-to-1 needs N-1 of these.',
      theoryEN: [
        'The other half of the cell is the 2-to-1 multiplexer, and in a divider it is literally the "commit or restore" switch. A 2-to-1 MUX is a 1-bit data selector: it has two data inputs I0 and I1 and a single select line S, and it routes exactly one of the two inputs to its output. Think of it as a railway track switch that sends one of two trains down a single line.',
        'Its boolean form is Y = S\'.I0 + S.I1. Read it directly: when S = 0 the S\' term is 1 and you get I0; when S = 1 the S term is 1 and you get I1. Two cases, two inputs, one clean equation.',
        'In our divider cell the wiring is fixed and meaningful: the select S is the Borrow-out, I0 is the Difference D, and I1 is the original minuend x. So when the row fit (S = 0) the MUX commits the difference, and when the row overflowed (S = 1) the MUX restores the minuend. The MUX is the physical embodiment of the restoring decision.',
        'The gate cost of one 2-to-1 MUX is tiny: one inverter to make S\', two AND gates for the two product terms, and one OR gate to combine them - four gates in total. That cheapness is exactly why we can afford one MUX in every cell of a large array.',
        'Wider selectors are built by stacking these. An N-to-1 MUX needs (N - 1) two-to-1 MUXes arranged as a tree; for example an 8-to-1 MUX is built from seven 2-to-1 MUXes laid out 4 + 2 + 1. The same Shannon-expansion idea, F = x\'.F0 + x.F1, shows a 2-to-1 MUX can implement any single-variable split of a function, which is why multiplexers are so widely reused in logic design.',
      ],
      theoryHI: [
        'cell का दूसरा आधा 2-to-1 multiplexer है, और एक divider में यह सचमुच "commit या restore" switch है। एक 2-to-1 MUX एक 1-bit data selector है: इसके दो data inputs I0 और I1 हैं और एक अकेली select line S, और यह दोनों में से ठीक एक input को अपने output तक भेजता है। इसे एक railway track switch समझिए जो दो trains में से एक को एक अकेली line पर भेजता है।',
        'इसका boolean रूप है Y = S\'.I0 + S.I1। इसे सीधे पढ़िए: जब S = 0 तो S\' term 1 है और आपको I0 मिलता है; जब S = 1 तो S term 1 है और आपको I1 मिलता है। दो हालात, दो inputs, एक साफ़ समीकरण।',
        'हमारे divider cell में wiring तय और सार्थक है: select S Borrow-out है, I0 Difference D है, और I1 मूल minuend x है। तो जब row fit हुई (S = 0) MUX difference commit करता है, और जब row overflow हुई (S = 1) MUX minuend restore करता है। MUX restoring फ़ैसले का भौतिक रूप है।',
        'एक 2-to-1 MUX की gate क़ीमत नन्ही है: S\' बनाने को एक inverter, दो product terms के लिए दो AND gates, और इन्हें जोड़ने को एक OR gate - कुल चार gates। वही सस्तापन ठीक वह वजह है कि हम एक बड़े array के हर cell में एक MUX रख सकते हैं।',
        'चौड़े selectors इन्हें जमाकर बनते हैं। एक N-to-1 MUX को (N - 1) two-to-1 MUXes चाहिए जो एक tree की तरह जमे हों; उदाहरण के लिए एक 8-to-1 MUX सात 2-to-1 MUXes से बनता है जो 4 + 2 + 1 बिछे हों। वही Shannon-expansion विचार, F = x\'.F0 + x.F1, दिखाता है कि एक 2-to-1 MUX किसी function का कोई भी single-variable split लागू कर सकता है, इसीलिए multiplexers logic design में इतने वापरे जाते हैं।',
      ],
      transcriptEN: 'The other half of the cell is the 2-to-1 MUX, the commit-or-restore switch. It has two data inputs I0 and I1 and one select S, and routes one input to the output. Boolean form: Y equals S-prime times I0 plus S times I1. When S is 0 you get I0; when S is 1 you get I1. In the divider, S is the borrow-out, I0 is the difference, I1 is the original minuend. Gate cost is four: one inverter, two ANDs, one OR. To go wider, an N-to-1 MUX needs N minus 1 two-to-1 MUXes; an 8-to-1 MUX is seven of them in a 4-2-1 tree. And by Shannon expansion, F equals x-prime F0 plus x F1, a 2-to-1 MUX can implement any single-variable split, which is why MUXes are everywhere.',
      transcriptHI: 'cell का दूसरा आधा 2-to-1 MUX है, commit-या-restore switch। इसके दो data inputs I0 और I1 और एक select S हैं, और यह एक input को output पर भेजता है। boolean रूप: Y बराबर S-prime गुणा I0 जमा S गुणा I1। जब S 0 तो I0; जब S 1 तो I1। divider में, S borrow-out है, I0 difference है, I1 मूल minuend है। gate क़ीमत चार: एक inverter, दो AND, एक OR। चौड़ा जाने को, N-to-1 MUX को N घटा 1 two-to-1 MUXes चाहिए; 8-to-1 MUX सात, 4-2-1 tree में। और Shannon expansion से, F बराबर x-prime F0 जमा x F1, एक 2-to-1 MUX कोई single-variable split लागू कर सकता है, इसीलिए MUX हर जगह हैं।',
      visualNote: 'Trapezoidal MUX symbol with I0, I1 on the left, S below, Y on the right; beside it a tree of seven 2-to-1 MUXes feeding one output, showing the 8-to-1 build.',
    },
    {
      id: 'S07_Array',
      label: 'The Array: A Cascading Matrix',
      kind: 'theory',
      subtitle: 'Borrow ripples sideways for one quotient bit; the partial remainder flows down to the next row.',
      theoryEN: [
        'Now stack the controlled-subtractor cells into a 2D grid - rows and columns of identical cells - and you have the schoolbook worksheet made physical. This lattice is the restoring array divider, and the same hardware works for any numbers because the structure never changes; only the bits flowing through it change.',
        'Read it one row at a time. One ROW of cells performs one trial subtraction of the divisor across all the bit positions at once, and that single row generates exactly ONE quotient bit. A row is one chocolate round: it asks "does the divisor fit into this pile?" all the way across, in parallel.',
        'Within a row, the borrow ripples SIDEWAYS from the least-significant cell to the most-significant cell, exactly like the carry in a ripple-carry adder. The borrow coming out of the most-significant cell is the row\'s verdict - its sign bit - telling the whole row whether the trial subtraction succeeded or went negative.',
        'Between rows, the partial remainder flows DOWNWARD. The bits each cell chose to pass on (difference if it fit, restored minuend if it did not) drop into the row below as that row\'s new minuend - the smaller pile you carry into the next round. So borrow moves horizontally to vote a quotient bit, while the remainder moves vertically to seed the next subtraction.',
        'The repetitive grid quietly encodes the "repetitive shifting" of long division: as you go down the rows, the divisor is effectively compared one bit position further to the right each time, which is the spatial version of shifting the remainder left every step. The result is a fixed lattice of subtract-and-restore cells - the restoring array divider - identical no matter what the actual dividend and divisor are.',
      ],
      theoryHI: [
        'अब controlled-subtractor cells को एक 2D grid में जमाइए - एक जैसे cells की rows और columns - और आपके पास स्कूली worksheet भौतिक रूप में है। यह जाली restoring array divider है, और वही hardware किसी भी संख्याओं पर काम करता है क्योंकि structure कभी नहीं बदलता; बस उसमें बहते bits बदलते हैं।',
        'इसे एक समय में एक row पढ़िए। cells की एक ROW सभी bit positions पर एक साथ divisor का एक trial subtraction करती है, और वह अकेली row ठीक एक quotient bit बनाती है। एक row एक chocolate round है: यह "क्या divisor इस pile में fit होता है?" पूरे चौड़ाई में, समानांतर में पूछती है।',
        'एक row के भीतर, borrow सबसे कम-महत्व वाले cell से सबसे ज़्यादा-महत्व वाले cell तक SIDEWAYS (बग़ल में) ripple होता है, ठीक एक ripple-carry adder के carry की तरह। सबसे ज़्यादा-महत्व वाले cell से निकलता borrow row का फ़ैसला है - उसका sign bit - जो पूरी row को बताता है कि trial subtraction सफल रहा या negative गया।',
        'rows के बीच, partial remainder नीचे (DOWNWARD) बहता है। हर cell ने जो bits आगे भेजने को चुने (fit होने पर difference, न होने पर restored minuend) वे नीचे वाली row में उसके नए minuend की तरह गिरते हैं - छोटा pile जो आप अगले round में ले जाते हैं। तो borrow एक quotient bit vote करने को क्षैतिज चलता है, जबकि remainder अगला subtraction बीज देने को ऊर्ध्वाधर चलता है।',
        'दोहराव वाली grid चुपचाप long division के "repetitive shifting" को encode करती है: जैसे-जैसे आप rows में नीचे जाते हैं, divisor हर बार एक bit position आगे दाईं ओर compare होता है, जो हर कदम remainder को बाएँ shift करने का स्थानिक रूप है। नतीजा है subtract-and-restore cells की एक तय जाली - restoring array divider - जो चाहे असली dividend और divisor कुछ भी हों, एक जैसी रहती है।',
      ],
      transcriptEN: 'Stack the controlled-subtractor cells into a 2D grid and you have the worksheet made physical - the restoring array divider, same hardware for any numbers. One row of cells does one trial subtraction across all bit positions and makes exactly one quotient bit; a row is one chocolate round. Inside a row, borrow ripples sideways from the least-significant cell to the most-significant, like carry in a ripple adder; the borrow out of the top cell is the row sign. Between rows, the partial remainder flows downward - whatever bits each cell chose drop into the next row as its new minuend. So borrow moves horizontally to vote a quotient bit, remainder moves vertically to seed the next subtraction. The grid encodes the repetitive shifting of long division: the divisor is effectively shifted one bit right per row.',
      transcriptHI: 'controlled-subtractor cells को एक 2D grid में जमाइए और आपके पास worksheet भौतिक रूप में है - restoring array divider, किसी भी संख्या के लिए वही hardware। cells की एक row सभी bit positions पर एक trial subtraction करती है और ठीक एक quotient bit बनाती है; एक row एक chocolate round है। row के भीतर, borrow सबसे कम-महत्व वाले cell से सबसे ज़्यादा तक बग़ल में ripple होता है, ripple adder के carry की तरह; ऊपरी cell से निकलता borrow row का sign है। rows के बीच, partial remainder नीचे बहता है - हर cell ने जो bits चुने वे अगली row में उसके नए minuend की तरह गिरते हैं। तो borrow क्षैतिज चलकर quotient bit vote करता है, remainder ऊर्ध्वाधर चलकर अगला subtraction बीज देता है। grid long division के repetitive shifting को encode करती है: divisor हर row एक bit दाईं ओर shift होता है।',
      visualNote: 'Cascading matrix: rows of subtractor+MUX cells; orange arrows = borrow rippling sideways, blue arrows = remainder flowing down; labels "Repetitive Shifting" and "Conditional Subtraction"; divisor shifts one bit right per row.',
    },
    {
      id: 'S08_ReadOut',
      label: 'Quotient and Remainder Read-Out',
      kind: 'theory',
      subtitle: 'q = (final borrow-out)\'; the bottom row is the remainder.',
      theoryEN: [
        'With the grid built, how do you actually read the answers off it? The quotient and the remainder both fall out of the same ripples that already drove the restoring decisions, so almost no extra logic is needed - which is part of what makes it so clean.',
        'Each row emits exactly one quotient bit, taken straight from the borrow-out at the end of that row. The rule is q = (final row borrow-out)\', an inversion. If the row\'s borrow-out is 0 the divisor FIT (the trial subtraction stayed non-negative), so the quotient bit is 1; if the borrow-out is 1 the divisor did NOT fit (it underflowed), so the quotient bit is 0. A successful chocolate round writes a 1, a skipped round writes a 0.',
        'Reading the rows from top to bottom gives you the quotient bits from most significant to least significant, in the natural order you would write them in long division. The top row produces the highest-value quotient bit and the bottom row the lowest.',
        'After the last row, the bits still flowing downward ARE the final remainder - whatever was left in the pile that could not make one more subtraction. The bottom edge of the grid, bundled together, is the remainder bus, and by construction it satisfies 0 <= Remainder < Divisor.',
        'Notice how cheap this read-out is: each quotient bit is just the inverted final borrow of its row, so a single inverter per row gives the whole quotient, and the remainder needs no logic at all - it is simply the bits that arrive at the bottom. The quotient literally falls out of the same borrow ripple that decided whether to restore.',
      ],
      theoryHI: [
        'grid बन जाने पर, आप उससे जवाब असल में कैसे पढ़ते हैं? quotient और remainder दोनों उन्हीं ripples से निकल आते हैं जिन्होंने पहले ही restoring फ़ैसले चलाए, तो लगभग कोई अतिरिक्त logic नहीं चाहिए - यही इसे इतना साफ़-सुथरा बनाने का हिस्सा है।',
        'हर row ठीक एक quotient bit निकालती है, सीधे उस row के अंत के borrow-out से ली गई। नियम है q = (row का final borrow-out)\', एक inversion। अगर row का borrow-out 0 है तो divisor FIT हुआ (trial subtraction non-negative रहा), तो quotient bit 1 है; अगर borrow-out 1 है तो divisor fit नहीं हुआ (underflow), तो quotient bit 0 है। एक सफल chocolate round 1 लिखता है, एक छोड़ा round 0 लिखता है।',
        'rows को ऊपर से नीचे पढ़ने पर आपको quotient bits सबसे महत्वपूर्ण से कम महत्वपूर्ण तक मिलते हैं, उसी प्राकृतिक क्रम में जिसमें आप उन्हें long division में लिखते। ऊपरी row सबसे ज़्यादा-मूल्य वाला quotient bit बनाती है और नीचे वाली row सबसे कम।',
        'आख़िरी row के बाद, अभी भी नीचे बहते bits ही final remainder हैं - pile में जो भी बचा जो एक और subtraction नहीं बना सका। grid का निचला किनारा, एक साथ बंडल किया हुआ, remainder bus है, और निर्माण से यह 0 <= Remainder < Divisor संतुष्ट करता है।',
        'ग़ौर कीजिए यह read-out कितना सस्ता है: हर quotient bit बस अपनी row का उल्टा final borrow है, तो हर row पर एक अकेला inverter पूरा quotient देता है, और remainder को कोई logic नहीं चाहिए - यह बस वे bits हैं जो नीचे पहुँचते हैं। quotient सचमुच उसी borrow ripple से निकलता है जिसने तय किया था कि restore करना है या नहीं।',
      ],
      transcriptEN: 'How do you read the answers off the grid? Each row emits exactly one quotient bit, taken from the borrow-out at the end of that row, inverted: q equals final-borrow-prime. Borrow 0 means the divisor fit, so q is 1; borrow 1 means it did not fit, so q is 0 - a successful round writes 1, a skipped round writes 0. Reading rows top to bottom gives the quotient from most significant to least significant. After the last row, the bits still flowing down are the final remainder, and the bottom edge bundled together is the remainder bus, always less than the divisor. The read-out is nearly free: one inverter per row gives the quotient, and the remainder needs no logic - it is just the bits arriving at the bottom.',
      transcriptHI: 'grid से जवाब कैसे पढ़ें? हर row ठीक एक quotient bit निकालती है, उस row के अंत के borrow-out से, उल्टा किया हुआ: q बराबर final-borrow-prime। borrow 0 मतलब divisor fit हुआ, तो q 1; borrow 1 मतलब fit नहीं हुआ, तो q 0 - सफल round 1 लिखता है, छोड़ा round 0। rows को ऊपर से नीचे पढ़ने पर quotient सबसे महत्वपूर्ण से कम तक मिलता है। आख़िरी row के बाद, अभी भी नीचे बहते bits final remainder हैं, और निचला किनारा बंडल किया remainder bus है, हमेशा divisor से छोटा। read-out लगभग मुफ़्त है: हर row पर एक inverter quotient देता है, और remainder को कोई logic नहीं - यह बस नीचे पहुँचते bits हैं।',
      visualNote: 'Side view of the array: each row\'s rightmost borrow line tapped, inverted, and labelled q[i]; the bottom edge bundled as the Remainder bus.',
    },
    {
      id: 'S09_Sizing',
      label: 'Sizing the Array',
      kind: 'theory',
      subtitle: '2n-bit dividend / n-bit divisor -> n-bit quotient, n-bit remainder, n rows, ~n^2 cells.',
      theoryEN: [
        'How big does the grid have to be? A standard restoring array divider divides a 2n-bit dividend by an n-bit divisor and yields an n-bit quotient and an n-bit remainder. Those four widths are the contract of the block, and they all hang off the single parameter n, the divisor width.',
        'The number of ROWS is n, because each row produces exactly one quotient bit and the quotient is n bits wide. So if you want a 4-bit quotient you stack 4 rows; an 8-bit quotient needs 8 rows. Each row is one chocolate round, and you need as many rounds as quotient bits.',
        'The number of CELLS per row scales with the divisor width n as well, so the total cell count grows on the order of n times n - roughly n^2 controlled-subtractor cells fill the parallelogram. Double the bit-width and you roughly quadruple the hardware, which is why dividers are large blocks.',
        'More bits also means a longer worst-case propagation delay. The borrow has to ripple all the way across each row, and the partial remainder has to ripple down through every row, so the longest path snakes across and down the entire grid. The delay grows with n, making a wide combinational divider slow as well as large.',
        'That is the fundamental trade-off. A combinational divider is wonderfully simple to read - no clock, no control, just drive the inputs and wait for the cloud of gates to settle - but it is expensive in area (about n^2 cells) and slow in its deep ripple paths. That cost is the price of unrolling every long-division step into pure hardware, and it is why real machines often choose sequential or higher-radix dividers when n gets large.',
      ],
      theoryHI: [
        'grid कितना बड़ा होना चाहिए? एक standard restoring array divider एक 2n-bit dividend को एक n-bit divisor से बाँटता है और एक n-bit quotient तथा एक n-bit remainder देता है। वे चार चौड़ाइयाँ block का अनुबंध हैं, और वे सब एक अकेले parameter n पर टँगी हैं, divisor की चौड़ाई।',
        'ROWS की संख्या n है, क्योंकि हर row ठीक एक quotient bit बनाती है और quotient n bits चौड़ा है। तो अगर आप 4-bit quotient चाहते हैं तो 4 rows जमाते हैं; एक 8-bit quotient को 8 rows चाहिए। हर row एक chocolate round है, और आपको quotient bits जितने rounds चाहिए।',
        'हर row में CELLS की संख्या भी divisor चौड़ाई n के साथ बढ़ती है, तो कुल cell गिनती n गुणा n के क्रम में बढ़ती है - लगभग n^2 controlled-subtractor cells parallelogram भरते हैं। bit-चौड़ाई दुगुनी कीजिए और आप लगभग hardware चौगुना कर देते हैं, इसीलिए dividers बड़े blocks हैं।',
        'ज़्यादा bits का मतलब लंबा worst-case propagation delay भी है। borrow को हर row के पार पूरा ripple होना पड़ता है, और partial remainder को हर row से नीचे ripple होना पड़ता है, तो सबसे लंबा path पूरे grid के पार और नीचे साँप की तरह जाता है। delay n के साथ बढ़ता है, जो एक चौड़े combinational divider को बड़ा होने के साथ-साथ धीमा भी बनाता है।',
        'यही मूलभूत trade-off है। एक combinational divider पढ़ने में बेहद सरल है - कोई clock नहीं, कोई control नहीं, बस inputs दीजिए और gates के बादल के थमने का इंतज़ार कीजिए - पर यह क्षेत्र में महँगा (लगभग n^2 cells) और अपने गहरे ripple paths में धीमा है। वह क़ीमत हर long-division कदम को शुद्ध hardware में unroll करने का दाम है, और इसीलिए असली machines अक्सर n बड़ा होने पर sequential या higher-radix dividers चुनती हैं।',
      ],
      transcriptEN: 'How big is the grid? A standard restoring array divider takes a 2n-bit dividend and an n-bit divisor and gives an n-bit quotient and an n-bit remainder. The number of rows is n, because each row makes one quotient bit. The cells per row also scale with n, so the total is about n squared cells - double the width and you roughly quadruple the hardware. More bits also mean a longer delay, because borrow ripples across each row and remainder ripples down every row, so the longest path snakes across and down the whole grid. That is the trade-off: a combinational divider is simple to read, no clock, but expensive in area and slow in its deep ripple paths - the price of unrolling every long-division step into hardware.',
      transcriptHI: 'grid कितना बड़ा? एक standard restoring array divider एक 2n-bit dividend और एक n-bit divisor लेता है और एक n-bit quotient तथा एक n-bit remainder देता है। rows की संख्या n है, क्योंकि हर row एक quotient bit बनाती है। हर row के cells भी n के साथ बढ़ते हैं, तो कुल लगभग n वर्ग cells - चौड़ाई दुगुनी कीजिए और hardware लगभग चौगुना। ज़्यादा bits का मतलब लंबा delay भी, क्योंकि borrow हर row के पार और remainder हर row से नीचे ripple होता है, तो सबसे लंबा path पूरे grid के पार और नीचे जाता है। यही trade-off है: combinational divider पढ़ने में सरल, clock नहीं, पर क्षेत्र में महँगा और गहरे ripple paths में धीमा - हर long-division कदम को hardware में unroll करने का दाम।',
      visualNote: 'Annotated n x n grid: left bracket "2n-bit dividend in", top label "n rows", right label "n-bit quotient out", bottom label "n-bit remainder out". A slider for n reports widths, total cells, and worst-case delay.',
    },
    {
      id: 'S10_Build',
      label: 'Build It For Real',
      kind: 'theory',
      subtitle: 'Wire one controlled-subtractor cell on the live workbench, then tile it into the array.',
      theoryEN: [
        'You have now seen the whole machine: the division identity, the long-division algorithm, the controlled-subtractor unit cell, its full-subtractor and 2-to-1 MUX halves, the cascading array, the quotient and remainder read-out, and the n^2 sizing. The one thing left is to wire it yourself on real hardware.',
        'Open the live workbench and build a single controlled-subtractor cell from gates: two cascaded XOR gates for the difference D = x ^ y ^ bin, an inverter plus three AND gates plus an OR for the borrow bout = x\'.y + x\'.bin + y.bin, and then a 2-to-1 MUX (inverter, two ANDs, one OR) wired with select = bout, I0 = D, I1 = x to build CellOut = bout\'.D + bout.x.',
        'Drive the inputs by hand and watch the cell behave exactly as the theory promised. When your trial subtraction fits, borrow-out is 0, the MUX passes the difference, and the quotient bit reads 1. When it underflows, borrow-out is 1, the MUX restores the original minuend, and the quotient bit reads 0. Prove the restoring decision on a real circuit, one bit at a time.',
        'Once one cell is solid, tiling is mechanical: chain the borrow output of each cell into the borrow input of the cell to its left to form a row, broadcast the row\'s final borrow as the select to every cell in that row, and feed each cell\'s output down into the cell below to start the next row. Stack n such rows and you have a complete restoring array divider that you built from nothing but gates.',
      ],
      theoryHI: [
        'अब आपने पूरी machine देख ली है: division identity, long-division algorithm, controlled-subtractor unit cell, उसके full-subtractor और 2-to-1 MUX आधे, cascading array, quotient और remainder read-out, और n^2 sizing। बची एक चीज़ है इसे ख़ुद असली hardware पर wire करना।',
        'live workbench खोलिए और एक अकेला controlled-subtractor cell gates से बनाइए: difference D = x ^ y ^ bin के लिए दो cascade XOR gates, borrow bout = x\'.y + x\'.bin + y.bin के लिए एक inverter जमा तीन AND gates जमा एक OR, और फिर एक 2-to-1 MUX (inverter, दो AND, एक OR) जो select = bout, I0 = D, I1 = x के साथ wire हो ताकि CellOut = bout\'.D + bout.x बने।',
        'inputs को हाथ से चलाइए और cell को ठीक वैसा बरतते देखिए जैसा theory ने वादा किया। जब आपका trial subtraction fit होता है, borrow-out 0 है, MUX difference भेजता है, और quotient bit 1 पढ़ता है। जब underflow होता है, borrow-out 1 है, MUX मूल minuend restore करता है, और quotient bit 0 पढ़ता है। restoring फ़ैसला एक असली circuit पर साबित कीजिए, एक समय एक bit।',
        'एक cell पक्का होने पर, tiling यांत्रिक है: हर cell के borrow output को बाईं ओर वाले cell के borrow input में chain कीजिए एक row बनाने को, row के final borrow को उस row के हर cell को select की तरह broadcast कीजिए, और हर cell के output को नीचे वाले cell में feed कीजिए अगली row शुरू करने को। ऐसी n rows जमाइए और आपके पास एक पूरा restoring array divider है जो आपने gates के सिवा कुछ नहीं से बनाया।',
      ],
      transcriptEN: 'You have seen the whole machine; the last step is to wire it yourself. Open the workbench and build one controlled-subtractor cell: two cascaded XORs for the difference, an inverter plus three ANDs plus an OR for the borrow, and a 2-to-1 MUX with select equal to the borrow, I0 the difference, I1 the original minuend. Drive the inputs and watch it behave: when the subtraction fits, borrow is 0, the MUX passes the difference, quotient bit 1; when it underflows, borrow is 1, the MUX restores the minuend, quotient bit 0. Once one cell is solid, tiling is mechanical - chain the borrow across to make a row, broadcast the row sign as the select, feed each output down to the next row, and stack n rows for a complete divider.',
      transcriptHI: 'आपने पूरी machine देख ली; आख़िरी कदम इसे ख़ुद wire करना है। workbench खोलिए और एक controlled-subtractor cell बनाइए: difference के लिए दो cascade XOR, borrow के लिए एक inverter जमा तीन AND जमा एक OR, और एक 2-to-1 MUX जिसका select borrow हो, I0 difference, I1 मूल minuend। inputs चलाइए और इसे बरतते देखिए: जब subtraction fit होता है, borrow 0, MUX difference भेजता है, quotient bit 1; जब underflow होता है, borrow 1, MUX minuend restore करता है, quotient bit 0। एक cell पक्का होने पर, tiling यांत्रिक है - एक row बनाने को borrow chain कीजिए, row sign को select की तरह broadcast कीजिए, हर output नीचे feed कीजिए, और एक पूरे divider के लिए n rows जमाइए।',
      visualNote: 'WorkbenchCTA opening /workbench?tutorial=array-divider-cell, plus a recap of the cell gate count: 2 XOR + 1 NOT (subtract) + 3 AND + 1 OR (borrow) + MUX (1 NOT, 2 AND, 1 OR).',
    },
    {
      id: 'S11_Flashcards',
      label: 'Flashcards',
      kind: 'flashcards',
      subtitle: 'Eight flip-cards to lock in the identity, the cell, the restore rule and the sizing.',
      theoryEN: [
        'These eight flip-cards drill the facts that matter most: the division identity, the controlled-subtractor unit cell, the restoring decision rule, the quotient-bit formula, the full-subtractor equations, the 2-to-1 MUX, the array data flow, and the array sizing. Cover the back, say the answer out loud, then flip to check, and repeat any card you fumble until recall is reflex.',
        'Give extra reps to the restore-rule card, because borrow-out = 0 keep / borrow-out = 1 restore is the single decision that the whole divider is built around, and to the cell card, since a full subtractor plus a 2-to-1 MUX is the atom everything else is tiled from.',
        'If you walk away remembering only one thing, make it this: a divider is long division frozen into a grid, where every cell trial-subtracts and the borrow decides keep-the-difference (q=1) or restore-the-minuend (q=0) - the same chocolate-round question asked everywhere at once.',
      ],
      theoryHI: [
        'ये आठ flip-cards सबसे ज़रूरी तथ्य रटाते हैं: division identity, controlled-subtractor unit cell, restoring फ़ैसला नियम, quotient-bit formula, full-subtractor equations, 2-to-1 MUX, array data flow, और array sizing। पीछे ढककर जवाब ज़ोर से बोलिए, फिर जाँचने को पलटिए, और जो card अटके उसे तब तक दोहराइए जब तक याद reflex न बन जाए।',
        'restore-rule वाले card को ज़्यादा दोहराइए, क्योंकि borrow-out = 0 रखो / borrow-out = 1 restore वही एक फ़ैसला है जिसके चारों ओर पूरा divider बना है, और cell card को भी, क्योंकि एक full subtractor जमा एक 2-to-1 MUX वह atom है जिससे बाक़ी सब tile होता है।',
        'अगर आप सिर्फ़ एक बात याद रखकर जाएँ, तो यह हो: एक divider एक grid में जमी long division है, जहाँ हर cell trial-subtract करता है और borrow तय करता है difference रखो (q=1) या minuend restore करो (q=0) - वही chocolate-round सवाल हर जगह एक साथ पूछा गया।',
      ],
      transcriptEN: 'Eight quick flip-cards to set it solid. Front asks, back answers - cover the back, say it aloud, flip to check. Give extra reps to the restore-rule card, because borrow 0 keep, borrow 1 restore is the decision the whole divider is built around, and to the unit-cell card, a full subtractor plus a 2-to-1 MUX.',
      transcriptHI: 'इसे पक्का करने के लिए आठ तेज़ flip-cards। आगे सवाल, पीछे जवाब - पीछे ढककर ज़ोर से बोलिए, पलटकर जाँचिए। restore-rule वाले card को ज़्यादा दोहराइए, क्योंकि borrow 0 रखो, borrow 1 restore वही फ़ैसला है जिसके चारों ओर पूरा divider बना है, और unit-cell card को भी, एक full subtractor जमा एक 2-to-1 MUX।',
      visualNote: 'Standard bilingual flip deck, eight cards.',
    },
    {
      id: 'S12_Quiz',
      label: 'Quiz Arena',
      kind: 'quiz',
      subtitle: 'Eight questions - prove you can build the cell and reason about the array.',
      theoryEN: [
        'Eight multiple-choice questions now check that the array divider has really sunk in: they probe the division identity, what the borrow-out controls, the restoring decision, the 2-to-1 MUX equation, the gate count to build an 8-to-1 MUX, which gates implement the difference, why the inverter sits on the minuend, and how many rows the array has.',
        'Several are circuit-building questions - gate counts and which gates implement an output - so reason from the boolean equations rather than guessing. When asked how many 2-to-1 MUXes make an 8-to-1, count the 4 + 2 + 1 tree; when asked about the difference, remember it is a 3-input XOR.',
        'Aim for full marks, because clearing all eight means you can not only describe a binary divider but actually build its cell from gates and size the whole array.',
      ],
      theoryHI: [
        'आठ bahu-vikalp सवाल अब जाँचते हैं कि array divider सचमुच बैठा या नहीं: ये पूछते हैं division identity, borrow-out क्या control करता है, restoring फ़ैसला, 2-to-1 MUX समीकरण, एक 8-to-1 MUX बनाने की gate गिनती, कौन से gates difference लागू करते हैं, inverter minuend पर क्यों बैठता है, और array में कितनी rows हैं।',
        'कई circuit-building सवाल हैं - gate गिनती और कौन से gates एक output लागू करते हैं - तो अंदाज़े के बजाय boolean equations से सोचिए। जब पूछा जाए कि कितने 2-to-1 MUXes एक 8-to-1 बनाते हैं, 4 + 2 + 1 tree गिनिए; जब difference के बारे में पूछा जाए, याद रखिए यह एक 3-input XOR है।',
        'पूरे अंक का लक्ष्य रखिए, क्योंकि आठों साफ़ करने का मतलब है आप न सिर्फ़ एक binary divider बता सकते हैं बल्कि उसका cell gates से बना सकते हैं और पूरे array को size कर सकते हैं।',
      ],
      transcriptEN: 'Eight questions in the arena. They check the division identity, what the borrow-out controls, the restoring decision, the 2-to-1 MUX equation, how many 2-to-1 MUXes build an 8-to-1, which gates implement the difference, why the inverter sits on the minuend, and how many rows the array has. Several are circuit-building questions, so reason from the boolean equations. Clear all eight and you can build the cell and size the array, not just describe it.',
      transcriptHI: 'Arena में आठ सवाल। ये जाँचते हैं division identity, borrow-out क्या control करता है, restoring फ़ैसला, 2-to-1 MUX समीकरण, कितने 2-to-1 MUXes एक 8-to-1 बनाते हैं, कौन से gates difference लागू करते हैं, inverter minuend पर क्यों बैठता है, और array में कितनी rows हैं। कई circuit-building सवाल हैं, तो boolean equations से सोचिए। आठों साफ़ कीजिए और आप cell बना सकते हैं तथा array size कर सकते हैं, सिर्फ़ बता नहीं सकते।',
      visualNote: 'Parameterized QuizArena, eight questions.',
    },
    {
      id: 'S13_Recap',
      label: 'Recap & Sources',
      kind: 'recap',
      subtitle: 'A divider is long division frozen into a grid of restoring controlled-subtractor cells.',
      theoryEN: [
        'Let us bank the whole thing. A binary divider splits a dividend by a divisor into a quotient and a remainder, and it must always satisfy the identity Dividend = Divisor . Quotient + Remainder with 0 <= Remainder < Divisor. A combinational divider has no clock; it is schoolbook long division unrolled flat into a 2D grid of identical cells.',
        'The atom of that grid is the controlled subtractor: one full subtractor (D = x ^ y ^ bin, bout = x\'.y + x\'.bin + y.bin) feeding one 2-to-1 MUX (Y = S\'.I0 + S.I1). The borrow-out drives the MUX select, so CellOut = bout\'.D + bout.x - keep the difference when the divisor fit, restore the original minuend when it did not. That single decision is what "restoring" means.',
        'Stacked into a grid, the borrow ripples sideways across each row to vote one quotient bit (q = borrow\'), while the partial remainder flows down to seed the next row. A standard array divides a 2n-bit dividend by an n-bit divisor using n rows of about n cells each - roughly n^2 controlled-subtractor cells - giving an n-bit quotient and an n-bit remainder.',
        'Step back and see the recurring genius: the same humble full subtractor, reused everywhere and topped with one tiny MUX, turns a paper algorithm into a cloud of gates that computes division with no clock at all. The chocolate-round question - "does the divisor fit?" - is asked everywhere in the grid at once, and the borrows and remainders simply ripple the answers out.',
        'Sources used to verify every equation and the restoring algorithm: GeeksforGeeks restoring division (geeksforgeeks.org/computer-organization-architecture/restoring-division-algorithm-unsigned-integer/), GeeksforGeeks full subtractor (geeksforgeeks.org/digital-logic/full-subtractor-in-digital-logic/), GeeksforGeeks multiplexers (geeksforgeeks.org/digital-logic/multiplexers-in-digital-logic/), ResearchGate restoring array divider of controlled-subtractor cells (researchgate.net/figure/Restoring-array-divider-composed-of-controlled-subtractor-cells_fig4_262836277), and AllAboutCircuits multiplexers/demultiplexers (allaboutcircuits.com/worksheets/multiplexers-and-demultiplexers/).',
      ],
      theoryHI: [
        'चलिए पूरी बात जमा कर लें। एक binary divider एक dividend को एक divisor से एक quotient और एक remainder में बाँटता है, और इसे हमेशा identity Dividend = Divisor . Quotient + Remainder संतुष्ट करनी पड़ती है, 0 <= Remainder < Divisor के साथ। एक combinational divider में कोई clock नहीं; यह स्कूली long division है जो एक 2D grid में सपाट unroll की हुई है, एक जैसे cells से बनी।',
        'उस grid का atom controlled subtractor है: एक full subtractor (D = x ^ y ^ bin, bout = x\'.y + x\'.bin + y.bin) जो एक 2-to-1 MUX (Y = S\'.I0 + S.I1) को feed करता है। borrow-out MUX की select चलाता है, तो CellOut = bout\'.D + bout.x - divisor fit होने पर difference रखो, न होने पर मूल minuend restore करो। वही एक फ़ैसला "restoring" का मतलब है।',
        'एक grid में जमे होने पर, borrow हर row के पार बग़ल में ripple होकर एक quotient bit vote करता है (q = borrow\'), जबकि partial remainder नीचे बहकर अगली row बीज देता है। एक standard array एक 2n-bit dividend को एक n-bit divisor से n rows से बाँटता है, हर एक लगभग n cells - लगभग n^2 controlled-subtractor cells - एक n-bit quotient और एक n-bit remainder देते हुए।',
        'पीछे हटकर बार-बार आती प्रतिभा देखिए: वही मामूली full subtractor, हर जगह दोबारा वापरा और एक नन्हे MUX से ढका, एक काग़ज़ी algorithm को gates के बादल में बदल देता है जो बिना किसी clock के division गिनता है। chocolate-round सवाल - "क्या divisor fit होता है?" - grid में हर जगह एक साथ पूछा जाता है, और borrows तथा remainders बस जवाब ripple कर बाहर कर देते हैं।',
        'हर समीकरण और restoring algorithm सत्यापित करने को वापरे sources: GeeksforGeeks restoring division (geeksforgeeks.org/computer-organization-architecture/restoring-division-algorithm-unsigned-integer/), GeeksforGeeks full subtractor (geeksforgeeks.org/digital-logic/full-subtractor-in-digital-logic/), GeeksforGeeks multiplexers (geeksforgeeks.org/digital-logic/multiplexers-in-digital-logic/), ResearchGate restoring array divider of controlled-subtractor cells (researchgate.net/figure/Restoring-array-divider-composed-of-controlled-subtractor-cells_fig4_262836277), और AllAboutCircuits multiplexers/demultiplexers (allaboutcircuits.com/worksheets/multiplexers-and-demultiplexers/)।',
      ],
      transcriptEN: 'Bank the whole thing. A binary divider splits a dividend by a divisor into a quotient and a remainder, always satisfying Dividend equals Divisor times Quotient plus Remainder, with the remainder less than the divisor. A combinational divider is long division unrolled into a 2D grid. The atom is the controlled subtractor: a full subtractor feeding a 2-to-1 MUX, with the borrow-out as the select, so CellOut equals borrow-prime times D plus borrow times x - keep the difference when it fit, restore the minuend when it did not. Borrow ripples sideways to make each quotient bit, q equals borrow-prime, and the remainder flows down. A standard array uses n rows of about n cells, roughly n squared, to divide a 2n-bit dividend by an n-bit divisor. The same humble full subtractor plus one tiny MUX turns a paper algorithm into a clock-free cloud of gates.',
      transcriptHI: 'पूरी बात जमा कीजिए। एक binary divider एक dividend को एक divisor से एक quotient और remainder में बाँटता है, हमेशा Dividend बराबर Divisor गुणा Quotient जमा Remainder, remainder divisor से छोटा। एक combinational divider एक 2D grid में unroll की long division है। atom controlled subtractor है: एक full subtractor एक 2-to-1 MUX को feed करता, borrow-out select के रूप में, तो CellOut बराबर borrow-prime गुणा D जमा borrow गुणा x - fit होने पर difference रखो, न होने पर minuend restore करो। borrow बग़ल में ripple होकर हर quotient bit बनाता है, q बराबर borrow-prime, और remainder नीचे बहता है। एक standard array n rows, लगभग n cells, लगभग n वर्ग, से एक 2n-bit dividend को एक n-bit divisor से बाँटता है। वही मामूली full subtractor जमा एक नन्हा MUX एक काग़ज़ी algorithm को clock-रहित gates के बादल में बदल देता है।',
      visualNote: 'Recap card: the controlled-subtractor cell on the left, the cascading array on the right; sources listed as plain links.',
    },
  ],
  flashcards: [
    {
      frontEN: 'State the division identity and the remainder bound.',
      backEN: 'Dividend = Divisor . Quotient + Remainder, with 0 <= Remainder < Divisor. Every divider must satisfy it.',
      frontHI: 'division identity और remainder सीमा बताइए।',
      backHI: 'Dividend = Divisor . Quotient + Remainder, 0 <= Remainder < Divisor के साथ। हर divider को इसे संतुष्ट करना पड़ता है।',
    },
    {
      frontEN: 'What is the unit cell of an array divider?',
      backEN: 'A controlled subtractor: one full subtractor plus a 2-to-1 MUX that either keeps the difference or restores the original minuend.',
      frontHI: 'एक array divider का unit cell क्या है?',
      backHI: 'एक controlled subtractor: एक full subtractor जमा एक 2-to-1 MUX जो या तो difference रखता है या मूल minuend restore करता है।',
    },
    {
      frontEN: 'State the restoring decision rule.',
      backEN: 'Borrow-out = 0 -> subtraction fit, keep difference, q = 1. Borrow-out = 1 -> underflow, restore minuend, q = 0. Borrow drives the MUX select.',
      frontHI: 'restoring फ़ैसला नियम बताइए।',
      backHI: 'Borrow-out = 0 -> subtraction fit, difference रखो, q = 1. Borrow-out = 1 -> underflow, minuend restore करो, q = 0. Borrow MUX की select चलाता है।',
    },
    {
      frontEN: 'How is each quotient bit read off the array?',
      backEN: 'q = (final row borrow-out)\'. Borrow = 0 means the divisor fit so q = 1; borrow = 1 means it did not fit so q = 0.',
      frontHI: 'हर quotient bit array से कैसे पढ़ा जाता है?',
      backHI: 'q = (row का final borrow-out)\'. Borrow = 0 मतलब divisor fit हुआ तो q = 1; borrow = 1 मतलब fit नहीं हुआ तो q = 0।',
    },
    {
      frontEN: 'Write the full-subtractor equations.',
      backEN: 'D = x ^ y ^ bin ; bout = x\'.y + x\'.bin + y.bin (the inverter sits on the minuend x). Built as 2 XOR, 2 AND, 2 NOT, 1 OR.',
      frontHI: 'full-subtractor equations लिखिए।',
      backHI: 'D = x ^ y ^ bin ; bout = x\'.y + x\'.bin + y.bin (inverter minuend x पर बैठता है)। 2 XOR, 2 AND, 2 NOT, 1 OR से बना।',
    },
    {
      frontEN: 'Give the 2-to-1 MUX equation and gate count.',
      backEN: 'Y = S\'.I0 + S.I1. Built from 1 inverter, 2 AND gates, 1 OR gate (4 gates). It is the restore switch in each divider cell.',
      frontHI: '2-to-1 MUX समीकरण और gate गिनती दीजिए।',
      backHI: 'Y = S\'.I0 + S.I1। 1 inverter, 2 AND gates, 1 OR gate (4 gates) से बना। यह हर divider cell का restore switch है।',
    },
    {
      frontEN: 'Describe the data flow through the array.',
      backEN: 'Borrow ripples SIDEWAYS along a row to form one quotient bit; the partial remainder flows DOWNWARD to the next row as its new minuend.',
      frontHI: 'array में data flow का वर्णन कीजिए।',
      backHI: 'Borrow एक row में बग़ल में (SIDEWAYS) ripple होकर एक quotient bit बनाता है; partial remainder नीचे (DOWNWARD) अगली row में उसके नए minuend की तरह बहता है।',
    },
    {
      frontEN: 'How is a standard restoring array divider sized?',
      backEN: '2n-bit dividend / n-bit divisor -> n-bit quotient, n-bit remainder, n rows, and about n^2 controlled-subtractor cells total.',
      frontHI: 'एक standard restoring array divider कैसे size होता है?',
      backHI: '2n-bit dividend / n-bit divisor -> n-bit quotient, n-bit remainder, n rows, और कुल लगभग n^2 controlled-subtractor cells।',
    },
  ],
  quiz: [
    {
      questionEN: 'What identity must every divider\'s outputs always satisfy?',
      options: [
        'Dividend = Divisor + Quotient + Remainder',
        'Dividend = Divisor . Quotient + Remainder',
        'Quotient = Dividend . Divisor + Remainder',
        'Remainder = Divisor . Quotient + Dividend',
      ],
      answerIndex: 1,
      explainEN: 'Division reverses multiplication: Dividend = Divisor * Quotient + Remainder is the core invariant, with 0 <= Remainder < Divisor.',
      explainHI: 'Division multiplication को उलटता है: Dividend = Divisor * Quotient + Remainder मूल invariant है, 0 <= Remainder < Divisor के साथ।',
      questionHI: 'हर divider के outputs को हमेशा कौन सी identity संतुष्ट करनी चाहिए?',
    },
    {
      questionEN: 'In a restoring-array unit cell, what does the Borrow-out signal control?',
      options: [
        'The clock enable of the cell',
        'The carry into the next adder',
        'The select line of the 2-to-1 MUX',
        'The reset of the remainder register',
      ],
      answerIndex: 2,
      explainEN: 'Borrow-out drives the MUX select, deciding whether to keep the difference (borrow 0) or restore the minuend (borrow 1).',
      explainHI: 'Borrow-out MUX की select चलाता है, तय करता है कि difference रखे (borrow 0) या minuend restore करे (borrow 1)।',
      questionHI: 'एक restoring-array unit cell में, Borrow-out संकेत क्या control करता है?',
    },
    {
      questionEN: 'If a row\'s final Borrow-out = 1, what happens?',
      options: [
        'The subtraction succeeded; quotient bit = 1; keep difference',
        'The subtraction underflowed; quotient bit = 0; restore the original minuend',
        'The cell halts and outputs the remainder',
        'Borrow-out = 1 is impossible in division',
      ],
      answerIndex: 1,
      explainEN: 'Borrow = 1 means the divisor did not fit (went negative), so q = 0 and the MUX passes the original minuend (restore).',
      explainHI: 'Borrow = 1 मतलब divisor fit नहीं हुआ (negative गया), तो q = 0 और MUX मूल minuend भेजता है (restore)।',
      questionHI: 'अगर किसी row का final Borrow-out = 1 हो, तो क्या होता है?',
    },
    {
      questionEN: 'Which Boolean expression correctly implements a 2-to-1 MUX output Y?',
      options: [
        'Y = S . I0 + S\' . I1',
        'Y = S\' . I0 + S . I1',
        'Y = S . I0 . I1',
        'Y = (I0 + I1)\'',
      ],
      answerIndex: 1,
      explainEN: 'Y = S\'.I0 + S.I1: when S = 0 you select I0, when S = 1 you select I1.',
      explainHI: 'Y = S\'.I0 + S.I1: जब S = 0 तो I0 चुनिए, जब S = 1 तो I1 चुनिए।',
      questionHI: 'कौन सी Boolean expression एक 2-to-1 MUX output Y को सही लागू करती है?',
    },
    {
      questionEN: 'How many 2-to-1 MUXes are needed to build an 8-to-1 MUX from a tree?',
      options: ['3', '6', '7', '8'],
      answerIndex: 2,
      explainEN: 'An N-to-1 MUX needs N - 1 two-to-1 MUXes; for N = 8 that is 7, arranged as a 4 + 2 + 1 tree.',
      explainHI: 'एक N-to-1 MUX को N - 1 two-to-1 MUXes चाहिए; N = 8 के लिए वह 7 है, 4 + 2 + 1 tree के रूप में।',
      questionHI: 'एक tree से एक 8-to-1 MUX बनाने को कितने 2-to-1 MUXes चाहिए?',
    },
    {
      questionEN: 'Which gates implement the Difference output D of a full subtractor (D = x ^ y ^ bin)?',
      options: [
        'Two cascaded XOR gates',
        'One AND gate and one OR gate',
        'Three NAND gates only',
        'One inverter and one OR gate',
      ],
      answerIndex: 0,
      explainEN: 'A 3-input XOR is built as two cascaded 2-input XOR gates: (x ^ y) ^ bin.',
      explainHI: 'एक 3-input XOR दो cascade 2-input XOR gates की तरह बनता है: (x ^ y) ^ bin।',
      questionHI: 'एक full subtractor के Difference output D (D = x ^ y ^ bin) को कौन से gates लागू करते हैं?',
    },
    {
      questionEN: 'In bout = x\'.y + x\'.bin + y.bin, why is the inverter on x and not on y?',
      options: [
        'It is arbitrary; either works',
        'Because a borrow is needed when the minuend x is too small (0) relative to the subtrahend / borrow',
        'Because x is the most significant bit',
        'To save one gate compared with a full adder',
      ],
      answerIndex: 1,
      explainEN: 'You borrow when the minuend x cannot cover y plus borrow-in; hence the NOT sits on the minuend x.',
      explainHI: 'आप तब borrow लेते हैं जब minuend x, y जमा borrow-in को ढक न सके; इसलिए NOT minuend x पर बैठता है।',
      questionHI: 'bout = x\'.y + x\'.bin + y.bin में, inverter x पर क्यों है और y पर क्यों नहीं?',
    },
    {
      questionEN: 'For a standard restoring array divider with an n-bit divisor and 2n-bit dividend, how many rows of cells does the array have?',
      options: ['2n rows', 'n rows', 'n^2 rows', '1 row'],
      answerIndex: 1,
      explainEN: 'Each row produces exactly one quotient bit, and the quotient is n bits wide, so there are n rows.',
      explainHI: 'हर row ठीक एक quotient bit बनाती है, और quotient n bits चौड़ा है, तो n rows हैं।',
      questionHI: 'एक n-bit divisor और 2n-bit dividend वाले standard restoring array divider में, array में cells की कितनी rows होती हैं?',
    },
  ],
}) as unknown as SubContent;
