import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/22 - The Demultiplexer (DEMUX), "One Input, Many Lines".
 * Source spec: _scratch/specs/dsd22.json.
 * A DEMUX routes one data input D to exactly one of 2^n outputs, chosen by n
 * select lines. Outputs = 2^n. Each output Yi = D . (minterm_i of the selects):
 * 1-to-2 -> Y0 = S'.D, Y1 = S.D ; 1-to-4 -> Y0 = S1'.S0'.D, Y1 = S1'.S0.D,
 * Y2 = S1.S0'.D, Y3 = S1.S0.D. A decoder with its enable used as the data input
 * IS a demux. Central analogy: a parcel courier dropping one package at exactly
 * one of many houses chosen by the address (the select lines).
 */
export const CONTENT = ({
  moduleTitle: 'The Demultiplexer (DEMUX) - One Input, Many Lines',
  moduleSubtitle: 'A 1-to-many data distributor: one input D is routed to exactly one of 2^n outputs, chosen by n select lines. The exact inverse of a multiplexer.',
  scenes: [
    {
      id: 'S00_Cover',
      label: 'One Input, Many Destinations',
      kind: 'cover',
      subtitle: 'Hand one parcel to a courier, write an address on it, and watch it land at exactly one house out of many.',
      theoryEN: [
        'This module builds the demultiplexer, written DEMUX for short. A DEMUX is a combinational circuit that takes a single data input, which we call D, and routes it to exactly one of many output lines. The particular output that receives the data is chosen by a small set of control wires called the select lines.',
        'Hold one picture in your head for the entire module: a parcel courier. The courier is carrying a single package, and there are several houses on the street. The package must land at exactly ONE house, and the binary address label written on the package tells the courier which one. Here the package is the data input D, the houses are the outputs Y0, Y1, Y2 and so on, and the address is the select lines.',
        'Every house that is not selected gets nothing, which in logic means it is held at 0. Only the one addressed house receives the package, so the selected output simply copies D while all the others stay quiet. That is the whole behaviour of a DEMUX in one sentence: one input, one chosen destination, everything else off.',
        'A DEMUX is the exact mirror image of a multiplexer (MUX). Where a MUX funnels many inputs down into one output (a collector gathering parcels into one truck), a DEMUX fans one input out to many destinations (a courier handing out one parcel to many houses). They are inverses, and they share the same select logic.',
        'By the end you will be able to write the routing equation for any output, build a 1-to-2 and a 1-to-4 DEMUX from inverters and AND gates, prove that a decoder with its enable used as data IS a demux, and build the real thing on a workbench.',
      ],
      theoryHI: [
        'इस module में हम demultiplexer बनाएँगे, छोटे में DEMUX। DEMUX एक combinational circuit है जो एक अकेला data input लेता है, जिसे हम D कहते हैं, और उसे कई output lines में से ठीक एक तक भेजता है। कौन सा output वह data पाएगा, यह control wires के एक छोटे समूह से तय होता है जिन्हें select lines कहते हैं।',
        'पूरे module के लिए एक तस्वीर मन में रखिए: एक parcel courier। courier के पास एक अकेला package है, और गली में कई घर हैं। package को ठीक एक घर पर पहुँचना है, और package पर लिखा binary address label courier को बताता है कि कौन सा। यहाँ package data input D है, घर outputs Y0, Y1, Y2 वग़ैरह हैं, और address select lines हैं।',
        'जो भी घर चुना नहीं गया उसे कुछ नहीं मिलता, जिसका logic में मतलब है वह 0 पर रखा जाता है। सिर्फ़ वही एक addressed घर package पाता है, तो चुना हुआ output बस D की नक़ल करता है जबकि बाक़ी सब चुप रहते हैं। यही DEMUX का पूरा व्यवहार एक वाक्य में है: एक input, एक चुना destination, बाक़ी सब बंद।',
        'DEMUX एक multiplexer (MUX) की बिलकुल उल्टी तस्वीर है। जहाँ MUX कई inputs को एक output में समेटता है (एक collector जो parcels को एक truck में जमा करता है), वहीं DEMUX एक input को कई destinations में फैलाता है (एक courier जो एक parcel कई घरों में बाँटता है)। ये inverses हैं, और दोनों एक ही select logic बाँटते हैं।',
        'अंत तक आप किसी भी output के लिए routing equation लिख पाएँगे, inverters और AND gates से 1-to-2 और 1-to-4 DEMUX बना पाएँगे, साबित कर पाएँगे कि जिस decoder का enable data की तरह वापरा जाए वही एक demux है, और workbench पर असली चीज़ बना पाएँगे।',
      ],
      transcriptEN: 'Welcome. Picture a parcel courier holding one package, walking down a street of houses. The package has to land at exactly one house, and a little binary address written on it tells the courier which. That is a demultiplexer. The package is the data input D, the houses are the outputs, and the address is the select lines. Only the addressed house receives the package; every other house gets nothing, a logic zero. A demux is the exact opposite of a multiplexer: a mux funnels many inputs into one output, a demux fans one input out to many. By the end you will write the routing equations, build a one-to-two and a one-to-four demux from inverters and AND gates, and see that a decoder whose enable is fed with data is exactly a demux.',
      transcriptHI: 'स्वागत है। एक parcel courier सोचिए जो एक package लिए घरों की गली में चल रहा है। package को ठीक एक घर पर पहुँचना है, और उस पर लिखा छोटा binary address courier को बताता है कि कौन सा। यही demultiplexer है। package data input D है, घर outputs हैं, और address select lines है। सिर्फ़ addressed घर package पाता है; हर दूसरे घर को कुछ नहीं, एक logic zero। demux multiplexer की बिलकुल उल्टी है: mux कई inputs को एक output में समेटता है, demux एक input को कई में फैलाता है। अंत तक आप routing equations लिखेंगे, inverters और AND gates से one-to-two और one-to-four demux बनाएँगे, और देखेंगे कि जिस decoder का enable data से भरा जाए वही ठीक एक demux है।',
      visualNote: 'Hero: a courier at the centre with one glowing package (D); n select bits form a binary address; fanned wires lead to houses Y0..Y3, only the addressed house lit, the rest dimmed to 0.',
    },
    {
      id: 'S01_Video',
      label: 'The Demultiplexer',
      kind: 'video',
      subtitle: 'A short lesson: one input, many lines, one address picks the destination.',
      theoryEN: [
        'Here is the whole idea in one breath before you watch. A demultiplexer has a single data input D, a handful of select lines, and many output lines. For any setting of the select lines, the data D appears on exactly one output and every other output is forced to 0. Nothing is added or transformed - D is simply steered to a chosen wire.',
        'Keep the courier in mind the entire time. The package never changes; what changes is which door it is dropped at. Flip the address bits and the same parcel is suddenly delivered to a different house, while the previously chosen house goes empty. That is exactly what happens to the outputs when you flip the select lines.',
        'The size rule is short and worth memorising: with n select lines you can address 2^n outputs, because each distinct binary code of the selects names one output. So 1 select gives a 1-to-2 demux, 2 selects give a 1-to-4, and 3 selects give a 1-to-8.',
        'The routing rule is just as short: each output Yi equals D ANDed with one unique minterm of the select lines. A minterm is the AND of every select line in either true or complemented form, so exactly one minterm is 1 at any time, which is why exactly one output can be active at a time.',
        'One running example to hold onto: a 1-to-4 demux with D = 1 and the select code 10 (S1 = 1, S0 = 0). The code 10 is decimal 2, so the package is delivered to output Y2, which goes to 1, while Y0, Y1 and Y3 all stay 0.',
      ],
      theoryHI: [
        'देखने से पहले पूरा विचार एक साँस में। एक demultiplexer में एक अकेला data input D, कुछ select lines, और कई output lines होती हैं। select lines की किसी भी setting के लिए, data D ठीक एक output पर दिखता है और हर दूसरा output 0 पर रखा जाता है। कुछ भी जोड़ा या बदला नहीं जाता - D बस एक चुने तार तक मोड़ दिया जाता है।',
        'पूरे समय courier को मन में रखिए। package कभी नहीं बदलता; जो बदलता है वह यह है कि उसे किस दरवाज़े पर गिराया जाए। address bits पलटिए और वही parcel अचानक किसी दूसरे घर पहुँच जाता है, जबकि पहले चुना घर ख़ाली रह जाता है। select lines पलटने पर outputs के साथ ठीक यही होता है।',
        'size नियम छोटा और याद रखने लायक़ है: n select lines से आप 2^n outputs address कर सकते हैं, क्योंकि selects का हर अलग binary code एक output का नाम है। तो 1 select से 1-to-2 demux, 2 selects से 1-to-4, और 3 selects से 1-to-8 बनता है।',
        'routing नियम उतना ही छोटा है: हर output Yi बराबर है D को select lines के एक अनोखे minterm के साथ AND करना। minterm हर select line का true या complemented रूप में AND है, तो किसी भी समय ठीक एक minterm 1 होता है, इसीलिए एक समय में ठीक एक output active हो सकता है।',
        'एक चलता उदाहरण पकड़े रखिए: एक 1-to-4 demux जिसमें D = 1 और select code 10 (S1 = 1, S0 = 0)। code 10 decimal में 2 है, तो package output Y2 पर पहुँचता है, जो 1 हो जाता है, जबकि Y0, Y1 और Y3 सब 0 रहते हैं।',
      ],
      transcriptEN: 'Here is the whole idea in one breath. A demultiplexer has a single data input D, a few select lines, and many outputs. For any setting of the selects, D appears on exactly one output and every other output is held at zero. Nothing is transformed; D is simply steered to a chosen wire. Keep the courier in mind: the package never changes, only which door it is dropped at. The size rule: with n select lines you address two-to-the-n outputs, so one select gives one-to-two, two selects give one-to-four, three selects give one-to-eight. The routing rule: each output is D ANDed with one unique minterm of the selects, and since exactly one minterm is one at a time, exactly one output is active. Running example: a one-to-four demux with D equals one and select code one-zero - that is decimal two - delivers the package to Y2, which goes high, while Y0, Y1 and Y3 stay zero.',
      transcriptHI: 'पूरा विचार एक साँस में। एक demultiplexer में एक अकेला data input D, कुछ select lines, और कई outputs होते हैं। selects की किसी भी setting के लिए, D ठीक एक output पर दिखता है और हर दूसरा output शून्य पर रखा जाता है। कुछ नहीं बदला जाता; D बस एक चुने तार तक मोड़ा जाता है। courier मन में रखिए: package कभी नहीं बदलता, सिर्फ़ किस दरवाज़े पर गिरे यह बदलता है। size नियम: n select lines से आप two-to-the-n outputs address करते हैं, तो one select से one-to-two, two selects से one-to-four, three selects से one-to-eight। routing नियम: हर output, D को selects के एक अनोखे minterm से AND करना है, और चूँकि एक समय ठीक एक minterm one होता है, ठीक एक output active होता है। उदाहरण: D बराबर one और select code one-zero - यानी decimal two - के साथ एक one-to-four demux package को Y2 पर पहुँचाता है, जो high हो जाता है, जबकि Y0, Y1 और Y3 शून्य रहते हैं।',
      visualNote: 'Animated explainer: package D enters a DEMUX box; an address dial set to 10; the wire to Y2 lights up and carries the package while the other three outputs stay dark at 0.',
    },
    {
      id: 'S02_WhatDoes',
      label: 'What A Demultiplexer Does',
      kind: 'theory',
      subtitle: 'One data input, 2^n outputs, the select lines pick the single destination.',
      theoryEN: [
        'Let us nail down exactly what a demultiplexer does. The name itself is a clue: to "de-multiplex" is to undo the funnelling that a multiplexer performed. A MUX takes many inputs and squeezes them down to one output; a DEMUX does the reverse, taking one input and spreading it out to many outputs. It is a 1-to-many operation instead of a many-to-1 one.',
        'Concretely, a DEMUX has exactly one data input, which we always call D. It has n select lines, and it has 2^n output lines, one for every distinct binary code the select lines can form. So the number of outputs is fixed by the number of select lines through the rule Outputs = 2^n.',
        'The select lines do one job: they pick which single output is allowed to receive the data. The output whose index matches the select code follows D exactly - if D is 1 the chosen output is 1, if D is 0 the chosen output is 0. Every other output, the ones not picked, is forced to logic 0 no matter what D is doing.',
        'Return to the courier to feel why this is natural. There is one package (D) and many houses (the outputs). The address written on the package (the select lines) points to one house, and the courier walks the package to exactly that door. Every other house on the street receives nothing, which is the 0 on every unselected output.',
        'Because exactly one output is active and it simply copies the data, a DEMUX is often called a "data distributor": it distributes a single data line to one addressed destination. Toggle the select bits in the panel below and watch the single live wire jump from one output to another while the rest fall to 0.',
      ],
      theoryHI: [
        'चलिए ठीक-ठीक तय करें कि demultiplexer करता क्या है। नाम ही एक संकेत है: "de-multiplex" का मतलब है वह funnelling उलटना जो multiplexer ने की थी। MUX कई inputs लेकर उन्हें एक output में निचोड़ता है; DEMUX उल्टा करता है, एक input लेकर उसे कई outputs में फैलाता है। यह 1-to-many काम है, many-to-1 नहीं।',
        'ठोस रूप में, एक DEMUX में ठीक एक data input होता है, जिसे हम हमेशा D कहते हैं। इसमें n select lines होती हैं, और 2^n output lines, हर अलग binary code के लिए एक जो select lines बना सकती हैं। तो outputs की गिनती select lines की गिनती से नियम Outputs = 2^n द्वारा तय होती है।',
        'select lines एक काम करती हैं: वे चुनती हैं कि कौन सा अकेला output data पाने की इजाज़त पाएगा। जिस output का index select code से मिलता है वह बिलकुल D का अनुसरण करता है - अगर D 1 है तो चुना output 1, अगर D 0 है तो चुना output 0। हर दूसरा output, जो चुना नहीं गया, चाहे D कुछ भी कर रहा हो, logic 0 पर रखा जाता है।',
        'courier पर लौटिए और महसूस कीजिए यह स्वाभाविक क्यों है। एक package (D) है और कई घर (outputs) हैं। package पर लिखा address (select lines) एक घर की ओर इशारा करता है, और courier package को ठीक उसी दरवाज़े तक ले जाता है। गली का हर दूसरा घर कुछ नहीं पाता, यही हर unselected output पर 0 है।',
        'चूँकि ठीक एक output active होता है और वह बस data की नक़ल करता है, DEMUX को अक्सर "data distributor" कहते हैं: यह एक अकेली data line को एक addressed destination तक बाँटता है। नीचे panel में select bits toggle कीजिए और देखिए कि वह अकेला live तार एक output से दूसरे पर कूदता है जबकि बाक़ी 0 पर गिर जाते हैं।',
      ],
      transcriptEN: 'Let us nail down what a demux does. To de-multiplex is to undo the funnelling a mux did: a mux squeezes many inputs into one output, a demux spreads one input out to many. A demux has one data input D, n select lines, and two-to-the-n outputs, one per binary code of the selects. The selects pick which single output receives the data. The chosen output follows D exactly; every other output is forced to zero. In courier terms: one package, many houses, the address picks one door, and the courier walks the package to exactly that house while every other house gets nothing. Because one output copies D and the rest are zero, a demux is a data distributor - it distributes one line to one addressed destination.',
      transcriptHI: 'चलिए तय करें demux करता क्या है। de-multiplex यानी वह funnelling उलटना जो mux ने की: mux कई inputs को एक output में निचोड़ता है, demux एक input को कई में फैलाता है। एक demux में एक data input D, n select lines, और two-to-the-n outputs होते हैं, selects के हर binary code के लिए एक। selects चुनती हैं कौन सा अकेला output data पाएगा। चुना output बिलकुल D का अनुसरण करता है; हर दूसरा output शून्य पर रखा जाता है। courier भाषा में: एक package, कई घर, address एक दरवाज़ा चुनता है, और courier package को ठीक उसी घर तक ले जाता है जबकि हर दूसरा घर कुछ नहीं पाता। चूँकि एक output D की नक़ल करता है और बाक़ी शून्य, demux एक data distributor है - यह एक line को एक addressed destination तक बाँटता है।',
      visualNote: 'DemuxViz (outputs=4): toggle D and the select bits; the selected Yi carries D while the others read 0.',
    },
    {
      id: 'S03_Sizing',
      label: 'Sizing: Selects vs Outputs',
      kind: 'theory',
      subtitle: 'Each extra select line doubles the reachable outputs: Outputs = 2^n.',
      theoryEN: [
        'How many houses can the courier reach? That depends entirely on how many bits the address has. The relationship is exponential, and it is the single most important number in this module: with n select lines a DEMUX drives 2^n outputs. Each output is named by one distinct binary code of the selects, and n bits make exactly 2^n codes.',
        'The key consequence is doubling. Every time you add one more select line you double the number of reachable outputs, because each new bit splits every existing address into two - a 0 version and a 1 version. One more wire of address, twice as many houses on the street.',
        'Let us walk the ladder with concrete numbers. 1 select line gives 2^1 = 2 outputs, a 1-to-2 demux. 2 select lines give 2^2 = 4 outputs, a 1-to-4. 3 select lines give 2^3 = 8 outputs, a 1-to-8. 4 select lines give 2^4 = 16 outputs, a 1-to-16. The pattern 2, 4, 8, 16 is just the powers of two.',
        'A worked example fixes it: a courier with a 3-bit address can reach 2^3 = 8 houses, so a DEMUX with 3 select lines is a 1-to-8 demux with eight output lines Y0 through Y7. Three address bits, eight possible doors.',
        'You can run the rule backwards too. If you know you need M output lines, the number of select lines you must provide is n = log2(M). For example, 16 destinations need log2(16) = 4 select lines, and 8 destinations need log2(8) = 3. Use the panel below to add select lines and watch the number of houses double each time.',
      ],
      theoryHI: [
        'courier कितने घर पहुँच सकता है? यह पूरी तरह इस पर निर्भर है कि address में कितने bits हैं। संबंध exponential है, और यह इस module का सबसे ज़रूरी अंक है: n select lines के साथ एक DEMUX 2^n outputs चलाता है। हर output selects के एक अलग binary code से नामित होता है, और n bits ठीक 2^n codes बनाते हैं।',
        'मुख्य नतीजा है doubling। जब भी आप एक और select line जोड़ते हैं तो आप reachable outputs की गिनती दुगनी कर देते हैं, क्योंकि हर नया bit हर मौजूद address को दो में बाँट देता है - एक 0 रूप और एक 1 रूप। address का एक और तार, गली में दुगने घर।',
        'चलिए ठोस अंकों के साथ सीढ़ी चढ़ें। 1 select line से 2^1 = 2 outputs, एक 1-to-2 demux। 2 select lines से 2^2 = 4 outputs, एक 1-to-4। 3 select lines से 2^3 = 8 outputs, एक 1-to-8। 4 select lines से 2^4 = 16 outputs, एक 1-to-16। pattern 2, 4, 8, 16 बस two की powers है।',
        'एक हल किया उदाहरण इसे पक्का करता है: 3-bit address वाला courier 2^3 = 8 घर पहुँच सकता है, तो 3 select lines वाला DEMUX एक 1-to-8 demux है जिसमें आठ output lines Y0 से Y7 तक हैं। तीन address bits, आठ संभव दरवाज़े।',
        'आप नियम को उल्टा भी चला सकते हैं। अगर आप जानते हैं कि आपको M output lines चाहिए, तो आपको देनी होने वाली select lines की गिनती है n = log2(M)। उदाहरण के लिए, 16 destinations को log2(16) = 4 select lines चाहिए, और 8 destinations को log2(8) = 3। नीचे panel से select lines जोड़िए और देखिए हर बार घरों की गिनती कैसे दुगनी होती है।',
      ],
      transcriptEN: 'How many houses can the courier reach? That is set entirely by how many bits the address has, and the relationship is exponential: with n select lines a demux drives two-to-the-n outputs, because n bits make exactly that many distinct codes. The consequence is doubling - each extra select line doubles the reachable outputs, since a new bit splits every existing address into a zero version and a one version. Walk the ladder: one select gives two outputs, two selects give four, three give eight, four give sixteen - the powers of two. Worked example: a three-bit address reaches eight houses, so three select lines make a one-to-eight demux with outputs Y0 through Y7. Backwards: to reach M outputs you need log-base-two of M select lines, so sixteen destinations need four selects.',
      transcriptHI: 'courier कितने घर पहुँच सकता है? यह पूरी तरह इस पर है कि address में कितने bits हैं, और संबंध exponential है: n select lines के साथ demux two-to-the-n outputs चलाता है, क्योंकि n bits ठीक उतने अलग codes बनाते हैं। नतीजा है doubling - हर अतिरिक्त select line reachable outputs को दुगना करती है, क्योंकि एक नया bit हर मौजूद address को एक zero रूप और एक one रूप में बाँट देता है। सीढ़ी चढ़िए: one select से two outputs, two selects से four, three से eight, four से sixteen - two की powers। उदाहरण: तीन-bit address आठ घर पहुँचता है, तो तीन select lines एक one-to-eight demux बनाती हैं जिसमें outputs Y0 से Y7 तक। उल्टा: M outputs पहुँचने को log-base-two of M select lines चाहिए, तो sixteen destinations को four selects चाहिए।',
      visualNote: 'A table mapping n -> 2^n: (1->2), (2->4), (3->8), (4->16). A DemuxViz set to outputs=8 lets the student feel the 3-select case.',
    },
    {
      id: 'S04_Routing',
      label: 'The Routing Equation',
      kind: 'theory',
      subtitle: 'Yi = D . (minterm_i of the selects) - one minterm high at a time.',
      theoryEN: [
        'Now the heart of the math: the routing equation. Each output of a DEMUX equals the data input D ANDed with one unique minterm of the select lines. In symbols, Yi = D . (minterm_i of the selects), where the dot means AND and the apostrophe will mean NOT. The minterm acts like a gate that opens for exactly one address.',
        'A minterm is the AND of every select line, each written in either its true form (like S1) or its complemented form (like S1\'). With two selects S1 and S0 there are four minterms: S1\'.S0\', S1\'.S0, S1.S0\', and S1.S0. Each minterm equals 1 for one and only one combination of the selects.',
        'This is the property that makes a DEMUX work cleanly: because only one minterm is high for any select code, only one output can be active at a time. The output Yi is high exactly when its own minterm is high AND the data D is 1, so the data lands on a single line and the others sit at 0.',
        'Notice what the selected output actually does. When its minterm is 1, Yi = D . 1 = D, so the output simply copies the data input - if D is 1 the output is 1, if D is 0 the output is 0. For every other output the minterm is 0, so Yi = D . 0 = 0 regardless of D.',
        'In courier language the minterm is the act of reading the address and recognising "this is my house". The general form Yi = D . (minterm_i), where i is the decimal value of the select code, says: deliver the package D to the one house whose address matches. That single matching house copies the parcel; all the others stay empty. This is exactly why a demux is also called a data distributor.',
      ],
      theoryHI: [
        'अब गणित का दिल: routing equation। एक DEMUX का हर output बराबर है data input D को select lines के एक अनोखे minterm से AND करना। प्रतीकों में, Yi = D . (selects का minterm_i), जहाँ dot का मतलब AND और apostrophe का मतलब NOT होगा। minterm एक ऐसे gate की तरह काम करता है जो ठीक एक address के लिए खुलता है।',
        'minterm हर select line का AND है, हर एक या तो अपने true रूप (जैसे S1) में या complemented रूप (जैसे S1\') में। दो selects S1 और S0 के साथ चार minterms हैं: S1\'.S0\', S1\'.S0, S1.S0\', और S1.S0। हर minterm selects के एक और सिर्फ़ एक combination के लिए 1 होता है।',
        'यही वह property है जो DEMUX को साफ़-साफ़ काम करवाती है: चूँकि किसी भी select code के लिए सिर्फ़ एक minterm high होता है, एक समय में सिर्फ़ एक output active हो सकता है। output Yi ठीक तब high होता है जब उसका अपना minterm high हो AND data D 1 हो, तो data एक अकेली line पर पहुँचता है और बाक़ी 0 पर बैठते हैं।',
        'ग़ौर कीजिए चुना हुआ output असल में करता क्या है। जब उसका minterm 1 हो, Yi = D . 1 = D, तो output बस data input की नक़ल करता है - अगर D 1 है तो output 1, अगर D 0 है तो output 0। हर दूसरे output के लिए minterm 0 है, तो Yi = D . 0 = 0, चाहे D कुछ भी हो।',
        'courier भाषा में minterm वह काम है जब address पढ़कर पहचाना जाए "यह मेरा घर है"। सामान्य रूप Yi = D . (minterm_i), जहाँ i select code का decimal मान है, कहता है: package D को उस एक घर तक पहुँचाओ जिसका address मिलता है। वह एक मिलता घर parcel की नक़ल करता है; बाक़ी सब ख़ाली रहते हैं। इसीलिए demux को data distributor भी कहते हैं।',
      ],
      transcriptEN: 'Now the heart of the math: the routing equation. Each output equals the data input D ANDed with one unique minterm of the selects: Yi equals D times minterm-i. A minterm is the AND of every select line in either true or complemented form. With two selects there are four minterms, and each is one for exactly one select combination. That is the key property: only one minterm is high for any code, so only one output is active at a time. When an output minterm is one, Yi equals D times one, which is D - the output copies the data. For every other output the minterm is zero, so Yi is zero regardless of D. In courier terms the minterm is recognising "this is my house"; the matching house copies the parcel and the rest stay empty. That is why a demux is a data distributor.',
      transcriptHI: 'अब गणित का दिल: routing equation। हर output बराबर है data input D को selects के एक अनोखे minterm से AND करना: Yi बराबर D times minterm-i। minterm हर select line का true या complemented रूप में AND है। दो selects के साथ चार minterms हैं, और हर एक ठीक एक select combination के लिए one है। यही मुख्य property है: किसी भी code के लिए सिर्फ़ एक minterm high होता है, तो एक समय सिर्फ़ एक output active होता है। जब किसी output का minterm one हो, Yi बराबर D times one, यानी D - output data की नक़ल करता है। हर दूसरे output के लिए minterm zero है, तो Yi zero है, चाहे D कुछ भी हो। courier भाषा में minterm यह पहचानना है "यह मेरा घर है"; मिलता घर parcel की नक़ल करता है और बाक़ी ख़ाली रहते हैं। इसीलिए demux एक data distributor है।',
      visualNote: 'A DecoderViz-style panel listing each output beside its minterm, with arrows from the select bits to the matching AND term.',
    },
    {
      id: 'S05_OneToTwo',
      label: '1-to-2 DEMUX (Gate Level)',
      kind: 'theory',
      subtitle: 'Y0 = S\'.D and Y1 = S.D - one inverter and two AND gates.',
      theoryEN: [
        'Let us build the smallest possible demux from real gates so the equations stop being abstract. The 1-to-2 DEMUX has one data input D, one select line S, and two outputs Y0 and Y1. With a single select line there are two minterms, S\' and S, so there are two outputs - one per minterm.',
        'The two routing equations are Y0 = S\'.D and Y1 = S.D. Read them plainly: Y0 carries the data only when S is 0 (because S\' is then 1), and Y1 carries the data only when S is 1. The select line is the address bit that chooses between the two houses, the upper one (Y0) and the lower one (Y1).',
        'Trace both settings. When S = 0: S\' = 1, so Y0 = 1.D = D and Y1 = 0.D = 0 - the package goes to the upper house. When S = 1: S\' = 0, so Y0 = 0.D = 0 and Y1 = 1.D = D - the package goes to the lower house. The data D is the same in both cases; only its destination changes.',
        'A worked example with live numbers: take D = 1 and S = 1. Then Y0 = NOT(1) . 1 = 0 . 1 = 0, and Y1 = 1 . 1 = 1. So the data routes to Y1 and Y0 stays at 0, exactly as the equations promise.',
        'The hardware is tiny. You need one NOT gate to produce S\' from S, and two 2-input AND gates: one computing D . S\' for Y0, and one computing D . S for Y1. That is the whole circuit - one inverter and two AND gates. The two live AND gates below compute Y0 and Y1 for whatever D and S you set, so you can prove every case yourself.',
      ],
      theoryHI: [
        'चलिए असली gates से सबसे छोटा संभव demux बनाएँ ताकि equations अमूर्त न रहें। 1-to-2 DEMUX में एक data input D, एक select line S, और दो outputs Y0 और Y1 होते हैं। एक अकेली select line के साथ दो minterms हैं, S\' और S, तो दो outputs हैं - हर minterm के लिए एक।',
        'दोनों routing equations हैं Y0 = S\'.D और Y1 = S.D। इन्हें सीधे पढ़िए: Y0 data तभी ले जाता है जब S 0 हो (क्योंकि तब S\' 1 होता है), और Y1 data तभी ले जाता है जब S 1 हो। select line वह address bit है जो दो घरों के बीच चुनती है, ऊपरी (Y0) और निचला (Y1)।',
        'दोनों settings trace कीजिए। जब S = 0: S\' = 1, तो Y0 = 1.D = D और Y1 = 0.D = 0 - package ऊपरी घर जाता है। जब S = 1: S\' = 0, तो Y0 = 0.D = 0 और Y1 = 1.D = D - package निचले घर जाता है। D दोनों हाल में वही है; सिर्फ़ उसका destination बदलता है।',
        'live अंकों के साथ एक हल किया उदाहरण: D = 1 और S = 1 लीजिए। तब Y0 = NOT(1) . 1 = 0 . 1 = 0, और Y1 = 1 . 1 = 1। तो data Y1 पर पहुँचता है और Y0 0 रहता है, ठीक जैसा equations वादा करते हैं।',
        'hardware बहुत छोटा है। आपको S से S\' बनाने को एक NOT gate चाहिए, और दो 2-input AND gates: एक D . S\' निकालता है Y0 के लिए, और एक D . S निकालता है Y1 के लिए। यही पूरी circuit है - एक inverter और दो AND gates। नीचे दो live AND gates आपके सेट किए किसी भी D और S के लिए Y0 और Y1 निकालते हैं, तो आप हर case ख़ुद साबित कर सकते हैं।',
      ],
      transcriptEN: 'Let us build the smallest demux from real gates. The one-to-two demux has one data input D, one select line S, and two outputs Y0 and Y1. One select gives two minterms, S-prime and S, hence two outputs. The equations are Y0 equals S-prime times D, and Y1 equals S times D. So Y0 carries the data only when S is zero, and Y1 only when S is one. Trace it: with S zero, Y0 equals D and Y1 is zero - the package goes up; with S one, Y0 is zero and Y1 equals D - the package goes down. Worked example: D equals one, S equals one gives Y0 equals not-one and-one equals zero, and Y1 equals one and-one equals one, so the data routes to Y1. The hardware is one inverter to make S-prime and two AND gates, D-and-S-prime for Y0 and D-and-S for Y1.',
      transcriptHI: 'चलिए असली gates से सबसे छोटा demux बनाएँ। one-to-two demux में एक data input D, एक select line S, और दो outputs Y0 और Y1 होते हैं। एक select से दो minterms, S-prime और S, तो दो outputs। equations हैं Y0 बराबर S-prime times D, और Y1 बराबर S times D। तो Y0 data तभी ले जाता है जब S zero हो, और Y1 तभी जब S one हो। trace कीजिए: S zero पर, Y0 बराबर D और Y1 zero - package ऊपर जाता है; S one पर, Y0 zero और Y1 बराबर D - package नीचे जाता है। उदाहरण: D बराबर one, S बराबर one से Y0 बराबर not-one and-one बराबर zero, और Y1 बराबर one and-one बराबर one, तो data Y1 पर पहुँचता है। hardware है S-prime बनाने को एक inverter और दो AND gates, Y0 के लिए D-and-S-prime और Y1 के लिए D-and-S।',
      visualNote: 'Two live AND gates: D.S\' -> Y0 and D.S -> Y1, with a NOT gate making S\'. The active output glows for the current D and S.',
    },
    {
      id: 'S06_OneToFour',
      label: '1-to-4 DEMUX (Build It)',
      kind: 'theory',
      subtitle: 'Four 3-input ANDs and two inverters: Y0..Y3 each gated by a select minterm.',
      theoryEN: [
        'Now scale up to the 1-to-4 DEMUX, the circuit you will build for real later in this module. Its inputs are the data D plus two select lines S1 (the MSB, more significant bit) and S0 (the LSB, less significant bit). Its outputs are four lines Y0, Y1, Y2 and Y3, one for each of the four select codes 00, 01, 10 and 11.',
        'The four routing equations follow the minterm rule exactly: Y0 = S1\'.S0\'.D, Y1 = S1\'.S0.D, Y2 = S1.S0\'.D, and Y3 = S1.S0.D. Each output gets the data D ANDed with the one minterm of S1 and S0 that names it, so for any address only a single output can carry D.',
        'Reading the select code as a binary number tells you which output is chosen. The code S1S0 is the decimal index of the destination: 00 picks Y0, 01 picks Y1, 10 picks Y2, and 11 picks Y3. So the courier just converts the two-bit address to a house number and walks there.',
        'A worked example to lock it in: set D = 1, S1 = 1, S0 = 0. The select code is 10, which is decimal 2, so the chosen output is Y2. Check the equation: Y2 = S1.S0\'.D = 1 . NOT(0) . 1 = 1 . 1 . 1 = 1, while Y0, Y1 and Y3 all evaluate to 0. The data is routed to Y2 just as the index says.',
        'The build cost is small and worth memorising for the exam: two inverters (to make S1\' and S0\') and four 3-input AND gates, one per output line, each fed by D and the correct pair of true or complemented selects. Toggle D and the two selects in the live demux below and watch exactly one output carry the data while the truth table beside it confirms every minterm.',
      ],
      theoryHI: [
        'अब 1-to-4 DEMUX तक बढ़िए, वह circuit जिसे आप इस module में आगे असल में बनाएँगे। इसके inputs हैं data D और दो select lines S1 (MSB, अधिक महत्व वाला bit) और S0 (LSB, कम महत्व वाला bit)। इसके outputs हैं चार lines Y0, Y1, Y2 और Y3, चार select codes 00, 01, 10 और 11 में से हर एक के लिए एक।',
        'चारों routing equations minterm नियम का ठीक पालन करती हैं: Y0 = S1\'.S0\'.D, Y1 = S1\'.S0.D, Y2 = S1.S0\'.D, और Y3 = S1.S0.D। हर output को data D, S1 और S0 के उस एक minterm से AND मिलता है जो उसे नामित करता है, तो किसी भी address के लिए सिर्फ़ एक output D ले जा सकता है।',
        'select code को binary संख्या की तरह पढ़ना बताता है कौन सा output चुना गया। code S1S0 destination का decimal index है: 00 चुनता है Y0, 01 चुनता है Y1, 10 चुनता है Y2, और 11 चुनता है Y3। तो courier बस दो-bit address को घर नंबर में बदलकर वहाँ चला जाता है।',
        'इसे पक्का करने को एक हल किया उदाहरण: D = 1, S1 = 1, S0 = 0 सेट कीजिए। select code 10 है, जो decimal 2 है, तो चुना output Y2 है। equation जाँचिए: Y2 = S1.S0\'.D = 1 . NOT(0) . 1 = 1 . 1 . 1 = 1, जबकि Y0, Y1 और Y3 सब 0 निकलते हैं। data Y2 पर पहुँचता है, ठीक जैसा index कहता है।',
        'build क़ीमत छोटी है और exam के लिए याद रखने लायक़: दो inverters (S1\' और S0\' बनाने को) और चार 3-input AND gates, हर output line के लिए एक, हर एक D और सही true या complemented selects की जोड़ी से भरा। नीचे live demux में D और दोनों selects toggle कीजिए और देखिए ठीक एक output data ले जाता है जबकि बग़ल की truth table हर minterm की पुष्टि करती है।',
      ],
      transcriptEN: 'Now scale up to the one-to-four demux, the circuit you will build for real. Its inputs are data D plus two selects, S1 the most significant bit and S0 the least. Its outputs are Y0, Y1, Y2, Y3, one per select code. The four equations follow the minterm rule: Y0 equals S1-prime S0-prime D, Y1 equals S1-prime S0 D, Y2 equals S1 S0-prime D, and Y3 equals S1 S0 D. The code S1S0 read as binary is the decimal index of the chosen output: zero-zero picks Y0, one-one picks Y3. Worked example: D one, S1 one, S0 zero is code one-zero, decimal two, so Y2 is chosen; check Y2 equals S1 times not-S0 times D equals one, and the others are zero. The build is two inverters for S1-prime and S0-prime, plus four three-input AND gates, one per output.',
      transcriptHI: 'अब one-to-four demux तक बढ़िए, वह circuit जिसे आप असल में बनाएँगे। इसके inputs हैं data D और दो selects, S1 सबसे महत्व वाला bit और S0 सबसे कम। इसके outputs हैं Y0, Y1, Y2, Y3, हर select code के लिए एक। चारों equations minterm नियम का पालन करती हैं: Y0 बराबर S1-prime S0-prime D, Y1 बराबर S1-prime S0 D, Y2 बराबर S1 S0-prime D, और Y3 बराबर S1 S0 D। code S1S0 binary की तरह चुने output का decimal index है: zero-zero चुनता है Y0, one-one चुनता है Y3। उदाहरण: D one, S1 one, S0 zero यानी code one-zero, decimal two, तो Y2 चुना; जाँचिए Y2 बराबर S1 times not-S0 times D बराबर one, और बाक़ी zero। build है S1-prime और S0-prime के लिए दो inverters, और चार three-input AND gates, हर output के लिए एक।',
      visualNote: 'DemuxViz (outputs=4) beside a TruthTable listing S1, S0 and the four Y columns with the active output highlighted; the live Y2 example is reproduced from the equations.',
    },
    {
      id: 'S07_TruthView',
      label: 'Truth Table View',
      kind: 'theory',
      subtitle: 'Exactly one output equals D in every row - the one-hot property.',
      theoryEN: [
        'A truth table makes the routing rule completely visible. For a DEMUX we list, for each select combination, which single output equals the data D and confirm that all the rest are 0. Reading the table top to bottom is the same as walking the courier through every possible address.',
        'For the 1-to-4 demux the four rows are simple. Select code S1S0 = 00 gives Y0 = D and the rest 0; 01 gives Y1 = D; 10 gives Y2 = D; and 11 gives Y3 = D. In every row exactly one output column holds D and the other three hold 0, so the data appears once and only once.',
        'This "exactly one active output per row" behaviour is called the one-hot property: of all the output lines, precisely one is "hot" (following D) at any time and every other line is cold (at 0). The one-hot guarantee is what makes a demux perfect for enabling exactly one device while keeping all the others silent.',
        'There is a neat special case. If you hold the data input D at a constant 1, then in every row the single active output becomes a hard 1 instead of merely copying a varying D. In that situation the DEMUX stops distributing data and instead lights up the one addressed line, which is precisely the behaviour of a decoder - a hint we will make exact on the next page.',
        'Most importantly, the truth table is not a separate fact to memorise: it directly confirms each Yi minterm equation we derived. Row 10 has Y2 = D because Y2 = S1.S0\'.D is the only minterm true at that address. Read the table and the equations together and they say the same thing in two languages.',
      ],
      theoryHI: [
        'एक truth table routing नियम को पूरी तरह दिखा देती है। एक DEMUX के लिए हम हर select combination के लिए सूचीबद्ध करते हैं कि कौन सा अकेला output data D के बराबर है और पुष्टि करते हैं कि बाक़ी सब 0 हैं। table को ऊपर से नीचे पढ़ना वही है जो courier को हर संभव address से गुज़ारना।',
        '1-to-4 demux के लिए चारों rows आसान हैं। select code S1S0 = 00 देता है Y0 = D और बाक़ी 0; 01 देता है Y1 = D; 10 देता है Y2 = D; और 11 देता है Y3 = D। हर row में ठीक एक output column D रखता है और बाक़ी तीन 0 रखते हैं, तो data एक बार और सिर्फ़ एक बार दिखता है।',
        'यह "हर row में ठीक एक active output" व्यवहार one-hot property कहलाता है: सभी output lines में से ठीक एक किसी भी समय "hot" (D का अनुसरण करता) होती है और हर दूसरी line ठंडी (0 पर) होती है। one-hot गारंटी ही demux को ठीक एक device enable करने के लिए बढ़िया बनाती है जबकि बाक़ी सब चुप रहते हैं।',
        'एक सुंदर ख़ास case है। अगर आप data input D को स्थिर 1 पर रखें, तो हर row में वह अकेला active output बदलते D की नक़ल करने के बजाय एक पक्का 1 बन जाता है। उस हाल में DEMUX data बाँटना बंद कर देता है और बजाय इसके वह एक addressed line जला देता है, जो ठीक एक decoder का व्यवहार है - एक संकेत जिसे हम अगले पन्ने पर सटीक बनाएँगे।',
        'सबसे ज़रूरी, truth table याद करने का कोई अलग तथ्य नहीं है: यह सीधे हर Yi minterm equation की पुष्टि करती है जो हमने निकाली। row 10 में Y2 = D है क्योंकि Y2 = S1.S0\'.D उस address पर एकमात्र सच्चा minterm है। table और equations साथ पढ़िए और वे एक ही बात दो भाषाओं में कहती हैं।',
      ],
      transcriptEN: 'A truth table makes the rule visible. For each select combination we list which single output equals the data D and confirm the rest are zero. For the one-to-four demux: code zero-zero gives Y0 equals D, zero-one gives Y1, one-zero gives Y2, one-one gives Y3, and in every row exactly one output holds D while the other three hold zero. That is the one-hot property: precisely one line is hot at a time. A neat special case: hold D at one and the single active output becomes a hard one in every row - that is exactly a decoder, which we make exact next. And the table is not separate from the algebra: row one-zero has Y2 equals D because Y2 equals S1 not-S0 D is the only minterm true there.',
      transcriptHI: 'एक truth table नियम को दिखा देती है। हर select combination के लिए हम सूचीबद्ध करते हैं कौन सा अकेला output data D के बराबर है और पुष्टि करते हैं बाक़ी zero हैं। one-to-four demux के लिए: code zero-zero देता है Y0 बराबर D, zero-one देता है Y1, one-zero देता है Y2, one-one देता है Y3, और हर row में ठीक एक output D रखता है जबकि बाक़ी तीन zero। यही one-hot property है: एक समय ठीक एक line hot होती है। एक सुंदर ख़ास case: D को one पर रखिए और वह अकेला active output हर row में एक पक्का one बन जाता है - यह ठीक एक decoder है, जिसे हम अगले बनाएँगे। और table algebra से अलग नहीं है: row one-zero में Y2 बराबर D है क्योंकि Y2 बराबर S1 not-S0 D वहाँ एकमात्र सच्चा minterm है।',
      visualNote: 'A computed TruthTable: columns S1, S0, Y3, Y2, Y1, Y0, each row showing a single D in one output column and 0 elsewhere; the active row highlighted.',
    },
    {
      id: 'S08_VsDecoder',
      label: 'DEMUX vs Decoder vs MUX',
      kind: 'theory',
      subtitle: 'A decoder with its enable used as data IS a demux; the MUX is its inverse.',
      theoryEN: [
        'Here is one of the most useful facts in combinational design, and it falls straight out of the routing equation. A decoder with its ENABLE line driven as the data input IS a demultiplexer. They are the same silicon - the same inverters and AND gates - just with one pin given a different name.',
        'Recall how a decoder works. An n-to-2^n decoder has an enable input E, and each of its outputs Di equals E ANDed with a select minterm: Di = E . (minterm_i). The enable gates all the outputs at once - when E is 0 every output is 0, and when E is 1 the one addressed minterm goes high. Now feed your data D into that enable pin: substitute E = D and each output becomes Di = D . (minterm_i), which is exactly the demux equation Yi = D . (minterm_i). Same circuit, different naming.',
        'There is a clean degenerate case in the other direction too. If you hold the demux data input D at a constant 1, then every active output is D . minterm = 1 . minterm = minterm, so the demux now lights the addressed line high - it has become a plain n-to-2^n decoder. So "decoder with D=1" and "decoder with enable used as data" are two views of the same identity.',
        'Now contrast the demux with its true inverse, the multiplexer. A MUX is a many-to-1 selector: it takes 2^n inputs and the same select lines pick one of them to drive a single output Y. A DEMUX is the mirror: a 1-to-many distributor that takes one input D and the selects fan it out to 2^n outputs. One funnels in, the other fans out, and they share identical select logic.',
        'This inverse relationship is exactly why a MUX and a DEMUX are used as a pair. On a shared communication channel a MUX at the sending end packs many logical channels onto one physical wire, and a DEMUX at the receiving end unpacks them back to the original destinations - the courier picking up many parcels into one truck, then handing them back out one house at a time.',
      ],
      theoryHI: [
        'यहाँ combinational design के सबसे उपयोगी तथ्यों में से एक है, और यह सीधे routing equation से निकलता है। जिस decoder का ENABLE line data input की तरह चलाया जाए वही एक demultiplexer है। ये एक ही silicon हैं - वही inverters और AND gates - बस एक pin को अलग नाम दिया गया।',
        'याद कीजिए decoder कैसे काम करता है। एक n-to-2^n decoder में एक enable input E होता है, और इसके हर output Di बराबर है E को एक select minterm से AND करना: Di = E . (minterm_i)। enable एक साथ सारे outputs को gate करता है - जब E 0 हो हर output 0, और जब E 1 हो वह एक addressed minterm high होता है। अब अपना data D उस enable pin में भरिए: E = D रखिए और हर output बन जाता है Di = D . (minterm_i), जो ठीक demux equation Yi = D . (minterm_i) है। वही circuit, अलग नाम।',
        'दूसरी दिशा में भी एक साफ़ degenerate case है। अगर आप demux data input D को स्थिर 1 पर रखें, तो हर active output है D . minterm = 1 . minterm = minterm, तो demux अब addressed line को high जलाता है - यह एक सादा n-to-2^n decoder बन गया। तो "decoder with D=1" और "decoder with enable used as data" एक ही पहचान के दो नज़रिए हैं।',
        'अब demux की तुलना उसके असली inverse, multiplexer से कीजिए। एक MUX एक many-to-1 selector है: यह 2^n inputs लेता है और वही select lines उनमें से एक चुनकर एक अकेला output Y चलाती हैं। एक DEMUX उल्टा है: एक 1-to-many distributor जो एक input D लेता है और selects उसे 2^n outputs में फैलाती हैं। एक अंदर समेटता है, दूसरा बाहर फैलाता है, और दोनों एक जैसी select logic बाँटते हैं।',
        'यही inverse संबंध है जिसके कारण MUX और DEMUX एक जोड़ी की तरह वापरे जाते हैं। एक साझा communication channel पर भेजने वाले छोर पर MUX कई logical channels को एक physical तार पर पैक करता है, और पाने वाले छोर पर DEMUX उन्हें वापस मूल destinations में unpack करता है - courier कई parcels एक truck में उठाता है, फिर एक-एक घर बाँटता है।',
      ],
      transcriptEN: 'One of the most useful facts in combinational design: a decoder with its enable line driven as the data input IS a demux. They are the same silicon, just one pin renamed. A decoder output is Di equals E times minterm-i; the enable gates all outputs, so E zero forces everything low and E one lights the addressed minterm. Feed your data into the enable - set E equals D - and each output becomes D times minterm-i, exactly the demux equation. The reverse case: hold the demux D at one and each active output becomes the bare minterm, so the demux is now a plain decoder. And the demux contrasts with its inverse, the mux: a mux is many-to-one, the selects pick one of many inputs to drive one output; a demux is one-to-many, the selects fan one input out. They share select logic and pair up on a shared channel - mux packs, demux unpacks.',
      transcriptHI: 'combinational design के सबसे उपयोगी तथ्यों में से एक: जिस decoder का enable line data input की तरह चलाया जाए वही एक demux है। ये एक ही silicon हैं, बस एक pin का नाम बदला। decoder output है Di बराबर E times minterm-i; enable सारे outputs को gate करता है, तो E zero सब को low करता है और E one addressed minterm जलाता है। अपना data enable में भरिए - E बराबर D रखिए - और हर output बन जाता है D times minterm-i, ठीक demux equation। उल्टा case: demux का D one पर रखिए और हर active output नंगा minterm बन जाता है, तो demux अब एक सादा decoder है। और demux की उल्टी mux से तुलना: mux many-to-one है, selects कई inputs में से एक चुनकर एक output चलाती हैं; demux one-to-many है, selects एक input को फैलाती हैं। दोनों select logic बाँटते हैं और एक साझा channel पर जोड़ी बनाते हैं - mux पैक करता है, demux unpack करता है।',
      visualNote: 'Side by side: a MUX symbol (many inputs, one output) mirrored against a DEMUX (one input, many outputs); plus a decoder box whose Enable pin is relabelled D.',
    },
    {
      id: 'S09_Proofs',
      label: 'Proofs & Derivations',
      kind: 'theory',
      subtitle: 'Step through the equations, the decoder equivalence, and why NAND suffices.',
      theoryEN: [
        'Now we make every claim airtight by deriving it from scratch. The walkthrough below steps through the full proofs so you can reproduce each one on an exam, not just quote the result. Take them one step at a time and check each line against the courier picture.',
        'The first derivation builds the four 1-to-4 demux equations straight from the truth table, treating each output as D gated by the minterm that selects it. It also checks a conservation property: Y0 + Y1 + Y2 + Y3 = D, because the four minterms are exhaustive and mutually exclusive, so all of D goes to exactly one line and nothing is lost.',
        'The second derivation proves the decoder-plus-enable equivalence in full: a 2-to-4 decoder with enable E gives Di = E.minterm_i, and substituting E = D yields Yi = D.minterm_i, term for term identical to the demux. The third shows the inverse 4-to-1 MUX equation Y = S1\'.S0\'.I0 + S1\'.S0.I1 + S1.S0\'.I2 + S1.S0.I3 so you can see the same minterms used as a fan-in instead of a fan-out.',
        'The fourth derivation proves that the whole demux can be built from NAND gates alone: NOT = NAND(a,a), AND = NAND then NOT, and OR = NAND of inverted inputs, so the inverters and AND gates of a demux map directly onto a single NAND-only fabric. The fifth, Shannon expansion, shows F = x\'.F0 + x.F1 and why a MUX/DEMUX pair can implement any function.',
        'The walkthrough closes with two companion code-routing derivations from the spec: binary-to-Gray and Gray-to-binary conversion (thin XOR networks), and a 4-to-2 priority encoder using don\'t-cares. These are not the demux itself but they share its minterm-and-routing DNA, and seeing them rounds out the family of select-and-route logic.',
      ],
      theoryHI: [
        'अब हम हर दावे को शुरू से derive करके पक्का करते हैं। नीचे का walkthrough पूरे proofs से गुज़रता है ताकि आप exam में हर एक को दोहरा सकें, सिर्फ़ नतीजा न बोलें। इन्हें एक-एक कदम लीजिए और हर line को courier तस्वीर के सामने जाँचिए।',
        'पहली derivation चारों 1-to-4 demux equations सीधे truth table से बनाती है, हर output को उस minterm से gate हुआ D मानकर जो उसे चुनता है। यह एक conservation property भी जाँचती है: Y0 + Y1 + Y2 + Y3 = D, क्योंकि चारों minterms exhaustive और परस्पर अनन्य हैं, तो पूरा D ठीक एक line पर जाता है और कुछ नहीं खोता।',
        'दूसरी derivation decoder-plus-enable समानता पूरी साबित करती है: enable E वाला 2-to-4 decoder देता है Di = E.minterm_i, और E = D रखने से निकलता है Yi = D.minterm_i, term-दर-term demux जैसा। तीसरी उल्टा 4-to-1 MUX equation Y = S1\'.S0\'.I0 + S1\'.S0.I1 + S1.S0\'.I2 + S1.S0.I3 दिखाती है ताकि आप वही minterms fan-out के बजाय fan-in की तरह वापरते देखें।',
        'चौथी derivation साबित करती है कि पूरा demux अकेले NAND gates से बन सकता है: NOT = NAND(a,a), AND = NAND फिर NOT, और OR = inverted inputs का NAND, तो demux के inverters और AND gates सीधे एक अकेले NAND-only fabric पर map होते हैं। पाँचवीं, Shannon expansion, दिखाती है F = x\'.F0 + x.F1 और क्यों एक MUX/DEMUX जोड़ी कोई भी function लागू कर सकती है।',
        'walkthrough spec की दो साथी code-routing derivations से बंद होता है: binary-to-Gray और Gray-to-binary conversion (पतले XOR networks), और don\'t-cares वापरता एक 4-to-2 priority encoder। ये ख़ुद demux नहीं हैं पर इसका minterm-and-routing DNA बाँटते हैं, और इन्हें देखना select-and-route logic के परिवार को पूरा करता है।',
      ],
      transcriptEN: 'Now we make every claim airtight by deriving it. The walkthrough steps through the full proofs so you can reproduce each on an exam. First, the four one-to-four demux equations straight from the truth table, plus the conservation check that Y0 plus Y1 plus Y2 plus Y3 equals D. Second, the decoder-plus-enable equivalence: a two-to-four decoder gives Di equals E times minterm-i, and setting E equals D gives the demux. Third, the inverse four-to-one mux equation, the same minterms used as a fan-in. Fourth, that the demux is buildable from NAND alone: NOT is NAND a a, AND is NAND then NOT, OR is NAND of inverted inputs. Fifth, Shannon expansion, F equals x-prime F0 plus x F1. And two companions: binary-Gray conversion and a four-to-two priority encoder with don-t-cares.',
      transcriptHI: 'अब हम हर दावे को derive करके पक्का करते हैं। walkthrough पूरे proofs से गुज़रता है ताकि आप exam में हर एक दोहरा सकें। पहला, चारों one-to-four demux equations सीधे truth table से, और conservation जाँच कि Y0 plus Y1 plus Y2 plus Y3 बराबर D। दूसरा, decoder-plus-enable समानता: एक two-to-four decoder देता है Di बराबर E times minterm-i, और E बराबर D रखने से demux मिलता है। तीसरा, उल्टा four-to-one mux equation, वही minterms fan-in की तरह। चौथा, कि demux अकेले NAND से बन सकता है: NOT है NAND a a, AND है NAND फिर NOT, OR है inverted inputs का NAND। पाँचवाँ, Shannon expansion, F बराबर x-prime F0 plus x F1। और दो साथी: binary-Gray conversion और don-t-cares वाला four-to-two priority encoder।',
      visualNote: 'A StepThrough walking the spec derivations: the four equations, decoder equivalence, the inverse MUX, NAND universality, Shannon expansion, and the Gray / priority-encoder companions.',
    },
    {
      id: 'S10_Build',
      label: 'Build The DEMUX For Real',
      kind: 'theory',
      subtitle: 'Open the workbench and wire a 1-to-4 demux from inverters and AND gates yourself.',
      theoryEN: [
        'You have seen the equations, the gate-level layout, the truth table and the proofs. Now build the thing yourself on the live workbench, because a circuit only truly becomes yours once you have wired it and watched real signals route through it.',
        'The guided build is the standard 1-to-4 demultiplexer, the exact circuit from the build-it page. You will place two inverters to make S1\' and S0\', then four 3-input AND gates, and wire each AND gate to D plus the correct pair of true or complemented selects so that A0 makes Y0, A1 makes Y1, A2 makes Y2 and A3 makes Y3.',
        'As you build, keep the courier in mind: D is the package fanning out to all four AND gates, and the select pair is the address that opens exactly one gate. Drive D high, set the selects to 10, and you should see the package travel only to Y2 while the other three outputs sit at 0 - the same one-hot routing you have proven on paper.',
        'Prove every row of the truth table on the real hardware: sweep the two select lines through 00, 01, 10 and 11 with D = 1 and confirm that the live output index always matches the binary address. Then flip D to 0 and watch every output drop to 0, since an empty package delivers nothing. Click below to open the workbench and start wiring.',
      ],
      theoryHI: [
        'आपने equations, gate-level layout, truth table और proofs देख लिए। अब चीज़ ख़ुद live workbench पर बनाइए, क्योंकि एक circuit सचमुच आपकी तभी बनती है जब आप उसे wire करके असली signals को उसमें route होते देख लें।',
        'guided build standard 1-to-4 demultiplexer है, build-it पन्ने वाली ठीक वही circuit। आप दो inverters रखकर S1\' और S0\' बनाएँगे, फिर चार 3-input AND gates, और हर AND gate को D तथा सही true या complemented selects की जोड़ी से wire करेंगे ताकि A0 बनाए Y0, A1 बनाए Y1, A2 बनाए Y2 और A3 बनाए Y3।',
        'बनाते समय courier को मन में रखिए: D वह package है जो चारों AND gates में फैलता है, और select जोड़ी वह address है जो ठीक एक gate खोलती है। D को high करिए, selects को 10 सेट करिए, और आपको package सिर्फ़ Y2 तक जाता दिखना चाहिए जबकि बाक़ी तीन outputs 0 पर बैठे - वही one-hot routing जो आपने काग़ज़ पर साबित की।',
        'truth table की हर row असली hardware पर साबित कीजिए: D = 1 के साथ दोनों select lines को 00, 01, 10 और 11 से घुमाइए और पुष्टि कीजिए कि live output index हमेशा binary address से मिलता है। फिर D को 0 करिए और देखिए हर output 0 पर गिर जाता है, क्योंकि एक ख़ाली package कुछ नहीं पहुँचाता। नीचे click करके workbench खोलिए और wiring शुरू कीजिए।',
      ],
      transcriptEN: 'You have seen the equations, the gates, the truth table and the proofs. Now build it yourself on the live workbench. The guided build is the standard one-to-four demux: place two inverters for S1-prime and S0-prime, then four three-input AND gates, and wire each to D plus the correct select pair so A0 makes Y0 through A3 makes Y3. Keep the courier in mind: D is the package fanning to all four gates, the select pair is the address that opens one gate. Drive D high, set the selects to one-zero, and the package should travel only to Y2 while the others stay zero. Sweep the selects through all four codes with D equals one and confirm the output index matches the address, then drop D to zero and watch every output fall - an empty package delivers nothing.',
      transcriptHI: 'आपने equations, gates, truth table और proofs देख लिए। अब इसे ख़ुद live workbench पर बनाइए। guided build standard one-to-four demux है: S1-prime और S0-prime के लिए दो inverters रखिए, फिर चार three-input AND gates, और हर एक को D तथा सही select जोड़ी से wire करिए ताकि A0 बनाए Y0 से A3 बनाए Y3। courier मन में रखिए: D वह package है जो चारों gates में फैलता है, select जोड़ी वह address है जो एक gate खोलती है। D को high करिए, selects को one-zero सेट करिए, और package सिर्फ़ Y2 तक जाना चाहिए जबकि बाक़ी zero रहें। D बराबर one के साथ selects को चारों codes से घुमाइए और पुष्टि कीजिए output index address से मिलता है, फिर D को zero करिए और देखिए हर output गिर जाता है - एक ख़ाली package कुछ नहीं पहुँचाता।',
      visualNote: 'WorkbenchCTA opening /workbench?tutorial=demux-1to4 to wire the standard 1-to-4 demux from two inverters and four 3-input AND gates.',
    },
    {
      id: 'S11_Flashcards',
      label: 'Flashcards',
      kind: 'flashcards',
      subtitle: 'Eight flip-cards to lock in the definition, the equations, and the decoder identity.',
      theoryEN: [
        'These eight flip-cards drill the facts that matter most: the definition of a demux, the Outputs = 2^n rule, the general routing equation, the 1-to-2 and 1-to-4 equations, the MUX inverse, the decoder identity, and the one-hot property. Cover the back, say the answer aloud, flip to check, and repeat any card you fumble until recall is reflex.',
        'Give extra reps to the routing-equation card, Yi = D . (minterm_i), because that single form generates every other equation in the module - the 1-to-2 and 1-to-4 cases are just it written out for one or two select lines.',
        'If you walk away remembering only one sentence, make it this: a demux routes one input D to exactly one of 2^n outputs chosen by the selects, and a decoder whose enable is used as data is the very same circuit - the courier handing one parcel to exactly one of many houses.',
      ],
      theoryHI: [
        'ये आठ flip-cards सबसे ज़रूरी तथ्य रटाते हैं: demux की परिभाषा, Outputs = 2^n नियम, सामान्य routing equation, 1-to-2 और 1-to-4 equations, MUX inverse, decoder पहचान, और one-hot property। पीछे ढककर जवाब ज़ोर से बोलिए, जाँचने को पलटिए, और जो card अटके उसे तब तक दोहराइए जब तक याद reflex न बन जाए।',
        'routing-equation वाले card, Yi = D . (minterm_i), को ज़्यादा दोहराइए, क्योंकि वही एक रूप module की हर दूसरी equation बनाता है - 1-to-2 और 1-to-4 cases बस उसे एक या दो select lines के लिए लिखा हुआ हैं।',
        'अगर आप सिर्फ़ एक वाक्य याद रखकर जाएँ, तो यह हो: एक demux एक input D को selects से चुने 2^n outputs में से ठीक एक तक भेजता है, और जिस decoder का enable data की तरह वापरा जाए वह वही circuit है - courier एक parcel कई घरों में से ठीक एक को थमाता हुआ।',
      ],
      transcriptEN: 'Eight quick flip-cards to set it solid. They cover the definition, the Outputs equals two-to-the-n rule, the general routing equation, the one-to-two and one-to-four equations, the mux inverse, the decoder identity, and the one-hot property. Give extra reps to the routing-equation card, Yi equals D times minterm-i, because every other equation is just that written out. If you remember one sentence, make it: a demux routes one input to exactly one of two-to-the-n outputs, and a decoder whose enable is used as data is the same circuit.',
      transcriptHI: 'इसे पक्का करने को आठ तेज़ flip-cards। ये परिभाषा, Outputs बराबर two-to-the-n नियम, सामान्य routing equation, one-to-two और one-to-four equations, mux inverse, decoder पहचान, और one-hot property ढकते हैं। routing-equation वाले card को ज़्यादा दोहराइए, Yi बराबर D times minterm-i, क्योंकि हर दूसरी equation बस वही लिखा हुआ है। अगर एक वाक्य याद रखें: एक demux एक input को two-to-the-n outputs में से ठीक एक तक भेजता है, और जिस decoder का enable data की तरह वापरा जाए वह वही circuit है।',
      visualNote: 'Standard bilingual flip deck, eight cards.',
    },
    {
      id: 'S12_Quiz',
      label: 'Quiz Arena',
      kind: 'quiz',
      subtitle: 'Eight questions - prove you can size, route, and build a demux.',
      theoryEN: [
        'Eight multiple-choice questions now check that the demux has really landed: they probe what a demux does, the Outputs = 2^n sizing, which Boolean equation gives a particular output, which gates build a 1-to-2 demux, the gate count for a 1-to-4, the decoder identity, and the one-hot property.',
        'Several questions are circuit-building: they ask how many AND gates and inverters a demux needs, or which minterm equation implements Y2. Work those by writing the minterm for the given index rather than guessing - the index in binary gives you the true/complemented pattern directly.',
        'Aim for full marks. Clearing all eight means you can size a demux, write any output equation, and build the gate-level circuit from memory - exactly the skills the workbench build and the exam will demand.',
      ],
      theoryHI: [
        'आठ bahu-vikalp सवाल अब जाँचते हैं कि demux सचमुच बैठा या नहीं: ये पूछते हैं demux करता क्या है, Outputs = 2^n sizing, कौन सी Boolean equation किसी ख़ास output को देती है, कौन से gates एक 1-to-2 demux बनाते हैं, 1-to-4 की gate गिनती, decoder पहचान, और one-hot property।',
        'कई सवाल circuit-building हैं: वे पूछते हैं demux को कितने AND gates और inverters चाहिए, या कौन सी minterm equation Y2 लागू करती है। इन्हें दिए index के लिए minterm लिखकर कीजिए, अंदाज़े से नहीं - binary में index आपको सीधे true/complemented pattern देता है।',
        'पूरे अंक का लक्ष्य रखिए। आठों साफ़ करना मतलब आप एक demux size कर सकते हैं, कोई भी output equation लिख सकते हैं, और gate-level circuit याद से बना सकते हैं - ठीक वही skills जो workbench build और exam माँगेंगे।',
      ],
      transcriptEN: 'Eight questions in the arena. They check what a demux does, the Outputs equals two-to-the-n sizing, which Boolean equation gives a particular output, which gates build a one-to-two demux, the gate count for a one-to-four, the decoder identity, and the one-hot property. Several are circuit-building - how many AND gates and inverters, or which minterm equation implements Y2. Work those by writing the minterm for the index, not by guessing: the index in binary gives the true and complemented pattern directly. Clear all eight and you can size, route, and build a demux from memory.',
      transcriptHI: 'Arena में आठ सवाल। ये जाँचते हैं demux करता क्या है, Outputs बराबर two-to-the-n sizing, कौन सी Boolean equation किसी ख़ास output को देती है, कौन से gates one-to-two demux बनाते हैं, one-to-four की gate गिनती, decoder पहचान, और one-hot property। कई circuit-building हैं - कितने AND gates और inverters, या कौन सी minterm equation Y2 लागू करती है। इन्हें index के लिए minterm लिखकर कीजिए, अंदाज़े से नहीं: binary में index सीधे true और complemented pattern देता है। आठों साफ़ कीजिए और आप एक demux size, route, और याद से बना सकते हैं।',
      visualNote: 'Parameterized QuizArena, eight questions.',
    },
    {
      id: 'S13_Recap',
      label: 'Recap & Sources',
      kind: 'recap',
      subtitle: 'One input, one chosen destination - the courier hack is yours.',
      theoryEN: [
        'Let us bank the whole thing. A demultiplexer routes a single data input D to exactly one of 2^n output lines, chosen by n select lines, and forces every other output to 0. It is the courier handing one parcel to exactly one of many houses, the address on the parcel picking the door - the precise inverse of a multiplexer.',
        'The sizing rule is Outputs = 2^n, so each extra select line doubles the reachable outputs, and to reach M outputs you need n = log2(M) selects. The routing rule is Yi = D . (minterm_i of the selects): the selected output copies D and all the others sit at 0, because exactly one minterm is high at a time - the one-hot property.',
        'At the gate level a 1-to-2 demux is one inverter and two AND gates (Y0 = S\'.D, Y1 = S.D), and a 1-to-4 demux is two inverters and four 3-input AND gates (Y0 = S1\'.S0\'.D up to Y3 = S1.S0.D). A decoder whose enable is fed with data is the identical circuit, and holding D = 1 turns a demux back into a plain decoder.',
        'Where it matters: demuxes do serial-to-parallel and channel demultiplexing, route a data or strobe to one selected register or memory bank, pair with a MUX to share one physical channel among many logical ones, and form the output stage of decoders and one-hot control logic. The one-hot guarantee - exactly one active output - is what makes them ideal for enabling one device at a time.',
        'Sources used to build this module: digisim.io/blog/demultiplexer-tutorial-1-to-4-and-1-to-8 (the 1-to-4 truth table, the four equations, the gate count, and the decoder-with-enable-as-data equivalence); geeksforgeeks.org/digital-logic/multiplexers-in-digital-logic (the inverse 4-to-1 MUX equation and its four-AND-into-one-OR structure); analogcircuitdesign.com/demultiplexers-demux-working-truth-table-circuits-applications (the n-select / 2^n-output definition and the per-output D.minterm gating); and electronics-tutorials.ws/combination/comb_3.html (the canonical DEMUX/decoder tutorial: enable fed into the output AND gates so all outputs are 0 when the enable is 0).',
      ],
      theoryHI: [
        'चलिए पूरी बात जमा कर लें। एक demultiplexer एक अकेले data input D को n select lines से चुने 2^n output lines में से ठीक एक तक भेजता है, और हर दूसरे output को 0 पर रखता है। यह courier है जो एक parcel कई घरों में से ठीक एक को थमाता है, parcel पर address दरवाज़ा चुनता है - एक multiplexer का सटीक inverse।',
        'sizing नियम है Outputs = 2^n, तो हर अतिरिक्त select line reachable outputs को दुगना करती है, और M outputs पहुँचने को आपको n = log2(M) selects चाहिए। routing नियम है Yi = D . (selects का minterm_i): चुना output D की नक़ल करता है और बाक़ी सब 0 पर बैठते हैं, क्योंकि एक समय ठीक एक minterm high होता है - one-hot property।',
        'gate level पर एक 1-to-2 demux एक inverter और दो AND gates है (Y0 = S\'.D, Y1 = S.D), और एक 1-to-4 demux दो inverters और चार 3-input AND gates है (Y0 = S1\'.S0\'.D से Y3 = S1.S0.D तक)। जिस decoder का enable data से भरा जाए वह वही circuit है, और D = 1 रखने पर demux वापस एक सादा decoder बन जाता है।',
        'कहाँ काम आता है: demuxes serial-to-parallel और channel demultiplexing करते हैं, एक data या strobe को एक चुने register या memory bank तक भेजते हैं, एक MUX के साथ जोड़ी बनाकर एक physical channel को कई logical में बाँटते हैं, और decoders तथा one-hot control logic का output stage बनाते हैं। one-hot गारंटी - ठीक एक active output - ही उन्हें एक समय एक device enable करने के लिए आदर्श बनाती है।',
        'इस module को बनाने में वापरे sources: digisim.io/blog/demultiplexer-tutorial-1-to-4-and-1-to-8 (1-to-4 truth table, चारों equations, gate गिनती, और decoder-with-enable-as-data समानता); geeksforgeeks.org/digital-logic/multiplexers-in-digital-logic (उल्टा 4-to-1 MUX equation और इसकी four-AND-into-one-OR संरचना); analogcircuitdesign.com/demultiplexers-demux-working-truth-table-circuits-applications (n-select / 2^n-output परिभाषा और per-output D.minterm gating); और electronics-tutorials.ws/combination/comb_3.html (canonical DEMUX/decoder tutorial: enable को output AND gates में भरना ताकि enable 0 पर सारे outputs 0 हों)।',
      ],
      transcriptEN: 'Let us bank the whole thing. A demux routes one data input D to exactly one of two-to-the-n outputs chosen by n selects, and forces every other output to zero - the courier handing one parcel to one of many houses, the exact inverse of a mux. Sizing: Outputs equals two-to-the-n, each extra select doubles the outputs, and to reach M outputs you need log-base-two of M selects. Routing: Yi equals D times minterm-i, the selected output copies D and the rest are zero - the one-hot property. At the gate level a one-to-two demux is one inverter and two AND gates, and a one-to-four is two inverters and four three-input AND gates; a decoder whose enable is fed with data is the identical circuit. Demuxes do serial-to-parallel routing, address memory and registers, pair with a mux on a shared channel, and form the output stage of decoders.',
      transcriptHI: 'चलिए पूरी बात जमा कर लें। एक demux एक data input D को n selects से चुने two-to-the-n outputs में से ठीक एक तक भेजता है, और हर दूसरे output को zero पर रखता है - courier एक parcel कई घरों में से एक को थमाता हुआ, एक mux का सटीक inverse। sizing: Outputs बराबर two-to-the-n, हर अतिरिक्त select outputs को दुगना करता है, और M outputs पहुँचने को log-base-two of M selects चाहिए। routing: Yi बराबर D times minterm-i, चुना output D की नक़ल करता है और बाक़ी zero - one-hot property। gate level पर one-to-two demux एक inverter और दो AND gates है, और one-to-four दो inverters और चार three-input AND gates; जिस decoder का enable data से भरा जाए वह वही circuit है। demuxes serial-to-parallel routing करते हैं, memory और registers address करते हैं, एक साझा channel पर mux से जोड़ी बनाते हैं, और decoders का output stage बनाते हैं।',
      visualNote: 'Recap card: the routing equation and the 1-to-4 gate layout on one side, the MUX<->DEMUX mirror on the other; a list of the four source links.',
    },
  ],
  flashcards: [
    {
      frontEN: 'What is a demultiplexer (DEMUX)?',
      backEN: 'A combinational circuit that routes one data input D to exactly one of 2^n outputs, chosen by n select lines. It is the inverse of a MUX. The unselected outputs are all 0.',
      frontHI: 'demultiplexer (DEMUX) क्या है?',
      backHI: 'एक combinational circuit जो एक data input D को n select lines से चुने 2^n outputs में से ठीक एक तक भेजता है। यह MUX का inverse है। unselected outputs सब 0 होते हैं।',
    },
    {
      frontEN: 'How many outputs does a DEMUX with n select lines have?',
      backEN: 'Outputs = 2^n. Each extra select line doubles the outputs, because each binary code of the selects names one output. To reach M outputs you need n = log2(M) selects.',
      frontHI: 'n select lines वाले DEMUX में कितने outputs होते हैं?',
      backHI: 'Outputs = 2^n। हर अतिरिक्त select line outputs को दुगना करती है, क्योंकि selects का हर binary code एक output का नाम है। M outputs पहुँचने को n = log2(M) selects चाहिए।',
    },
    {
      frontEN: 'Write the general DEMUX output equation.',
      backEN: 'Yi = D . (minterm_i of the select lines), where i is the decimal value of the select code. The selected output copies D; all others are 0 because only one minterm is high at a time.',
      frontHI: 'सामान्य DEMUX output equation लिखिए।',
      backHI: 'Yi = D . (select lines का minterm_i), जहाँ i select code का decimal मान है। चुना output D की नक़ल करता है; बाक़ी सब 0 क्योंकि एक समय सिर्फ़ एक minterm high होता है।',
    },
    {
      frontEN: 'Give the 1-to-2 DEMUX equations and the gates needed.',
      backEN: 'Y0 = S\'.D and Y1 = S.D. S=0 routes D to Y0; S=1 routes D to Y1. Built from one NOT gate (for S\') and two 2-input AND gates.',
      frontHI: '1-to-2 DEMUX equations और ज़रूरी gates बताइए।',
      backHI: 'Y0 = S\'.D और Y1 = S.D। S=0, D को Y0 तक भेजता है; S=1, D को Y1 तक। एक NOT gate (S\' के लिए) और दो 2-input AND gates से बना।',
    },
    {
      frontEN: 'Give the four 1-to-4 DEMUX equations.',
      backEN: 'Y0 = S1\'.S0\'.D, Y1 = S1\'.S0.D, Y2 = S1.S0\'.D, Y3 = S1.S0.D. The select code S1S0 read as binary picks the output index. Built from 2 inverters and 4 three-input AND gates.',
      frontHI: 'चारों 1-to-4 DEMUX equations बताइए।',
      backHI: 'Y0 = S1\'.S0\'.D, Y1 = S1\'.S0.D, Y2 = S1.S0\'.D, Y3 = S1.S0.D। select code S1S0 binary की तरह output index चुनता है। 2 inverters और 4 three-input AND gates से बना।',
    },
    {
      frontEN: 'How is a DEMUX related to a MUX?',
      backEN: 'They are exact inverses. A MUX is a many-to-1 selector; a DEMUX is a 1-to-many distributor. They share the same select logic and are often used as a pair on a shared channel - MUX packs, DEMUX unpacks.',
      frontHI: 'DEMUX का MUX से क्या संबंध है?',
      backHI: 'ये सटीक inverses हैं। MUX एक many-to-1 selector है; DEMUX एक 1-to-many distributor। दोनों एक ही select logic बाँटते हैं और अक्सर एक साझा channel पर जोड़ी की तरह वापरे जाते हैं - MUX पैक करता है, DEMUX unpack करता है।',
    },
    {
      frontEN: 'How is a DEMUX the same as a decoder?',
      backEN: 'A decoder with its enable line used as the data input IS a demux: Di = E.minterm_i becomes Yi = D.minterm_i when E = D. Equivalently, holding D = 1 turns a demux into an n-to-2^n decoder.',
      frontHI: 'DEMUX एक decoder जैसा कैसे है?',
      backHI: 'जिस decoder का enable line data input की तरह वापरा जाए वही एक demux है: E = D पर Di = E.minterm_i बन जाता है Yi = D.minterm_i। उसी तरह, D = 1 रखने पर demux एक n-to-2^n decoder बन जाता है।',
    },
    {
      frontEN: 'What is the one-hot property of a DEMUX?',
      backEN: 'For any select code exactly one minterm is 1, so exactly one output follows the data D while every other output is forced to 0. This makes a demux ideal for enabling one device at a time.',
      frontHI: 'DEMUX की one-hot property क्या है?',
      backHI: 'किसी भी select code के लिए ठीक एक minterm 1 होता है, तो ठीक एक output data D का अनुसरण करता है जबकि हर दूसरा output 0 पर रखा जाता है। यह demux को एक समय एक device enable करने के लिए आदर्श बनाता है।',
    },
  ],
  quiz: [
    {
      questionEN: 'What does a demultiplexer do?',
      options: [
        'Selects one of many inputs to drive a single output',
        'Routes one input to exactly one of 2^n outputs',
        'Adds two binary numbers',
        'Stores one bit of data',
      ],
      answerIndex: 1,
      explainEN: 'A DEMUX takes a single data input D and routes it to exactly one of 2^n outputs chosen by the select lines - the inverse of a MUX. Option 1 describes a MUX.',
      explainHI: 'एक DEMUX एक अकेला data input D लेकर उसे select lines से चुने 2^n outputs में से ठीक एक तक भेजता है - MUX का inverse। विकल्प 1 एक MUX का वर्णन है।',
      questionHI: 'एक demultiplexer क्या करता है?',
    },
    {
      questionEN: 'A DEMUX has 3 select lines. How many output lines does it have?',
      options: ['3', '6', '8', '9'],
      answerIndex: 2,
      explainEN: 'Outputs = 2^n = 2^3 = 8, giving a 1-to-8 DEMUX. Each binary code of the 3 selects names one of the 8 outputs.',
      explainHI: 'Outputs = 2^n = 2^3 = 8, एक 1-to-8 DEMUX। 3 selects का हर binary code 8 outputs में से एक को नामित करता है।',
      questionHI: 'एक DEMUX में 3 select lines हैं। इसमें कितनी output lines हैं?',
    },
    {
      questionEN: 'In a 1-to-4 DEMUX, which Boolean equation correctly describes output Y2?',
      options: [
        'Y2 = S1\'.S0\'.D',
        'Y2 = S1.S0\'.D',
        'Y2 = S1.S0.D',
        'Y2 = S1\'.S0.D',
      ],
      answerIndex: 1,
      explainEN: 'Y2 corresponds to select code 10, so S1 = 1 (S1) and S0 = 0 (S0\'), giving Y2 = S1.S0\'.D.',
      explainHI: 'Y2 select code 10 से मेल खाता है, तो S1 = 1 (S1) और S0 = 0 (S0\'), यानी Y2 = S1.S0\'.D।',
      questionHI: 'एक 1-to-4 DEMUX में, कौन सी Boolean equation output Y2 का सही वर्णन करती है?',
    },
    {
      questionEN: 'Which gates are needed to build a 1-to-2 DEMUX (Y0 = S\'.D, Y1 = S.D)?',
      options: [
        'One inverter and two 2-input AND gates',
        'Two OR gates only',
        'One XOR gate and one AND gate',
        'Three NAND gates and one NOR gate',
      ],
      answerIndex: 0,
      explainEN: 'You need one NOT gate to make S\' and two 2-input AND gates: D.S\' for Y0 and D.S for Y1.',
      explainHI: 'आपको S\' बनाने को एक NOT gate और दो 2-input AND gates चाहिए: Y0 के लिए D.S\' और Y1 के लिए D.S।',
      questionHI: 'एक 1-to-2 DEMUX (Y0 = S\'.D, Y1 = S.D) बनाने को कौन से gates चाहिए?',
    },
    {
      questionEN: 'For a 1-to-4 DEMUX with D = 1, S1 = 1, S0 = 0, which output goes high?',
      options: ['Y0', 'Y1', 'Y2', 'Y3'],
      answerIndex: 2,
      explainEN: 'Select code S1S0 = 10 = decimal 2, so Y2 = S1.S0\'.D = 1.1.1 = 1; all other outputs are 0.',
      explainHI: 'Select code S1S0 = 10 = decimal 2, तो Y2 = S1.S0\'.D = 1.1.1 = 1; बाक़ी सब outputs 0 हैं।',
      questionHI: 'D = 1, S1 = 1, S0 = 0 वाले 1-to-4 DEMUX के लिए, कौन सा output high होता है?',
    },
    {
      questionEN: 'How many 3-input AND gates and how many inverters does a basic 1-to-4 DEMUX need?',
      options: [
        '2 AND gates and 1 inverter',
        '4 AND gates and 2 inverters',
        '8 AND gates and 3 inverters',
        '4 AND gates and 4 inverters',
      ],
      answerIndex: 1,
      explainEN: 'Each of the 4 outputs needs its own 3-input AND gate (D plus two selects), and two inverters produce S1\' and S0\'.',
      explainHI: '4 outputs में से हर एक को अपना 3-input AND gate चाहिए (D और दो selects), और दो inverters S1\' तथा S0\' बनाते हैं।',
      questionHI: 'एक basic 1-to-4 DEMUX को कितने 3-input AND gates और कितने inverters चाहिए?',
    },
    {
      questionEN: 'How is a DEMUX related to a decoder?',
      options: [
        'They are completely unrelated circuits',
        'A decoder whose enable line is used as the data input becomes a DEMUX',
        'A DEMUX always needs twice as many gates as a decoder',
        'A decoder routes many inputs to one output',
      ],
      answerIndex: 1,
      explainEN: 'A decoder with its enable driven as data is exactly a DEMUX (Di = E.minterm_i becomes Yi = D.minterm_i); equivalently, holding D = 1 turns a DEMUX into a decoder.',
      explainHI: 'जिस decoder का enable data की तरह चलाया जाए वह ठीक एक DEMUX है (Di = E.minterm_i बन जाता है Yi = D.minterm_i); उसी तरह, D = 1 रखने पर DEMUX एक decoder बन जाता है।',
      questionHI: 'एक DEMUX का एक decoder से क्या संबंध है?',
    },
    {
      questionEN: 'At any given time, how many outputs of a DEMUX can be actively following the data input D?',
      options: ['All of them', 'Exactly one', 'Exactly two', 'None'],
      answerIndex: 1,
      explainEN: 'Only the minterm matching the current select code is 1, so exactly one output follows D while all the rest are forced to 0 - the one-hot property.',
      explainHI: 'सिर्फ़ मौजूदा select code से मिलता minterm 1 होता है, तो ठीक एक output D का अनुसरण करता है जबकि बाक़ी सब 0 पर रखे जाते हैं - one-hot property।',
      questionHI: 'किसी भी समय, एक DEMUX के कितने outputs सक्रिय रूप से data input D का अनुसरण कर सकते हैं?',
    },
  ],
}) as unknown as SubContent;
