/**
 * Exporters for K-Map Lab
 * Generates Verilog HDL, VHDL, LaTeX, SVG, and shareable URLs.
 */

export const generateVerilog = (expression: string, moduleName: string = "kmap_simplified"): string => {
  if (!expression || expression === '0') return `// Verilog HDL\nmodule ${moduleName} (input wire A, B, C, D, E, output wire F);\n    assign F = 1'b0;\nendmodule\n`;
  if (expression === '1') return `// Verilog HDL\nmodule ${moduleName} (input wire A, B, C, D, E, output wire F);\n    assign F = 1'b1;\nendmodule\n`;

  const terms = expression.split(/\s*\+\s*/).map(term => {
    // Break term like A'BC' into tokens: A', B, C'
    const literals = term.match(/([A-E]'?)/g) || [];
    return literals.map(lit => lit.endsWith("'") ? `~${lit[0]}` : lit[0]).join(' & ');
  });

  return `// Verilog HDL generated by BitforBytes K-Map Lab
module ${moduleName} (
    input wire A, B, C, D, E,
    output wire F
);

    assign F = ${terms.map(t => `(${t})`).join(' | ')};

endmodule
`;
};

export const generateVHDL = (expression: string, entityName: string = "kmap_simplified"): string => {
  if (!expression || expression === '0') return `-- VHDL\nentity ${entityName} is Port (A,B,C,D,E: in STD_LOGIC; F: out STD_LOGIC); end;\narchitecture Behavioral of ${entityName} is begin F <= '0'; end;`;
  if (expression === '1') return `-- VHDL\nentity ${entityName} is Port (A,B,C,D,E: in STD_LOGIC; F: out STD_LOGIC); end;\narchitecture Behavioral of ${entityName} is begin F <= '1'; end;`;

  const terms = expression.split(/\s*\+\s*/).map(term => {
    const literals = term.match(/([A-E]'?)/g) || [];
    return literals.map(lit => lit.endsWith("'") ? `not ${lit[0]}` : lit[0]).join(' and ');
  });

  return `-- VHDL entity generated by BitforBytes K-Map Lab
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity ${entityName} is
    Port (
        A, B, C, D, E : in STD_LOGIC;
        F : out STD_LOGIC
    );
end ${entityName};

architecture Behavioral of ${entityName} is
begin
    F <= ${terms.map(t => `(${t})`).join(' or ')};
end Behavioral;
`;
};

export const generateLaTeX = (expression: string): string => {
  const latexExpr = (expression || "0")
    .replace(/([A-E])'/g, "\\overline{$1}")
    .replace(/\+/g, " + ");

  return `\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}
\\begin{equation*}
F = ${latexExpr}
\\end{equation*}
\\end{document}
`;
};
