import React from 'react';
import { motion } from 'framer-motion';
import { Link as LinkIcon, Zap, Flag, Hourglass, ArrowRight } from 'lucide-react';

interface Props { isActive?: boolean; isDarkMode: boolean }

const AMBER = '#f59e0b';
const EMERALD = '#34d399';
const VIOLET = '#a78bfa';
const SKY = '#38bdf8';
const ROSE = '#fb7185';

const ANATOMY: Array<{ port: string; role: string; color: string }> = [
  { port: 'A input',  role: 'Runner energy one - a bit of the first number',  color: SKY },
  { port: 'B input',  role: 'Runner energy two - a bit of the second number', color: SKY },
  { port: 'Cin',      role: 'The baton received from the runner behind',       color: AMBER },
  { port: 'Cout',     role: 'The baton passed to the runner ahead',            color: AMBER },
  { port: 'S output', role: "The runner's final position - this column's sum bit", color: EMERALD },
];

export const S01_Analogy: React.FC<Props> = ({ isDarkMode }) => {
  const textColor = isDarkMode ? 'text-white' : 'text-slate-900';
  const subText   = isDarkMode ? 'text-slate-300' : 'text-slate-600';
  const cardBg    = isDarkMode ? 'bg-white/5 border-white/10' : 'bg-white border-slate-200 shadow-xl';

  // runner states for the "starting gun" visual: only runner 1 (bit 0) can go
  const runners = [
    { name: 'Runner 4', bit: 'bit 3', state: 'waiting' },
    { name: 'Runner 3', bit: 'bit 2', state: 'waiting' },
    { name: 'Runner 2', bit: 'bit 1', state: 'waiting' },
    { name: 'Runner 1', bit: 'bit 0', state: 'running' },
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-12 py-4">
      {/* header */}
      <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="space-y-4 text-center">
        <div className="flex items-center justify-center gap-2 font-mono text-[10px] tracking-[0.4em] uppercase" style={{ color: AMBER }}>
          <LinkIcon size={14} /> The Digital Relay
        </div>
        <h1 className={`text-4xl md:text-5xl font-black tracking-tight ${textColor}`}>
          A relay race, where the baton <span style={{ color: AMBER }}>is the carry.</span>
        </h1>
        <p className={`text-base md:text-lg max-w-2xl mx-auto ${subText}`}>
          A ripple-carry adder is a relay team. Each full adder is a runner; the carry bit is the
          baton. A runner can sprint only once the baton is in their hand, so the team is only as
          fast as one runner after another after another, in order.
        </p>
      </motion.section>

      {/* the burden of the carry */}
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}
                  className={`p-6 md:p-8 rounded-3xl border ${cardBg}`}>
        <div className="grid md:grid-cols-2 gap-6 items-center">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-widest mb-2" style={{ color: AMBER }}>The burden of the carry</div>
            <p className={`text-base leading-relaxed ${subText}`}>
              When you add, any value that overflows a column must be passed to the next column up.
              Because that overflow is <strong style={{ color: textHex(isDarkMode) }}>generated by one
              column and needed by the next</strong>, addition is inherently sequential - you cannot
              finish a column until you know the carry coming into it.
            </p>
          </div>
          <div className={`rounded-2xl border p-5 font-mono ${isDarkMode ? 'bg-black/20 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
            <div className="text-center text-sm space-y-1">
              <div className={subText}><span style={{ color: AMBER }}>carry → 1 1 1</span></div>
              <div className={`text-2xl ${textColor}`}>0 1 1 1</div>
              <div className={`text-2xl ${textColor}`}>+ 0 0 0 1</div>
              <div className="h-px my-1" style={{ background: AMBER }} />
              <div className="text-2xl font-black" style={{ color: EMERALD }}>1 0 0 0</div>
            </div>
            <p className={`mt-3 text-[11px] text-center ${subText}`}>
              One carry sets off a chain: 1+1 carries, which makes the next column carry, which makes
              the next... a single ripple all the way up.
            </p>
          </div>
        </div>
      </motion.div>

      {/* anatomy of a runner */}
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}
                  className={`p-6 md:p-8 rounded-3xl border ${cardBg}`}>
        <div className="text-center mb-6">
          <div className="font-mono text-[10px] uppercase tracking-widest" style={{ color: VIOLET }}>Anatomy of a runner</div>
          <h3 className={`text-2xl font-black ${textColor}`}>Every full adder is one runner</h3>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {ANATOMY.map(({ port, role, color }) => (
            <div key={port} className={`p-4 rounded-2xl border ${isDarkMode ? 'bg-black/30 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
              <div className="font-mono text-sm font-black" style={{ color }}>{port}</div>
              <p className={`mt-1 text-[12px] leading-relaxed ${subText}`}>{role}</p>
            </div>
          ))}
          <div className="p-4 rounded-2xl border flex items-center justify-center text-center"
               style={{ borderColor: `${VIOLET}55`, background: `${VIOLET}10` }}>
            <p className="text-[12px] font-mono" style={{ color: VIOLET }}>
              5 ports, one runner. The baton in (Cin) and the baton out (Cout) are the carry.
            </p>
          </div>
        </div>
      </motion.div>

      {/* building the relay team + the starting gun */}
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}
                  className={`p-6 md:p-8 rounded-3xl border ${cardBg}`}>
        <div className="text-center mb-6">
          <div className="font-mono text-[10px] uppercase tracking-widest" style={{ color: AMBER }}>The starting gun</div>
          <h3 className={`text-2xl font-black ${textColor}`}>Everyone has their numbers - but only one can run</h3>
          <p className={`mt-2 text-sm max-w-2xl mx-auto ${subText}`}>
            All four runners receive their A and B bits the instant the inputs arrive. But the race
            still cannot finish: runners 2 through 4 must stand idle, because they have no baton yet.
          </p>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {runners.map((r, i) => {
            const running = r.state === 'running';
            const color = running ? EMERALD : AMBER;
            return (
              <div key={r.name} className="relative">
                <div className={`p-5 rounded-2xl border-2 text-center transition-all`}
                     style={{
                       borderColor: running ? EMERALD : `${AMBER}55`,
                       background: running ? `${EMERALD}12` : isDarkMode ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.02)',
                       opacity: running ? 1 : 0.65,
                     }}>
                  <div className="font-mono text-[10px] uppercase tracking-widest" style={{ color }}>{r.bit}</div>
                  <div className={`mt-1 text-sm font-extrabold ${textColor}`}>{r.name}</div>
                  <div className="mt-2 inline-flex items-center gap-1.5 font-mono text-[10px] font-black uppercase tracking-widest" style={{ color }}>
                    {running ? <><Zap size={11} /> running</> : <><Hourglass size={11} /> waiting</>}
                  </div>
                </div>
                {i < runners.length - 1 && (
                  <ArrowRight size={14} className="hidden sm:block absolute top-1/2 -right-2.5 -translate-y-1/2 opacity-40" style={{ color: AMBER }} />
                )}
              </div>
            );
          })}
        </div>
        <p className={`mt-4 text-center text-xs font-mono ${subText}`}>
          baton (carry) travels right to left · only the runner holding it can finish
        </p>
      </motion.div>

      {/* the sequence close */}
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}
                  className="p-6 md:p-8 rounded-3xl border-2"
                  style={{ borderColor: `${AMBER}66`, background: isDarkMode ? 'rgba(245,158,11,0.06)' : 'rgba(245,158,11,0.05)' }}>
        <div className="flex items-center gap-2 mb-4 justify-center">
          <Flag size={18} style={{ color: AMBER }} />
          <span className="font-mono text-[11px] uppercase tracking-widest" style={{ color: AMBER }}>The relay sequence</span>
        </div>
        <div className="grid sm:grid-cols-3 gap-4">
          {[
            ['Step 1', 'Runner 1 computes', 'The lowest adder has its bits and a known Cin of 0, so it finishes first and produces a carry.'],
            ['Step 2', 'It passes the baton', 'That carry-out becomes the carry-in for runner 2 - the baton is handed forward.'],
            ['Step 3', 'Runner 2 waits, then runs', 'Only now can runner 2 finish. Then it hands its carry to runner 3, and the wave continues.'],
          ].map(([step, title, body]) => (
            <div key={step} className={`p-4 rounded-2xl border ${isDarkMode ? 'bg-black/20 border-white/10' : 'bg-white border-slate-200'}`}>
              <div className="font-mono text-[10px] uppercase tracking-widest" style={{ color: AMBER }}>{step}</div>
              <h4 className={`mt-1 text-[15px] font-extrabold ${textColor}`}>{title}</h4>
              <p className={`mt-1 text-[12px] leading-relaxed ${subText}`}>{body}</p>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

function textHex(dark: boolean) { return dark ? '#ffffff' : '#0f172a'; }

export default S01_Analogy;
