import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/14 - Recall & Prime. The interactive review that OPENS the subtractor
 * track: reload binary place value, XOR, the half/full adder, carry-vs-borrow
 * and the two's-complement idea, so the half subtractor lands on solid ground.
 * Hand-authored bilingual content (the other three modules are workflow-drafted).
 */
export const CONTENT: SubContent = {
  moduleTitle: 'Recall & Prime',
  moduleSubtitle: 'Before you subtract, reload the five ideas every subtractor is quietly built from.',
  scenes: [
    {
      id: 'S00_Cover',
      label: 'Recall & Prime',
      kind: 'cover',
      subtitle: 'Warm up the exact circuits subtraction is about to reuse.',
      theoryEN: [
        'Here is the comforting truth that opens this whole track: subtraction does not start from scratch. It quietly reuses almost everything you already built while making adders, so think of the subtractor as the adder you already know, just wearing a different hat. Nothing here is brand new - it is the same machine seen from a new angle.',
        'To get ready, you only need to reload five ideas. First, binary place value (each column is worth a power of two: 8, 4, 2, 1). Second, the XOR gate (the gate that outputs 1 only when its two inputs differ). Third, the half adder and the full adder (the tiny circuits that add one column). Fourth, carry versus borrow (the two ways a column can overflow or come up short). Fifth, complements (the trick that lets a computer subtract by adding).',
        'The plan is short and active. First flip through the recall deck, where each card asks a question on the front and gives the real logic on the back. Then run the worked drills that compute live in front of you, and finish with a six-question boss round. By the end nothing is missing, and the half subtractor in the next module will land on solid ground.',
        'One thing to keep in mind: this entire module is review. There is no brand-new circuit to memorise yet - the only goal is to lock the foundation firmly in place so that when the new ideas arrive, they actually stick instead of sliding off.',
      ],
      theoryHI: [
        'पूरे track को खोलने वाली एक राहत भरी बात: subtraction शून्य से शुरू नहीं होता। यह चुपचाप लगभग वह सब कुछ फिर से इस्तेमाल करता है जो आपने adders बनाते हुए सीखा, इसलिए subtractor को वही adder समझिए जिसे आप पहले से जानते हैं, बस अलग टोपी पहने हुए। यहाँ कुछ भी बिलकुल नया नहीं है - यह वही मशीन है, बस नए कोण से देखी गई।',
        'तैयार होने के लिए आपको सिर्फ़ पाँच विचार फिर से load करने हैं। पहला, binary place value (हर column two की एक power के बराबर है: 8, 4, 2, 1)। दूसरा, XOR gate (वह gate जो तभी 1 देता है जब उसके दो inputs अलग हों)। तीसरा, half adder और full adder (एक column जोड़ने वाली छोटी circuits)। चौथा, carry बनाम borrow (एक column के overflow होने या कम पड़ने के दो तरीके)। पाँचवाँ, complements (वह trick जो computer को जोड़कर घटाने देती है)।',
        'योजना छोटी और active है। पहले recall deck पलटिए, जहाँ हर card के आगे एक सवाल और पीछे असली logic है। फिर वे drills चलाइए जो आपके सामने live compute होती हैं, और आख़िर में छह सवालों का boss round कीजिए। अंत तक कुछ नहीं छूटेगा, और अगले module का half subtractor पक्की नींव पर उतरेगा।',
        'एक बात याद रखिए: यह पूरा module सिर्फ़ review है। अभी कोई बिलकुल नई circuit रटनी नहीं है - मक़सद सिर्फ़ नींव को मज़बूती से जमाना है, ताकि जब नई बातें आएँ तो वे फिसलने के बजाय सचमुच टिक जाएँ।',
      ],
      transcriptEN: 'Welcome to the subtractor track. Before we build anything that subtracts, we are going to reload your memory, because subtraction is not a brand new machine - it is the adder you already know, wearing a different hat. In the next few screens you will refresh five ideas: how a binary number carries its value column by column, why the XOR gate shows up in every arithmetic circuit, what a half and a full adder actually output, the mirror relationship between a carry and a borrow, and the one trick - the complement - that lets a computer subtract without ever owning a subtract circuit. Flip the cards, take the short drill, and you will be primed.',
      transcriptHI: 'Subtractor track में आपका स्वागत है। घटाने वाली कोई भी चीज़ बनाने से पहले हम आपकी memory फिर से load करेंगे, क्योंकि subtraction कोई बिलकुल नई मशीन नहीं है - यह वही adder है जिसे आप पहले से जानते हैं, बस अलग टोपी पहने हुए। अगली कुछ screens में आप पाँच विचार ताज़ा करेंगे: binary संख्या column-दर-column अपनी value कैसे रखती है, हर arithmetic circuit में XOR gate क्यों आता है, half और full adder असल में क्या output देते हैं, carry और borrow का आईने जैसा रिश्ता, और वह एक trick - complement - जो computer को बिना subtract circuit के घटाने देती है। Cards पलटिए, छोटी drill कीजिए, और आप तैयार हो जाएँगे।',
    },
    {
      id: 'S01_Deck',
      label: 'The Recall Deck',
      kind: 'flashcards',
      subtitle: 'Question on the front, the real logic on the back. Flip every card you are unsure about.',
      theoryEN: ['Tap a card to flip it.', 'Use the EN / हिं toggle in the header to read either language.'],
      theoryHI: ['पलटने के लिए card को tap कीजिए।', 'header में EN / हिं toggle से कोई भी भाषा पढ़िए।'],
      transcriptEN: 'These eight cards are the whole prerequisite set for the subtractor track. If a card flips and the back surprises you, that is exactly the idea to slow down on before moving ahead.',
      transcriptHI: 'ये आठ cards ही subtractor track की पूरी prerequisite सूची हैं। अगर कोई card पलटे और पीछे की बात चौंका दे, तो आगे बढ़ने से पहले रुककर ठीक वही विचार दोहराइए।',
    },
    {
      id: 'S02_Binary',
      label: 'Binary Subtraction by Hand',
      kind: 'theory',
      subtitle: 'Borrowing, one column at a time.',
      theoryEN: [
        'Subtracting binary by hand is the same ritual you learned for decimal subtraction, except there are only two digits to deal with instead of ten. You write the expression as x - y, where x is the minuend (the amount you start with, sitting on top) and y is the subtrahend (the amount you take away, written underneath). You then line the two numbers up by column and work from right to left, exactly the way you have always done sums on paper.',
        'Most columns are completely effortless because the answer never leaves the column. 0 - 0 gives 0, 1 - 0 gives 1, and 1 - 1 gives 0. In all three the top digit is at least as big as the bottom digit, so you simply write down the difference and move one column to the left without any fuss.',
        'The single column that needs care is 0 - 1, because you are being asked to take one away from nothing. You cannot, so you BORROW 1 from the next-higher column on the left - exactly like borrowing a ten in grade-school subtraction. That borrowed 1 is worth two in this column (binary, remember), so the sum becomes 10 - 1 = 1, you write a 1, and you mark that the left column now owes a borrow.',
        'This is where the hat analogy pays off. A borrow is the exact mirror image of a carry. When you are adding and a column makes too much, a carry travels up and to the left into the next column. When you are subtracting and a column comes up short, a borrow travels down and to the left out of the next column. Same direction along the row, opposite job - and that single borrow is the whole reason a subtractor circuit needs a second output wire, which is exactly the idea the half subtractor turns into hardware next module.',
      ],
      theoryHI: [
        'Binary को हाथ से घटाना वही रस्म है जो आपने decimal subtraction में सीखी, बस यहाँ दस के बजाय सिर्फ़ दो digits से निपटना है। आप इसे x - y लिखते हैं, जहाँ x है minuend (जहाँ से शुरू करते हैं, ऊपर बैठा हुआ) और y है subtrahend (जो हटाते हैं, नीचे लिखा हुआ)। फिर दोनों संख्याओं को column के हिसाब से सीध में रखकर दाएँ से बाएँ चलते हैं, ठीक वैसे जैसे आप हमेशा कागज़ पर करते आए हैं।',
        'ज़्यादातर columns बिलकुल आसान हैं क्योंकि जवाब कभी column से बाहर नहीं जाता। 0 - 0 = 0, 1 - 0 = 1, और 1 - 1 = 0। तीनों में ऊपर वाला digit नीचे वाले से कम नहीं है, इसलिए आप सीधा difference लिख देते हैं और बिना किसी झंझट के एक column बाएँ बढ़ जाते हैं।',
        'सिर्फ़ एक column ध्यान माँगता है: 0 - 1, क्योंकि यहाँ आपसे कुछ में से एक हटाने को कहा जा रहा है। यह सीधे नहीं हो सकता, इसलिए आप बाईं ओर वाले अगले बड़े column से 1 BORROW करते हैं - ठीक वैसे जैसे स्कूल की subtraction में दस उधार लेते हैं। वह उधार लिया 1 इस column में दो के बराबर है (binary है, याद रखिए), इसलिए हिसाब 10 - 1 = 1 बन जाता है, आप 1 लिख देते हैं, और बता देते हैं कि बायाँ column अब एक borrow का कर्ज़दार है।',
        'यहीं टोपी वाली analogy काम आती है। Borrow, carry का बिलकुल आईना है। जोड़ते समय जब column बहुत ज़्यादा बना लेता है, carry ऊपर और बाईं ओर अगले column में जाता है। घटाते समय जब column कम पड़ जाता है, borrow नीचे और बाईं ओर अगले column से बाहर खिंचता है। row के साथ एक ही दिशा, उल्टा काम - और वही एक borrow पूरी वजह है कि subtractor circuit को दूसरा output wire चाहिए, और यही विचार half subtractor अगले module में hardware में बदल देता है।',
      ],
      transcriptEN: 'Subtracting binary by hand is the same ritual as decimal, with only two digits. Line the numbers up, work right to left, and most columns are trivial. The only moment that needs care is zero minus one: there is nothing to take away from, so you borrow a one from the column to your left, exactly like borrowing a ten in grade-school subtraction. That single borrow is the whole reason a subtractor needs a second output, and it is the idea the half subtractor is about to make into a circuit.',
      transcriptHI: 'Binary को हाथ से घटाना decimal जैसी ही रस्म है, बस दो ही digits के साथ। संख्याओं को सीध में रखिए, दाएँ से बाएँ चलिए, और ज़्यादातर columns आसान हैं। ध्यान सिर्फ़ एक पल माँगता है: शून्य में से एक - यहाँ हटाने को कुछ है ही नहीं, इसलिए आप बाएँ column से एक borrow करते हैं, ठीक वैसे जैसे स्कूल की subtraction में दस उधार लेते हैं। वही एक borrow पूरी वजह है कि subtractor को दूसरा output चाहिए, और यही विचार half subtractor अब एक circuit में बदलने वाला है।',
    },
    {
      id: 'S03_BorrowVsCarry',
      label: 'Carry vs Borrow',
      kind: 'theory',
      subtitle: 'Same XOR difference, opposite overflow.',
      theoryEN: [
        'This is the punch line that ties the entire track together, and it is the heart of the different-hat analogy: an adder and a subtractor are almost the same circuit. Both of them take their two input bits and run them through an XOR gate to produce their main result bit. For the adder that bit is the Sum (Sum = a XOR b); for the subtractor it is the Difference (Difference = x XOR y). The expensive, headline part of the circuit is literally identical.',
        'The only place they actually disagree is the second, helper output. The adder emits a CARRY: it ran into 1 + 1, made too much for one column to hold, and has to push the overflow up to the next column. So whenever both of its inputs are 1, its carry is 1 - which is exactly the AND of the two inputs.',
        'The subtractor instead emits a BORROW: it ran into 0 - 1, did not have enough in this column, and has to pull a 1 down from the next column. So its borrow is raised in exactly one case, when the top bit is 0 and the bottom bit is 1 - which is the AND of NOT-x and y.',
        'Lay the two definitions side by side and the symmetry jumps out. Half adder: Sum = a XOR b, Carry = a AND b. Half subtractor: Difference = x XOR y, Borrow = (NOT x) AND y. The XOR is shared word for word; only the helper gate changes, and it changes by just one inverter on the x input.',
        'That near-perfect symmetry is the secret the whole subtractor track is built on. Because only one tiny gate differs, a single piece of silicon can do both jobs: feed it a mode bit (a control wire) that flips one input through an XOR, and the very same hardware adds when the bit is 0 and subtracts when the bit is 1. Hold onto that picture - it is the trick the next module unwraps in full.',
      ],
      theoryHI: [
        'यह वह निचोड़ है जो पूरे track को बाँधता है, और यही अलग-टोपी वाली analogy का दिल है: adder और subtractor लगभग एक ही circuit हैं। दोनों अपने दो input bits को XOR gate से गुज़ारकर अपना मुख्य result bit बनाते हैं। adder के लिए वह bit Sum है (Sum = a XOR b); subtractor के लिए Difference है (Difference = x XOR y)। circuit का महँगा, मुख्य हिस्सा बिलकुल एक जैसा है।',
        'फ़र्क़ सिर्फ़ दूसरे, helper output में आता है। Adder एक CARRY देता है: उसे 1 + 1 मिला, एक column के लिए बहुत ज़्यादा बन गया, और overflow को ऊपर अगले column में धकेलना पड़ता है। इसलिए जब भी उसके दोनों inputs 1 हों, उसका carry 1 होता है - जो ठीक दोनों inputs का AND है।',
        'Subtractor इसके बजाय एक BORROW देता है: उसे 0 - 1 मिला, इस column में पर्याप्त नहीं था, और अगले column से 1 नीचे खींचना पड़ता है। इसलिए उसका borrow सिर्फ़ एक हालत में उठता है, जब ऊपर वाला bit 0 और नीचे वाला bit 1 हो - जो NOT-x और y का AND है।',
        'दोनों परिभाषाओं को अग़ल-बग़ल रखिए तो समरूपता उछलकर सामने आ जाती है। Half adder: Sum = a XOR b, Carry = a AND b। Half subtractor: Difference = x XOR y, Borrow = (NOT x) AND y। XOR हू-ब-हू एक जैसा है; सिर्फ़ helper gate बदलता है, और वह भी x वाले input पर बस एक inverter से।',
        'यही लगभग-संपूर्ण समरूपता वह राज़ है जिस पर पूरा subtractor track खड़ा है। चूँकि सिर्फ़ एक नन्हा gate बदलता है, एक ही silicon का टुकड़ा दोनों काम कर सकता है: उसे एक mode bit (एक control wire) दीजिए जो XOR से एक input को पलटा दे, और वही hardware bit 0 पर जोड़ता है और bit 1 पर घटाता है। इस तस्वीर को थामे रखिए - यही trick अगला module पूरा खोलता है।',
      ],
      transcriptEN: 'Here is the punch line that ties the whole track together. An adder and a subtractor are almost the same circuit. Both take their two inputs and run them through an XOR to make the main result bit - Sum for the adder, Difference for the subtractor. The only real difference is the helper output. When adding, a column can overflow upward and hand a carry to the next column. When subtracting, a column can come up short and pull a borrow from the next column. Look at the gates: half adder carry is a AND b, half subtractor borrow is NOT-x AND y. Swap one gate, steer it with a control bit, and the same silicon adds or subtracts on command. Hold that idea - it is the secret the next module reveals in full.',
      transcriptHI: 'यह वह निचोड़ है जो पूरे track को बाँधता है। Adder और subtractor लगभग एक ही circuit हैं। दोनों अपने दो inputs को XOR से गुज़ारकर मुख्य result bit बनाते हैं - adder के लिए Sum, subtractor के लिए Difference। असली फ़र्क़ सिर्फ़ helper output में है। जोड़ते समय column ऊपर की ओर overflow होकर अगले column को carry देता है। घटाते समय column कम पड़कर अगले column से borrow खींचता है। Gates देखिए: half adder का carry है a AND b, half subtractor का borrow है NOT-x AND y। एक gate बदलिए, एक control bit से चलाइए, और वही silicon आदेश पर जोड़ता या घटाता है। इस विचार को थामे रखिए - अगला module इसी राज़ को पूरा खोलता है।',
    },
    {
      id: 'S04_Quiz',
      label: 'Recall Boss Round',
      kind: 'quiz',
      subtitle: 'Six questions across all five reloaded ideas.',
      theoryEN: ['Answer each one; the walkthrough opens the moment you pick.'],
      theoryHI: ['हर सवाल का जवाब दीजिए; चुनते ही walkthrough खुल जाता है।'],
      transcriptEN: 'A quick six-question check across the whole warm-up. Anything you miss, flip back to its card before you start the half subtractor.',
      transcriptHI: 'पूरे warm-up पर छह सवालों की त्वरित जाँच। जो भी छूटे, half subtractor शुरू करने से पहले उसके card पर वापस जाइए।',
    },
    {
      id: 'S05_Recap',
      label: 'The Cheatsheet',
      kind: 'recap',
      subtitle: 'One page to carry into the half subtractor.',
      theoryEN: [
        'Here is the whole foundation on one page, so keep it close - every screen from here on leans on one of these five ideas. Start with place value: a binary number is positional, with columns worth ...8, 4, 2, 1 from left to right, and the rightmost bit always worth 2 to the power 0, which is 1. Doubling happens every step you move left.',
        'Next, the XOR gate, the workhorse of all arithmetic. XOR outputs 1 only when its two inputs differ, and that one gate quietly builds both the adder\'s Sum and the subtractor\'s Difference - the same gate, doing the headline work for both jobs.',
        'Then the adder pair. A half adder produces Sum = a XOR b and Carry = a AND b, but it has no way to accept an incoming carry. A full adder fixes that by taking a third input, the carry-in, giving Sum = a XOR b XOR cin, which is what lets adders chain column to column across a whole number.',
        'Now the borrow, the star of this track. A borrow is simply a carry running in reverse: whenever a column hits 0 - 1 and comes up short, it pulls a 1 down from the next column to the left. Carry up while adding, borrow down while subtracting - the same machine in a different hat.',
        'Finally the complement trick, the reason real computers never bother to build a separate subtract circuit. To compute A - B they instead add: A - B = A + (NOT B) + 1. Inverting every bit of B and adding one gives the two\'s complement of B, which is just negative B, so the ordinary adder quietly does the subtraction.',
        'That is the warm-up complete. Next up, the Half Subtractor takes that single borrow you just reloaded and turns it into two real output wires you can wire up and test.',
      ],
      theoryHI: [
        'यहाँ पूरी नींव एक page पर है, इसे पास रखिए - यहाँ से हर screen इन्हीं पाँच में से किसी एक विचार पर टिकी है। शुरुआत place value से: binary संख्या स्थान पर निर्भर है, बाएँ से दाएँ columns की value ...8, 4, 2, 1 है, और सबसे दायाँ bit हमेशा 2 की power 0 के बराबर, यानी 1। हर कदम बाएँ बढ़ने पर value दोगुनी होती है।',
        'अगला, XOR gate, हर arithmetic का घोड़ा। XOR तभी 1 देता है जब उसके दो inputs अलग हों, और यही एक gate चुपचाप adder का Sum और subtractor का Difference दोनों बनाता है - वही gate, दोनों कामों का मुख्य काम करता हुआ।',
        'फिर adder की जोड़ी। Half adder देता है Sum = a XOR b और Carry = a AND b, पर इसमें आने वाला carry लेने का कोई रास्ता नहीं। Full adder यह तीसरा input - carry-in - लेकर ठीक करता है, जिससे Sum = a XOR b XOR cin बनता है, और यही adders को पूरी संख्या भर column-दर-column जुड़ने देता है।',
        'अब borrow, इस track का सितारा। Borrow बस उल्टा चलता carry है: जब भी column 0 - 1 पर कम पड़ता है, यह बाईं ओर अगले column से 1 नीचे खींच लेता है। जोड़ते समय carry ऊपर, घटाते समय borrow नीचे - वही मशीन, अलग टोपी में।',
        'आख़िर में complement की trick, वह वजह कि असली computer कभी अलग subtract circuit बनाने की ज़हमत नहीं उठाते। A - B निकालने के लिए वे जोड़ते हैं: A - B = A + (NOT B) + 1। B के हर bit को invert करके एक जोड़ने पर B का two\'s complement मिलता है, जो बस ऋणात्मक B है, इसलिए साधारण adder ही चुपचाप घटाव कर देता है।',
        'बस, warm-up पूरा। आगे, Half Subtractor उसी एक borrow को, जो आपने अभी reload किया, दो असली output wires में बदल देता है जिन्हें आप जोड़कर test कर सकते हैं।',
      ],
      transcriptEN: 'That is the whole foundation on one page. Place value, the XOR, the half and full adder, the borrow as a reversed carry, and the complement trick. Keep this nearby - every screen from here on leans on one of these five. On to the half subtractor.',
      transcriptHI: 'यही पूरी नींव एक page पर है। Place value, XOR, half और full adder, उल्टे carry जैसा borrow, और complement की trick। इसे पास रखिए - यहाँ से हर screen इन्हीं पाँच में से किसी एक पर टिकी है। चलिए half subtractor की ओर।',
    },
  ],
  flashcards: [
    {
      frontEN: 'What does each column of a binary number mean?',
      backEN: 'Positional powers of two: ... 8, 4, 2, 1. The rightmost bit is 2⁰. Shift left and the weight doubles.',
      frontHI: 'binary संख्या के हर column का क्या मतलब है?',
      backHI: 'two की स्थानीय शक्तियाँ: ... 8, 4, 2, 1। सबसे दायाँ bit 2⁰ है। बाएँ बढ़ने पर weight दोगुना होता है।',
    },
    {
      frontEN: 'When does an XOR gate output 1?',
      backEN: 'Only when its two inputs differ. Both the adder\'s Sum and the subtractor\'s Difference are an XOR of the inputs.',
      frontHI: 'XOR gate कब 1 देता है?',
      backHI: 'सिर्फ़ तब जब उसके दो inputs अलग हों। adder का Sum और subtractor का Difference, दोनों inputs का XOR हैं।',
    },
    {
      frontEN: 'What are the two outputs of a half adder?',
      backEN: 'Sum = a ⊕ b and Carry = a · b. It has no carry-in, so it cannot chain across columns on its own.',
      frontHI: 'half adder के दो outputs क्या हैं?',
      backHI: 'Sum = a ⊕ b और Carry = a · b। इसमें carry-in नहीं होता, इसलिए यह अकेले columns को जोड़ नहीं सकता।',
    },
    {
      frontEN: 'Why do we need a FULL adder?',
      backEN: 'It accepts a third input - the carry-in - so adders can chain column to column. Sum = a⊕b⊕cin, Carry = majority of the three.',
      frontHI: 'हमें FULL adder क्यों चाहिए?',
      backHI: 'यह तीसरा input - carry-in - लेता है, ताकि adders column-दर-column जुड़ सकें। Sum = a⊕b⊕cin, Carry = तीनों का बहुमत।',
    },
    {
      frontEN: 'In x − y, which is the minuend and which the subtrahend?',
      backEN: 'x is the minuend (the amount you start with); y is the subtrahend (the amount being taken away).',
      frontHI: 'x − y में minuend कौन और subtrahend कौन?',
      backHI: 'x है minuend (जहाँ से शुरू करते हैं); y है subtrahend (जो घटाई जाती है)।',
    },
    {
      frontEN: 'What is a borrow?',
      backEN: 'When a column cannot subtract (0 − 1), it borrows a 1 from the next-higher column. It is the mirror image of a carry.',
      frontHI: 'borrow क्या है?',
      backHI: 'जब column घटा न सके (0 − 1), तो यह अगले बड़े column से 1 borrow करता है। यह carry का आईना है।',
    },
    {
      frontEN: 'Carry vs borrow - which way does each travel?',
      backEN: 'Adding, a carry pushes a 1 UP to the next column. Subtracting, a borrow pulls a 1 DOWN from the next column.',
      frontHI: 'carry बनाम borrow - कौन किस ओर चलता है?',
      backHI: 'जोड़ते समय carry 1 को ऊपर अगले column में धकेलता है। घटाते समय borrow 1 को अगले column से नीचे खींचता है।',
    },
    {
      frontEN: 'How does a computer compute A − B?',
      backEN: 'It adds instead: A + (~B) + 1. Invert every bit of B and add one - that is the two\'s complement, the same adder doing subtraction.',
      frontHI: 'computer A − B कैसे निकालता है?',
      backHI: 'वह जोड़ता है: A + (~B) + 1। B के हर bit को invert करके एक जोड़िए - यही two\'s complement है, वही adder घटाव करते हुए।',
    },
  ],
  quiz: [
    {
      questionEN: 'XOR(1, 1) = ?',
      questionHI: 'XOR(1, 1) = ?',
      options: ['0', '1', '2', 'undefined'],
      answerIndex: 0,
      explainEN: 'XOR is 1 only when inputs differ. Both inputs are 1 (they match), so the output is 0.',
      explainHI: 'XOR तभी 1 होता है जब inputs अलग हों। दोनों inputs 1 हैं (मेल खाते हैं), इसलिए output 0 है।',
    },
    {
      questionEN: 'For a half adder with a = 1 and b = 1, the Sum bit is…',
      questionHI: 'a = 1 और b = 1 वाले half adder के लिए Sum bit क्या है?',
      options: ['0 (carry = 1)', '1 (carry = 0)', '2', '1 (carry = 1)'],
      answerIndex: 0,
      explainEN: 'Sum = a ⊕ b = 1 ⊕ 1 = 0, and Carry = a · b = 1. So Sum is 0 with the carry going to the next column.',
      explainHI: 'Sum = a ⊕ b = 1 ⊕ 1 = 0, और Carry = a · b = 1। यानी Sum 0 है और carry अगले column में जाता है।',
    },
    {
      questionEN: 'Subtracting a single column 0 − 1, the Difference and Borrow are…',
      questionHI: 'एक column 0 − 1 घटाने पर Difference और Borrow क्या होंगे?',
      options: ['D = 1, Borrow = 1', 'D = 0, Borrow = 0', 'D = 1, Borrow = 0', 'D = 0, Borrow = 1'],
      answerIndex: 0,
      explainEN: '0 − 1 cannot be done directly: you borrow, making it 10 − 1 = 1, so Difference = 1 and a Borrow of 1 is raised.',
      explainHI: '0 − 1 सीधे नहीं हो सकता: आप borrow करते हैं, जिससे यह 10 − 1 = 1 बनता है, इसलिए Difference = 1 और Borrow = 1 उठता है।',
    },
    {
      questionEN: 'In the expression x − y, the value y is called the…',
      questionHI: 'x − y में y को क्या कहते हैं?',
      options: ['Subtrahend', 'Minuend', 'Difference', 'Borrow'],
      answerIndex: 0,
      explainEN: 'y is the subtrahend - the amount being taken away. x is the minuend, the amount you start with.',
      explainHI: 'y है subtrahend - वह मात्रा जो हटाई जाती है। x है minuend, जहाँ से शुरू करते हैं।',
    },
    {
      questionEN: 'A carry and a borrow move in which directions?',
      questionHI: 'carry और borrow किन दिशाओं में चलते हैं?',
      options: ['Carry up, borrow down', 'Both up', 'Both down', 'Carry down, borrow up'],
      answerIndex: 0,
      explainEN: 'Adding, a carry is pushed up to the next-higher column; subtracting, a borrow is pulled down from the next-higher column.',
      explainHI: 'जोड़ते समय carry ऊपर अगले column में जाता है; घटाते समय borrow अगले column से नीचे आता है।',
    },
    {
      questionEN: 'Using two\'s complement, A − B equals…',
      questionHI: 'two\'s complement से, A − B किसके बराबर है?',
      options: ['A + (~B) + 1', 'A + B − 1', 'A + (~B)', '(~A) + B + 1'],
      answerIndex: 0,
      explainEN: 'Invert every bit of B (~B), add one to get −B in two\'s complement, then add A: A + (~B) + 1. The adder does the subtraction.',
      explainHI: 'B के हर bit को invert कीजिए (~B), एक जोड़कर two\'s complement में −B पाइए, फिर A जोड़िए: A + (~B) + 1। adder ही घटाव कर देता है।',
    },
  ],
};
