import type { SubContent } from '../_subtractor/kit';

/**
 * dsd/14 - Recall & Prime. The interactive review that OPENS the subtractor
 * track: reload binary place value, XOR, the half/full adder, carry-vs-borrow
 * and the two's-complement idea, so the half subtractor lands on solid ground.
 * Hand-authored bilingual content (the other three modules are workflow-drafted).
 */
export const CONTENT: SubContent = {
  moduleTitle: 'Recall & Prime',
  moduleSubtitle: 'Before you subtract, reload the five ideas every subtractor is quietly built from.',
  scenes: [
    {
      id: 'S00_Cover',
      label: 'Recall & Prime',
      kind: 'cover',
      subtitle: 'Warm up the exact circuits subtraction is about to reuse.',
      theoryEN: [
        'Subtraction does not start from scratch - it reuses almost everything you built making adders.',
        'Five things to reload: binary place value, the XOR gate, the half / full adder, carry vs borrow, and complements.',
        'Flip the recall deck, run the drills, then walk into the half subtractor with nothing missing.',
        'This whole module is review - no new circuit yet, just locking the foundation so the new ideas stick.',
      ],
      theoryHI: [
        'Subtraction शून्य से शुरू नहीं होता - यह लगभग वह सब कुछ फिर से इस्तेमाल करता है जो आपने adders बनाते हुए सीखा।',
        'पाँच चीज़ें फिर से load करनी हैं: binary place value, XOR gate, half / full adder, carry बनाम borrow, और complements।',
        'पहले recall deck पलटिए, drills कीजिए, फिर बिना कुछ छूटे half subtractor में दाख़िल होइए।',
        'यह पूरा module सिर्फ़ review है - अभी कोई नई circuit नहीं, बस नींव पक्की करना ताकि नई बातें टिकें।',
      ],
      transcriptEN: 'Welcome to the subtractor track. Before we build anything that subtracts, we are going to reload your memory, because subtraction is not a brand new machine - it is the adder you already know, wearing a different hat. In the next few screens you will refresh five ideas: how a binary number carries its value column by column, why the XOR gate shows up in every arithmetic circuit, what a half and a full adder actually output, the mirror relationship between a carry and a borrow, and the one trick - the complement - that lets a computer subtract without ever owning a subtract circuit. Flip the cards, take the short drill, and you will be primed.',
      transcriptHI: 'Subtractor track में आपका स्वागत है। घटाने वाली कोई भी चीज़ बनाने से पहले हम आपकी memory फिर से load करेंगे, क्योंकि subtraction कोई बिलकुल नई मशीन नहीं है - यह वही adder है जिसे आप पहले से जानते हैं, बस अलग टोपी पहने हुए। अगली कुछ screens में आप पाँच विचार ताज़ा करेंगे: binary संख्या column-दर-column अपनी value कैसे रखती है, हर arithmetic circuit में XOR gate क्यों आता है, half और full adder असल में क्या output देते हैं, carry और borrow का आईने जैसा रिश्ता, और वह एक trick - complement - जो computer को बिना subtract circuit के घटाने देती है। Cards पलटिए, छोटी drill कीजिए, और आप तैयार हो जाएँगे।',
    },
    {
      id: 'S01_Deck',
      label: 'The Recall Deck',
      kind: 'flashcards',
      subtitle: 'Question on the front, the real logic on the back. Flip every card you are unsure about.',
      theoryEN: ['Tap a card to flip it.', 'Use the EN / हिं toggle in the header to read either language.'],
      theoryHI: ['पलटने के लिए card को tap कीजिए।', 'header में EN / हिं toggle से कोई भी भाषा पढ़िए।'],
      transcriptEN: 'These eight cards are the whole prerequisite set for the subtractor track. If a card flips and the back surprises you, that is exactly the idea to slow down on before moving ahead.',
      transcriptHI: 'ये आठ cards ही subtractor track की पूरी prerequisite सूची हैं। अगर कोई card पलटे और पीछे की बात चौंका दे, तो आगे बढ़ने से पहले रुककर ठीक वही विचार दोहराइए।',
    },
    {
      id: 'S02_Binary',
      label: 'Binary Subtraction by Hand',
      kind: 'theory',
      subtitle: 'Borrowing, one column at a time.',
      theoryEN: [
        'In x − y, x is the minuend (what you start with) and y is the subtrahend (what you remove).',
        'Each column can read 0−0=0, 1−0=1, 1−1=0 with no trouble.',
        'The hard column is 0 − 1: you cannot, so you BORROW 1 from the next-higher column, turning it into 10 − 1 = 1.',
        'A borrow is the exact mirror of a carry: a carry travels up while adding, a borrow travels down while subtracting.',
      ],
      theoryHI: [
        'x − y में, x है minuend (जहाँ से शुरू करते हैं) और y है subtrahend (जो हटाते हैं)।',
        'हर column आसानी से पढ़ सकता है: 0−0=0, 1−0=1, 1−1=0।',
        'कठिन column है 0 − 1: यह सीधे नहीं हो सकता, इसलिए आप अगले बड़े column से 1 BORROW करते हैं, जिससे यह 10 − 1 = 1 बन जाता है।',
        'Borrow, carry का बिलकुल आईना है: जोड़ते समय carry ऊपर जाता है, घटाते समय borrow नीचे आता है।',
      ],
      transcriptEN: 'Subtracting binary by hand is the same ritual as decimal, with only two digits. Line the numbers up, work right to left, and most columns are trivial. The only moment that needs care is zero minus one: there is nothing to take away from, so you borrow a one from the column to your left, exactly like borrowing a ten in grade-school subtraction. That single borrow is the whole reason a subtractor needs a second output, and it is the idea the half subtractor is about to make into a circuit.',
      transcriptHI: 'Binary को हाथ से घटाना decimal जैसी ही रस्म है, बस दो ही digits के साथ। संख्याओं को सीध में रखिए, दाएँ से बाएँ चलिए, और ज़्यादातर columns आसान हैं। ध्यान सिर्फ़ एक पल माँगता है: शून्य में से एक - यहाँ हटाने को कुछ है ही नहीं, इसलिए आप बाएँ column से एक borrow करते हैं, ठीक वैसे जैसे स्कूल की subtraction में दस उधार लेते हैं। वही एक borrow पूरी वजह है कि subtractor को दूसरा output चाहिए, और यही विचार half subtractor अब एक circuit में बदलने वाला है।',
    },
    {
      id: 'S03_BorrowVsCarry',
      label: 'Carry vs Borrow',
      kind: 'theory',
      subtitle: 'Same XOR difference, opposite overflow.',
      theoryEN: [
        'The adder and subtractor share a body: both compute their main bit with an XOR (Sum = a⊕b, Difference = x⊕y).',
        'They differ in the second output. The adder emits a CARRY (it made too much for one column).',
        'The subtractor emits a BORROW (it did not have enough in this column).',
        'Half adder: Sum = a⊕b, Carry = a·b. Half subtractor: Diff = x⊕y, Borrow = x′·y. Notice only the second gate changes.',
        'That near-symmetry is why a single circuit, steered by a mode bit, can do both jobs.',
      ],
      theoryHI: [
        'Adder और subtractor का शरीर एक है: दोनों अपना मुख्य bit XOR से निकालते हैं (Sum = a⊕b, Difference = x⊕y)।',
        'फ़र्क़ दूसरे output में है। Adder एक CARRY देता है (एक column के लिए बहुत ज़्यादा बन गया)।',
        'Subtractor एक BORROW देता है (इस column में पर्याप्त नहीं था)।',
        'Half adder: Sum = a⊕b, Carry = a·b। Half subtractor: Diff = x⊕y, Borrow = x′·y। ग़ौर कीजिए, सिर्फ़ दूसरा gate बदलता है।',
        'यही लगभग-समरूपता वजह है कि एक ही circuit, mode bit से चलाई जाकर, दोनों काम कर सकती है।',
      ],
      transcriptEN: 'Here is the punch line that ties the whole track together. An adder and a subtractor are almost the same circuit. Both take their two inputs and run them through an XOR to make the main result bit - Sum for the adder, Difference for the subtractor. The only real difference is the helper output. When adding, a column can overflow upward and hand a carry to the next column. When subtracting, a column can come up short and pull a borrow from the next column. Look at the gates: half adder carry is a AND b, half subtractor borrow is NOT-x AND y. Swap one gate, steer it with a control bit, and the same silicon adds or subtracts on command. Hold that idea - it is the secret the next module reveals in full.',
      transcriptHI: 'यह वह निचोड़ है जो पूरे track को बाँधता है। Adder और subtractor लगभग एक ही circuit हैं। दोनों अपने दो inputs को XOR से गुज़ारकर मुख्य result bit बनाते हैं - adder के लिए Sum, subtractor के लिए Difference। असली फ़र्क़ सिर्फ़ helper output में है। जोड़ते समय column ऊपर की ओर overflow होकर अगले column को carry देता है। घटाते समय column कम पड़कर अगले column से borrow खींचता है। Gates देखिए: half adder का carry है a AND b, half subtractor का borrow है NOT-x AND y। एक gate बदलिए, एक control bit से चलाइए, और वही silicon आदेश पर जोड़ता या घटाता है। इस विचार को थामे रखिए - अगला module इसी राज़ को पूरा खोलता है।',
    },
    {
      id: 'S04_Quiz',
      label: 'Recall Boss Round',
      kind: 'quiz',
      subtitle: 'Six questions across all five reloaded ideas.',
      theoryEN: ['Answer each one; the walkthrough opens the moment you pick.'],
      theoryHI: ['हर सवाल का जवाब दीजिए; चुनते ही walkthrough खुल जाता है।'],
      transcriptEN: 'A quick six-question check across the whole warm-up. Anything you miss, flip back to its card before you start the half subtractor.',
      transcriptHI: 'पूरे warm-up पर छह सवालों की त्वरित जाँच। जो भी छूटे, half subtractor शुरू करने से पहले उसके card पर वापस जाइए।',
    },
    {
      id: 'S05_Recap',
      label: 'The Cheatsheet',
      kind: 'recap',
      subtitle: 'One page to carry into the half subtractor.',
      theoryEN: [
        'Binary value is positional: ...8 4 2 1, right bit is 2⁰.',
        'XOR = 1 only when inputs differ - it builds both Sum and Difference.',
        'Half adder: Sum=a⊕b, Carry=a·b. Full adder adds a carry-in: Sum=a⊕b⊕cin.',
        'Borrow is a carry in reverse: it pulls 1 down from the next column when 0−1 happens.',
        'Computers subtract by adding: A − B = A + (~B) + 1, the two\'s complement.',
        'Next: the Half Subtractor turns that single borrow into two wires.',
      ],
      theoryHI: [
        'Binary value स्थान पर निर्भर है: ...8 4 2 1, दायाँ bit 2⁰ है।',
        'XOR = 1 तभी जब inputs अलग हों - यह Sum और Difference दोनों बनाता है।',
        'Half adder: Sum=a⊕b, Carry=a·b। Full adder एक carry-in जोड़ता है: Sum=a⊕b⊕cin।',
        'Borrow उल्टा carry है: 0−1 होने पर यह अगले column से 1 नीचे खींचता है।',
        'Computer जोड़कर घटाते हैं: A − B = A + (~B) + 1, यानी two\'s complement।',
        'आगे: Half Subtractor उसी एक borrow को दो wires में बदल देता है।',
      ],
      transcriptEN: 'That is the whole foundation on one page. Place value, the XOR, the half and full adder, the borrow as a reversed carry, and the complement trick. Keep this nearby - every screen from here on leans on one of these five. On to the half subtractor.',
      transcriptHI: 'यही पूरी नींव एक page पर है। Place value, XOR, half और full adder, उल्टे carry जैसा borrow, और complement की trick। इसे पास रखिए - यहाँ से हर screen इन्हीं पाँच में से किसी एक पर टिकी है। चलिए half subtractor की ओर।',
    },
  ],
  flashcards: [
    {
      frontEN: 'What does each column of a binary number mean?',
      backEN: 'Positional powers of two: ... 8, 4, 2, 1. The rightmost bit is 2⁰. Shift left and the weight doubles.',
      frontHI: 'binary संख्या के हर column का क्या मतलब है?',
      backHI: 'two की स्थानीय शक्तियाँ: ... 8, 4, 2, 1। सबसे दायाँ bit 2⁰ है। बाएँ बढ़ने पर weight दोगुना होता है।',
    },
    {
      frontEN: 'When does an XOR gate output 1?',
      backEN: 'Only when its two inputs differ. Both the adder\'s Sum and the subtractor\'s Difference are an XOR of the inputs.',
      frontHI: 'XOR gate कब 1 देता है?',
      backHI: 'सिर्फ़ तब जब उसके दो inputs अलग हों। adder का Sum और subtractor का Difference, दोनों inputs का XOR हैं।',
    },
    {
      frontEN: 'What are the two outputs of a half adder?',
      backEN: 'Sum = a ⊕ b and Carry = a · b. It has no carry-in, so it cannot chain across columns on its own.',
      frontHI: 'half adder के दो outputs क्या हैं?',
      backHI: 'Sum = a ⊕ b और Carry = a · b। इसमें carry-in नहीं होता, इसलिए यह अकेले columns को जोड़ नहीं सकता।',
    },
    {
      frontEN: 'Why do we need a FULL adder?',
      backEN: 'It accepts a third input - the carry-in - so adders can chain column to column. Sum = a⊕b⊕cin, Carry = majority of the three.',
      frontHI: 'हमें FULL adder क्यों चाहिए?',
      backHI: 'यह तीसरा input - carry-in - लेता है, ताकि adders column-दर-column जुड़ सकें। Sum = a⊕b⊕cin, Carry = तीनों का बहुमत।',
    },
    {
      frontEN: 'In x − y, which is the minuend and which the subtrahend?',
      backEN: 'x is the minuend (the amount you start with); y is the subtrahend (the amount being taken away).',
      frontHI: 'x − y में minuend कौन और subtrahend कौन?',
      backHI: 'x है minuend (जहाँ से शुरू करते हैं); y है subtrahend (जो घटाई जाती है)।',
    },
    {
      frontEN: 'What is a borrow?',
      backEN: 'When a column cannot subtract (0 − 1), it borrows a 1 from the next-higher column. It is the mirror image of a carry.',
      frontHI: 'borrow क्या है?',
      backHI: 'जब column घटा न सके (0 − 1), तो यह अगले बड़े column से 1 borrow करता है। यह carry का आईना है।',
    },
    {
      frontEN: 'Carry vs borrow - which way does each travel?',
      backEN: 'Adding, a carry pushes a 1 UP to the next column. Subtracting, a borrow pulls a 1 DOWN from the next column.',
      frontHI: 'carry बनाम borrow - कौन किस ओर चलता है?',
      backHI: 'जोड़ते समय carry 1 को ऊपर अगले column में धकेलता है। घटाते समय borrow 1 को अगले column से नीचे खींचता है।',
    },
    {
      frontEN: 'How does a computer compute A − B?',
      backEN: 'It adds instead: A + (~B) + 1. Invert every bit of B and add one - that is the two\'s complement, the same adder doing subtraction.',
      frontHI: 'computer A − B कैसे निकालता है?',
      backHI: 'वह जोड़ता है: A + (~B) + 1। B के हर bit को invert करके एक जोड़िए - यही two\'s complement है, वही adder घटाव करते हुए।',
    },
  ],
  quiz: [
    {
      questionEN: 'XOR(1, 1) = ?',
      questionHI: 'XOR(1, 1) = ?',
      options: ['0', '1', '2', 'undefined'],
      answerIndex: 0,
      explainEN: 'XOR is 1 only when inputs differ. Both inputs are 1 (they match), so the output is 0.',
      explainHI: 'XOR तभी 1 होता है जब inputs अलग हों। दोनों inputs 1 हैं (मेल खाते हैं), इसलिए output 0 है।',
    },
    {
      questionEN: 'For a half adder with a = 1 and b = 1, the Sum bit is…',
      questionHI: 'a = 1 और b = 1 वाले half adder के लिए Sum bit क्या है?',
      options: ['0 (carry = 1)', '1 (carry = 0)', '2', '1 (carry = 1)'],
      answerIndex: 0,
      explainEN: 'Sum = a ⊕ b = 1 ⊕ 1 = 0, and Carry = a · b = 1. So Sum is 0 with the carry going to the next column.',
      explainHI: 'Sum = a ⊕ b = 1 ⊕ 1 = 0, और Carry = a · b = 1। यानी Sum 0 है और carry अगले column में जाता है।',
    },
    {
      questionEN: 'Subtracting a single column 0 − 1, the Difference and Borrow are…',
      questionHI: 'एक column 0 − 1 घटाने पर Difference और Borrow क्या होंगे?',
      options: ['D = 1, Borrow = 1', 'D = 0, Borrow = 0', 'D = 1, Borrow = 0', 'D = 0, Borrow = 1'],
      answerIndex: 0,
      explainEN: '0 − 1 cannot be done directly: you borrow, making it 10 − 1 = 1, so Difference = 1 and a Borrow of 1 is raised.',
      explainHI: '0 − 1 सीधे नहीं हो सकता: आप borrow करते हैं, जिससे यह 10 − 1 = 1 बनता है, इसलिए Difference = 1 और Borrow = 1 उठता है।',
    },
    {
      questionEN: 'In the expression x − y, the value y is called the…',
      questionHI: 'x − y में y को क्या कहते हैं?',
      options: ['Subtrahend', 'Minuend', 'Difference', 'Borrow'],
      answerIndex: 0,
      explainEN: 'y is the subtrahend - the amount being taken away. x is the minuend, the amount you start with.',
      explainHI: 'y है subtrahend - वह मात्रा जो हटाई जाती है। x है minuend, जहाँ से शुरू करते हैं।',
    },
    {
      questionEN: 'A carry and a borrow move in which directions?',
      questionHI: 'carry और borrow किन दिशाओं में चलते हैं?',
      options: ['Carry up, borrow down', 'Both up', 'Both down', 'Carry down, borrow up'],
      answerIndex: 0,
      explainEN: 'Adding, a carry is pushed up to the next-higher column; subtracting, a borrow is pulled down from the next-higher column.',
      explainHI: 'जोड़ते समय carry ऊपर अगले column में जाता है; घटाते समय borrow अगले column से नीचे आता है।',
    },
    {
      questionEN: 'Using two\'s complement, A − B equals…',
      questionHI: 'two\'s complement से, A − B किसके बराबर है?',
      options: ['A + (~B) + 1', 'A + B − 1', 'A + (~B)', '(~A) + B + 1'],
      answerIndex: 0,
      explainEN: 'Invert every bit of B (~B), add one to get −B in two\'s complement, then add A: A + (~B) + 1. The adder does the subtraction.',
      explainHI: 'B के हर bit को invert कीजिए (~B), एक जोड़कर two\'s complement में −B पाइए, फिर A जोड़िए: A + (~B) + 1। adder ही घटाव कर देता है।',
    },
  ],
};
